// ankleSheetSet.js -- the sentences of the Ankle / Foot "everyday words" sheet (PhysioMind-AnkleFoot-Everyday-Words-DRAFT.pdf), written the way the
// CLINICIAN would type about the patient ("the patient", "they", short notes): English in four styles, Hinglish and Hindi, for all 17 ankle and foot
// conditions. Used by ankleSheetSet.test.js (not a test itself). Row = [lang, text, must, may]:
//   must = options a physio would tick from that sentence (a miss costs recall)
//   may  = options that are also fair to suggest (neither right nor wrong: they do not count against precision)
//   anything else it suggests counts as wrong. A sentence with no must and no may must stay silent.
// lang: en = English, hi = Hinglish (Hindi in Latin letters), de = Hindi in Devanagari. The answer keys are DRAFTS written by Claude
// for Aditi to check. The Ankle/Foot form has no question for "how it started" or "how long" as such, so those lines only count where a
// sentence also says something a form question covers (e.g. "no injury", "after a fall").
import { KEYS } from "./ankleFootWildSets.js";
import { understandStory } from "../ankleFootPhraseMap.js";

const { ACHI, ACHM, ACHRUP, ANTA, BAREFOOT, BETW, BURN, BURNBETW, CHG, DIRECT, DORSI, DOWNH, EVER, FALLH, FIRST, FORE, HIGH, INSID, INTER, INV, LAND, LATA, MEDA, MORNIMP, NIGHT, OTTWEIGHT, PERON, PLANT, POSTA, SHIN, SMILD, SMOD, SOLE, SSEV, STAIRS, TARSAL, TIGHT, TOE1, TOP, TRAIN, WALKRUN, WARM } = KEYS;

export const ANKLE_SHEET = [
  ["en", "Rolled ankle with pain and swelling on the outer side. Hard to put weight on it.", [LATA, INV], [SMOD, SMILD, SSEV, OTTWEIGHT]],
  ["en", "The patient rolled the ankle inwards and now the outside of the ankle is swollen and bruised. They can hardly walk on it.", [INV, LATA], [OTTWEIGHT, SMOD, SMILD, SSEV, WALKRUN]],
  ["en", "Inversion injury. Lateral ankle pain, swelling, bruising. Painful weight bearing.", [INV, LATA], [OTTWEIGHT, SMOD, SMILD, SSEV]],
  ["en", "They landed on someone’s foot and the ankle turned in. The outer side swelled up straight away and walking hurts.", [INV], [LATA, LAND, SSEV, SMOD, WALKRUN, OTTWEIGHT]],
  ["hi", "Takhna andar ki taraf mud gaya, bahar ki taraf dard aur sujan, chalne mein dikkat.", [INV, LATA], [SMOD, SMILD, SSEV, OTTWEIGHT, WALKRUN]],
  ["de", "टखना अंदर की तरफ मुड़ गया, बाहर की तरफ दर्द और सूजन, चलने में दिक्कत।", [INV, LATA], [SMOD, SMILD, SSEV, OTTWEIGHT, WALKRUN]],
  ["en", "Sudden, at the moment of the twist.", [], [INV]],
  ["en", "It happened in a flash, while playing.", [], []],
  ["en", "Sudden, during sport.", [], []],
  ["en", "There was no warning. They stepped on uneven ground and the ankle went over.", [], [INV, CHG]],
  ["hi", "Achanak, khelte waqt.", [], []],
  ["de", "अचानक, खेलते समय।", [], []],
  ["en", "Rolled the ankle inwards on uneven ground or landing on someone’s foot.", [INV], [LAND, CHG]],
  ["en", "The foot turned in while cutting or landing from a jump.", [INV, LAND], []],
  ["en", "Inversion with the foot pointing down. Football, basketball, uneven surface.", [INV], [CHG, LAND]],
  ["en", "They came down on another player’s foot after a rebound and the ankle rolled in.", [INV], [LAND]],
  ["hi", "Ubad-khabad zameen par ya kood kar utarte waqt takhna andar ki taraf mud gaya.", [INV, LAND], [CHG]],
  ["de", "ऊबड़-खाबड़ ज़मीन पर या कूदकर उतरते समय टखना अंदर की तरफ मुड़ गया।", [INV, LAND], [CHG]],
  ["en", "A few days to six weeks.", [], []],
  ["en", "It has been two weeks.", [], []],
  ["en", "Days to six weeks.", [], []],
  ["en", "Still swollen and sore after a week.", [], [SMILD, SMOD]],
  ["hi", "Kuch din se chhe hafte.", [], []],
  ["de", "कुछ दिन से छह हफ्ते।", [], []],
  ["en", "The ankle keeps rolling over. Several sprains in the last year and it feels unstable.", [INV], [LATA]],
  ["en", "The patient says the ankle gives way on uneven ground and they have had repeated sprains. It swells after sport.", [], [INV, SSEV, SMOD, SMILD, CHG, LATA]],
  ["en", "Recurrent lateral ankle sprains. Giving way. Instability on rough ground.", [LATA], [INV, CHG]],
  ["en", "They have lost count of how many times they have rolled the ankle. It lets them down on rough ground.", [INV], [LATA, CHG, SSEV]],
  ["hi", "Takhna baar baar andar ki taraf mud jata hai, ubad-khabad zameen par bharosa nahi.", [INV], [CHG, LATA]],
  ["de", "टखना बार बार अंदर की तरफ मुड़ जाता है, ऊबड़-खाबड़ ज़मीन पर भरोसा नहीं।", [INV], [CHG, LATA]],
  ["en", "After a bad sprain a year or two ago, then it gave way again and again.", [], [INV]],
  ["en", "It began with one sprain and never really settled.", [], []],
  ["en", "Old sprain, now recurring.", [], []],
  ["en", "It started after a football injury years ago and has slowly got worse.", [], [INSID]],
  ["hi", "Purani moch ke baad se, baar baar.", [], []],
  ["de", "पुरानी मोच के बाद से, बार बार।", [], []],
  ["en", "Repeated inversion sprains on uneven ground.", [INV], [CHG]],
  ["en", "Rolled the ankle again and again, often when stepping off a kerb or on rough ground.", [INV], [CHG]],
  ["en", "Recurrent inversion. Weak peroneals, poor balance.", [INV], []],
  ["en", "Each new roll happens more easily, on flat ground now.", [], [INV]],
  ["hi", "Baar baar takhna andar ki taraf mudna, ubad-khabad zameen par.", [INV], [CHG]],
  ["de", "बार बार टखना अंदर की तरफ मुड़ना, ऊबड़-खाबड़ ज़मीन पर।", [INV], [CHG]],
  ["en", "More than a year, on and off.", [], [INTER]],
  ["en", "It has been going on for years.", [], []],
  ["en", "More than 12 months.", [], []],
  ["en", "Better and worse for a couple of years.", [], [INTER]],
  ["hi", "Saal bhar se zyada.", [], []],
  ["de", "साल भर से ज़्यादा।", [], []],
  ["en", "Pain above the ankle at the front and outer side, worse when pushing off or turning the foot out.", [ANTA], [LATA, HIGH, WALKRUN, DORSI]],
  ["en", "The patient has pain just above the ankle joint, mainly at the front, and it hurts a lot to put weight on it.", [], [ANTA, LATA, OTTWEIGHT, SHIN]],
  ["en", "Anterolateral ankle pain above the joint. Pain on external rotation and push-off.", [], [ANTA, LATA, HIGH]],
  ["en", "They get a sharp pain high up at the front of the ankle every time they push off or twist the foot outwards.", [ANTA], [HIGH, WALKRUN, LATA]],
  ["hi", "Takhne ke thik upar aage ki taraf dard, pair bahar ki taraf ghumane aur zor lagane par badhta hai.", [], [ANTA, LATA, HIGH]],
  ["de", "टखने के ठीक ऊपर आगे की तरफ दर्द, पैर बाहर की तरफ घुमाने और ज़ोर लगाने पर बढ़ता है।", [], [ANTA, LATA, HIGH]],
  ["en", "Sudden, during a tackle or a fall.", [], [HIGH, DIRECT, FALLH]],
  ["en", "It happened in a flash.", [], []],
  ["en", "Sudden.", [], []],
  ["en", "No warning. The foot was fixed and the body kept turning.", [], [HIGH]],
  ["hi", "Achanak.", [], []],
  ["de", "अचानक।", [], []],
  ["en", "The foot was forced outwards while the ankle was bent up, in football or skiing.", [HIGH], [EVER]],
  ["en", "Planted foot and the body twisted over it, or another player fell on the leg.", [], [HIGH, DIRECT]],
  ["en", "External rotation with dorsiflexion. Football, skiing.", [HIGH], []],
  ["en", "They were tackled from behind while the foot was fixed, and the ankle twisted outwards.", [HIGH], [DIRECT, EVER]],
  ["hi", "Football ya skiing mein pair bahar ki taraf mud gaya jab takhna upar ki taraf mura tha.", [HIGH], [EVER]],
  ["de", "फुटबॉल या स्कीइंग में पैर बाहर की तरफ मुड़ गया जब टखना ऊपर की तरफ मुड़ा था।", [HIGH], [EVER]],
  ["en", "Weeks to months.", [], []],
  ["en", "Slower to settle than a normal sprain.", [], []],
  ["en", "Weeks–months.", [], []],
  ["en", "Still sore after six weeks.", [], []],
  ["hi", "Hafte se mahine.", [], []],
  ["de", "हफ्ते से महीने।", [], []],
  ["en", "Pain in the Achilles about 4 cm above the heel, stiff first thing in the morning and sore when they start running.", [ACHM], [MORNIMP, FIRST, WALKRUN, WARM]],
  ["en", "The patient has a sore thickened Achilles a few centimetres above the heel. It is stiff in the morning but eases once they warm up.", [ACHM], [MORNIMP, FIRST, WARM]],
  ["en", "Mid-portion Achilles pain. Morning stiffness. Pain at start of run.", [ACHM], [MORNIMP, FIRST, WALKRUN]],
  ["en", "They have a tender lump at the back of the heel where the tendon attaches, and it hurts when they bend the foot up.", [ACHI], [DORSI, WALKRUN]],
  ["hi", "Edi ke peeche jahan Achilles judta hai wahan dard aur ubhaar, takhna upar modne par badhta hai.", [ACHI], [DORSI]],
  ["de", "एड़ी के पीछे जहां अकिलीज़ जुड़ती है वहां दर्द और उभार, टखना ऊपर मोड़ने पर बढ़ता है।", [ACHI], [DORSI]],
  ["en", "Gradual, no injury, after a jump in mileage.", [INSID], [TRAIN]],
  ["en", "It crept up over weeks after they increased their running.", [TRAIN], [INSID]],
  ["en", "Gradual onset, new shoes.", [INSID], [CHG]],
  ["en", "No single event. It built up as the training load went up.", [], [INSID, TRAIN]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [INSID], []],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [INSID], []],
  ["en", "Overload from running: more mileage, hills and speed work.", [TRAIN], [INSID, DOWNH]],
  ["en", "Sudden increase in training and a change to harder surfaces.", [TRAIN, CHG], []],
  ["en", "Training error. Hills, intervals, new spikes.", [], [TRAIN, INSID, CHG]],
  ["en", "They doubled their weekly running and switched to a hard track.", [TRAIN], [CHG, INSID]],
  ["hi", "Daud ki doori achanak badha di aur sakht zameen par daudna shuru kiya.", [TRAIN], [CHG]],
  ["de", "दौड़ की दूरी अचानक बढ़ा दी और सख्त ज़मीन पर दौड़ना शुरू किया।", [TRAIN], [CHG]],
  ["en", "Months, often more than three months.", [], []],
  ["en", "It has been there for many months.", [], []],
  ["en", "Months. Chronic.", [], []],
  ["en", "On and off for six months.", [], [INTER]],
  ["hi", "Kai mahine se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "A sudden pop at the back of the ankle like being kicked. Cannot push off or stand on tiptoe.", [ACHRUP], [ACHI, ACHM, POSTA]],
  ["en", "The patient heard a snap in the calf and felt a sharp pain behind the ankle. They cannot rise onto the toes on that leg.", [ACHRUP], [POSTA, ACHI, ACHM]],
  ["en", "Sudden snap, back of the ankle. Cannot do a heel raise.", [ACHRUP], [POSTA, ACHM, ACHI]],
  ["en", "They felt as if someone had kicked them in the back of the leg, but nobody was there. Walking is weak and they cannot push off.", [ACHRUP], [POSTA, WALKRUN]],
  ["hi", "Takhne ke peeche achanak pop ki awaaz aur tez dard, panjon par khade nahi ho pa rahe.", [ACHRUP], [POSTA]],
  ["de", "टखने के पीछे अचानक पॉप की आवाज़ और तेज़ दर्द, पंजों पर खड़े नहीं हो पा रहे।", [ACHRUP], [POSTA]],
  ["en", "Sudden, during a sprint or a jump.", [], []],
  ["en", "It happened in a flash.", [], []],
  ["en", "Sudden.", [], []],
  ["en", "No warning at all, and no earlier tendon pain.", [], []],
  ["hi", "Achanak.", [], []],
  ["de", "अचानक।", [], []],
  ["en", "Pushing off hard with the knee straight, such as a sprint start or a jump.", [], [LAND, TRAIN]],
  ["en", "A sudden upward jolt of the foot, for example stepping into a hole.", [], []],
  ["en", "Forceful push-off. Sprint, jump, quick stop.", [], []],
  ["en", "They were playing tennis, pushed off for a drop shot and felt the snap.", [], []],
  ["hi", "Daud shuru karte waqt ya kood kar zor se panje se dhakka dete waqt.", [], [LAND]],
  ["de", "दौड़ शुरू करते समय या कूदकर ज़ोर से पंजे से धक्का देते समय।", [], [LAND]],
  ["en", "Acute. Needs urgent assessment.", [], []],
  ["en", "It happened today.", [], []],
  ["en", "Acute.", [], []],
  ["en", "Since yesterday.", [], []],
  ["hi", "Abhi abhi hua.", [], []],
  ["de", "अभी अभी हुआ।", [], []],
  ["en", "Stiff, aching ankle, worse with walking and at the start after rest. Some swelling.", [], [WALKRUN, FIRST, MORNIMP, SMOD, SMILD, ANTA]],
  ["en", "The patient has a deep ache in the ankle joint that is worse after walking and stiff in the morning.", [], [MORNIMP, FIRST, WALKRUN]],
  ["en", "Ankle pain and stiffness. Worse walking. Morning stiffness. Grinding.", [], [WALKRUN, MORNIMP]],
  ["en", "Their ankle has gone stiff and sore over the years, especially on uneven ground and after a long walk.", [], [WALKRUN, CHG, INSID]],
  ["hi", "Takhne mein akdan aur dard, chalne par badhta hai, subah zyada akda hua.", [], [MORNIMP, WALKRUN, FIRST]],
  ["de", "टखने में अकड़न और दर्द, चलने पर बढ़ता है, सुबह ज़्यादा अकड़ा हुआ।", [], [MORNIMP, WALKRUN, FIRST]],
  ["en", "Gradual over years.", [], [INSID]],
  ["en", "It came on slowly after an old fracture.", [], [INSID]],
  ["en", "Gradual; old injury.", [], [INSID]],
  ["en", "No new injury. It crept up over the years after a bad ankle fracture long ago.", [], [INSID]],
  ["hi", "Saalon mein dheere dheere.", [], [INSID]],
  ["de", "सालों में धीरे धीरे।", [], [INSID]],
  ["en", "Wear and tear after an old fracture or many sprains.", [], [INSID]],
  ["en", "The joint has worn out after repeated sprains.", [], [INSID]],
  ["en", "Post-traumatic wear.", [], [INSID]],
  ["en", "An old fracture that never healed perfectly.", [], [INSID]],
  ["hi", "Purani fracture ya baar baar moch ke baad ghisaav.", [], [INSID]],
  ["de", "पुरानी फ्रैक्चर या बार बार मोच के बाद घिसाव।", [], [INSID]],
  ["en", "Years.", [], []],
  ["en", "It has been going on for years.", [], []],
  ["en", "Years, with flares.", [], [INTER]],
  ["en", "Some weeks it is fine, some weeks it is bad.", [], [INTER]],
  ["hi", "Kai saalon se.", [], []],
  ["de", "कई सालों से।", [], []],
  ["en", "Aching on the inner side of the ankle and arch, with swelling behind the inner ankle bone.", [MEDA], [PLANT, SMOD, SMILD, POSTA]],
  ["en", "The patient has a tired, vague ache on the inside of the foot and ankle that gets worse with activity. The arch looks flatter than before.", [MEDA], [PLANT, WALKRUN]],
  ["en", "Medial ankle pain and swelling. Arch collapsing. Pain on single heel raise.", [MEDA], [PLANT, SMOD]],
  ["en", "They notice the arch of the foot sinking and the inner ankle feels sore and puffy after a day on their feet.", [MEDA], [PLANT, SMOD, SMILD, WALKRUN]],
  ["hi", "Takhne ke andar ki taraf dard aur sujan, pair ka arch dheere dheere beith raha hai.", [MEDA], [PLANT]],
  ["de", "टखने के अंदर की तरफ दर्द और सूजन, पैर की मेहराब धीरे धीरे बैठ रही है।", [MEDA], [PLANT]],
  ["en", "Gradual over weeks, no injury.", [INSID], []],
  ["en", "It crept up slowly with no fall or twist.", [], [INSID]],
  ["en", "Gradual onset, no injury.", [INSID], []],
  ["en", "No single event. It has built up over several months.", [], [INSID]],
  ["hi", "Dheere dheere, koi chot nahi.", [INSID], []],
  ["de", "धीरे धीरे, कोई चोट नहीं।", [INSID], []],
  ["en", "Overload and wear of the tendon, more likely with flat feet and extra weight.", [], [INSID, TRAIN]],
  ["en", "Standing and walking a lot, with a flat foot.", [], [INSID]],
  ["en", "Degenerative. Flat foot, obesity.", [], [INSID]],
  ["en", "A lot of standing at work and gradually flatter feet.", [], [INSID]],
  ["hi", "Zyada der khade rehna aur chapte paer.", [], [INSID]],
  ["de", "ज़्यादा देर खड़े रहना और चपटे पैर।", [], [INSID]],
  ["en", "Months, getting worse.", [], []],
  ["en", "It has been building for several months.", [], []],
  ["en", "Months; progressive.", [], []],
  ["en", "A year of aching and the arch is lower now.", [], [PLANT]],
  ["hi", "Kai mahine se badhta hua.", [], []],
  ["de", "कई महीनों से बढ़ता हुआ।", [], []],
  ["en", "Pain behind the outer ankle bone, worse turning the foot outwards and pushing off.", [LATA], [POSTA, WALKRUN]],
  ["en", "The patient has a sore spot just behind the outside ankle bone, with a snapping feeling when the foot turns out.", [LATA], [POSTA, PERON]],
  ["en", "Lateral ankle pain behind the fibula. Snapping. Worse pushing off.", [LATA], [POSTA, PERON, WALKRUN]],
  ["en", "They feel the tendon flick over the bone on the outside of the ankle, and it is tender after running.", [LATA], [PERON, WALKRUN]],
  ["hi", "Takhne ki bahari haddi ke peeche dard aur chatakne ki awaaz, pair bahar ki taraf modne par badhta hai.", [], [LATA, POSTA, PERON]],
  ["de", "टखने की बाहरी हड्डी के पीछे दर्द और चटकने की आवाज़, पैर बाहर की तरफ मोड़ने पर बढ़ता है।", [], [LATA, POSTA, PERON]],
  ["en", "Gradual, often after earlier sprains.", [], [INSID, INV]],
  ["en", "After a sprain that never settled, or a pop when the ankle bent upwards.", [], [INV, INSID]],
  ["en", "Gradual, or after a sprain.", [], [INSID, INV]],
  ["en", "It followed a bad sprain and has built up with running.", [], [INSID, INV, TRAIN]],
  ["hi", "Moch ke baad dheere dheere.", [], [INSID, INV]],
  ["de", "मोच के बाद धीरे धीरे।", [], [INSID, INV]],
  ["en", "Overuse with repeated outer-ankle sprains.", [], [INV, INSID, LATA]],
  ["en", "Repeated sprains and running on a banked road.", [], [INV, INSID, CHG]],
  ["en", "Overuse. Recurrent inversion.", [], [INV, INSID]],
  ["en", "They roll the ankle often and run a lot.", [], [INV, INSID, TRAIN]],
  ["hi", "Baar baar moch aur zyada daudna.", [], [INV, INSID, TRAIN]],
  ["de", "बार बार मोच और ज़्यादा दौड़ना।", [], [INV, INSID, TRAIN]],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been several weeks.", [], []],
  ["en", "Weeks–months.", [], []],
  ["en", "A few months of on and off pain.", [], [INTER]],
  ["hi", "Hafte se mahine.", [], []],
  ["de", "हफ्ते से महीने।", [], []],
  ["en", "Burning and tingling in the sole of the foot, worse at night or after standing.", [TARSAL], [SOLE, BURN, NIGHT]],
  ["en", "The patient describes numbness and pins and needles in the sole that spread from the inner ankle. It is worse at night.", [], [TARSAL, SOLE, BURN, NIGHT, MEDA]],
  ["en", "Burning sole. Tingling toes. Night symptoms. Inner ankle.", [], [TARSAL, SOLE, BURN, NIGHT, MEDA]],
  ["en", "They have to take their shoes off at night because the sole of the foot burns and buzzes.", [TARSAL], [SOLE, BURN, NIGHT]],
  ["hi", "Talve mein jalan aur jhunjhuni, raat ko aur der khade rehne par badhti hai.", [], [TARSAL, SOLE, BURN, NIGHT]],
  ["de", "तलवे में जलन और झनझनाहट, रात को और देर खड़े रहने पर बढ़ती है।", [], [TARSAL, SOLE, BURN, NIGHT]],
  ["en", "Gradual.", [], [INSID]],
  ["en", "It came on slowly over weeks.", [], [INSID]],
  ["en", "Gradual onset.", [], [INSID]],
  ["en", "No injury. It built up over a few months.", [], [INSID]],
  ["hi", "Dheere dheere.", [], [INSID]],
  ["de", "धीरे धीरे।", [], [INSID]],
  ["en", "Nerve squeezed behind the inner ankle, often with flat feet.", [], [INSID, MEDA, POSTA]],
  ["en", "A flat foot and a swollen tendon pressing on the nerve.", [], [INSID]],
  ["en", "Nerve compression. Flat foot.", [], [INSID]],
  ["en", "They stand a lot and the arch has dropped over the years.", [], [INSID]],
  ["hi", "Takhne ke andar nas dabna, chapte paer ke saath.", [], [INSID, MEDA]],
  ["de", "टखने के अंदर नस दबना, चपटे पैर के साथ।", [], [INSID, MEDA]],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been several months.", [], []],
  ["en", "Weeks–months.", [], []],
  ["en", "Worse at night for about three months.", [], [NIGHT]],
  ["hi", "Hafte se mahine.", [], []],
  ["de", "हफ्ते से महीने।", [], []],
  ["en", "Pain at the front of the ankle on squatting or going downstairs, with a pinching feeling.", [ANTA, DORSI], [STAIRS]],
  ["en", "The patient has a stab of pain in front of the ankle when they bend the foot up or kick the ball properly.", [ANTA], [DORSI]],
  ["en", "Anterior ankle pain. Pinch on dorsiflexion. Squat and lunge limited.", [ANTA, DORSI], []],
  ["en", "They cannot squat down fully because something blocks and pinches at the front of the ankle.", [ANTA], [DORSI]],
  ["hi", "Takhne ke aage dard, ghutne modkar baithne aur seedhiyan utarne par chubhan.", [ANTA], [DORSI, STAIRS]],
  ["de", "टखने के आगे दर्द, घुटने मोड़कर बैठने और सीढ़ियां उतरने पर चुभन।", [ANTA], [DORSI, STAIRS]],
  ["en", "Gradual, often after earlier sprains.", [], [INSID, INV]],
  ["en", "It built up slowly in a footballer with old sprains.", [], [INSID, INV]],
  ["en", "Gradual; past sprains.", [], [INSID, INV]],
  ["en", "No single event. It got worse over a season of kicking.", [], [INSID, TRAIN]],
  ["hi", "Dheere dheere, purani moch ke baad.", [], [INSID, INV]],
  ["de", "धीरे धीरे, पुरानी मोच के बाद।", [], [INSID, INV]],
  ["en", "Repeated kicking or deep squatting. Footballers and dancers.", [], [INSID, TRAIN]],
  ["en", "Repeated forced bending of the ankle upwards in sport.", [], [INSID, TRAIN]],
  ["en", "Repetitive dorsiflexion. Kicking. Squats.", [], [INSID, TRAIN]],
  ["en", "They kick a lot and squat deeply in training.", [], [INSID, TRAIN]],
  ["hi", "Baar baar laat maarna aur gehra baithna.", [], [INSID, TRAIN]],
  ["de", "बार बार लात मारना और गहरा बैठना।", [], [INSID, TRAIN]],
  ["en", "Months to years.", [], []],
  ["en", "It has been there for a long time.", [], []],
  ["en", "Months–years.", [], []],
  ["en", "Two seasons of on and off pain.", [], [INTER]],
  ["hi", "Mahine se saal.", [], []],
  ["de", "महीने से साल।", [], []],
  ["en", "Heel pain on the first steps in the morning, easing as they walk, and worse after sitting.", [PLANT, FIRST], [MORNIMP, INTER]],
  ["en", "The patient has a sharp pain under the heel when they get out of bed that settles after a few minutes but returns after sitting.", [PLANT, FIRST], [MORNIMP]],
  ["en", "Plantar heel pain. First-step pain. Worse after rest.", [PLANT, FIRST], [MORNIMP]],
  ["en", "They dread the first few steps out of bed because of a stabbing pain in the heel and arch.", [PLANT, FIRST], [MORNIMP]],
  ["hi", "Edi ke neeche dard, subah uthte hi pehle kadam par tez dard, thoda chalne par kam hota hai.", [PLANT, FIRST], [MORNIMP]],
  ["de", "एड़ी के नीचे दर्द, सुबह उठते ही पहले कदम पर तेज़ दर्द, थोड़ा चलने पर कम होता है।", [PLANT, FIRST], [MORNIMP]],
  ["en", "Gradual, no injury.", [INSID], []],
  ["en", "It came on slowly after they started standing all day at work.", [], [INSID]],
  ["en", "Gradual onset.", [INSID], []],
  ["en", "No injury. It started when they began walking more in new shoes.", [INSID], [CHG, TRAIN]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [INSID], []],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [INSID], []],
  ["en", "More standing and walking on hard floors, in flat unsupportive shoes.", [], [CHG, INSID, BAREFOOT]],
  ["en", "A sudden increase in walking or running, or a new pair of shoes.", [TRAIN], [CHG]],
  ["en", "Overload. Hard floors, flat shoes, tight calves.", [], [CHG, INSID, BAREFOOT]],
  ["en", "They work on a hard shop floor all day and recently switched to thin sandals.", [], [CHG, INSID, BAREFOOT]],
  ["hi", "Zyada der sakht farsh par khade rehna aur patli chappal.", [], [CHG, INSID, BAREFOOT]],
  ["de", "ज़्यादा देर सख्त फर्श पर खड़े रहना और पतली चप्पल।", [], [CHG, INSID, BAREFOOT]],
  ["en", "Months. Often settles over 6 to 12 months.", [], []],
  ["en", "It has been going on for a few months.", [], []],
  ["en", "Months.", [], []],
  ["en", "Six months now, better and worse.", [], [INTER]],
  ["hi", "Kai mahine se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "Deep bruise-like pain in the middle of the heel, worse on hard floors and barefoot.", [PLANT, BAREFOOT], []],
  ["en", "The patient feels as if they are walking on a stone bruise under the heel, especially on hard surfaces.", [PLANT], [BAREFOOT]],
  ["en", "Central heel pain. Bruised feeling. Hard floors, barefoot.", [PLANT, BAREFOOT], []],
  ["en", "They get a deep dull ache in the centre of the heel by the end of the day when they stand on concrete.", [PLANT], [BAREFOOT]],
  ["hi", "Edi ke beech mein gehra dard jaise chot lagi ho, sakht farsh par aur nange pair chalne par badhta hai.", [PLANT, BAREFOOT], []],
  ["de", "एड़ी के बीच में गहरा दर्द जैसे चोट लगी हो, सख्त फर्श पर और नंगे पैर चलने पर बढ़ता है।", [PLANT, BAREFOOT], []],
  ["en", "After jumping down onto the heel, or gradually.", [], [FALLH, LAND, INSID]],
  ["en", "It began after a hard landing on the heel.", [], [LAND, FALLH, DIRECT]],
  ["en", "Sudden heel strike, or gradual.", [], [FALLH, LAND, INSID, DIRECT]],
  ["en", "It crept up over weeks of working on concrete.", [], [INSID]],
  ["hi", "Kood kar edi par girne ke baad ya dheere dheere.", [], [FALLH, LAND, INSID]],
  ["de", "कूदकर एड़ी पर गिरने के बाद या धीरे धीरे।", [], [FALLH, LAND, INSID]],
  ["en", "Landing on the heel from a height, or repeated heel strikes on hard ground.", [], [FALLH, LAND, INSID, CHG]],
  ["en", "Jumping onto the heel, or a lot of running on hard roads.", [], [FALLH, LAND, INSID, CHG]],
  ["en", "Impact. Hard ground. Thin shoes.", [], [INSID, CHG]],
  ["en", "They stand on concrete all day in thin-soled shoes.", [], [INSID, CHG]],
  ["hi", "Oonchai se edi par girna ya sakht sadak par daudna.", [], [FALLH, LAND, INSID, CHG]],
  ["de", "ऊंचाई से एड़ी पर गिरना या सख्त सड़क पर दौड़ना।", [], [FALLH, LAND, INSID, CHG]],
  ["en", "Weeks to months.", [], []],
  ["en", "A bruise takes one to three weeks.", [], []],
  ["en", "Weeks–months.", [], []],
  ["en", "A couple of months now.", [], []],
  ["hi", "Hafte se mahine.", [], []],
  ["de", "हफ्ते से महीने।", [], []],
  ["en", "Burning pain in the ball of the foot with tingling in the third and fourth toes. It feels like a pebble in the shoe.", [FORE], [BETW, BURNBETW, TIGHT, BURN, TARSAL]],
  ["en", "The patient has a sharp, burning pain between the third and fourth toes, worse in tight shoes and better when the shoes come off.", [BETW, TIGHT], [BURNBETW, FORE, BURN]],
  ["en", "Interdigital pain, 3rd–4th toes. Burning. Tight shoes.", [TIGHT], [BETW, BURNBETW, FORE]],
  ["en", "They feel a lump or a folded sock under the ball of the foot, and the toes go numb in narrow shoes.", [FORE], [TIGHT, BETW, BURNBETW]],
  ["hi", "Panje ke neeche jalan, teesri aur chauthi ungli ke beech jhunjhuni, tang joote pehanne par badhti hai.", [BETW, TIGHT], [BURNBETW, FORE]],
  ["de", "पंजे के नीचे जलन, तीसरी और चौथी उंगली के बीच झनझनाहट, तंग जूते पहनने पर बढ़ती है।", [BETW, TIGHT], [BURNBETW, FORE]],
  ["en", "Gradual.", [], [INSID]],
  ["en", "It came on slowly over months.", [], [INSID]],
  ["en", "Gradual onset.", [], [INSID]],
  ["en", "No injury. It built up after they started wearing pointed shoes.", [], [INSID, CHG, TIGHT]],
  ["hi", "Dheere dheere.", [], [INSID]],
  ["de", "धीरे धीरे।", [], [INSID]],
  ["en", "Narrow shoes and high heels squeezing the front of the foot.", [], [TIGHT, CHG, INSID]],
  ["en", "Tight pointed shoes for work, or a lot of running.", [], [TIGHT, CHG, INSID, TRAIN]],
  ["en", "Nerve squeeze. Narrow shoes. High heels.", [], [TIGHT, CHG, INSID]],
  ["en", "They wear high heels all day and the front of the foot is squashed.", [], [TIGHT, CHG, INSID]],
  ["hi", "Tang aur nukile joote ya heel se panje par dabaav.", [], [TIGHT, CHG, INSID]],
  ["de", "तंग और नुकीले जूते या हील से पंजे पर दबाव।", [], [TIGHT, CHG, INSID]],
  ["en", "Months.", [], []],
  ["en", "It has been several months.", [], []],
  ["en", "Months.", [], []],
  ["en", "A year of on and off pain.", [], [INTER]],
  ["hi", "Kai mahine se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "Pain under the ball of the foot, worse on walking and pushing off, and in high heels.", [FORE], [WALKRUN, TIGHT]],
  ["en", "The patient has an aching, burning pain under the front of the foot when they stand for long or walk, as if on pebbles.", [FORE], [WALKRUN, BURN]],
  ["en", "Forefoot pain under the metatarsal heads. Push-off. High heels.", [FORE], [WALKRUN, TIGHT]],
  ["en", "They get a bruised feeling under the toes by the afternoon after a day in heels.", [], [FORE, TIGHT]],
  ["hi", "Panje ke neeche dard, chalne aur panje par zor dene par badhta hai, heel pehanne par zyada.", [FORE], [WALKRUN, TIGHT]],
  ["de", "पंजे के नीचे दर्द, चलने और पंजे पर ज़ोर देने पर बढ़ता है, हील पहनने पर ज़्यादा।", [FORE], [WALKRUN, TIGHT]],
  ["en", "Gradual.", [], [INSID]],
  ["en", "It came on slowly over weeks.", [], [INSID]],
  ["en", "Gradual onset.", [], [INSID, TRAIN]],
  ["en", "No injury. It began after they took up running.", [], [INSID, TRAIN]],
  ["hi", "Dheere dheere.", [], [INSID]],
  ["de", "धीरे धीरे।", [], [INSID]],
  ["en", "Running and jumping, high heels, or a high-arched foot.", [], [INSID, TRAIN, TIGHT, CHG]],
  ["en", "A lot of time on the feet in thin-soled or high-heeled shoes.", [], [INSID, TIGHT, CHG]],
  ["en", "Forefoot overload. Heels. High arch.", [], [INSID, TIGHT, CHG, FORE]],
  ["en", "They run on hard roads in worn-out shoes.", [], [INSID, TRAIN, CHG]],
  ["hi", "Daudna, kudna, ya ooncha heel.", [], [INSID, TRAIN, TIGHT]],
  ["de", "दौड़ना, कूदना, या ऊंची हील।", [], [INSID, TRAIN, TIGHT]],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been going on for a few months.", [], []],
  ["en", "Weeks–months.", [], []],
  ["en", "On and off since the summer.", [], [INTER]],
  ["hi", "Hafte se mahine.", [], []],
  ["de", "हफ्ते से महीने।", [], []],
  ["en", "Pain and stiffness in the big toe joint, worse when pushing off and in tight shoes.", [TOE1, TIGHT], [WALKRUN]],
  ["en", "The patient has a stiff, sore big toe joint with a bony bump on top. It hurts to walk and to wear narrow shoes.", [TOE1, TIGHT], [WALKRUN, TOP]],
  ["en", "1st MTP pain. Stiff. Push-off pain. Dorsal bump.", [TOE1], [WALKRUN, TOP]],
  ["en", "They can hardly bend the big toe up, and the joint aches when they walk or squat.", [TOE1], [WALKRUN, DORSI]],
  ["hi", "Anguthe ke jod mein dard aur akdan, chalte waqt zor dene aur tang joote pehanne par badhta hai.", [TOE1, TIGHT], [WALKRUN]],
  ["de", "अंगूठे के जोड़ में दर्द और अकड़न, चलते समय ज़ोर देने और तंग जूते पहनने पर बढ़ता है।", [TOE1, TIGHT], [WALKRUN]],
  ["en", "Gradual over years.", [], [INSID]],
  ["en", "It came on slowly, with the toe getting stiffer.", [], [INSID]],
  ["en", "Gradual onset.", [], [INSID]],
  ["en", "No injury. It has crept up over several years.", [], [INSID]],
  ["hi", "Saalon mein dheere dheere.", [], [INSID]],
  ["de", "सालों में धीरे धीरे।", [], [INSID]],
  ["en", "Wear and tear after an old injury, flat feet, or years of squatting.", [], [INSID]],
  ["en", "The joint has worn out, and flat feet add strain.", [], [INSID]],
  ["en", "Degenerative. Old injury. Flat feet.", [], [INSID]],
  ["en", "Years of work that needed a lot of squatting.", [], [INSID]],
  ["hi", "Purani chot ya chapte paer se ghisaav.", [], [INSID]],
  ["de", "पुरानी चोट या चपटे पैर से घिसाव।", [], [INSID]],
  ["en", "Years.", [], []],
  ["en", "It has been getting worse for years.", [], []],
  ["en", "Years.", [], []],
  ["en", "A long time, with the toe slowly stiffening.", [], []],
  ["hi", "Kai saalon se.", [], []],
  ["de", "कई सालों से।", [], []],
  ["en", "Sudden pain at the base of the big toe after pushing off, with swelling.", [TOE1], [SMOD, SMILD, SSEV, WALKRUN]],
  ["en", "The patient jammed the big toe on the turf and now the big toe joint is swollen and sore when pushing off.", [TOE1], [DIRECT, SMOD, SMILD, WALKRUN]],
  ["en", "Big toe joint sprain. Hyperextension. Painful push-off, swelling.", [TOE1], [SMOD, SMILD, WALKRUN]],
  ["en", "They felt the big toe bend back sharply as they pushed off, and the joint ballooned up.", [], [TOE1, SSEV, SMOD, WALKRUN, DIRECT]],
  ["hi", "Anguthe ke jod mein achanak dard aur sujan, panje se dhakka dene par.", [TOE1], [WALKRUN, SMOD]],
  ["de", "अंगूठे के जोड़ में अचानक दर्द और सूजन, पंजे से धक्का देने पर।", [TOE1], [WALKRUN, SMOD]],
  ["en", "Sudden, during a sprint or a cut.", [], []],
  ["en", "It happened in a flash on the artificial turf.", [], [CHG]],
  ["en", "Sudden.", [], []],
  ["en", "No warning. The toe just bent back.", [], []],
  ["hi", "Achanak.", [], []],
  ["de", "अचानक।", [], []],
  ["en", "The toe was forced upwards while the foot was fixed, on artificial turf in flexible shoes.", [], [DIRECT, CHG]],
  ["en", "Another player stood on the heel while the toe was pressed into the ground.", [], [DIRECT]],
  ["en", "Forced hyperextension. Turf. Flexible shoes.", [], [DIRECT, CHG]],
  ["en", "They pushed off in thin boots on a hard pitch.", [], [CHG]],
  ["hi", "Naqli ghaas par panje ko upar ki taraf mod diya gaya.", [], [DIRECT, CHG]],
  ["de", "नकली घास पर पंजे को ऊपर की तरफ मोड़ दिया गया।", [], [DIRECT, CHG]],
  ["en", "Weeks.", [], []],
  ["en", "It has been two weeks.", [], []],
  ["en", "Weeks.", [], []],
  ["en", "Still sore after ten days.", [], []],
  ["hi", "Kuch hafte.", [], []],
  ["de", "कुछ हफ्ते।", [], []],
  ["en", "Pain on top of the middle of the foot after a twist, worse pushing off, with swelling.", [TOP], [PLANT, WALKRUN, SMOD, SMILD, INV]],
  ["en", "The patient has pain in the midfoot and bruising under the arch after landing awkwardly. It hurts to put weight on it.", [], [TOP, PLANT, LAND, OTTWEIGHT, SMOD]],
  ["en", "Midfoot pain. Dorsal swelling. Push-off pain. Plantar bruising.", [], [TOP, PLANT, WALKRUN, SMOD]],
  ["en", "They feel a deep ache across the top of the foot that gets worse when they stand and push off.", [TOP], [WALKRUN, PLANT]],
  ["hi", "Paer ke upar beech mein dard aur sujan, mudne ke baad, panje se zor dene par badhta hai.", [TOP], [WALKRUN, SMOD]],
  ["de", "पैर के ऊपर बीच में दर्द और सूजन, मुड़ने के बाद, पंजे से ज़ोर देने पर बढ़ता है।", [TOP], [WALKRUN, SMOD]],
  ["en", "Sudden after a twist or a fall, or gradual if it is arthritis.", [], [INV, FALLH, INSID]],
  ["en", "It began after the foot twisted under them.", [], [INV]],
  ["en", "Sudden after a twist, or gradual.", [], [INV, INSID]],
  ["en", "No single event for the arthritis type; it built up over years.", [], [INSID]],
  ["hi", "Mudne ya girne ke baad achanak, ya dheere dheere.", [], [INV, FALLH, INSID]],
  ["de", "मुड़ने या गिरने के बाद अचानक, या धीरे धीरे।", [], [INV, FALLH, INSID]],
  ["en", "Twisted foot, or landing on a pointed foot, or stepping off a kerb.", [], [INV, LAND]],
  ["en", "The foot rolled over and the middle of the foot took the load.", [], [INV, LAND, TOP]],
  ["en", "Twist. Axial load through a pointed foot.", [], [INV, LAND]],
  ["en", "They stepped off a kerb and felt the middle of the foot give.", [], [LAND, INV, TOP]],
  ["hi", "Pair mud gaya ya kood kar utarte waqt zor pada.", [], [INV, LAND]],
  ["de", "पैर मुड़ गया या कूदकर उतरते समय ज़ोर पड़ा।", [], [INV, LAND]],
  ["en", "Weeks for a sprain, years for arthritis.", [], []],
  ["en", "It has been two weeks.", [], []],
  ["en", "Weeks. Or years if arthritis.", [], []],
  ["en", "Still swollen after three weeks.", [], [SMILD, SMOD]],
  ["hi", "Moch ho to hafte, gathiya ho to saal.", [], []],
  ["de", "मोच हो तो हफ्ते, गठिया हो तो साल।", [], []],
  ["en", "The patient is a 38 year old shop assistant from Jaipur.", [], []],
  ["en", "Referred by the family doctor for physiotherapy.", [], []],
  ["en", "Wants to get back to walking the dog every morning.", [], []],
  ["en", "A colleague recommended the clinic.", [], []],
  ["en", "His father had a fracture of the ankle many years ago.", [], []],
  ["en", "Assessment done on Friday and the plan was explained.", [], []],
  ["hi", "Mareez ek dukaan mein kaam karte hain aur Jaipur se aate hain.", [], []],
  ["de", "मरीज़ को डॉक्टर ने फिज़ियोथेरेपी के लिए भेजा है।", [], []],
];

// Same scoring as the other exams, except "may" answers are neutral.
export function scoreSheet(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, must, may] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const okSet = new Set([...must, ...may]);
    for (const g of got) { suggested++; if (okSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of must) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
