// ankleFootWildSets.js -- shared by the Ankle/Foot phrase-matcher tests (not a test itself).
// Sets of messy, real-life sentences written the way students type, each marked with what a physio would
// tick ("field|option"). These answer keys are DRAFTS written by Claude for Aditi to review.
// A = the first exam, used to find what the first draft missed; B and C = fair exams written after the
// earlier sets' fixes and NOT used to tune the matcher until their first run was recorded.
// See ankleFootPhraseMapWild.test.js for the history.
import { ANKLE_FOOT_PHRASES, understandStory } from "../ankleFootPhraseMap.js";

const O = (field, i) => Object.keys(ANKLE_FOOT_PHRASES[field])[i];
const k = (field, i) => `${field}|${O(field, i)}`;
// location
const LATA = k("location", 0), MEDA = k("location", 1), ANTA = k("location", 2), POSTA = k("location", 3), ACHI = k("location", 4), ACHM = k("location", 5),
  PLANT = k("location", 6), TOE1 = k("location", 7), FORE = k("location", 8), BETW = k("location", 9), TOP = k("location", 10), SHIN = k("location", 11);
// radiation
const NORAD = k("radiation", 0), BACK = k("radiation", 1), TARSAL = k("radiation", 2), BURNBETW = k("radiation", 3), SOLE = k("radiation", 4);
// mechanism
const INSID = k("mechanism", 0), INV = k("mechanism", 1), EVER = k("mechanism", 2), HIGH = k("mechanism", 3), DIRECT = k("mechanism", 4),
  FALLH = k("mechanism", 5), LAND = k("mechanism", 6), CHG = k("mechanism", 7), TRAIN = k("mechanism", 8);
// aggravating
const FIRST = k("aggravating", 0), WALKRUN = k("aggravating", 1), DOWNH = k("aggravating", 2), DORSI = k("aggravating", 3), STAIRS = k("aggravating", 4),
  BAREFOOT = k("aggravating", 5), TIGHT = k("aggravating", 6);
// 24-hour pattern (ankle/foot's own six answers)
const INTER = k("pattern", 0), CONST = k("pattern", 1), MORNIMP = k("pattern", 2), WARM = k("pattern", 3), NIGHT = k("pattern", 4), BURN = k("pattern", 5);
// swelling
const SNONE = k("swelling", 0), SMILD = k("swelling", 1), SMOD = k("swelling", 2), SSEV = k("swelling", 3);
// red flags
const OTTBONE = k("redFlags", 0), OTTWEIGHT = k("redFlags", 1), ACHRUP = k("redFlags", 2), ATFL = k("redFlags", 3), STRESS = k("redFlags", 4),
  PERON = k("redFlags", 5), HOTJ = k("redFlags", 6), COMPART = k("redFlags", 7), CANCER = k("redFlags", 8), RFNONE = k("redFlags", 9);
export const KEYS = { LATA, MEDA, ANTA, POSTA, ACHI, ACHM, PLANT, TOE1, FORE, BETW, TOP, SHIN, NORAD, BACK, TARSAL, BURNBETW, SOLE, INSID, INV, EVER, HIGH,
  DIRECT, FALLH, LAND, CHG, TRAIN, FIRST, WALKRUN, DOWNH, DORSI, STAIRS, BAREFOOT, TIGHT, INTER, CONST, MORNIMP, WARM, NIGHT, BURN, SNONE, SMILD, SMOD,
  SSEV, OTTBONE, OTTWEIGHT, ACHRUP, ATFL, STRESS, PERON, HOTJ, COMPART, CANCER, RFNONE };

export const ANKLE_FOOT_A = [
  // ── English ──
  ["en", "rolled my ankle playing football, pain on the outer side", [INV, LATA]],
  ["en", "pain on the inside of the ankle after landing from a jump", [MEDA, LAND]],
  ["en", "heel pain, worst with the first steps in the morning", [PLANT, FIRST]],
  ["en", "pain at the back of the heel where the achilles attaches", [ACHI]],
  ["en", "thickened achilles about 4 cm above the heel, pain on running", [ACHM, WALKRUN]],
  ["en", "pain in the arch of the foot after standing all day", [PLANT]],
  ["en", "big toe joint swollen and painful, I think it is gout", [TOE1]],
  ["en", "pain under the ball of the foot when wearing heels", [FORE, TIGHT]],
  ["en", "sharp pain between the third and fourth toes", [BETW]],
  ["en", "pain on top of the foot after tying shoes tightly", [TOP]],
  ["en", "shin splints when I run on hard roads", [SHIN]],
  ["en", "burning down into the sole and toes, I have tarsal tunnel", [TARSAL]],
  ["en", "pain from my lower back going down to the foot", [BACK]],
  ["en", "burning between the toes", [BURNBETW, BETW]],
  ["en", "the pain goes into the sole of the foot", [SOLE]],
  ["en", "no radiation", [NORAD]],
  ["en", "I started running more and doubled my mileage", [TRAIN]],
  ["en", "got new running shoes last month", [CHG]],
  ["en", "fell from a ladder and landed on my feet", [FALLH]],
  ["en", "someone stepped on my foot", [DIRECT]],
  ["en", "inversion sprain in basketball", [INV]],
  ["en", "high ankle sprain, foot planted and body twisted", [HIGH]],
  ["en", "my ankle rolled outwards", [EVER]],
  ["en", "no injury, the pain came on gradually", [INSID]],
  ["en", "pain going downhill", [DOWNH]],
  ["en", "pain when squatting", [DORSI]],
  ["en", "pain on stairs", [STAIRS]],
  ["en", "pain walking barefoot on tiles", [BAREFOOT]],
  ["en", "narrow shoes hurt", [TIGHT]],
  ["en", "pain when running", [WALKRUN]],
  ["en", "worse in the morning and improves through the day", [MORNIMP]],
  ["en", "it warms up and then gets worse after the run", [WARM]],
  ["en", "burning pain at night", [BURN]],
  ["en", "the pain is worse at night", [NIGHT]],
  ["en", "the pain is constant", [CONST]],
  ["en", "the pain comes and goes", [INTER]],
  ["en", "no swelling", [SNONE]],
  ["en", "mild swelling that goes down by evening", [SMILD]],
  ["en", "the ankle is always swollen", [SMOD]],
  ["en", "it swells up a lot after running", [SSEV]],
  ["en", "tender over the ankle bone", [OTTBONE]],
  ["en", "cannot weight bear since the injury", [OTTWEIGHT]],
  ["en", "heard a pop at the back of the ankle and cannot rise on my toes", [ACHRUP, POSTA]],
  ["en", "the ankle feels very loose and unstable after the sprain, I felt it tear", [ATFL]],
  ["en", "stress fracture suspected, one sore spot on the shin", [STRESS, SHIN]],
  ["en", "the peroneal tendon snaps over the outer ankle bone", [PERON, LATA]],
  ["en", "the ankle is red hot and swollen with fever", [HOTJ]],
  ["en", "the foot is cold and pale and the calf is hard", [COMPART]],
  ["en", "history of cancer", [CANCER]],
  ["en", "no red flags", [RFNONE]],
  // ── must stay silent ──
  ["en", "my knee hurts on stairs", []],
  ["en", "shoulder pain at night", []],
  ["en", "no history of cancer", []],
  ["en", "her aunt had cancer", []],
  ["en", "the shoe shop is closed", []],
  ["en", "I am going to the market tomorrow", []],
  // ── Hinglish ──
  ["hi", "takhna mud gaya khelte waqt, takhne ke bahar dard", [INV, LATA]],
  ["hi", "edi me dard subah pehle kadam par", [PLANT, FIRST]],
  ["hi", "achilles ke beech me dard daudte waqt", [ACHM, WALKRUN]],
  ["hi", "pair ke angutha ke jod me dard aur sujan", [TOE1]],
  ["hi", "pair ke panje me dard jab heels pehenta hoon", [FORE, TIGHT]],
  ["hi", "ungliyon ke beech jalan", [BURNBETW, BETW]],
  ["hi", "talwe me jalan raat ko", [TARSAL, BURN]],
  ["hi", "kamar se pair tak dard jata hai", [BACK]],
  ["hi", "naye joote pehne ke baad dard shuru hua", [CHG]],
  ["hi", "chat se gir gaya", [FALLH]],
  ["hi", "kood kar utarte waqt takhna mud gaya", [LAND, INV]],
  ["hi", "dhalan utarte waqt dard", [DOWNH]],
  ["hi", "seedhiyan chadhte waqt dard", [STAIRS]],
  ["hi", "nange pair chalne se dard", [BAREFOOT]],
  ["hi", "tang joote pehenne se dard", [TIGHT]],
  ["hi", "lagatar dard rehta hai", [CONST]],
  ["hi", "kabhi kabhi dard hota hai", [INTER]],
  ["hi", "sujan nahi hai", [SNONE]],
  ["hi", "thodi sujan jo raat tak utar jati hai", [SMILD]],
  ["hi", "khelne ke baad bahut sujan aa jati hai", [SSEV]],
  ["hi", "pair par bhaar nahi daal pa raha", [OTTWEIGHT]],
  ["hi", "takhna bilkul dheela lagta hai", [ATFL]],
  ["hi", "pair thanda aur peela pad gaya", [COMPART]],
  ["hi", "pehle cancer hua tha", [CANCER]],
  ["hi", "ghutne me dard hai", []],
  ["hi", "kal bazaar jaunga", []],
  // ── Hindi (Devanagari) ──
  ["de", "टखने के बाहर की तरफ दर्द", [LATA]],
  ["de", "एड़ी में दर्द", [PLANT]],
  ["de", "पैर के पंजे में दर्द", [FORE]],
  ["de", "पैर बाहर की तरफ मुड़ गया", [EVER]],
  ["de", "नए जूते पहनने के बाद दर्द", [CHG]],
  ["de", "सीढ़ियां चढ़ते समय दर्द", [STAIRS]],
  ["de", "रात को ज्यादा दर्द", [NIGHT]],
  ["de", "सूजन नहीं है", [SNONE]],
  ["de", "लगातार सूजन", [SMOD]],
  ["de", "पंजों के बल खड़ा नहीं हो पा रहा", [ACHRUP]],
  ["de", "मेरी बहन को कैंसर है", []],
  ["de", "सिर में दर्द है", []],
];

// Set B: the first fair exam. Written after Set A had been used to improve the matcher, and NOT used to tune it afterwards.
export const ANKLE_FOOT_B = [
  // ── English ──
  ["en", "I went over on my ankle on a pavement edge, the outer ankle swelled up like an egg", [INV, LATA]],
  ["en", "sharp pain at the base of the heel when I step out of bed", [PLANT, FIRST]],
  ["en", "stiff achilles in the mornings, pain about 5 cm above the heel bone", [ACHM]],
  ["en", "the back of my heel is tender where the tendon inserts", [ACHI]],
  ["en", "pain under my big toe joint when I push off", [TOE1]],
  ["en", "stabbing pain in the forefoot, like walking on a pebble", [FORE]],
  ["en", "numb patch between my second and third toes with burning", [BURNBETW, BETW]],
  ["en", "swelling and ache over the dorsum of the foot after a long hike", [TOP]],
  ["en", "the front of my lower leg aches along the bone when I run", [SHIN, WALKRUN]],
  ["en", "pins and needles under the sole after standing, worse at night", [TARSAL, NIGHT]],
  ["en", "sciatica from my back shoots down to the foot", [BACK]],
  ["en", "the pain travels from the heel into the sole", [SOLE, PLANT]],
  ["en", "I switched from cushioned trainers to minimalist shoes two weeks ago", [CHG]],
  ["en", "started couch to 5k, three runs a week", [TRAIN]],
  ["en", "slipped off a kerb and my foot turned inwards", [INV]],
  ["en", "twisted it badly, the foot rotated outward with my knee going in", [EVER]],
  ["en", "tackled from the side while my foot was planted, with pain above the ankle", [HIGH]],
  ["en", "a heavy box dropped on my foot", [DIRECT]],
  ["en", "jumped off a compound wall and landed hard on my heels", [FALLH, LAND]],
  ["en", "wearing flip flops all summer, then the pain started", [CHG]],
  ["en", "no obvious cause", [INSID]],
  ["en", "the ankle is stiff and sore whenever I go downhill on a trek", [DOWNH]],
  ["en", "it hurts to crouch down to pick something up", [DORSI]],
  ["en", "I can't walk barefoot on the marble floor", [BAREFOOT]],
  ["en", "my feet hurt in pointy shoes", [TIGHT]],
  ["en", "pain on first getting out of bed that eases after a few minutes", [FIRST]],
  ["en", "after the match the pain gets much worse though it eased during", [WARM]],
  ["en", "burning at night in both feet", [BURN]],
  ["en", "the pain keeps me awake", [NIGHT]],
  ["en", "it never really settles", [CONST]],
  ["en", "only hurts during sport", [INTER]],
  ["en", "she has puffy ankles every evening that go away by morning", [SMILD]],
  ["en", "the swelling has been there for three weeks and is not going down", [SMOD]],
  ["en", "the ankle blows up after every football match", [SSEV]],
  ["en", "pressing on the lower tip of the fibula is very painful", [OTTBONE]],
  ["en", "I couldn't take four steps after the injury", [OTTWEIGHT]],
  ["en", "felt a sudden snap like being shot in the back of the calf", [ACHRUP]],
  ["en", "the ankle has been giving way repeatedly since the sprain and feels loose", [ATFL]],
  ["en", "pain at one spot in the middle of the tibia that I can point to, worse with running", [STRESS, SHIN, WALKRUN]],
  ["en", "the tendon flicks forward over the outer ankle bone when I turn my foot", [PERON, LATA]],
  ["en", "the whole foot is hot, red and puffy and he is shivering", [HOTJ]],
  ["en", "the calf is tight like a balloon and the toes are numb", [COMPART]],
  ["en", "lymphoma five years ago", [CANCER]],
  // ── must stay silent ──
  ["en", "my wrist is swollen", []],
  ["en", "she wore heels to the wedding", []],
  ["en", "the stairs at my office are steep", []],
  ["en", "his father had bone cancer", []],
  ["en", "I will run a marathon next year", []],
  ["en", "no pain at night", []],
  // ── Hinglish ──
  ["hi", "pair ka angutha sujan gaya hai aur bahut dard hai", [TOE1]],
  ["hi", "edi ke neeche chubhne wala dard subah uthte hi", [PLANT, FIRST]],
  ["hi", "takhne ke andar ki taraf sujan aur dard", [MEDA]],
  ["hi", "ungliyon ke beech me tez dard", [BETW]],
  ["hi", "pair ke upar sujan aur dard joota pehenne ke baad", [TOP]],
  ["hi", "shin ki haddi me dard daudne par", [SHIN, WALKRUN]],
  ["hi", "kamar ka dard pair tak utarta hai", [BACK]],
  ["hi", "talwe tak dard fail jata hai", [SOLE]],
  ["hi", "naye shoes lene ke baad dard shuru hua", [CHG]],
  ["hi", "football me tackle hua aur takhna andar mud gaya", [INV]],
  ["hi", "zyada daudne ki wajah se dard shuru hua", [INSID]],
  ["hi", "seedhiyan utarte waqt pair me dard", [DORSI]],
  ["hi", "sujan raat tak utar jati hai", [SMILD]],
  ["hi", "hamesha sujan rehti hai", [SMOD]],
  ["hi", "khelne ke baad takhna bahut phool jata hai", [SSEV]],
  ["hi", "takhne ki haddi dabane par bahut dard", [OTTBONE]],
  ["hi", "ek kadam bhi nahi rakh pa raha", [OTTWEIGHT]],
  ["hi", "panjon ke bal chalna mushkil ho gaya aur peeche pop ki awaaz aayi", [ACHRUP]],
  ["hi", "stress fracture ka shak hai shin me", [STRESS, SHIN]],
  ["hi", "raat ko pair jalte hain", [BURN]],
  ["hi", "raat ko dard badh jata hai", [NIGHT]],
  ["hi", "dard subah zyada hota hai aur din me kam", [MORNIMP]],
  ["hi", "sirf sports ke time dard", [INTER]],
  ["hi", "mere papa ko cancer hai", []],
  ["hi", "sir me dard hai", []],
  ["hi", "chai pi li", []],
  // ── Hindi (Devanagari) ──
  ["de", "टखने के पीछे दर्द", [POSTA]],
  ["de", "एड़ी के नीचे चुभने वाला दर्द", [PLANT]],
  ["de", "पैर के अंगूठे में दर्द", [TOE1]],
  ["de", "ढलान उतरते समय दर्द", [DOWNH]],
  ["de", "नंगे पैर चलने में दर्द", [BAREFOOT]],
  ["de", "तंग जूते पहनने से दर्द", [TIGHT]],
  ["de", "रात को जलन", [BURN]],
  ["de", "सूजन उतरती ही नहीं", [SMOD]],
  ["de", "पैर पर खड़ा नहीं हो पा रहा", [OTTWEIGHT]],
  ["de", "मेरे पिताजी को कैंसर था", []],
  ["de", "आज धूप है", []],
];

// Set C: the second fair exam, written after Set B's fixes. Its first run is the best estimate of how the matcher does
// on typing it has never seen; it was used to improve the matcher only afterwards (see ankleFootPhraseMapWild.test.js).
export const ANKLE_FOOT_C = [
  // ── English ──
  ["en", "twisted my left ankle stepping off the bus, swelling on the outside", [INV, LATA]],
  ["en", "plantar fasciitis diagnosed last year, worst when I get up", [PLANT, FIRST]],
  ["en", "pain in the tendon just above my heel when I push off to run", [ACHM]],
  ["en", "bunion on my right foot is red and sore", [TOE1]],
  ["en", "it feels like walking on stones under the ball of my foot", [FORE]],
  ["en", "tingling in the toe web, especially the third and fourth", [BETW, BURNBETW]],
  ["en", "an ache on the dorsum of the foot where the laces sit", [TOP]],
  ["en", "the inner side of the shin is tender, I have been training for a half marathon", [SHIN, TRAIN]],
  ["en", "burning pain in the soles of both feet, worse at night", [TARSAL, BURN]],
  ["en", "my sciatic pain goes down to my ankle and foot", [BACK]],
  ["en", "pain shoots into the sole when I stand on tiptoe", [SOLE]],
  ["en", "stepped on a stone and my foot rolled in", [INV]],
  ["en", "kicked hard on the shin during a football match", [DIRECT, SHIN]],
  ["en", "dropped from the first floor balcony and landed on both feet", [FALLH]],
  ["en", "the pain began after I moved from sandals to football boots", [CHG]],
  ["en", "doubled my weekly distance in a month", [TRAIN]],
  ["en", "pain going down the hill on our trip", [DOWNH]],
  ["en", "it hurts to kneel down on the prayer mat", [DORSI]],
  ["en", "my arches ache when I walk barefoot on the hard tile floor", [PLANT, BAREFOOT]],
  ["en", "my toes are squashed in these tight sports shoes", [TIGHT]],
  ["en", "stiffness on waking that loosens within half an hour", [MORNIMP]],
  ["en", "once I start running it feels fine then it hurts after", [WARM]],
  ["en", "I wake up with burning feet", [BURN]],
  ["en", "the pain is there from morning till night", [CONST]],
  ["en", "off and on pain depending on the day", [INTER]],
  ["en", "no puffiness", [SNONE]],
  ["en", "slight swelling in the evening but gone by morning", [SMILD]],
  ["en", "the swelling stays all week and never really goes", [SMOD]],
  ["en", "it swells massively after a long walk or a run", [SSEV, WALKRUN]],
  ["en", "very tender when I press the bump on the inside of the ankle", [OTTBONE, MEDA]],
  ["en", "I could not bear any weight at all", [OTTWEIGHT]],
  ["en", "it snapped like a gunshot in the heel cord and now I can't push up on my toes", [ACHRUP]],
  ["en", "the ankle gave way again and again after the first sprain and the joint feels floppy", [ATFL]],
  ["en", "pinpoint tenderness on the tibia, worse with each run", [STRESS, SHIN, WALKRUN]],
  ["en", "I feel a click on the outside of my ankle bone when I twist", [PERON, LATA]],
  ["en", "my foot is swollen, burning hot and red, with a fever of 102", [HOTJ]],
  ["en", "the foot is white and cold and I cannot feel it", [COMPART]],
  ["en", "I am a cancer survivor", [CANCER]],
  ["en", "the doctor says no red flags", [RFNONE]],
  // ── must stay silent ──
  ["en", "my hip hurts at night", []],
  ["en", "my cousin had a stress fracture", []],
  ["en", "I bought a pair of shoes", []],
  ["en", "the stairs were slippery", []],
  ["en", "no history of cancer", []],
  ["en", "my heel is fine, the knee is the problem", []],
  ["en", "going to the gym tomorrow", []],
  // ── Hinglish ──
  ["hi", "takhne ke andar ki taraf dard aur moch", [MEDA, INV]],
  ["hi", "edi ke peeche nas me dard daudne se", [ACHI, WALKRUN]],
  ["hi", "pair ke aage ke hisse me jalan aur sunnpan", [FORE]],
  ["hi", "pair ki ungliyon ke beech sunnpan", [BURNBETW, BETW]],
  ["hi", "shin splints ho gaye hain", [SHIN]],
  ["hi", "naye chappal pehenne ke baad takhne me dard", [CHG]],
  ["hi", "unchai se kood kar pair mud gaya", [FALLH, LAND]],
  ["hi", "dhalan par daudne se pair me dard", [DOWNH]],
  ["hi", "nange pair tiles par dard", [BAREFOOT]],
  ["hi", "heels pehenne se pair dukhta hai", [TIGHT]],
  ["hi", "subah ka dard din me kam ho jata hai", [MORNIMP]],
  ["hi", "pair jalte rehte hain raat ko", [BURN]],
  ["hi", "sujan nahi aati", [SNONE]],
  ["hi", "kabhi kabhi hi sujan aati hai jo shaam tak utar jati hai", [SMILD]],
  ["hi", "poore pair me sujan hai jo kam hi nahi hoti", [SMOD]],
  ["hi", "daudne ke baad takhna bahut phool jata hai", [SSEV]],
  ["hi", "takhna chhune par haddi pe dard", [OTTBONE]],
  ["hi", "meri mummy ko cancer tha", []],
  ["hi", "mausam kaisa hai", []],
  // ── Hindi (Devanagari) ──
  ["de", "टखने के अंदर की तरफ दर्द", [MEDA]],
  ["de", "एड़ी के पीछे दर्द", [ACHI]],
  ["de", "उंगलियों के बीच जलन", [BURNBETW, BETW]],
  ["de", "चलने में दर्द", [WALKRUN]],
  ["de", "सुबह पहले कदम पर दर्द", [FIRST]],
  ["de", "रात को ज्यादा दर्द", [NIGHT]],
  ["de", "हल्की सूजन रात तक उतर जाती है", [SMILD]],
  ["de", "पैर पर वजन नहीं डाल पा रहा", [OTTWEIGHT]],
  ["de", "मेरी मां को कैंसर था", []],
  ["de", "बारिश हो रही है", []],
];

export function score(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, want] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const wantSet = new Set(want);
    for (const g of got) { suggested++; if (wantSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of want) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
