// cervicalWildSets.js -- shared by the Cervical phrase-matcher tests (not a test itself).
// Sets of messy, real-life sentences written the way students type, each marked with what a physio would
// tick ("field|option"). These answer keys are DRAFTS written by Claude for Aditi to review.
// A = the first exam, used to find what the first draft missed; B and C = fair exams written after the
// earlier sets' fixes and NOT used to tune the matcher until their first run was recorded.
// See cervicalPhraseMapWild.test.js for the history.
import { CERVICAL_PHRASES, understandStory } from "../cervicalPhraseMap.js";

const ks = (field) => Object.keys(CERVICAL_PHRASES[field]).map((o) => `${field}|${o}`);
// location
const [SUBOCC, UPPERC, MIDC, LOWERC, ANTN, POSTN, LATL, LATR, CTJ, TRAPL, TRAPR, LEVAT, SCM, SCAL] = ks("location");
// radiation
const [RNONE, ROCC, REYE, RTEMP, RJAW, REAR, RSHTOP, RSHL, RSHR, RARML, RARMR, RHANDL, RHANDR, RBIL, RCHEST, RBLADE] = ks("radiation");
// mechanism
const [MINS, MREAR, MFRONT, MSIDE, MHFLEX, MHEXT, MFLROT, MDIRECT, MDIVE, MPOST, MSLEEP, MLIFT, MSURG, MILL] = ks("mechanismType");
// arm / hand, Lhermitte
const [ANO, AL, AR, ABIL] = ks("armPresent");
const [LNO, LYES, LUNS, LNOT] = ks("lhermitte");
// aggravating / relieving movements
const [GFLEX, GEXT, GROTL, GROTR, GSBL, GSBR, GQL, GQR, GFLROT, GSUST, GQUICK, GALL] = ks("aggMovements");
const [VCHIN, VRETR, VEXT, VFLEX, VROTL, VROTR, VMCK, VSCAP, VELEV, VARM, VSTRETCH, VSHOWER] = ks("relMovements");
// 24-hour pattern, headache
const [PCONST, PCONSTVAR, PINTTRIG, PINTUNP, PACT, PPOS, PMORN, PEVE, PNIGHT, PFLARE, PWARM, PGONE] = ks("overallPattern");
const [HNO, HPRIM, HSEC, HCONC, HPREV] = ks("haPresent");
// red flags
const [MYNO, MYHAND, MYFINE, MYGAIT, MYFALL, MYLEG, MYHYPER, MYBAB, MYHOFF, MYBLAD, MYBOW, MYLHER, MYPROG] = ks("redFlagsMyelopathy");
const [VNO, VDIZ, VDIP, VDROP, VDYS, VDYSP, VATAX, VNAUS, VNYS, VNUMB, VTHUN, VHORN] = ks("redFlagsVbi");
const [INNO, INRA, INDOWN, INTRAUMA, INFUSION, INUNST, INOCC, INSPASM, INFLEX] = ks("redFlagsInstability");
const [OTNO, OTDISS, OTTHUN, OTCA, OTHIGH, OTTORT, OTCONST] = ks("redFlagsOther");
const [FRNA, FRHIGH, FRAXIAL, FRSPASM, FRSPLINT, FRNEURO, FRODON, FRNEXUS, FRCAN, FRFACET, FRCLAY] = ks("fractureScreen");
// function
const [NNONE, NDRIVE, NSHOULDER, NCOMP, NREAD, NTV, NSLEEP, NHAIR, NOVER, NCARRY, NSPORT, NWORK, NCHILD, NSEX, NCONC, NSOCIAL] = ks("fnAdl");
export const KEYS = {
  SUBOCC, UPPERC, MIDC, LOWERC, ANTN, POSTN, LATL, LATR, CTJ, TRAPL, TRAPR, LEVAT, SCM, SCAL,
  RNONE, ROCC, REYE, RTEMP, RJAW, REAR, RSHTOP, RSHL, RSHR, RARML, RARMR, RHANDL, RHANDR, RBIL, RCHEST, RBLADE,
  MINS, MREAR, MFRONT, MSIDE, MHFLEX, MHEXT, MFLROT, MDIRECT, MDIVE, MPOST, MSLEEP, MLIFT, MSURG, MILL,
  ANO, AL, AR, ABIL, LNO, LYES, LUNS, LNOT,
  GFLEX, GEXT, GROTL, GROTR, GSBL, GSBR, GQL, GQR, GFLROT, GSUST, GQUICK, GALL,
  VCHIN, VRETR, VEXT, VFLEX, VROTL, VROTR, VMCK, VSCAP, VELEV, VARM, VSTRETCH, VSHOWER,
  PCONST, PCONSTVAR, PINTTRIG, PINTUNP, PACT, PPOS, PMORN, PEVE, PNIGHT, PFLARE, PWARM, PGONE,
  HNO, HPRIM, HSEC, HCONC, HPREV,
  MYNO, MYHAND, MYFINE, MYGAIT, MYFALL, MYLEG, MYHYPER, MYBAB, MYHOFF, MYBLAD, MYBOW, MYLHER, MYPROG,
  VNO, VDIZ, VDIP, VDROP, VDYS, VDYSP, VATAX, VNAUS, VNYS, VNUMB, VTHUN, VHORN,
  INNO, INRA, INDOWN, INTRAUMA, INFUSION, INUNST, INOCC, INSPASM, INFLEX,
  OTNO, OTDISS, OTTHUN, OTCA, OTHIGH, OTTORT, OTCONST,
  FRNA, FRHIGH, FRAXIAL, FRSPASM, FRSPLINT, FRNEURO, FRODON, FRNEXUS, FRCAN, FRFACET, FRCLAY,
  NNONE, NDRIVE, NSHOULDER, NCOMP, NREAD, NTV, NSLEEP, NHAIR, NOVER, NCARRY, NSPORT, NWORK, NCHILD, NSEX, NCONC, NSOCIAL,
};

export const CERVICAL_A = [
  // ── English ──
  ["en", "pain at the back of the neck for two weeks, started after sitting at the laptop for hours every day", [POSTN, MPOST]],
  ["en", "sharp pain on the left side of my neck when I turn my head to the left", [LATL, GROTL]],
  ["en", "pain on the right side of the neck, turning to the right is the worst", [LATR, GROTR]],
  ["en", "pain at the base of my skull and a headache that comes from the neck", [SUBOCC, HSEC]],
  ["en", "she has pain in the left trapezius, it feels like a knot", [TRAPL]],
  ["en", "tight right upper trap after driving", [TRAPR]],
  ["en", "pain at the front of the neck", [ANTN]],
  ["en", "tenderness over the sternocleidomastoid muscle", [SCM]],
  ["en", "lower neck pain near the shoulders", [LOWERC]],
  ["en", "pain in the middle of the neck", [MIDC]],
  ["en", "the pain goes down my left arm to the elbow", [RARML, AL]],
  ["en", "pain and tingling in the right arm and fingers", [RARMR, RHANDR, AR]],
  ["en", "tingling in my left hand", [RHANDL, AL]],
  ["en", "pins and needles in both hands", [RBIL, ABIL, MYHAND]],
  ["en", "pain goes to the top of the shoulder", [RSHTOP]],
  ["en", "pain spreads into the back of the head", [ROCC]],
  ["en", "pain behind my eye on the same side", [REYE]],
  ["en", "pain spreads to the jaw", [RJAW]],
  ["en", "pain between the shoulder blades as well", [RBLADE]],
  ["en", "the pain stays in the neck and does not spread", [RNONE]],
  ["en", "no pins and needles in the arms", [ANO]],
  ["en", "rear ended at a traffic light last month, whiplash", [MREAR]],
  ["en", "head on collision, the head went forward and back", [MFRONT]],
  ["en", "woke up with a stiff neck after sleeping on the sofa", [MSLEEP]],
  ["en", "slowly got worse over months, no injury", [MINS]],
  ["en", "dived into the shallow end of a pool and hit my head", [MDIVE, FRHIGH]],
  ["en", "pain started after a heavy box was lifted", [MLIFT]],
  ["en", "after the neck operation the pain started", [MSURG]],
  ["en", "looking down at my phone makes it worse", [GFLEX]],
  ["en", "looking up at the ceiling hurts", [GEXT]],
  ["en", "bending my neck to the left is painful", [GSBL]],
  ["en", "tilting my head to the right makes it sharp", [GSBR]],
  ["en", "looking up and to the right is the worst position", [GQR]],
  ["en", "all movements hurt the same", [GALL]],
  ["en", "sudden jerky movements set it off", [GQUICK]],
  ["en", "staying in one position for hours makes it worse", [GSUST]],
  ["en", "chin tucks help", [VCHIN]],
  ["en", "pulling my shoulders back eases it", [VSCAP]],
  ["en", "putting my hand on top of my head relieves the arm pain", [VARM]],
  ["en", "a hot shower on my neck helps", [VSHOWER]],
  ["en", "gentle stretching relieves it", [VSTRETCH]],
  ["en", "shrugging my shoulders up gives relief", [VELEV]],
  ["en", "constant pain that never goes away", [PCONST]],
  ["en", "it comes and goes with no pattern", [PINTUNP]],
  ["en", "worse in the morning when I wake up", [PMORN]],
  ["en", "pain builds up through the day and is worst in the evening", [PEVE]],
  ["en", "worse at night, it wakes me up", [PNIGHT]],
  ["en", "it warms up and eases once I get moving", [PWARM]],
  ["en", "totally pain free between episodes", [PGONE]],
  ["en", "no headache", [HNO]],
  ["en", "the headaches are the main problem", [HPRIM]],
  ["en", "she used to get headaches years ago", [HPREV]],
  ["en", "electric shock down the spine when I bend my neck forward", [LYES, MYLHER]],
  ["en", "no electric shocks", [LNO]],
  ["en", "both legs feel weak and stiff", [MYLEG]],
  ["en", "difficulty doing up my buttons", [MYFINE]],
  ["en", "unsteady on my feet and falling", [MYGAIT]],
  ["en", "new bladder problems since the pain started", [MYBLAD]],
  ["en", "double vision when I look to one side", [VDIP]],
  ["en", "dizzy when I turn my neck", [VDIZ]],
  ["en", "slurred speech", [VDYS]],
  ["en", "difficulty swallowing food", [VDYSP]],
  ["en", "drop attacks, legs just give way", [VDROP]],
  ["en", "numbness around the mouth", [VNUMB]],
  ["en", "she has rheumatoid arthritis", [INRA]],
  ["en", "he has down syndrome", [INDOWN]],
  ["en", "had a cervical fusion two years ago", [INFUSION]],
  ["en", "feels like the head is too heavy for the neck", [INUNST]],
  ["en", "severe muscle spasm, guarding the neck", [INSPASM]],
  ["en", "no instability signs", [INNO]],
  ["en", "stiff neck with a high fever", [OTTORT]],
  ["en", "thunderclap headache", [VTHUN, OTTHUN]],
  ["en", "history of cancer in the spine", [OTCA]],
  ["en", "night sweats and weight loss with the neck pain", [OTCONST]],
  ["en", "no other red flags", [OTNO]],
  ["en", "landed on my head", [FRAXIAL]],
  ["en", "cannot move the neck at all", [FRSPLINT]],
  ["en", "fell from a ladder", [FRHIGH]],
  ["en", "clay shoveler fracture", [FRCLAY]],
  ["en", "difficulty driving, cannot turn to check my blind spot", [NDRIVE]],
  ["en", "cant look at a computer screen for long", [NCOMP]],
  ["en", "difficulty sleeping because of the pain", [NSLEEP]],
  ["en", "cannot lift my toddler", [NCHILD]],
  ["en", "hair washing is difficult", [NHAIR]],
  ["en", "no limitations in daily activities", [NNONE]],
  // ── must stay silent ──
  ["en", "my knee hurts at night", []],
  ["en", "lower back pain when I bend forward", []],
  ["en", "the weather is nice today", []],
  ["en", "my friend had a whiplash injury", []],
  ["en", "no history of cancer", []],
  ["en", "her sister has rheumatoid arthritis", []],
  ["en", "I did not fall or hit my head", []],
  ["en", "the MRI report was normal", []],
  ["en", "plantar fasciitis in the right foot", []],
  ["en", "she works at a bank", []],
  // ── Hinglish ──
  ["hi", "gardan ke peeche dard hai", [POSTN]],
  ["hi", "gardan ke bayen taraf dard hota hai", [LATL]],
  ["hi", "dayen kandhe ke upar maspeshi me dard", [TRAPR]],
  ["hi", "gardan se dard bayen haath me jhunjhuni ke saath aata hai", [RHANDL, AL]],
  ["hi", "dono haathon me sunnpan", [RBIL, ABIL, MYHAND]],
  ["hi", "neeche dekhne par gardan me dard badhta hai", [GFLEX]],
  ["hi", "upar dekhne par dard", [GEXT]],
  ["hi", "raat ko dard se neend khul jati hai", [PNIGHT]],
  ["hi", "subah uthte hi gardan akad jati hai", [PMORN]],
  ["hi", "galat takiye par sone se gardan jam gayi", [MSLEEP]],
  ["hi", "peeche se takkar lagi gaadi ki", [MREAR]],
  ["hi", "sir ke peeche tak dard jata hai", [ROCC]],
  ["hi", "chakkar aate hain jab gardan ghumata hoon", [VDIZ]],
  ["hi", "pairon me kamzori aur akdan", [MYLEG]],
  ["hi", "gaadi chalane me dikkat hoti hai", [NDRIVE]],
  ["hi", "mere dost ki gardan me dard hai", []],
  ["hi", "ghutne me dard hai", []],
  ["hi", "aaj bahut garmi hai", []],
  // ── Hindi (Devanagari) ──
  ["de", "गर्दन के पीछे दर्द है", [POSTN]],
  ["de", "बाएं तरफ गर्दन में दर्द", [LATL]],
  ["de", "नीचे देखने पर दर्द", [GFLEX]],
  ["de", "रात को दर्द से नींद खुल जाती है", [PNIGHT]],
  ["de", "दोनों हाथों में झनझनाहट", [RBIL, ABIL, MYHAND]],
  ["de", "सिर के पीछे तक दर्द जाता है", [ROCC]],
  ["de", "गर्दन घुमाने पर चक्कर आते हैं", [VDIZ]],
  ["de", "मेरी बहन को गठिया है", []],
  ["de", "पेट में दर्द है", []],
];

export const CERVICAL_B = [
  // ── English ──
  ["en", "38 yr old accountant, ache across the back of the neck and tight left trap, worse by the end of the day at the desk", [POSTN, TRAPL, PEVE]],
  ["en", "c/o pain on the right side of the neck going into the shoulder and upper arm", [LATR, RSHR, AR]],
  ["en", "she says the pain starts in the neck and shoots down to the fingers of the left hand", [RHANDL, AL]],
  ["en", "neck pain with tingling in the right thumb and index finger", [RHANDR, AR]],
  ["en", "dull pain around the base of the skull on both sides", [SUBOCC]],
  ["en", "pain high up in the neck just under the skull", [UPPERC, SUBOCC]],
  ["en", "knot between the neck and the left shoulder blade", [LEVAT]],
  ["en", "pain also felt behind the ear and in the temple", [REAR, RTEMP]],
  ["en", "he gets a pain around the jaw and ear on the same side", [RJAW, REAR]],
  ["en", "the ache goes up into the back of the head like a band", [ROCC]],
  ["en", "the pain spreads to the front of the chest", [RCHEST]],
  ["en", "pain referred over the top of the right shoulder", [RSHTOP]],
  ["en", "pins and needles in both arms and hands", [RBIL, ABIL, MYHAND]],
  ["en", "no arm symptoms at all", [ANO]],
  ["en", "car hit me from behind while stopped at lights", [MREAR]],
  ["en", "side impact crash on the driver's side", [MSIDE]],
  ["en", "head snapped back and then forward in the collision", [MHEXT, MHFLEX]],
  ["en", "something heavy fell on my head from a shelf", [MDIRECT, FRAXIAL]],
  ["en", "looking at my phone for hours with my head down", [MPOST]],
  ["en", "the pain began about a week after a bad flu", [MILL]],
  ["en", "lifted a heavy suitcase and felt a pull in the neck", [MLIFT]],
  ["en", "no obvious cause, it just built up", [MINS]],
  ["en", "pain after the fusion surgery", [MSURG, INFUSION]],
  ["en", "turning to the left hurts", [GROTL]],
  ["en", "pain when I look over my right shoulder", [GROTR]],
  ["en", "looking up with my head tilted back is painful", [GEXT]],
  ["en", "bending the head to the right side is sore", [GSBR]],
  ["en", "looking down and turning at the same time is bad", [GFLROT]],
  ["en", "quick head movements are painful", [GQUICK]],
  ["en", "keeping my neck in one posture for a long time brings it on", [GSUST]],
  ["en", "retraction exercises make it feel better", [VRETR]],
  ["en", "looking down eases the pain", [VFLEX]],
  ["en", "tilting my head back gives relief", [VEXT]],
  ["en", "turning to the right relieves it", [VROTR]],
  ["en", "putting the arm up over my head takes away the arm tingling", [VARM]],
  ["en", "heat in the shower helps the stiffness", [VSHOWER]],
  ["en", "there is a directional preference, repeated movements in one direction help", [VMCK]],
  ["en", "squeezing my shoulder blades together helps", [VSCAP]],
  ["en", "it is there all the time but some hours are worse than others", [PCONSTVAR]],
  ["en", "pain only comes on when I do certain things and settles after", [PINTTRIG]],
  ["en", "only hurts during activity", [PACT]],
  ["en", "pain only in certain positions", [PPOS]],
  ["en", "constant ache with flare ups every few weeks", [PFLARE, PCONST]],
  ["en", "stiff in the morning, better after a few minutes of moving", [PWARM, PMORN]],
  ["en", "pain wakes me during the night", [PNIGHT]],
  ["en", "headache is the main thing that brings her in", [HPRIM]],
  ["en", "neck pain then a headache starts from the base of the skull", [HSEC, SUBOCC]],
  ["en", "he also gets migraines which are separate", [HCONC]],
  ["en", "shock like feeling down my back when I put my chin on my chest", [LYES, MYLHER]],
  ["en", "not sure about the electric shock thing", [LUNS]],
  ["en", "both hands are clumsy and numb, dropping cups", [MYHAND, ABIL, RBIL]],
  ["en", "my handwriting has got a lot worse", [MYFINE]],
  ["en", "walking is wobbly, wide based gait", [MYGAIT]],
  ["en", "she has had several falls with no reason", [MYFALL]],
  ["en", "legs feel stiff and heavy", [MYLEG]],
  ["en", "hyperreflexia on examination", [MYHYPER]],
  ["en", "babinski is positive", [MYBAB]],
  ["en", "hoffmans sign positive", [MYHOFF]],
  ["en", "she cant control her bowels since this started", [MYBOW]],
  ["en", "symptoms are getting worse quickly over days", [MYPROG]],
  ["en", "no myelopathy signs", [MYNO]],
  ["en", "seeing double now and then", [VDIP]],
  ["en", "feels sick when she turns her head", [VNAUS]],
  ["en", "drooping eyelid on one side", [VHORN]],
  ["en", "his eyes flicker from side to side", [VNYS]],
  ["en", "trouble coordinating my movements, bumping into things", [VATAX]],
  ["en", "numb face on one side", [VNUMB]],
  ["en", "no vbi signs", [VNO]],
  ["en", "she had a bad fall and head injury last week", [INTRAUMA, MDIRECT]],
  ["en", "constant pain at the base of the skull that nothing relieves", [INOCC, PCONST, SUBOCC]],
  ["en", "sharp pain when I drop my chin to my chest", [INFLEX]],
  ["en", "suspected vertebral artery dissection", [OTDISS]],
  ["en", "neck pain with a sudden explosive headache, worst of my life", [VTHUN, OTTHUN, HSEC]],
  ["en", "serious accident on the motorway, neck injury", [OTHIGH, FRHIGH]],
  ["en", "weight loss and night sweats with the neck pain", [OTCONST]],
  ["en", "elderly lady fell and has neck pain", [FRODON]],
  ["en", "numb straight after the fall", [FRNEURO]],
  ["en", "immediate severe pain and spasm after the injury", [FRSPASM]],
  ["en", "nexus criteria not cleared", [FRNEXUS]],
  ["en", "canadian c spine rule high risk", [FRCAN]],
  ["en", "bilateral facet dislocation", [FRFACET]],
  ["en", "cannot reverse the car because I cant turn my head", [NDRIVE]],
  ["en", "worried about checking over my shoulder on the road", [NSHOULDER]],
  ["en", "reading a book for more than ten minutes hurts", [NREAD, GFLEX]],
  ["en", "watching tv is a problem", [NTV]],
  ["en", "cant hang the washing on the line", [NOVER]],
  ["en", "carrying a rucksack is difficult", [NCARRY]],
  ["en", "had to stop playing badminton", [NSPORT]],
  ["en", "struggling at work", [NWORK]],
  ["en", "sex is painful", [NSEX]],
  ["en", "cannot concentrate because of the headaches", [NCONC]],
  ["en", "avoiding social events", [NSOCIAL]],
  // ── must stay silent ──
  ["en", "my left ankle is swollen", []],
  ["en", "thoracic pain between the shoulder blades only", [RBLADE]],
  ["en", "he has a cousin with neck pain", []],
  ["en", "hip pain on walking", []],
  ["en", "my mother has rheumatoid arthritis", []],
  ["en", "no dizziness and no double vision", []],
  ["en", "the patient is a 40 year old teacher", []],
  ["en", "my uncle had spine cancer", []],
  ["en", "knee surgery last year", []],
  ["en", "booked for a follow up in two weeks", []],
  // ── Hinglish ──
  ["hi", "gardan ke dayen taraf dard aur dayen haath me jhunjhuni", [LATR, RHANDR, AR]],
  ["hi", "gardan ke aage dard hota hai", [ANTN]],
  ["hi", "gardan ke beech me dard hai", [MIDC]],
  ["hi", "kaan ke peeche aur sir ke ek taraf dard", [REAR]],
  ["hi", "dard kandhe tak aur bayen bazu tak utarta hai", [RSHL, RARML, AL]],
  ["hi", "gardan ghumane par bayen taraf dard", [GROTL]],
  ["hi", "gardan peeche karne par dard badhta hai", [GEXT]],
  ["hi", "mobile dekhne par gardan me dard badhta hai", [GFLEX, NCOMP]],
  ["hi", "garam paani se nahane se aaram milta hai", [VSHOWER]],
  ["hi", "halka stretching karne se dard kam hota hai", [VSTRETCH]],
  ["hi", "shaam ko dard sabse zyada hota hai", [PEVE]],
  ["hi", "hamesha dard rehta hai", [PCONST]],
  ["hi", "sir dard nahi hai", [HNO]],
  ["hi", "chalte waqt ladkhadata hoon", [MYGAIT]],
  ["hi", "button lagane me dikkat hoti hai", [MYFINE]],
  ["hi", "do do dikhta hai", [VDIP]],
  ["hi", "bolne me ladkhadahat hai", [VDYS]],
  ["hi", "nigalne me takleef hai", [VDYSP]],
  ["hi", "chehre par sunnpan hai", [VNUMB]],
  ["hi", "computer par kaam karne me dikkat", [NCOMP]],
  ["hi", "sone me dikkat hoti hai dard ki wajah se", [NSLEEP]],
  ["hi", "mere cousin ko gardan dard hai", []],
  ["hi", "kamar me dard hai", []],
  ["hi", "kal barish hui", []],
  // ── Hindi (Devanagari) ──
  ["de", "गर्दन के दाएं तरफ दर्द", [LATR]],
  ["de", "बाएं हाथ में झनझनाहट", [RHANDL, AL]],
  ["de", "ऊपर देखने पर दर्द", [GEXT]],
  ["de", "शाम को ज्यादा दर्द", [PEVE]],
  ["de", "सुबह उठते ही गर्दन में दर्द", [PMORN]],
  ["de", "दो दो दिखता है", [VDIP]],
  ["de", "निगलने में दिक्कत", [VDYSP]],
  ["de", "गाड़ी चलाने में दिक्कत", [NDRIVE]],
  ["de", "मेरे चाचा को गर्दन में कैंसर था", []],
  ["de", "घुटने में दर्द है", []],
];
export const CERVICAL_C = [
  // ── English ──
  ["en", "26F, software tester, WFH. dull ache at the back of the neck radiating into the right shoulder, worse towards evening", [POSTN, RSHR, PEVE]],
  ["en", "sharp stabbing pain on the left side of my neck when I turn to look at the person next to me", [LATL]],
  ["en", "pain on top of both shoulders and at the base of the neck", [RSHTOP, CTJ]],
  ["en", "tenderness over the right levator scapulae", [LEVAT]],
  ["en", "pain is mostly in the scalenes", [SCAL]],
  ["en", "my right upper trapezius is really tight and knotted", [TRAPR]],
  ["en", "numbness and pins and needles in the little finger of the left hand", [RHANDL, AL]],
  ["en", "pain comes down the back of the right arm to the elbow", [RARMR, AR]],
  ["en", "pins and needles in both hands especially at night", [RBIL, ABIL, MYHAND]],
  ["en", "also has pain between the shoulder blades", [RBLADE]],
  ["en", "he describes a band of pain going from the neck round to the chest", [RCHEST]],
  ["en", "pain also felt in the temple and behind the right eye", [RTEMP, REYE]],
  ["en", "the pain starts at the neck and travels up to the back of the head", [ROCC]],
  ["en", "ear ache on the same side as the neck pain", [REAR]],
  ["en", "arms are fine, no tingling or numbness", [ANO]],
  ["en", "got whiplash in a car crash when the car behind ran into us", [MREAR]],
  ["en", "we hit a wall head on and my head jerked forward", [MFRONT, MHFLEX]],
  ["en", "another car smashed into the passenger side of our car", [MSIDE]],
  ["en", "my head was thrown backwards in the accident", [MHEXT]],
  ["en", "I twisted my neck while looking down at the same time", [MFLROT]],
  ["en", "got hit on the back of the neck by a cricket ball", [MDIRECT, POSTN]],
  ["en", "came up too fast from a dive and banged my head on the pool floor", [MDIVE, MDIRECT, FRHIGH]],
  ["en", "bad posture over the years from studying", [MPOST]],
  ["en", "woke up unable to turn my head, slept on a hard pillow", [MSLEEP]],
  ["en", "carried heavy water cans and strained my neck", [MLIFT]],
  ["en", "the pain began after an ACDF operation", [MSURG, INFUSION]],
  ["en", "started a few days after a viral fever", [MILL]],
  ["en", "pain just came on, no accident or injury", [MINS]],
  ["en", "looking down to read hurts", [GFLEX, NREAD]],
  ["en", "tilting my head back to look up is the worst", [GEXT]],
  ["en", "bending the neck to the left makes the pain sharp", [GSBL]],
  ["en", "looking up and to the left is very painful", [GQL]],
  ["en", "every direction I move my neck hurts the same", [GALL]],
  ["en", "any jolt or sudden movement makes it flare", [GQUICK]],
  ["en", "retracting the head pulling it back over the shoulders gives relief", [VRETR]],
  ["en", "chin tuck exercises ease it", [VCHIN]],
  ["en", "rotating the head to the left makes it feel better", [VROTL]],
  ["en", "a hot shower makes the neck feel a lot better", [VSHOWER]],
  ["en", "shrugging the shoulders up takes the pressure off", [VELEV]],
  ["en", "stretches help a little", [VSTRETCH]],
  ["en", "the pain never fully goes, even at night", [PCONST]],
  ["en", "always present with some days worse than others", [PCONSTVAR]],
  ["en", "only when I do overhead work", [PACT]],
  ["en", "pain depends on how I hold my neck", [PPOS]],
  ["en", "worst first thing in the morning", [PMORN]],
  ["en", "by the evening the neck is killing me", [PEVE]],
  ["en", "pain in bed at night keeps me awake", [PNIGHT]],
  ["en", "she gets bad episodes every few weeks and is fine in between", [PGONE]],
  ["en", "no headaches with the neck pain", [HNO]],
  ["en", "she has had headaches in the past which have settled", [HPREV]],
  ["en", "headaches come on when the neck gets stiff", [HSEC]],
  ["en", "no electric shock feeling when looking down", [LNO]],
  ["en", "lhermittes not assessed yet", [LNOT]],
  ["en", "zaps of electricity run down my spine if I look down", [LYES, MYLHER]],
  ["en", "my legs have become stiff and weak and I feel unsteady", [MYLEG, MYGAIT]],
  ["en", "cannot fasten buttons or write properly any more", [MYFINE]],
  ["en", "dropping things with both hands", [MYHAND]],
  ["en", "has had unexplained falls recently", [MYFALL]],
  ["en", "bladder urgency and leaking, new since this started", [MYBLAD]],
  ["en", "brisk reflexes", [MYHYPER]],
  ["en", "clonus and positive hoffmanns", [MYHOFF]],
  ["en", "weakness is progressing over the last few days", [MYPROG]],
  ["en", "everything looks double at times", [VDIP]],
  ["en", "sudden drop attacks while walking", [VDROP]],
  ["en", "speech is slurred when it happens", [VDYS]],
  ["en", "food sticks when I swallow", [VDYSP]],
  ["en", "queasy when I look up", [VNAUS]],
  ["en", "numbness on the face and tongue", [VNUMB]],
  ["en", "sudden thunderclap headache", [VTHUN, OTTHUN]],
  ["en", "left eyelid droops and the pupil is small", [VHORN]],
  ["en", "diagnosed with ra ten years ago", [INRA]],
  ["en", "trisomy 21", [INDOWN]],
  ["en", "fell off a motorbike yesterday and has neck pain", [INTRAUMA]],
  ["en", "neck muscles are in severe spasm", [INSPASM]],
  ["en", "cervical tumour on the scan", [OTCA]],
  ["en", "neck stiffness with fever and a sore throat", [OTTORT]],
  ["en", "serious crash at speed with neck trauma", [OTHIGH, FRHIGH]],
  ["en", "dived into the shallow end", [FRHIGH, MDIVE]],
  ["en", "hit the top of the head on a low beam", [FRAXIAL, MDIRECT]],
  ["en", "he is unable to move his neck at all, holding it rigid", [FRSPLINT]],
  ["en", "70 year old who fell and now has neck pain", [FRODON]],
  ["en", "heard a snap in the lower neck while shovelling", [FRCLAY, LOWERC]],
  ["en", "no red flags", [OTNO]],
  ["en", "no fracture concern as there was no injury", [FRNA]],
  ["en", "driving is difficult now", [NDRIVE]],
  ["en", "cant manage the laptop for more than half an hour", [NCOMP]],
  ["en", "no longer able to read for long", [NREAD]],
  ["en", "cannot watch a film without the neck hurting", [NTV]],
  ["en", "drying my hair is a struggle", [NHAIR]],
  ["en", "reaching up to the top shelf is painful", [NOVER]],
  ["en", "cant lift shopping bags", [NCARRY]],
  ["en", "cannot play cricket now", [NSPORT]],
  ["en", "had to cut my hours at work", [NWORK]],
  ["en", "cant pick up my baby", [NCHILD]],
  ["en", "brain fog and poor concentration", [NCONC]],
  ["en", "have stopped going out", [NSOCIAL]],
  // ── must stay silent ──
  ["en", "left knee replacement planned", []],
  ["en", "lumbar disc prolapse at L4 L5", []],
  ["en", "his father had a stroke", []],
  ["en", "my neighbour has down syndrome", []],
  ["en", "the clinic opens at nine", []],
  ["en", "she hurt her ankle playing netball", []],
  ["en", "did not have any dizziness", []],
  ["en", "I will arrange an x-ray", []],
  ["en", "my sister has rheumatoid arthritis", []],
  ["en", "I am going to Mumbai next week", []],
  // ── Hinglish ──
  ["hi", "gardan ke peeche aur dayen kandhe tak dard", [POSTN, RSHR]],
  ["hi", "gardan ke neeche kandhon ke paas dard", [LOWERC]],
  ["hi", "dard dayen haath ki ungliyon tak jata hai", [RHANDR, AR]],
  ["hi", "bayen bazu me dard utarta hai", [RARML, AL]],
  ["hi", "aankh ke peeche dard", [REYE]],
  ["hi", "jabde me bhi dard hota hai", [RJAW]],
  ["hi", "peeche se gaadi ne thok diya tha", [MREAR]],
  ["hi", "kharab posture ki wajah se dard", [MPOST]],
  ["hi", "gardan bayen taraf ghumane par dard", [GROTL]],
  ["hi", "sir jhukane par dard badhta hai", [GFLEX]],
  ["hi", "raat ko gardan me dard badhta hai", [PNIGHT]],
  ["hi", "subah sabse zyada akdan", [PMORN]],
  ["hi", "dono haath sunn ho jate hain", [RBIL, ABIL, MYHAND]],
  ["hi", "pair kamzor lagte hain aur chalne me dikkat", [MYLEG]],
  ["hi", "chakkar aata hai gardan hilane par", [VDIZ]],
  ["hi", "bukhar ke saath gardan jam gayi", [OTTORT]],
  ["hi", "padhne me dikkat hoti hai", [NREAD]],
  ["hi", "bachche ko utha nahi pata", [NCHILD]],
  ["hi", "mere padosi ko gardan dard hai", []],
  ["hi", "pet me dard hai", []],
  ["hi", "kal meeting hai", []],
  // ── Hindi (Devanagari) ──
  ["de", "गर्दन के आगे दर्द", [ANTN]],
  ["de", "दाएं हाथ में झनझनाहट", [RHANDR, AR]],
  ["de", "रात में गर्दन दर्द बढ़ता है", [PNIGHT]],
  ["de", "सुबह उठते ही गर्दन अकड़ जाती है", [PMORN]],
  ["de", "नीचे देखने पर दर्द", [GFLEX]],
  ["de", "सिर दर्द नहीं है", [HNO]],
  ["de", "चलने में संतुलन नहीं", [MYGAIT]],
  ["de", "काम पर जाना मुश्किल", [NWORK]],
  ["de", "मेरी दादी को कैंसर था", []],
  ["de", "बुखार है", []],
];

export function score(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, want] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const wantSet = new Set(want);
    for (const g of got) { suggested++; if (wantSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of want) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
