// cervicalSheetSet.js -- the sentences of the Cervical "everyday words" sheet (PhysioMind-Cervical-Everyday-Words-DRAFT.pdf), written the way the
// CLINICIAN would type about the patient ("the patient", "they", short notes): English in four styles, Hinglish and Hindi, for all 11
// conditions. Used by cervicalSheetSet.test.js (not a test itself). Row = [lang, text, must, may]:
//   must = options a physio would tick from that sentence (a miss costs recall)
//   may  = options that are also fair to suggest (neither right nor wrong: they do not count against precision)
//   anything else it suggests counts as wrong. A sentence with no must and no may must stay silent.
// lang: en = English, hi = Hinglish (Hindi in Latin letters), de = Hindi in Devanagari. The answer keys are DRAFTS written by Claude
// for Aditi to check. The Cervical form has no question for how it started or how long as such, so those lines only count where a sentence also says something a form question covers.
import { KEYS } from "./cervicalWildSets.js";
import { understandStory } from "../cervicalPhraseMap.js";

const { ABIL, AL, AR, FRAXIAL, FRHIGH, FRSPLINT, GALL, GEXT, GFLEX, GQL, GQR, GQUICK, GROTL, GROTR, GSBL, GSBR, GSUST, HCONC, HNO, HPRIM, HSEC, INRA, INSPASM, INTRAUMA, INUNST, LATL, LATR, LEVAT, LOWERC, LYES, MDIRECT, MFLROT, MFRONT, MHEXT, MHFLEX, MINS, MLIFT, MPOST, MREAR, MSIDE, MSLEEP, MYBLAD, MYFALL, MYFINE, MYGAIT, MYHAND, MYLEG, MYLHER, MYPROG, NCOMP, NDRIVE, NREAD, NSHOULDER, NWORK, OTCA, OTCONST, OTDISS, OTHIGH, OTTHUN, OTTORT, PACT, PCONST, PCONSTVAR, PEVE, PFLARE, PINTTRIG, PINTUNP, PMORN, PNIGHT, POSTN, PPOS, PWARM, RARML, RARMR, RBIL, REYE, RHANDL, RHANDR, RNONE, ROCC, RSHL, RSHTOP, RTEMP, SUBOCC, TRAPL, TRAPR, VARM, VCHIN, VDIP, VDIZ, VDYS, VELEV, VFLEX, VNAUS, VSCAP, VSHOWER, VSTRETCH, VTHUN } = KEYS;

export const CERVICAL_SHEET = [
  ["en", "The patient has pain at the back of the neck, worse on looking down and after long hours at the computer.", [POSTN, GFLEX, NCOMP], [MPOST, PPOS, RNONE, NWORK]],
  ["en", "They say the back of the neck aches, looking down makes it worse, and a full day on the computer is the worst.", [POSTN, GFLEX, NCOMP], [MPOST, PPOS, RNONE, NWORK]],
  ["en", "Posterior neck pain. Worse with flexion and computer use.", [POSTN, GFLEX, NCOMP], [MPOST, PPOS, RNONE, NWORK]],
  ["en", "It's a dull ache across the back of the neck that gets worse when they look down at a phone, and after eight hours at a screen.", [POSTN, GFLEX, NCOMP], [MPOST, PPOS, RNONE, NWORK]],
  ["hi", "Gardan ke peeche dard, neeche dekhne par aur computer par kaam karne se badhta hai.", [POSTN, GFLEX, NCOMP], [MPOST, PPOS, RNONE, NWORK]],
  ["de", "गर्दन के पीछे दर्द, नीचे देखने पर और कंप्यूटर पर काम करने से बढ़ता है।", [POSTN, GFLEX, NCOMP], [MPOST, PPOS, RNONE, NWORK]],
  ["en", "The patient woke with a stiff neck after sleeping in an awkward position.", [MSLEEP], [MINS, PMORN]],
  ["en", "They woke up with a stiff neck after sleeping on a different pillow.", [MSLEEP], [MINS, PMORN]],
  ["en", "Woke with stiff neck. Slept awkwardly.", [MSLEEP], [MINS, PMORN]],
  ["en", "She slept on the sofa with the neck bent to the side and woke with a stiff, sore neck that has not eased since.", [MSLEEP], [MINS, PMORN]],
  ["hi", "Ajeeb tareeke se sone ke baad subah gardan akdi hui.", [MSLEEP], [MINS, PMORN]],
  ["de", "अजीब तरीके से सोने के बाद सुबह गर्दन अकड़ी हुई।", [MSLEEP], [MINS, PMORN]],
  ["en", "Better with gentle stretching and a hot shower, and it loosens up once they move around.", [VSTRETCH, VSHOWER], [PWARM]],
  ["en", "A hot shower and some stretches help, and it eases as the day goes on.", [VSTRETCH, VSHOWER], [PWARM]],
  ["en", "Better: stretching, hot shower. Eases with movement.", [VSTRETCH, VSHOWER], [PWARM]],
  ["en", "The neck feels better after a hot shower with the water running on it, and a few gentle stretches ease it too.", [VSTRETCH, VSHOWER], [PWARM]],
  ["hi", "Garam paani se nahane aur halke stretch karne se aaram milta hai.", [VSTRETCH, VSHOWER], [PWARM]],
  ["de", "गर्म पानी से नहाने और हल्का स्ट्रेच करने से आराम मिलता है।", [VSTRETCH, VSHOWER], [PWARM]],
  ["en", "Days to weeks.", [], []],
  ["en", "It has been there for about two weeks.", [], []],
  ["en", "2 weeks.", [], []],
  ["en", "It started last week and has been much the same since.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has neck pain with pain and tingling down the right arm to the fingers.", [RHANDR, AR], [RARMR, POSTN, LOWERC, LATR]],
  ["en", "The pain starts in the neck and runs down the right arm into the fingers with pins and needles.", [RHANDR, AR], [RARMR, POSTN, LOWERC, LATR]],
  ["en", "Neck pain with right arm radiation to the hand. Paraesthesia.", [RHANDR, AR], [RARMR, POSTN, LOWERC, LATR]],
  ["en", "At first it was just the neck, but now there is a burning pain down the right arm and tingling in the fingers.", [RHANDR, AR], [RARMR, POSTN, LOWERC, LATR]],
  ["hi", "Gardan dard ke saath daayein haath mein ungliyon tak jhunjhuni.", [RHANDR, AR], [RARMR, POSTN, LOWERC, LATR]],
  ["de", "गर्दन दर्द के साथ दाएं हाथ में उंगलियों तक झुनझुनी।", [RHANDR, AR], [RARMR, POSTN, LOWERC, LATR]],
  ["en", "Worse on looking up and turning the head to the right, better when they rest the hand on top of the head.", [GEXT, GQR, VARM], [GROTR, AR, RARMR, RHANDR]],
  ["en", "Looking up and turning right sets off the arm pain, and putting the hand on the head eases it.", [GEXT, GQR, VARM], [GROTR, AR, RARMR, RHANDR]],
  ["en", "Worse: extension, right rotation. Better: hand on head.", [GEXT, GQR, VARM], [GROTR, AR, RARMR, RHANDR]],
  ["en", "Looking up and turning to the right sends the pain down the arm, but if they rest their hand on top of their head the arm settles.", [GEXT, GQR, VARM], [GROTR, AR, RARMR, RHANDR]],
  ["hi", "Upar dekhne aur daayein ghumne par dard badhta hai, haath sir par rakhne se aaram.", [GEXT, GQR, VARM], [GROTR, AR, RARMR, RHANDR]],
  ["de", "ऊपर देखने और दाएं मुड़ने पर दर्द बढ़ता है, हाथ सिर पर रखने से आराम।", [GEXT, GQR, VARM], [GROTR, AR, RARMR, RHANDR]],
  ["en", "Sudden onset after lifting something heavy.", [MLIFT], [MINS, MHEXT]],
  ["en", "It came on when they lifted a heavy bag and felt a sharp pull in the neck.", [MLIFT], [MINS, MHEXT]],
  ["en", "Sudden. Lifting a heavy load.", [MLIFT], [MINS, MHEXT]],
  ["en", "They were lifting a heavy suitcase onto a shelf when something sharp caught in the neck, and the arm pain began that night.", [MLIFT], [MINS, MHEXT]],
  ["hi", "Bhaari saman uthate waqt achanak gardan mein tez dard, raat se haath mein dard.", [MLIFT], [MINS, MHEXT]],
  ["de", "भारी सामान उठाते समय अचानक गर्दन में तेज दर्द, रात से हाथ में दर्द।", [MLIFT], [MINS, MHEXT]],
  ["en", "The arm pain is constant and wakes them at night.", [PCONST, PNIGHT], []],
  ["en", "It never goes away and is worst at night.", [PCONST, PNIGHT], []],
  ["en", "Constant arm pain, night disturbance.", [PCONST, PNIGHT], []],
  ["en", "The pain doesn't let up through the day and is at its worst at night when they lie down.", [PCONST, PNIGHT], []],
  ["hi", "Dard lagatar rehta hai aur raat ko sabse zyada.", [PCONST, PNIGHT], []],
  ["de", "दर्द लगातार रहता है और रात को सबसे ज़्यादा।", [PCONST, PNIGHT], []],
  ["en", "Weeks.", [], []],
  ["en", "It has been about four weeks.", [], []],
  ["en", "4 weeks.", [], []],
  ["en", "It began a month ago and the arm pain has stayed the same.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has pain on the left side of the neck, worse on looking up and turning to the left.", [LATL, GEXT, GQL], [GROTL, POSTN]],
  ["en", "It's on the left side of the neck, and looking up or turning left makes it worse.", [LATL, GEXT, GQL], [GROTL, POSTN]],
  ["en", "Left sided neck pain. Worse with extension and left rotation.", [LATL, GEXT, GQL], [GROTL, POSTN]],
  ["en", "The pain sits to the left of the spine in the neck and catches when they tip their head back or turn it to the left.", [LATL, GEXT, GQL], [GROTL, POSTN]],
  ["hi", "Gardan mein baayein taraf dard, upar dekhne aur baayein ghumne par badhta hai.", [LATL, GEXT, GQL], [GROTL, POSTN]],
  ["de", "गर्दन में बाईं तरफ दर्द, ऊपर देखने और बाएं मुड़ने पर बढ़ता है।", [LATL, GEXT, GQL], [GROTL, POSTN]],
  ["en", "The pain spreads from the neck to the top of the shoulder and up to the back of the head.", [RSHTOP, ROCC], []],
  ["en", "It goes up into the back of the head and across the top of the shoulder.", [RSHTOP, ROCC], []],
  ["en", "Referral to occiput and top of shoulder.", [RSHTOP, ROCC], []],
  ["en", "From the neck it travels over the top of the shoulder on that side and up behind the head.", [RSHTOP, ROCC], []],
  ["hi", "Dard gardan se kandhe ke upar aur sir ke peeche tak jata hai.", [RSHTOP, ROCC], []],
  ["de", "दर्द गर्दन से कंधे के ऊपर और सिर के पीछे तक जाता है।", [RSHTOP, ROCC], []],
  ["en", "Worse with quick or sudden movements of the neck.", [GQUICK], [GROTL, GROTR]],
  ["en", "Any sudden turn of the head sets it off.", [GQUICK], [GROTL, GROTR]],
  ["en", "Worse: quick movements.", [GQUICK], [GROTL, GROTR]],
  ["en", "A sudden jerk of the head, like checking the mirror quickly, makes it flare.", [GQUICK], [GROTL, GROTR]],
  ["hi", "Achanak sir ghumane par dard badhta hai.", [GQUICK], [GROTL, GROTR]],
  ["de", "अचानक सिर घुमाने पर दर्द बढ़ता है।", [GQUICK], [GROTL, GROTR]],
  ["en", "Eases when they look down.", [VFLEX], [VCHIN]],
  ["en", "Bending the neck forward gives relief.", [VFLEX], [VCHIN]],
  ["en", "Better in flexion.", [VFLEX], [VCHIN]],
  ["en", "If they drop the head forward and look down at their lap, the pain settles.", [VFLEX], [VCHIN]],
  ["hi", "Neeche dekhne par aaram milta hai.", [VFLEX], [VCHIN]],
  ["de", "नीचे देखने पर आराम मिलता है।", [VFLEX], [VCHIN]],
  ["en", "Days to weeks.", [], []],
  ["en", "It has been there for five days.", [], []],
  ["en", "5 days.", [], []],
  ["en", "It started last week and has been the same since.", [], []],
  ["hi", "Kuch dinon se.", [], []],
  ["de", "कुछ दिनों से।", [], []],
  ["en", "The patient has a headache that starts from the neck at the base of the skull.", [HSEC, SUBOCC], [ROCC]],
  ["en", "The headache begins in the neck and sits at the base of the skull.", [HSEC, SUBOCC], [ROCC]],
  ["en", "Suboccipital pain with headache secondary to neck pain.", [HSEC, SUBOCC], [ROCC]],
  ["en", "It begins as an ache at the base of the skull and then builds into a headache; it clearly comes from the neck.", [HSEC, SUBOCC], [ROCC]],
  ["hi", "Gardan se shuru hone wala sir dard, khopdi ke neeche ke hisse mein.", [HSEC, SUBOCC], [ROCC]],
  ["de", "गर्दन से शुरू होने वाला सिरदर्द, खोपड़ी के नीचे के हिस्से में।", [HSEC, SUBOCC], [ROCC]],
  ["en", "The headache spreads from the neck to the temple and behind the eye.", [RTEMP, REYE], [HSEC, ROCC]],
  ["en", "It goes up to the temple and behind the eye on that side.", [RTEMP, REYE], [HSEC, ROCC]],
  ["en", "Pain referring to temporal region and retro-orbital.", [RTEMP, REYE], [HSEC, ROCC]],
  ["en", "The pain climbs from the neck up to the temple and settles behind the eye.", [RTEMP, REYE], [HSEC, ROCC]],
  ["hi", "Dard gardan se kanpati aur aankh ke peeche tak jata hai.", [RTEMP, REYE], [HSEC, ROCC]],
  ["de", "दर्द गर्दन से कनपटी और आंख के पीछे तक जाता है।", [RTEMP, REYE], [HSEC, ROCC]],
  ["en", "The headache is brought on by turning the neck and by holding one position for long.", [GSUST], [GROTL, GROTR, PPOS, NCOMP, PINTTRIG, MPOST, HSEC]],
  ["en", "Sitting in one position for long sets it off, and so does turning the neck.", [GSUST], [GROTL, GROTR, PPOS, NCOMP, PINTTRIG, MPOST, HSEC]],
  ["en", "Triggers: neck movement, sustained posture.", [GSUST], [GROTL, GROTR, PPOS, NCOMP, PINTTRIG, MPOST, HSEC]],
  ["en", "Long spells of sitting at the computer and turning to look at the side bring on the headache.", [], [GSUST, GROTL, GROTR, PPOS, NCOMP, PINTTRIG, MPOST, HSEC]],
  ["hi", "Der tak ek hi position mein baithne aur gardan ghumane se sir dard shuru hota hai.", [GSUST], [GROTL, GROTR, PPOS, NCOMP, PINTTRIG, MPOST, HSEC]],
  ["de", "देर तक एक ही स्थिति में बैठने और गर्दन घुमाने से सिरदर्द शुरू होता है।", [GSUST], [GROTL, GROTR, PPOS, NCOMP, PINTTRIG, MPOST, HSEC]],
  ["en", "The headache is the main problem, the neck pain is minor.", [HPRIM], []],
  ["en", "They came mainly because of the headaches; the neck is only a little stiff.", [HPRIM], []],
  ["en", "Headache is the primary complaint.", [HPRIM], []],
  ["en", "It's the headaches that bother them most; the neck is a side issue.", [HPRIM], []],
  ["hi", "Mukhya takleef sir dard hai, gardan thodi akdi hai.", [HPRIM], []],
  ["de", "मुख्य तकलीफ सिरदर्द है, गर्दन थोड़ी अकड़ी है।", [HPRIM], []],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been going on for about three months.", [], []],
  ["en", "3 months.", [], []],
  ["en", "Slowly more than a year, with the headaches coming more often.", [], []],
  ["hi", "Kai mahino se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "The patient was rear-ended in a car accident two days ago and has neck pain.", [MREAR], [FRHIGH, OTHIGH, INTRAUMA]],
  ["en", "Another car hit them from behind at a traffic light.", [MREAR], [FRHIGH, OTHIGH, INTRAUMA]],
  ["en", "RTA. Rear-end collision. Neck pain.", [MREAR], [FRHIGH, OTHIGH, INTRAUMA]],
  ["en", "They were waiting at a junction when a car ran into the back of theirs, and the neck started to hurt within hours.", [MREAR], [FRHIGH, OTHIGH, INTRAUMA]],
  ["hi", "Gaadi ko peeche se takkar lagi, uske baad gardan mein dard.", [MREAR], [FRHIGH, OTHIGH, INTRAUMA]],
  ["de", "गाड़ी को पीछे से टक्कर लगी, उसके बाद गर्दन में दर्द।", [MREAR], [FRHIGH, OTHIGH, INTRAUMA]],
  ["en", "They braked suddenly and ran into the car in front, and the head was thrown forward.", [MFRONT], [MHFLEX, FRHIGH, OTHIGH, INTRAUMA]],
  ["en", "A front-end collision, the neck jerked forward.", [MFRONT], [MHFLEX, FRHIGH, OTHIGH, INTRAUMA]],
  ["en", "Frontal impact RTA.", [MFRONT], [MHFLEX, FRHIGH, OTHIGH, INTRAUMA]],
  ["en", "The car hit the one ahead, the seat belt held them but the head whipped forward.", [MFRONT], [MHFLEX, FRHIGH, OTHIGH, INTRAUMA]],
  ["hi", "Saamne wali gaadi se takkar, sir jhatke se aage gaya.", [MFRONT], [MHFLEX, FRHIGH, OTHIGH, INTRAUMA]],
  ["de", "सामने वाली गाड़ी से टक्कर, सिर झटके से आगे गया।", [MFRONT], [MHFLEX, FRHIGH, OTHIGH, INTRAUMA]],
  ["en", "Every neck movement hurts, and they cannot drive.", [GALL, NDRIVE], [PCONST, NSHOULDER]],
  ["en", "Everything they do with the neck hurts and driving is out.", [GALL, NDRIVE], [PCONST, NSHOULDER]],
  ["en", "Pain with all movements. Unable to drive.", [GALL, NDRIVE], [PCONST, NSHOULDER]],
  ["en", "Looking in any direction hurts, and since the crash they have been unable to turn their head enough to drive safely.", [GALL, NDRIVE], [PCONST, NSHOULDER]],
  ["hi", "Gardan ki har harkat mein dard, gaadi nahi chala pate.", [GALL, NDRIVE], [PCONST, NSHOULDER]],
  ["de", "गर्दन की हर हरकत में दर्द, गाड़ी नहीं चला पाते।", [GALL, NDRIVE], [PCONST, NSHOULDER]],
  ["en", "They feel dizzy when they turn the neck and have had headaches since the accident.", [VDIZ], [HSEC, HCONC, HPRIM, GROTL, GROTR]],
  ["en", "Turning the neck makes them dizzy, and there have been headaches since the crash.", [VDIZ], [HSEC, HCONC, HPRIM, GROTL, GROTR]],
  ["en", "Dizziness on neck rotation. Headaches post RTA.", [VDIZ], [HSEC, HCONC, HPRIM, GROTL, GROTR]],
  ["en", "Turning the neck makes the room swim, and there have been headaches since the accident.", [VDIZ], [HSEC, HCONC, HPRIM, GROTL, GROTR]],
  ["hi", "Gardan ghumane par chakkar aate hain, accident ke baad se sir dard.", [VDIZ], [HSEC, HCONC, HPRIM, GROTL, GROTR]],
  ["de", "गर्दन घुमाने पर चक्कर आते हैं, दुर्घटना के बाद से सिरदर्द।", [VDIZ], [HSEC, HCONC, HPRIM, GROTL, GROTR]],
  ["en", "Acute; days to weeks.", [], [INTRAUMA, FRHIGH, OTHIGH, MREAR, MFRONT, MSIDE]],
  ["en", "The accident was ten days ago.", [], [INTRAUMA, FRHIGH, OTHIGH, MREAR, MFRONT, MSIDE]],
  ["en", "10 days.", [], [INTRAUMA, FRHIGH, OTHIGH, MREAR, MFRONT, MSIDE]],
  ["en", "It started with the accident three weeks ago and has not eased much.", [], [INTRAUMA, FRHIGH, OTHIGH, MREAR, MFRONT, MSIDE]],
  ["hi", "Do hafte pehle accident hua tha.", [], [INTRAUMA, FRHIGH, OTHIGH, MREAR, MFRONT, MSIDE]],
  ["de", "दो हफ्ते पहले दुर्घटना हुई थी।", [], [INTRAUMA, FRHIGH, OTHIGH, MREAR, MFRONT, MSIDE]],
  ["en", "The patient woke up with the neck stuck to one side after sleeping in a draught.", [MSLEEP], [PMORN, INSPASM, MINS, GALL, FRSPLINT]],
  ["en", "Woke up with a locked neck and cannot turn the head.", [MSLEEP], [PMORN, INSPASM, MINS, GALL, FRSPLINT]],
  ["en", "Waking torticollis. Cannot rotate.", [MSLEEP], [PMORN, INSPASM, MINS, GALL, FRSPLINT]],
  ["en", "They went to bed fine and woke with the neck twisted and locked to one side, unable to turn it.", [MSLEEP], [PMORN, INSPASM, MINS, GALL, FRSPLINT]],
  ["hi", "Subah uthte hi gardan ek taraf atak gayi, ghuma nahi sakte.", [MSLEEP], [PMORN, INSPASM, MINS, GALL, FRSPLINT]],
  ["de", "सुबह उठते ही गर्दन एक तरफ अटक गई, घुमा नहीं सकते।", [MSLEEP], [PMORN, INSPASM, MINS, GALL, FRSPLINT]],
  ["en", "The patient has pain and tightness along the right side of the neck, in the levator scapulae.", [LEVAT], [LATR, TRAPR, INSPASM]],
  ["en", "The tight spot is in the levator muscle on the right, between the neck and shoulder blade.", [LEVAT], [LATR, TRAPR, INSPASM]],
  ["en", "R levator scapulae spasm.", [LEVAT], [LATR, TRAPR, INSPASM]],
  ["en", "It's the muscle running from the neck down to the top of the right shoulder blade that is sore and tight.", [], [LEVAT, LATR, TRAPR, INSPASM]],
  ["hi", "Daayein taraf gardan se kandhe ke blade tak ki maanspeshi mein khinchav.", [], [LEVAT, LATR, TRAPR, INSPASM]],
  ["de", "दाईं तरफ गर्दन से कंधे के ब्लेड तक की मांसपेशी में खिंचाव।", [], [LEVAT, LATR, TRAPR, INSPASM]],
  ["en", "Sudden, after lifting a heavy bag with a twist of the neck.", [MLIFT], [MINS, MFLROT]],
  ["en", "They pulled the neck lifting a heavy sack.", [MLIFT], [MINS, MFLROT]],
  ["en", "Strain lifting. Sudden.", [MLIFT], [MINS, MFLROT]],
  ["en", "While lifting a heavy sack onto a truck they felt a sharp pull in the neck.", [MLIFT], [MINS, MFLROT]],
  ["hi", "Bhaari bori uthate waqt gardan mein khichav.", [MLIFT], [MINS, MFLROT]],
  ["de", "भारी बोरी उठाते समय गर्दन में खिंचाव।", [MLIFT], [MINS, MFLROT]],
  ["en", "Worse when they tilt the head to the left.", [GSBL], [GROTL]],
  ["en", "Bending the neck towards the left shoulder hurts.", [GSBL], [GROTL]],
  ["en", "Worse: left side flexion.", [GSBL], [GROTL]],
  ["en", "Dropping the left ear towards the left shoulder pulls on the muscle.", [GSBL], [GROTL]],
  ["hi", "Sir baayein taraf jhukane par dard badhta hai.", [GSBL], [GROTL]],
  ["de", "सिर बाईं तरफ झुकाने पर दर्द बढ़ता है।", [GSBL], [GROTL]],
  ["en", "Acute; days.", [], []],
  ["en", "It started three days ago.", [], []],
  ["en", "3 days.", [], []],
  ["en", "It came on suddenly at the weekend and is slowly easing.", [], []],
  ["hi", "Teen din se.", [], []],
  ["de", "तीन दिन से।", [], []],
  ["en", "The patient has numb, clumsy hands on both sides and cannot do up buttons or write properly.", [MYHAND, MYFINE, ABIL], [RBIL]],
  ["en", "Both hands are numb and clumsy, and they struggle with buttons and handwriting.", [MYHAND, MYFINE, ABIL], [RBIL]],
  ["en", "Bilateral hand numbness. Poor fine motor control: buttons, writing.", [MYHAND, MYFINE, ABIL], [RBIL]],
  ["en", "Over the last few months both hands have become numb and awkward; buttons and handwriting are now difficult.", [MYHAND, MYFINE, ABIL], [RBIL]],
  ["hi", "Dono haathon mein sunn-pan aur kamzori, button lagane aur likhne mein dikkat.", [MYHAND, MYFINE, ABIL], [RBIL]],
  ["de", "दोनों हाथों में सुन्नपन और कमज़ोरी, बटन लगाने और लिखने में दिक्कत।", [MYHAND, MYFINE, ABIL], [RBIL]],
  ["en", "Their walking has become unsteady, the legs feel stiff and weak, and they have fallen twice.", [MYGAIT, MYFALL, MYLEG], []],
  ["en", "They are wobbly on their feet, the legs feel stiff, and they have fallen a couple of times.", [MYGAIT, MYFALL, MYLEG], []],
  ["en", "Gait unsteady. Falls x2. Bilateral leg stiffness.", [MYGAIT, MYFALL, MYLEG], []],
  ["en", "Walking has gone off over the last year; the legs feel heavy and stiff and they have had two unexplained falls.", [MYFALL, MYLEG], [MYGAIT]],
  ["hi", "Chalne mein ladkhadahat, dono taango mein akdan, do baar gir chuke hain.", [MYGAIT, MYFALL, MYLEG], []],
  ["de", "चलने में लड़खड़ाहट, दोनों टांगों में अकड़न, दो बार गिर चुके हैं।", [MYGAIT, MYFALL, MYLEG], []],
  ["en", "They get an electric shock down the spine when they bend the neck forward.", [LYES, MYLHER], [GFLEX]],
  ["en", "Bending the head forward sends a shock down the back.", [LYES, MYLHER], [GFLEX]],
  ["en", "Lhermitte's sign present on flexion.", [LYES, MYLHER], [GFLEX]],
  ["en", "When they look down there's a sudden electric shock that runs down the spine and into the legs.", [LYES, MYLHER], [GFLEX]],
  ["hi", "Gardan aage jhukane par reedh mein bijli jaisa jhatka.", [LYES, MYLHER], [GFLEX]],
  ["de", "गर्दन आगे झुकाने पर रीढ़ में बिजली जैसा झटका।", [LYES, MYLHER], [GFLEX]],
  ["en", "The patient has new bladder control problems along with the hand and leg symptoms.", [MYBLAD], []],
  ["en", "They have started leaking urine and cannot get to the toilet in time.", [MYBLAD], []],
  ["en", "New urinary urgency and incontinence.", [MYBLAD], []],
  ["en", "Recently they cannot hold their urine as before, along with the clumsy hands.", [MYBLAD], []],
  ["hi", "Peshaab rokne mein nayi dikkat.", [MYBLAD], []],
  ["de", "पेशाब रोकने में नई दिक्कत।", [MYBLAD], []],
  ["en", "The numbness and weakness are getting worse quickly over a few weeks.", [], [MYPROG]],
  ["en", "In the last few weeks the symptoms have been rapidly progressing.", [], [MYPROG]],
  ["en", "Rapidly progressive neurological symptoms.", [], [MYPROG]],
  ["en", "What began as a little clumsiness is now clearly worse every week.", [], [MYPROG]],
  ["hi", "Kuch hafton mein lakshan tezi se badh rahe hain.", [], [MYPROG]],
  ["de", "कुछ हफ्तों में लक्षण तेज़ी से बढ़ रहे हैं।", [], [MYPROG]],
  ["en", "Months to years.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["en", "It has been creeping on for about two years.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["en", "2 years.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["en", "Slowly over several years, with a sharp step down in the last few months.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["hi", "Kai saalon se.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["de", "कई सालों से।", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["en", "The patient was tackled in rugby and felt a burning shock down the left arm to the fingers.", [RHANDL, AL], [MDIRECT, RARML]],
  ["en", "After a hard tackle, a burning pain shot down the left arm into the hand.", [RHANDL, AL], [MDIRECT, RARML]],
  ["en", "Rugby tackle. Burner L arm to fingers.", [RHANDL, AL], [MDIRECT, RARML]],
  ["en", "They lowered the shoulder into a tackle, and a hot electric pain ran down the left arm into the fingers and left the arm weak.", [RHANDL, AL], [MDIRECT, RARML]],
  ["hi", "Tackle ke baad baayein haath mein ungliyon tak jalan jaisa jhatka.", [RHANDL, AL], [MDIRECT, RARML]],
  ["de", "टैकल के बाद बाएं हाथ में उंगलियों तक जलन जैसा झटका।", [RHANDL, AL], [MDIRECT, RARML]],
  ["en", "The numbness stayed in the left shoulder and upper arm and passed within minutes.", [RSHL, AL], []],
  ["en", "The left shoulder and upper arm went numb and weak, then recovered in a few minutes.", [RSHL, AL], []],
  ["en", "L shoulder and upper arm paraesthesia, resolved in minutes.", [RSHL, AL], []],
  ["en", "Right after the hit the left upper arm went dead and heavy for a few minutes, then came back.", [RSHL, AL], []],
  ["hi", "Baayein kandhe aur upri baanh mein sunnpan, kuch minute mein theek.", [RSHL, AL], []],
  ["de", "बाएं कंधे और ऊपरी बांह में सुन्नपन, कुछ मिनट में ठीक।", [RSHL, AL], []],
  ["en", "Tilting the head to the right (away from the left arm) brings on the arm pain.", [GSBR], [AL, RARML, RHANDL, RSHL]],
  ["en", "Bending the head to the right pulls on the left arm and brings the pain on.", [GSBR], [AL, RARML, RHANDL, RSHL]],
  ["en", "Right side bend reproduces L arm pain.", [GSBR], [AL, RARML, RHANDL, RSHL]],
  ["en", "If they lean the head away to the right, the left arm starts to burn.", [GSBR], [AL, RARML, RHANDL, RSHL]],
  ["hi", "Sir daayein jhukane par baayein haath mein jalan.", [GSBR], [AL, RARML, RHANDL, RSHL]],
  ["de", "सिर दाएं झुकाने पर बाएं हाथ में जलन।", [GSBR], [AL, RARML, RHANDL, RSHL]],
  ["en", "It has happened three times this season, always after a hard tackle.", [], [PINTTRIG, MDIRECT, PACT]],
  ["en", "Three episodes this season, each one in a tackle.", [], [PINTTRIG, MDIRECT, PACT]],
  ["en", "Recurrent burners x3, contact triggered.", [], [PINTTRIG, MDIRECT, PACT]],
  ["en", "It keeps coming back whenever they take a heavy hit, three times so far this season.", [], [PINTTRIG, MDIRECT, PACT]],
  ["hi", "Is season teen baar hua, har baar tackle ke baad.", [], [PINTTRIG, MDIRECT, PACT]],
  ["de", "इस सीज़न में तीन बार हुआ, हर बार टैकल के बाद।", [], [PINTTRIG, MDIRECT, PACT]],
  ["en", "Minutes to days.", [], []],
  ["en", "It settled in ten minutes.", [], []],
  ["en", "10 minutes.", [], []],
  ["en", "The arm was weak for two days afterwards, then back to normal.", [], []],
  ["hi", "Kuch minute mein theek ho gaya.", [], []],
  ["de", "कुछ मिनट में ठीक हो गया।", [], []],
  ["en", "The patient has tingling in the right thumb and first two fingers, worse at night, and the neck is not sore.", [AR, RHANDR, PNIGHT], []],
  ["en", "Tingling in the right hand at night wakes them, no neck pain.", [AR, RHANDR, PNIGHT], []],
  ["en", "Right hand paraesthesia, nocturnal. No neck pain.", [AR, RHANDR, PNIGHT], []],
  ["en", "The right thumb and fingers tingle and go numb at night, and shaking the hand helps; there is no pain in the neck at all.", [AR, RHANDR, PNIGHT], []],
  ["hi", "Daayein haath ki ungliyon mein raat ko jhunjhuni, gardan mein dard nahi.", [AR, RHANDR, PNIGHT], []],
  ["de", "दाएं हाथ की उंगलियों में रात को झुनझुनी, गर्दन में दर्द नहीं।", [AR, RHANDR, PNIGHT], []],
  ["en", "The little and ring fingers of the left hand tingle when the elbow is bent for long.", [AL, RHANDL], []],
  ["en", "Left little finger and ring finger go numb when the elbow stays bent, e.g. on the phone.", [AL, RHANDL], []],
  ["en", "Left ulnar-sided finger numbness with prolonged elbow flexion.", [AL, RHANDL], []],
  ["en", "Holding the phone to the ear with the left elbow bent makes the little and ring fingers tingle.", [AL, RHANDL], []],
  ["hi", "Baayein haath ki chhoti aur anamika ungli mein jhunjhuni, kohni mode rakhne par.", [AL, RHANDL], []],
  ["de", "बाएं हाथ की छोटी और अनामिका उंगली में झुनझुनी, कोहनी मोड़कर रखने पर।", [AL, RHANDL], []],
  ["en", "Moving the neck does not change the tingling in the hand.", [], []],
  ["en", "Neck movements make no difference to the hand symptoms.", [], []],
  ["en", "Neck ROM does not alter hand symptoms.", [], []],
  ["en", "Whatever way they move the neck, the tingling in the hand stays the same.", [], []],
  ["hi", "Gardan hilane se haath ki jhunjhuni par koi farak nahi padta.", [], []],
  ["de", "गर्दन हिलाने से हाथ की झुनझुनी पर कोई फर्क नहीं पड़ता।", [], []],
  ["en", "The patient has no headaches.", [HNO], []],
  ["en", "No headaches at all.", [HNO], []],
  ["en", "No headache.", [HNO], []],
  ["en", "They don't get headaches with this.", [HNO], []],
  ["hi", "Sir dard nahi hai.", [HNO], []],
  ["de", "सिरदर्द नहीं है।", [HNO], []],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been there for about two months.", [], []],
  ["en", "2 months.", [], []],
  ["en", "It crept on slowly over the last year.", [], []],
  ["hi", "Kuch mahino se.", [], []],
  ["de", "कुछ महीनों से।", [], []],
  ["en", "The patient has tender knots in the upper trapezius on both sides.", [TRAPL, TRAPR], [LEVAT]],
  ["en", "Both upper traps are tight and sore with trigger points.", [TRAPL, TRAPR], [LEVAT]],
  ["en", "Bilateral upper trapezius trigger points.", [TRAPL, TRAPR], [LEVAT]],
  ["en", "Along the top of both shoulders there are hard sore bands that are tender to press.", [TRAPL, TRAPR], [LEVAT]],
  ["hi", "Dono kandhon ke upar ki maanspeshiyon mein dardnaak gaanth.", [TRAPL, TRAPR], [LEVAT]],
  ["de", "दोनों कंधों के ऊपर की मांसपेशियों में दर्दनाक गांठें।", [TRAPL, TRAPR], [LEVAT]],
  ["en", "The pain builds up through the working day and is worst by the evening.", [PEVE], [PCONSTVAR, PPOS, PACT]],
  ["en", "It gets worse as the day goes on, evenings are the worst.", [PEVE], [PCONSTVAR, PPOS, PACT]],
  ["en", "Evening dominant. Builds through the day.", [PEVE], [PCONSTVAR, PPOS, PACT]],
  ["en", "In the morning it's barely there, but by the evening after work the neck and shoulders ache badly.", [PEVE], [PCONSTVAR, PPOS, PACT]],
  ["hi", "Din bhar mein dard badhta hai, shaam ko sabse zyada.", [PEVE], [PCONSTVAR, PPOS, PACT]],
  ["de", "दिन भर में दर्द बढ़ता है, शाम को सबसे ज़्यादा।", [PEVE], [PCONSTVAR, PPOS, PACT]],
  ["en", "Relieved by shrugging the shoulders, squeezing the shoulder blades together and stretching.", [VSCAP, VELEV, VSTRETCH], []],
  ["en", "Shrugging the shoulders up and squeezing the blades together helps, and so does stretching.", [VSCAP, VELEV, VSTRETCH], []],
  ["en", "Better: shoulder shrug, scapular retraction, stretching.", [VSCAP, VELEV, VSTRETCH], []],
  ["en", "Lifting the shoulders up toward the ears or pinching the shoulder blades together gives relief, as do gentle stretches.", [VSCAP, VELEV, VSTRETCH], []],
  ["hi", "Kandhe uchkane, shoulder blade ko paas laane aur stretch karne se aaram.", [VSCAP, VELEV, VSTRETCH], []],
  ["de", "कंधे उचकाने, शोल्डर ब्लेड को पास लाने और स्ट्रेच करने से आराम।", [VSCAP, VELEV, VSTRETCH], []],
  ["en", "Struggling to keep up with computer work and desk duties.", [NCOMP, NWORK], [NREAD, MPOST]],
  ["en", "Computer work and a full desk job are getting hard.", [NCOMP, NWORK], [NREAD, MPOST]],
  ["en", "Limited: computer use, desk work.", [NCOMP, NWORK], [NREAD, MPOST]],
  ["en", "Long spells at the screen at work are now difficult because of the pain.", [NCOMP, NWORK], [NREAD, MPOST]],
  ["hi", "Computer par aur daftar ka kaam karne mein dikkat.", [NCOMP, NWORK], [NREAD, MPOST]],
  ["de", "कंप्यूटर और दफ्तर का काम करने में दिक्कत।", [NCOMP, NWORK], [NREAD, MPOST]],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been there for about six weeks.", [], []],
  ["en", "6 weeks.", [], []],
  ["en", "On and off for months, worse in the last fortnight.", [], []],
  ["hi", "Kuch mahino se.", [], []],
  ["de", "कुछ महीनों से।", [], []],
  ["en", "The patient reports dizziness, double vision and slurred speech with neck movement.", [VDIZ, VDIP, VDYS], [VNAUS]],
  ["en", "Turning the neck brings on dizziness, they see double and their speech slurs.", [VDIZ, VDIP, VDYS], [VNAUS]],
  ["en", "VBI: dizziness, diplopia, dysarthria on rotation.", [VDIZ, VDIP, VDYS], [VNAUS]],
  ["en", "When they turn the head they feel faint, the vision doubles and the words come out slurred.", [VDIZ, VDIP, VDYS], [VNAUS]],
  ["hi", "Gardan ghumane par chakkar, double dikhna aur zubaan ladkhadana.", [VDIZ, VDIP, VDYS], [VNAUS]],
  ["de", "गर्दन घुमाने पर चक्कर, दोहरा दिखना और ज़ुबान लड़खड़ाना।", [VDIZ, VDIP, VDYS], [VNAUS]],
  ["en", "Sudden severe headache, the worst of their life, with neck pain.", [VTHUN, OTTHUN], [OTDISS, HPRIM, HSEC, HCONC]],
  ["en", "A thunderclap headache came on suddenly, the worst they have ever had.", [VTHUN, OTTHUN], [OTDISS, HPRIM, HSEC, HCONC]],
  ["en", "Thunderclap headache, worst ever, with neck pain.", [VTHUN, OTTHUN], [OTDISS, HPRIM, HSEC, HCONC]],
  ["en", "Out of nowhere came the worst headache of their life, and the neck has been sore since.", [VTHUN, OTTHUN], [OTDISS, HPRIM, HSEC, HCONC]],
  ["hi", "Achanak zindagi ka sabse tez sir dard, saath mein gardan dard.", [VTHUN, OTTHUN], [OTDISS, HPRIM, HSEC, HCONC]],
  ["de", "अचानक ज़िंदगी का सबसे तेज़ सिरदर्द, साथ में गर्दन दर्द।", [VTHUN, OTTHUN], [OTDISS, HPRIM, HSEC, HCONC]],
  ["en", "The patient has a known tumour affecting the neck, with weight loss and night sweats.", [OTCA, OTCONST], [PNIGHT]],
  ["en", "A tumour in the neck was found last year, and now they have lost weight and sweat at night.", [OTCA, OTCONST], [PNIGHT]],
  ["en", "Known cervical tumour. Weight loss, night sweats.", [OTCA, OTCONST], [PNIGHT]],
  ["en", "They have a known growth in the neck, and recently they have lost a lot of weight and wake drenched in sweat.", [OTCA, OTCONST], [PNIGHT]],
  ["hi", "Gardan mein gaanth (tumour) ka pata hai, vazan kam, raat ko paseena.", [OTCA, OTCONST], [PNIGHT]],
  ["de", "गर्दन में ट्यूमर का पता है, वज़न कम हुआ, रात को पसीना।", [OTCA, OTCONST], [PNIGHT]],
  ["en", "Sudden torticollis with a fever.", [OTTORT], [OTCONST, INSPASM]],
  ["en", "Neck suddenly locked to one side and they have a high temperature.", [OTTORT], [OTCONST, INSPASM]],
  ["en", "Acute torticollis + fever.", [OTTORT], [OTCONST, INSPASM]],
  ["en", "The neck locked up within a day and now they are running a high temperature.", [OTTORT], [OTCONST, INSPASM]],
  ["hi", "Gardan achanak ek taraf atak gayi aur bukhaar hai.", [OTTORT], [OTCONST, INSPASM]],
  ["de", "गर्दन अचानक एक तरफ अटक गई और बुखार है।", [OTTORT], [OTCONST, INSPASM]],
  ["en", "The patient fell from a ladder and landed on the head, and now has severe neck pain.", [FRAXIAL, FRHIGH], [MDIRECT, OTHIGH, INTRAUMA]],
  ["en", "They fell off a ladder and came down head first.", [FRAXIAL, FRHIGH], [MDIRECT, OTHIGH, INTRAUMA]],
  ["en", "Fall from height onto head. Severe neck pain.", [FRAXIAL, FRHIGH], [MDIRECT, OTHIGH, INTRAUMA]],
  ["en", "From the top of a ladder they came down headfirst onto the concrete.", [FRAXIAL, FRHIGH], [MDIRECT, OTHIGH, INTRAUMA]],
  ["hi", "Seedhi se sir ke bal gire, gardan mein bahut dard.", [FRAXIAL, FRHIGH], [MDIRECT, OTHIGH, INTRAUMA]],
  ["de", "सीढ़ी से सिर के बल गिरे, गर्दन में बहुत दर्द।", [FRAXIAL, FRHIGH], [MDIRECT, OTHIGH, INTRAUMA]],
  ["en", "The patient has rheumatoid arthritis and feels the head is unstable on the neck.", [INRA, INUNST], []],
  ["en", "Known RA, and the head feels wobbly on the neck.", [INRA, INUNST], []],
  ["en", "RA. Sense of instability in neck.", [INRA, INUNST], []],
  ["en", "With rheumatoid arthritis for years, they now feel their head might fall off the neck.", [INRA, INUNST], []],
  ["hi", "Gathiya (RA) hai aur sir gardan par hilta hua mehsoos hota hai.", [INRA, INUNST], []],
  ["de", "गठिया (RA) है और सिर गर्दन पर हिलता हुआ महसूस होता है।", [INRA, INUNST], []],
  ["en", "Urgent; may be days or weeks.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["en", "It has been getting worse over three weeks.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["en", "3 weeks, worsening.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["en", "Over a month, with the pain now constant.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["hi", "Kuch hafton se badhta hua.", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["de", "कुछ हफ्तों से बढ़ता हुआ।", [], [MINS, PINTTRIG, PINTUNP, PCONST, PFLARE]],
  ["en", "Patient works as a driver and lives in Surat.", [], []],
  ["en", "Medical history: type 2 diabetes, on metformin.", [], []],
  ["en", "Pain score is 6 out of 10.", [], []],
  ["en", "He has been referred by his employer.", [], []],
  ["en", "She would like to return to yoga eventually.", [], []],
  ["en", "Husband brought the patient to the clinic.", [], []],
  ["hi", "Mareez ko pichle hafte doctor ne dekha tha.", [], []],
  ["de", "मरीज़ की उम्र पचास साल है।", [], []],
];

// Same scoring as the other exams, except "may" answers are neutral.
export function scoreSheet(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, must, may] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const okSet = new Set([...must, ...may]);
    for (const g of got) { suggested++; if (okSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of must) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
