// elbowWildSets.js -- shared by the Elbow phrase-matcher tests (not a test itself).
// Four sets of messy, real-life sentences written the way students type, each marked with what a physio
// would tick ("field|option"). A = first exam of version 1; B = written just before the word-order rules;
// C = written after the rules were frozen; D = the final exam. See each set's test file for its history.
import { ELBOW_PHRASES, understandStory } from "../elbowPhraseMap.js";

const O = (field, i) => Object.keys(ELBOW_PHRASES[field])[i];
const LAT = O("location", 0), MED = O("location", 1), POST = O("location", 2), ANT = O("location", 3), FORE = O("location", 4),
  DORS = O("location", 5), RAD = O("location", 7), ULN = O("location", 8), THUMB = O("location", 9);
const NORAD = O("radiation", 0), INTOF = O("radiation", 1), MEDN = O("radiation", 3), ULNN = O("radiation", 4);
const INSID = O("mechanism", 0), FALL = O("mechanism", 1), REPG = O("mechanism", 2), RACQ = O("mechanism", 3), GOLF = O("mechanism", 4),
  THUMBUSE = O("mechanism", 5), TRAUMA = O("mechanism", 6), VIB = O("mechanism", 7);
const GRIP = O("aggravating", 0), LIFT = O("aggravating", 1), THMOV = O("aggravating", 4), TYPE = O("aggravating", 5), SUST = O("aggravating", 6);
const CONST = O("pattern", 0), INTER = O("pattern", 1), MORN = O("pattern", 2), NIGHT = O("pattern", 3), ACT = O("pattern", 4), IMPR = O("pattern", 5);
const NNONE = O("neuro", 0), NCARP = O("neuro", 1), NCUB = O("neuro", 2), WEAK = O("neuro", 3), DROP = O("neuro", 4), WASTE = O("neuro", 5);
const FRAC = O("redFlags", 0), SNUFF = O("redFlags", 1), TEND = O("redFlags", 2), COMP = O("redFlags", 3), HOT = O("redFlags", 4), BILAT = O("redFlags", 5);
const k = (field, option) => `${field}|${option}`;

export const WILD_A = [
  // ── English ──
  ["en", "elbow outer side hurting since I started playing badminton two months ago", [k("location", LAT), k("mechanism", RACQ)]],
  ["en", "it hurts on the outer part of my elbow when I pick up my coffee cup", [k("location", LAT), k("aggravating", GRIP)]],
  ["en", "my fingers go numb at night and I wake up shaking my hands", [k("neuro", NCARP)]],
  ["en", "fell on my left hand yesterday while running, wrist looks bent and swollen", [k("mechanism", FALL), k("redFlags", FRAC)]],
  ["en", "pain in the elbow when I turn the door handle", [k("aggravating", GRIP)]],
  ["en", "dull ache in the back of the elbow after leaning on the desk all day", [k("location", POST)]],
  ["en", "painful to lift anything heavy, even a kettle", [k("aggravating", LIFT)]],
  ["en", "cannot hold a pen properly, it keeps slipping", [k("neuro", WEAK), k("neuro", DROP)]], // a physio would tick both
  ["en", "tingling in my pinky and ring finger when I bend my elbow for long", [k("radiation", ULNN), k("neuro", NCUB)]],
  ["en", "my elbow clicks and hurts when I straighten it fully", []],
  ["en", "elbow pain after the gym, I did a lot of curls", [k("mechanism", REPG)]],
  ["en", "pain on the inside of the elbow and I throw a cricket ball a lot", [k("location", MED), k("mechanism", GOLF)]],
  ["en", "it is worse at night and I cannot sleep on that side", [k("pattern", NIGHT)]],
  ["en", "the pain is there all day, it never stops", [k("pattern", CONST)]],
  ["en", "hurts mostly in the morning then loosens up", [k("pattern", MORN), k("pattern", IMPR)]],
  ["en", "I type a lot for work and my wrist hurts", [k("aggravating", TYPE)]],
  ["en", "pain along the thumb side of the wrist when I lift my baby", [k("location", RAD), k("mechanism", THUMBUSE)]],
  ["en", "numbness in thumb, index and middle fingers", [k("radiation", MEDN)]],
  ["en", "pain goes down the arm to my fingers", [k("radiation", INTOF)]],
  ["en", "pain at the elbow and also in the forearm", [k("location", FORE)]],
  ["en", "pain only comes when I am playing, not when resting", [k("pattern", ACT)]],
  ["en", "I had an accident on my bike and landed on my elbow", [k("mechanism", TRAUMA)]],
  ["en", "cannot straighten my little finger since this morning, it happened suddenly", [k("redFlags", TEND)]],
  ["en", "both my hands tingle at night", [k("redFlags", BILAT), k("neuro", NCARP)]],
  ["en", "gripping hurts and I drop things", [k("aggravating", GRIP), k("neuro", DROP)]],
  ["en", "it began after painting my house for a week", [k("mechanism", REPG)]],
  ["en", "he plays tennis and the outer elbow hurts when he grips the racket", [k("mechanism", RACQ), k("location", LAT), k("aggravating", GRIP)]],
  ["en", "no pain at rest, hurts only with use", [k("pattern", ACT)]],
  ["en", "I do not have any numbness", []],
  ["en", "the pain is not at the back of the elbow", []],
  ["en", "I did not fall or hit it", []],
  // ── Hinglish ──
  ["hi", "kohni me bahar ki taraf dard hai jab chai ka cup pakadta hoon", [k("location", LAT), k("aggravating", GRIP)]],
  ["hi", "raat ko haath sunn ho jata hai", [k("neuro", NCARP)]],
  ["hi", "gir gaya tha haath ke bal, ab kalai me bahut dard hai", [k("mechanism", FALL)]],
  ["hi", "kaam karte waqt kohni me dard hota hai, aaram se theek", [k("pattern", ACT)]],
  ["hi", "mobile chalane se angoothe me dard", [k("location", THUMB)]],
  ["hi", "bhari saman uthane se dard badh jata hai", [k("aggravating", LIFT), k("mechanism", REPG)]],
  ["hi", "dono kohni me dard hai", [k("redFlags", BILAT)]],
  ["hi", "ungliyon me jhunjhuni raat ko zyada", [k("neuro", NCARP)]],
  ["hi", "subah dard zyada hota hai", [k("pattern", MORN)]],
  ["hi", "dard har waqt rehta hai", [k("pattern", CONST)]],
  ["hi", "dard kabhi kabhi aata hai aur chala jata hai", [k("pattern", INTER)]],
  ["hi", "haath me kamzori aur saman gir jata hai", [k("neuro", WEAK), k("neuro", DROP)]],
  ["hi", "tennis khelne ke baad kohni me bahar dard", [k("mechanism", RACQ), k("location", LAT)]],
  ["hi", "hathode se kaam karta hu roz", [k("mechanism", REPG)]],
  ["hi", "kohni me sujan aur garam hai", [k("redFlags", HOT)]],
  ["hi", "elbow ke bahar dard hai", [k("location", LAT)]],
  ["hi", "mere dono haath sunn hain raat ko", [k("redFlags", BILAT), k("neuro", NCARP)]],
  ["hi", "kohni me chot lagi thi", [k("mechanism", TRAUMA)]],
  // ── Hindi (Devanagari) ──
  ["de", "कोहनी के बाहर दर्द है जब मैं कप पकड़ता हूँ", [k("location", LAT), k("aggravating", GRIP)]],
  ["de", "रात को हाथ में झनझनाहट होती है", [k("neuro", NCARP)]],
  ["de", "हाथ के बल गिर गया था", [k("mechanism", FALL)]],
  ["de", "सुबह के समय दर्द ज्यादा रहता है", [k("pattern", MORN)]],
  ["de", "दोनों कोहनी में दर्द है", [k("redFlags", BILAT)]],
  ["de", "भारी सामान उठाने में दर्द होता है", [k("aggravating", LIFT), k("mechanism", REPG)]],
  ["de", "टाइप करने से कलाई में दर्द", [k("aggravating", TYPE)]],
  ["de", "बच्चे को गोद में उठाने से दर्द", [k("mechanism", THUMBUSE), k("aggravating", LIFT)]], // pain from lifting the baby: both
  ["de", "उंगलियों में सुन्नपन रहता है", []],
  ["de", "कोहनी में चोट लगी थी", [k("mechanism", TRAUMA)]],
  // ── other nonsense that must stay silent ──
  ["en", "my knee gives way on the stairs", []],
  ["en", "headache since two days with some fever", []],
  ["hi", "pet me dard hai aur ulti ho rahi hai", []],
  ["de", "मेरे पैर में दर्द है", []],
];

export const WILD_B = [
  // ── English ──
  ["en", "pain just below my elbow on the outside, started after weeding the garden for hours", [k("location", LAT), k("mechanism", REPG)]],
  ["en", "when I shake hands or grab a bottle it hurts on the outer elbow", [k("aggravating", GRIP), k("location", LAT)]],
  ["en", "my elbow is sore on the inner side and I play a lot of golf", [k("location", MED), k("mechanism", GOLF)]],
  ["en", "pins and needles in my little and ring finger if I keep my elbow bent while sleeping", [k("radiation", ULNN), k("neuro", NCUB)]],
  ["en", "I have weakness, I cannot open jar lids anymore", [k("neuro", WEAK)]],
  ["en", "I keep dropping my phone and cups", [k("neuro", DROP)]],
  ["en", "pain all the time, day and night", [k("pattern", CONST)]],
  ["en", "the pain comes on and off during the week", [k("pattern", INTER)]],
  ["en", "it hurts the most first thing when I wake up and feels stiff", [k("pattern", MORN)]],
  ["en", "the pain wakes me from sleep", [k("pattern", NIGHT)]],
  ["en", "it hurts only when I use the arm for work, otherwise fine", [k("pattern", ACT)]],
  ["en", "pain gets better as I keep moving through the day", [k("pattern", IMPR)]],
  ["en", "fell off the bike onto my outstretched palm", [k("mechanism", FALL)]],
  ["en", "my wrist hurts on the thumb side when I pour water from a jug", [k("location", RAD)]],
  ["en", "pain on top of my wrist when I do pushups", [k("location", DORS)]],
  ["en", "I think the bone is broken, the arm looks crooked and I heard it snap", [k("redFlags", FRAC)]],
  ["en", "elbow swelling is getting bigger quickly and the forearm is very tight", [k("redFlags", COMP), k("location", FORE)]],
  ["en", "my elbow is hot to touch, red and puffy", [k("redFlags", HOT)]],
  ["en", "left and right elbow both hurt", [k("redFlags", BILAT)]],
  ["en", "numb tingling in my little finger", [k("radiation", ULNN)]],
  ["en", "hand muscles look thin and wasted at the base of the thumb", [k("neuro", WASTE)]],
  ["en", "since I became a mum I carry my baby on one hip all day and the thumb side of my wrist is painful", [k("mechanism", THUMBUSE), k("location", RAD)]],
  ["en", "pain when I type on my laptop all day", [k("aggravating", TYPE)]],
  ["en", "no pain when gripping but it hurts at night", [k("pattern", NIGHT)]],
  ["en", "it is not painful on the inside of the elbow", []],
  ["en", "I have not had any trauma", []],
  ["en", "my shoulder and neck are fine, only the lower arm hurts", [k("location", FORE)]],
  ["en", "dropping things and weak hand", [k("neuro", DROP), k("neuro", WEAK)]],
  ["en", "pain goes down my forearm into the fingers", [k("radiation", INTOF)]],
  // ── Hinglish ──
  ["hi", "kohni ke bahar wale hisse me dard rehta hai", [k("location", LAT)]],
  ["hi", "bahar ki taraf kohni me jalan jaisa dard", [k("location", LAT)]],
  ["hi", "kohni ke pichle hisse me dard", [k("location", POST)]],
  ["hi", "kalai ke angoothe wale side dard", [k("location", RAD)]],
  ["hi", "glass pakadte hi dard hota hai", [k("aggravating", GRIP)]],
  ["hi", "bhari bag uthane se kohni dukhti hai", [k("aggravating", LIFT), k("mechanism", REPG)]],
  ["hi", "subah ke time zyada dard hota hai", [k("pattern", MORN)]],
  ["hi", "raat ko neend se jaag jata hu dard ki wajah se", [k("pattern", NIGHT)]],
  ["hi", "kaam ke dauran hi dard hota hai", [k("pattern", ACT)]],
  ["hi", "haath pe gira tha cycle se", [k("mechanism", FALL)]],
  ["hi", "mere ek haath ki ungliyan raat me sunn ho jati hain", [k("neuro", NCARP)]],
  ["hi", "kohni modne par chhoti ungli me jhunjhuni", [k("neuro", NCUB), k("radiation", ULNN)]],
  ["hi", "pakad bahut kamzor ho gayi hai", [k("neuro", WEAK)]],
  ["hi", "chai ka cup haath se gir jata hai", [k("neuro", DROP)]],
  ["hi", "dono kohni dukh rahi hain", [k("redFlags", BILAT)]],
  ["hi", "kabhi dard hota hai kabhi bilkul nahi", [k("pattern", INTER)]],
  ["hi", "hamesha dard rehta hai chain nahi milta", [k("pattern", CONST)]],
  ["hi", "tennis ya badminton nahi khelta", []],
  ["hi", "koi chot nahi lagi thi", []],
  // ── Hindi (Devanagari) ──
  ["de", "कोहनी के बाहर वाले हिस्से में दर्द रहता है", [k("location", LAT)]],
  ["de", "चाय का कप पकड़ते ही कोहनी में दर्द", [k("aggravating", GRIP)]],
  ["de", "सुबह उठने पर अकड़न और दर्द", [k("pattern", MORN)]],
  ["de", "रात को दर्द से नींद टूट जाती है", [k("pattern", NIGHT)]],
  ["de", "दर्द कभी कभी होता है", [k("pattern", INTER)]],
  ["de", "हाथ से चीज़ें छूट जाती हैं", [k("neuro", DROP)]],
  ["de", "भारी वजन उठाते समय कोहनी में दर्द", [k("aggravating", LIFT), k("mechanism", REPG)]],
  ["de", "कोहनी में गर्मी और लाल सूजन है", [k("redFlags", HOT)]],
  ["de", "दोनों कलाई में सुन्नपन", [k("redFlags", BILAT)]],
  ["de", "गिरने के बाद कलाई टेढ़ी लग रही है", [k("redFlags", FRAC)]],
  // ── mixed ──
  ["mx", "outer elbow me dard jab main cup pakadta hoon", [k("location", LAT), k("aggravating", GRIP)]],
  ["mx", "wrist ke thumb side par pain hai", [k("location", RAD)]],
  ["mx", "badminton khelte waqt elbow ke outside dard", [k("mechanism", RACQ), k("location", LAT)]],
  ["mx", "night me hand numb ho jata hai", [k("neuro", NCARP)]],
  // ── should stay silent: they contain words the rules look for, but are not about this complaint ──
  ["en", "my back hurts when I lift heavy boxes", []],
  ["en", "knee pain when climbing stairs", []],
  ["en", "the lifting of the ban was announced", []],
  ["en", "I lift weights regularly and feel great", []],
  ["en", "a morning walk is good for health", []],
  ["en", "I work night shifts", []],
  ["en", "there is not much elbow room in the car", []],
  ["en", "grip strength training equipment on sale", []],
  ["en", "my stomach hurts all day and I cannot sleep", []],
  ["en", "the neck pain is worse at night", []],
  ["en", "I fell asleep with my hand under my head", []],
  ["en", "hot weather and swollen feet", []],
  ["en", "what type of pain is it? sharp", []],
  ["hi", "raat ko movie dekhi", []],
  ["hi", "subah chai pi", []],
  ["hi", "kamar me dard hai bhari saman uthane se", []],
  ["de", "रात को फिल्म देखी", []],
  ["de", "घुटने में दर्द है सीढ़ियां चढ़ते समय", []],
];

export const WILD_C = [
  // ── English ──
  ["en", "I've had this nagging ache on the outer side of my right elbow for about six weeks", [k("location", LAT)]],
  ["en", "it really hurts when I lift a full kettle or carry shopping bags", [k("aggravating", LIFT)]],
  ["en", "my forearm feels tight and the pain shoots towards my wrist", [k("location", FORE)]],
  ["en", "pain is on the inner part of the elbow near the bony bump, I think it's golfer's elbow", [k("location", MED)]],
  ["en", "I started swimming a lot more and then this began", []],
  ["en", "I work on a construction site with a jackhammer all day", [k("mechanism", VIB)]],
  ["en", "it hurts mostly when I'm gripping the steering wheel on long drives", [k("aggravating", SUST), k("aggravating", GRIP)]],
  ["en", "I get pins and needles in my thumb and first two fingers, mostly when I sleep", [k("radiation", MEDN), k("neuro", NCARP)]],
  ["en", "the little finger goes numb whenever my elbow stays bent, like on a phone call", [k("neuro", NCUB), k("radiation", ULNN)]],
  ["en", "no numbness, no weakness, nothing like that", [k("neuro", NNONE)]],
  ["en", "I slipped on the stairs and put my hand out to stop the fall", [k("mechanism", FALL)]],
  ["en", "my wrist is swollen, very hot and red since yesterday and I feel feverish", [k("redFlags", HOT)]],
  ["en", "pain lasts the whole day and doesn't ease even with rest", [k("pattern", CONST)]],
  ["en", "pain flares up now and then for a few days and then settles", [k("pattern", INTER)]],
  ["en", "the elbow is most painful when I first get out of bed", [k("pattern", MORN)]],
  ["en", "I often wake up at 3am with a throbbing arm", [k("pattern", NIGHT)]],
  ["en", "it only hurts while I'm actually playing squash", [k("pattern", ACT), k("mechanism", RACQ)]],
  ["en", "swelling around the elbow has doubled in a few hours and the pain is unbearable", [k("redFlags", COMP)]],
  ["en", "both of my wrists ache in the mornings", [k("redFlags", BILAT), k("pattern", MORN)]],
  ["en", "I crashed my scooter and landed on the elbow", [k("mechanism", TRAUMA)]],
  ["en", "my fingers feel clumsy and I drop my keys", [k("neuro", DROP)]],
  ["en", "the thumb muscles look flat and hollow compared to the other hand", [k("neuro", WASTE)]],
  ["en", "tennis elbow I guess, started after a weekend of badminton", [k("location", LAT), k("mechanism", RACQ)]],
  ["en", "it does not radiate anywhere, stays right at the elbow", [k("radiation", NORAD)]],
  ["en", "the pain travels from the elbow down to my ring finger and pinky", [k("radiation", INTOF)]],
  ["en", "I think I broke my wrist, it looks bent and is very swollen", [k("redFlags", FRAC)]],
  ["en", "I type reports all day and my wrist is aching", [k("aggravating", TYPE)]],
  ["en", "the doctor said nothing is broken", []],
  ["en", "I was not injured in any accident", []],
  ["en", "my elbow does not hurt when I lift things", []],
  ["en", "the pain is not worse in the morning", []],
  // ── Hinglish ──
  ["hi", "kohni ke bahar ki side pe dard hai", [k("location", LAT)]],
  ["hi", "bag uthate waqt haath me dard hota hai", [k("aggravating", LIFT)]],
  ["hi", "tennis khelne ke baad se kohni dukh rahi hai", [k("mechanism", RACQ)]],
  ["hi", "raat ko hath sunn ho jata hai aur neend khul jati hai", [k("neuro", NCARP)]],
  ["hi", "haath se glass chhut jata hai", [k("neuro", DROP)]],
  ["hi", "pakadne me bahut takleef hoti hai", [k("aggravating", GRIP)]],
  ["hi", "kohni ke andar wali side dard hai, golf khelta hu", [k("mechanism", GOLF)]],
  ["hi", "dono kalai me dard hai", [k("redFlags", BILAT)]],
  ["hi", "subah uthte waqt dard zyada hota hai", [k("pattern", MORN)]],
  ["hi", "dard lagatar bana rehta hai din raat", [k("pattern", CONST)]],
  ["hi", "dard aata-jata rehta hai", [k("pattern", INTER)]],
  ["hi", "girne ke baad kohni tedhi ho gayi", [k("redFlags", FRAC)]],
  ["hi", "kalai ke upar ki taraf sujan aur garam", [k("redFlags", HOT)]],
  ["hi", "ungliyon me jhunjhuni hoti hai jab kohni mudti hai", [k("neuro", NCUB)]],
  ["hi", "kamzori ki wajah se cup nahi pakad pata", [k("neuro", WEAK)]],
  ["hi", "mere haath ki mansapeshiyan patli ho gayi hain", [k("neuro", WASTE)]],
  ["hi", "kapde dhone ke baad kohni me dard shuru hua", [k("mechanism", REPG)]],
  ["hi", "mujhe chot nahi lagi kabhi", []],
  ["hi", "kamar dard me bhari saman uthana mushkil hai", []],
  ["hi", "badminton nahi khelta main", []],
  // ── Hindi (Devanagari) ──
  ["de", "कोहनी के बाहर की तरफ दर्द रहता है", [k("location", LAT)]],
  ["de", "बैग उठाते समय हाथ में दर्द होता है", [k("aggravating", LIFT)]],
  ["de", "रात को दर्द ज्यादा बढ़ जाता है", [k("pattern", NIGHT)]],
  ["de", "सुबह सबसे ज्यादा दर्द होता है", [k("pattern", MORN)]],
  ["de", "हाथ में सुन्नपन रात में होता है", [k("neuro", NCARP)]],
  ["de", "हड्डी टूटी हुई लग रही है", [k("redFlags", FRAC)]],
  ["de", "कोहनी पर चोट लगी", [k("mechanism", TRAUMA)]],
  ["de", "सूजन तेजी से बढ़ रही है", [k("redFlags", COMP)]],
  ["de", "दर्द आता जाता रहता है", [k("pattern", INTER)]],
  ["de", "वजन उठाने पर दर्द", [k("aggravating", LIFT)]],
  // ── mixed ──
  ["mx", "elbow ke inner side me pain", [k("location", MED)]],
  ["mx", "morning me wrist stiff aur dard", [k("pattern", MORN)]],
  ["mx", "cup pakadte time outside elbow dard", [k("location", LAT), k("aggravating", GRIP)]],
  ["mx", "thumb ke paas wrist side pain, mobile chalane se", [k("location", RAD)]],
  ["mx", "golf aur tennis dono khelta hu", [k("mechanism", GOLF), k("mechanism", RACQ)]],
  ["mx", "no pain at night, only hurts when I type", [k("aggravating", TYPE)]],
  // ── look-alikes and unrelated: must stay silent ──
  ["en", "I read an article about elbow injuries", []],
  ["en", "my friend has tennis elbow", []],
  ["en", "the elbow macaroni was overcooked", []],
  ["en", "wrist watch repair shop is closed", []],
  ["en", "I need a hand with moving house", []],
  ["en", "thumbs down on that movie", []],
  ["en", "back to work on monday", []],
  ["en", "the grip of the golf club was new", []],
  ["en", "morning sickness and night shifts", []],
  ["en", "I lift my spirits by dancing", []],
  ["en", "heavy rain and strong wind", []],
  ["en", "the hot sun made me red and tired", []],
  ["en", "knee swelling is increasing quickly", []],
  ["en", "I could not sleep because of my cough", []],
  ["en", "pain in my tooth at night", []],
  ["en", "I have pain in my stomach after eating", []],
  ["en", "the Hindi word for elbow is kohni", []],
  ["en", "I woke up and made tea", []],
  ["en", "he has weak eyesight", []],
  ["en", "the hold music was annoying", []],
  ["hi", "paani garam hai", []],
  ["hi", "main raat ko jaldi so jata hu", []],
  ["hi", "bachche school gaye hain", []],
  ["de", "रात का खाना तैयार है", []],
  ["de", "सुबह की सैर अच्छी है", []],
  ["de", "कमर और घुटने में दर्द है", []],
];

export const WILD_D = [
  // ── English ──
  ["en", "pain at the point of my elbow when I lean on it at the desk", [k("location", POST)]],
  ["en", "there's a burning feeling along the thumb side of the forearm", [k("location", FORE)]],
  ["en", "I get a sharp pain on the inside of the elbow when I throw a ball", [k("mechanism", GOLF)]],
  ["en", "pain at the front of the elbow when I bend it and lift groceries", [k("location", ANT), k("aggravating", LIFT)]],
  ["en", "my grip has gone weak over the last month", [k("neuro", WEAK)]],
  ["en", "I keep spilling my tea because my hand shakes and drops the cup", [k("neuro", DROP)]],
  ["en", "waking up with numb hands almost every night", [k("neuro", NCARP)]],
  ["en", "tingling in the ring and little finger of my left hand after resting on my elbow", [k("radiation", ULNN)]],
  ["en", "I fell onto my wrist while skating", [k("mechanism", FALL)]],
  ["en", "after my fall the thumb base is very tender", [k("redFlags", SNUFF)]],
  ["en", "my elbow is swollen, warm and red and I have a fever", [k("redFlags", HOT)]],
  ["en", "my forearm swelling keeps getting bigger and the pain is terrible", [k("redFlags", COMP), k("location", FORE)]],
  ["en", "since the accident my elbow looks deformed", [k("redFlags", FRAC), k("mechanism", TRAUMA)]],
  ["en", "the pain never really goes away, it's there from morning to night", [k("pattern", CONST)]],
  ["en", "some days it hurts, some days it doesn't", [k("pattern", INTER)]],
  ["en", "elbow aches when I wake up and loosens as I move about", [k("pattern", MORN), k("pattern", IMPR)]],
  ["en", "during the night the pain is worse and I can't get comfortable", [k("pattern", NIGHT)]],
  ["en", "only when I use a screwdriver does it hurt", [k("pattern", ACT)]],
  ["en", "numbness in my pinky and the ring finger when I bend my elbow", [k("radiation", ULNN), k("neuro", NCUB)]],
  ["en", "I cannot make a proper fist, the grip is really weak", [k("neuro", WEAK)]],
  ["en", "I run a drill press at work, the vibration is constant", [k("mechanism", VIB)]],
  ["en", "the lateral side of my elbow hurts after a long squash match", [k("location", LAT), k("mechanism", RACQ)]],
  ["en", "wrist hurts on the pinky side when I turn a door handle", [k("location", ULN), k("aggravating", GRIP)]],
  ["en", "I opened a heavy door and now my wrist is sore at the base of the thumb", [k("location", THUMB)]],
  ["en", "he complains of pain when typing and mouse use for long hours", [k("aggravating", TYPE)]],
  ["en", "I hit my elbow on a table corner", [k("mechanism", TRAUMA)]],
  ["en", "No tingling, no fracture, no fever", []],
  ["en", "the pain is not constant", []],
  ["en", "never had numbness in my fingers", []],
  // ── Hinglish ──
  ["hi", "kohni ke bahar ki taraf jalan hoti hai", [k("location", LAT)]],
  ["hi", "kohni ke peeche chot lagi thi", [k("location", POST), k("mechanism", TRAUMA)]],
  ["hi", "haath me jhunjhuni raat bhar rehti hai", [k("neuro", NCARP)]],
  ["hi", "bhari bucket uthate waqt dard hota hai", [k("aggravating", LIFT), k("mechanism", REPG)]],
  ["hi", "tennis ya badminton khelte waqt kohni me dard", [k("mechanism", RACQ)]],
  ["hi", "chhoti ungli sunn rehti hai kohni modne par", [k("neuro", NCUB), k("radiation", ULNN)]],
  ["hi", "mera haath kamzor ho gaya hai pakad nahi bani", [k("neuro", WEAK)]],
  ["hi", "haath se chai ka cup gir jata hai", [k("neuro", DROP)]],
  ["hi", "kohni garam aur laal hai aur sujan bhi", [k("redFlags", HOT)]],
  ["hi", "dono haath sunn hain", [k("redFlags", BILAT)]],
  ["hi", "dard subah sabse zyada hota hai", [k("pattern", MORN)]],
  ["hi", "dard din bhar rehta hai", [k("pattern", CONST)]],
  ["hi", "kabhi kabhi hi dard hota hai", [k("pattern", INTER)]],
  ["hi", "gir gaya tha haath ke bal kalai tedhi dikh rahi hai", [k("mechanism", FALL), k("redFlags", FRAC)]],
  ["hi", "mobile chalane se angutha dukhta hai", [k("location", THUMB), k("aggravating", THMOV)]],
  ["hi", "tennis nahi khelta lekin dard hai", []],
  ["hi", "kohni me chot nahi lagi", []],
  // ── Hindi (Devanagari) ──
  ["de", "कोहनी के अंदरूनी हिस्से में दर्द है", [k("location", MED)]],
  ["de", "गिलास पकड़ते समय कोहनी में दर्द", [k("aggravating", GRIP)]],
  ["de", "रात में दर्द के कारण नींद नहीं आती", [k("pattern", NIGHT)]],
  ["de", "ठंड में दर्द बढ़ जाता है", []],
  ["de", "सुबह उठने पर कोहनी अकड़ जाती है", [k("pattern", MORN)]],
  ["de", "दोनों हाथों में झनझनाहट रहती है", [k("redFlags", BILAT)]],
  ["de", "कोहनी में गर्मी और सूजन है", [k("redFlags", HOT)]],
  ["de", "कलाई टेढ़ी दिख रही है", [k("redFlags", FRAC)]],
  ["de", "उंगली अचानक सीधी नहीं हो रही", [k("redFlags", TEND)]],
  // ── mixed ──
  ["mx", "outer elbow pain aur pakadne me problem", [k("location", LAT), k("aggravating", GRIP)]],
  ["mx", "wrist me tingling raat ko", [k("neuro", NCARP)]],
  ["mx", "elbow ke back side me dard", [k("location", POST)]],
  ["mx", "cup uthate time elbow me pain", [k("aggravating", GRIP)]],
  // ── look-alikes and unrelated: must stay silent ──
  ["en", "the elbow grease was needed to clean the floor", []],
  ["en", "I will go to the gym tomorrow", []],
  ["en", "please send the report by night", []],
  ["en", "both teams played well", []],
  ["en", "my hand is full, can you help?", []],
  ["en", "arm yourself with knowledge", []],
  ["en", "the pain of waiting was unbearable", []],
  ["en", "the football match was played in the morning", []],
  ["en", "he lifted the trophy", []],
  ["en", "grip tape for tennis rackets", []],
  ["en", "I have a headache and fever", []],
  ["en", "ankle sprain last year, now fine", []],
  ["en", "shoulder dislocation two years back", []],
  ["en", "the swelling in my ankle has increased", []],
  ["en", "I put my hand out to wave", []],
  ["en", "hot tea and cold water", []],
  ["hi", "kal subah meeting hai", []],
  ["hi", "raat ko dard nahi hota", []],
  ["de", "आज रात बारिश होगी", []],
];

export function score(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, want] of rows) {
    const got = understandStory(text).suggestions.map((s) => k(s.field, s.option));
    const wantSet = new Set(want);
    for (const g of got) { suggested++; if (wantSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of want) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
