// hipSheetSet.js -- the sentences of the Hip "everyday words" sheet (PhysioMind-Hip-Everyday-Words-DRAFT.pdf), written the way the
// CLINICIAN would type about the patient ("the patient", "they", short notes): English in four styles, Hinglish and Hindi, for all 7 hip
// conditions. Used by hipSheetSet.test.js (not a test itself). Row = [lang, text, must, may]:
//   must = options a physio would tick from that sentence (a miss costs recall)
//   may  = options that are also fair to suggest (neither right nor wrong: they do not count against precision)
//   anything else it suggests counts as wrong. A sentence with no must and no may must stay silent.
// lang: en = English, hi = Hinglish (Hindi in Latin letters), de = Hindi in Devanagari. The answer keys are DRAFTS written by Claude
// for Aditi to check. The Hip form has no question for "how it started" or "how long" as such, so those lines only count where a
// sentence also says something a form question covers (e.g. "no injury", "after a fall").
import { KEYS } from "./hipWildSets.js";
import { understandStory } from "../hipPhraseMap.js";

const { ADD, AGE, CAR, CATCH, CLICKOK, CLICKPAIN, EXTSNAP, FADIR, FALL, FAST, FLEXOR, GROIN, HARD, INSID, INTER, INTSNAP, ISCH, KICK, LATERAL, LUNGE, LYING, MORN, NIGHT, POST, PSIT, RETURN, STAIRS, TWIST, WALK, WORSE } = KEYS;

export const HIP_SHEET = [
  ["en", "Deep groin pain, worse with sitting and bending the hip. Sometimes a click or catch.", [GROIN, CATCH], [PSIT, CLICKOK, CLICKPAIN, FADIR]],
  ["en", "The patient says there is a deep ache at the front of the hip or groin when they sit for long, get out of a car or squat. Now and then it clicks or catches.", [FLEXOR, GROIN, CAR, CATCH], [PSIT, CLICKOK, CLICKPAIN, FADIR]],
  ["en", "Groin pain. Worse sitting, squatting. Clicking, catching.", [GROIN, CATCH], [PSIT, FADIR, CLICKOK, CLICKPAIN]],
  ["en", "They feel a deep pinching in the groin when they bring the knee up towards the chest, and it catches sometimes. Getting out of the car is the worst.", [GROIN, CATCH, CAR], [FADIR]],
  ["hi", "Kulhe ke aage groin mein gehra dard, der tak baithne aur ghutna seene ki taraf lane par badhta hai. Kabhi kabhi click ya atak.", [GROIN, FLEXOR, PSIT, CATCH], [FADIR, CLICKOK, CLICKPAIN]],
  ["de", "कूल्हे के आगे जांघ के जोड़ में गहरा दर्द, देर तक बैठने और घुटना सीने की तरफ लाने पर बढ़ता है। कभी कभी क्लिक या अटकना।", [FLEXOR, GROIN, PSIT, CATCH], [FADIR, CLICKOK, CLICKPAIN]],
  ["en", "Gradual, no injury. Sometimes after a twist.", [INSID], [TWIST]],
  ["en", "It crept up slowly over months with no real injury, or it began after a twist on the hip.", [INSID, TWIST], []],
  ["en", "Gradual, or after a twist.", [], [INSID, TWIST]],
  ["en", "No single event. It built up while they were playing football, and then got worse after a bad twist.", [TWIST], [INSID, FAST]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi. Kabhi mudne ke baad.", [INSID], [TWIST]],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं। कभी मुड़ने के बाद।", [INSID], [TWIST]],
  ["en", "Repeated deep bending and turning of the hip in sport, such as football, hockey or martial arts.", [], [INSID, TWIST, FAST]],
  ["en", "Lots of deep squats and twisting on the hip in sport.", [], [INSID, TWIST, FAST]],
  ["en", "Repetitive hip flexion and rotation. Sport.", [INSID], [TWIST, FAST]],
  ["en", "They play a lot of football and keep twisting on the hip. Sometimes a sudden pivot made it worse.", [TWIST], [INSID, FAST]],
  ["hi", "Khel mein baar baar kulha mod kar ghumana, football, hockey.", [], [INSID, TWIST, FAST]],
  ["de", "खेल में बार बार कूल्हा मोड़कर घुमाना, फुटबॉल, हॉकी।", [], [INSID, TWIST, FAST]],
  ["en", "Months to years.", [], []],
  ["en", "It has been there for months, even years.", [], []],
  ["en", "Months–years.", [], []],
  ["en", "On and off for a couple of years, worse with activity.", [], [INTER, INSID]],
  ["hi", "Mahino se saalon tak.", [], []],
  ["de", "महीनों से सालों तक।", [], []],
  ["en", "Groin or thigh pain with walking, stiffness in the morning, trouble with shoes and socks.", [GROIN, MORN, WALK], []],
  ["en", "The patient has a deep ache in the groin that goes to the thigh or knee, and the hip is stiff in the morning.", [GROIN, MORN], []],
  ["en", "Groin and thigh pain. Morning stiffness under 30 minutes. Difficulty with socks and shoes.", [GROIN, MORN], []],
  ["en", "Putting on socks and shoes is hard now, and the hip aches when they walk any distance.", [WALK], []],
  ["hi", "Groin ya jaangh mein dard, chalne par, subah akdan, moze aur joote pehanne mein dikkat.", [GROIN, WALK, MORN], []],
  ["de", "जांघ के जोड़ या जांघ में दर्द, चलने पर, सुबह अकड़न, मोज़े और जूते पहनने में दिक्कत।", [MORN], [GROIN, WALK]],
  ["en", "Slowly over months or years, usually after 50.", [], [INSID, AGE]],
  ["en", "It came on gradually over the years.", [], [INSID]],
  ["en", "Gradual; age over 50.", [], [INSID, AGE]],
  ["en", "No injury. It crept up over the years.", [INSID], [AGE]],
  ["hi", "Mahino ya saalon mein dheere dheere, aam taur par 50 ke baad.", [INSID], [AGE]],
  ["de", "महीनों या सालों में धीरे धीरे, आमतौर पर 50 के बाद।", [INSID], [AGE]],
  ["en", "Wear and tear. More likely with extra weight, an old hip problem or heavy work.", [AGE], [INSID]],
  ["en", "It is wear and tear, with a family history in some.", [AGE], []],
  ["en", "Degenerative.", [], [AGE]],
  ["en", "Years of heavy work and an old hip injury.", [], [AGE, INSID]],
  ["hi", "Ghisaav. Mote hone, purani chot ya bhari kaam se zyada hota hai.", [AGE], [INSID]],
  ["de", "घिसाव। मोटापे, पुरानी चोट या भारी काम से ज्यादा होता है।", [AGE], [INSID]],
  ["en", "Months to years, with good spells and bad spells.", [], [INTER]],
  ["en", "Months to years, with good days and bad days.", [], [INTER]],
  ["en", "Months to years. Flare-ups.", [], [INTER]],
  ["en", "Some weeks it is fine, some weeks it is bad.", [], [INTER]],
  ["hi", "Mahine se saal, kabhi theek kabhi zyada.", [], [INTER]],
  ["de", "महीने से साल, कभी ठीक कभी ज़्यादा।", [], [INTER]],
  ["en", "Pain on the outer side of the hip, worse lying on that side at night and on stairs.", [LATERAL, LYING, STAIRS], [NIGHT]],
  ["en", "The patient cannot lie on the painful side at night. There is a sore spot on the outside of the hip.", [LATERAL, LYING], [NIGHT]],
  ["en", "Lateral hip pain. Side-lying at night. Stairs.", [LATERAL], [STAIRS, LYING, NIGHT]],
  ["en", "They wake at night when they roll onto the sore side, and climbing stairs makes the outer hip burn.", [LATERAL, LYING, STAIRS], [NIGHT]],
  ["hi", "Kulhe ke bahar ki taraf dard, raat ko us karwat lette hue aur seedhiyan chadhne par badhta hai.", [LATERAL, LYING, STAIRS], [NIGHT]],
  ["de", "कूल्हे के बाहर की तरफ दर्द, रात को उस करवट लेटने पर और सीढ़ियां चढ़ने पर बढ़ता है।", [LATERAL, LYING, STAIRS], [NIGHT]],
  ["en", "Gradual, or after more walking than usual.", [], [INSID]],
  ["en", "It came on slowly, or after a sudden rise in walking or exercise.", [], [INSID]],
  ["en", "Gradual; women 40–60 mostly.", [], [INSID]],
  ["en", "No injury. It started after they began a new exercise class.", [INSID], []],
  ["hi", "Dheere dheere, ya zyada chalne ke baad.", [], [INSID]],
  ["de", "धीरे धीरे, या ज्यादा चलने के बाद।", [], [INSID]],
  ["en", "Overload of the hip muscle tendons from standing, walking or single-leg activity.", [], [INSID]],
  ["en", "Too much walking or standing, or a new exercise.", [], [INSID]],
  ["en", "Tendon overload. Prolonged standing, single-leg loading.", [], [INSID]],
  ["en", "They stand a lot at work and started running again, and the outer hip got sore.", [LATERAL, RETURN], [INSID]],
  ["hi", "Zyada der khade rehna, chalna ya naya exercise.", [], [INSID]],
  ["de", "ज्यादा देर खड़े रहना, चलना या नई कसरत।", [], [INSID]],
  ["en", "Months, often long-lasting.", [], []],
  ["en", "It has been going on for months.", [], []],
  ["en", "Months.", [], []],
  ["en", "It has been bothering them for a few months, worse at night on that side.", [], [NIGHT, LYING]],
  ["hi", "Kai mahine se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "Deep pain in the buttock at the sitting bone, worse sitting on hard surfaces and when running fast.", [ISCH, HARD], [PSIT, POST, FAST]],
  ["en", "The patient has a deep ache at the sit bone when sitting for a long time, especially on a hard seat. Sprinting makes it worse.", [ISCH, HARD, PSIT], [FAST]],
  ["en", "Sit bone pain. Hard seats. Fast running.", [ISCH], [HARD, FAST, PSIT]],
  ["en", "They get a deep cramp in the buttock on long car journeys and when they speed up on a run.", [], [POST, PSIT, FAST, CAR]],
  ["hi", "Baithne ki haddi (sit bone) par gehra dard, sakht jagah par baithne aur tez daudne par badhta hai.", [ISCH, HARD], [PSIT, FAST]],
  ["de", "बैठने की हड्डी पर गहरा दर्द, सख्त जगह पर बैठने और तेज़ दौड़ने पर बढ़ता है।", [ISCH, HARD], [PSIT, FAST]],
  ["en", "Gradual with no single event. Many cannot name a moment.", [], [INSID]],
  ["en", "It came on slowly over weeks after training changes.", [], [INSID]],
  ["en", "Gradual onset, no injury.", [INSID], []],
  ["en", "No fall or injury. It just built up as the mileage increased.", [INSID], []],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [INSID], []],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [INSID], []],
  ["en", "More mileage, hills and speed work. Long stride when running.", [], [INSID, FAST]],
  ["en", "Training load went up with hill sessions and intervals.", [], [INSID, FAST]],
  ["en", "Running overload: mileage, hills, intervals.", [], [INSID, FAST]],
  ["en", "They increased their weekly mileage and added hill sprints.", [INSID], [FAST]],
  ["hi", "Daud ki doori badhana, chadhai aur tez daud ka abhyas.", [], [INSID, FAST]],
  ["de", "दौड़ की दूरी बढ़ाना, चढ़ाई और तेज़ दौड़ का अभ्यास।", [], [INSID, FAST]],
  ["en", "Months, often long-lasting.", [], []],
  ["en", "It has been going on for many months.", [], []],
  ["en", "Months–years.", [], []],
  ["en", "Over a year of symptoms, worse the day after running.", [], [INTER, WORSE]],
  ["hi", "Kai mahine se, aksar lambe samay tak.", [], []],
  ["de", "कई महीनों से, अक्सर लंबे समय तक।", [], []],
  ["en", "Inner thigh and groin pain with kicking and changing direction.", [ADD, GROIN], [KICK, TWIST, FAST]],
  ["en", "The patient has a sharp pain in the groin when they kick or sprint, and the inner thigh is tender.", [GROIN, ADD, KICK], [FAST]],
  ["en", "Groin pain. Inner thigh tender. Kicking, cutting.", [GROIN, ADD], [KICK, TWIST, FAST]],
  ["en", "They felt a sudden twinge high on the inside of the thigh while sprinting for the ball, and it still hurts when they squeeze their legs together.", [ADD], [FAST, TWIST, KICK]],
  ["hi", "Jaangh ke andar aur groin mein dard, laat maarne aur direction badalne par.", [ADD, GROIN, KICK], [TWIST, FAST]],
  ["de", "जांघ के अंदर और ग्रोइन में दर्द, लात मारने और दिशा बदलने पर।", [ADD, GROIN, KICK], [TWIST, FAST]],
  ["en", "Sudden during a kick or a sprint, or gradual over weeks.", [], [KICK, FAST, INSID]],
  ["en", "It happened suddenly while kicking, and then built up over the next few days.", [], [KICK, INSID]],
  ["en", "Sudden (kick or sprint) or gradual.", [], [KICK, FAST, INSID]],
  ["en", "No warning at first, then it got worse over a few weeks of football training.", [], [INSID, FAST]],
  ["hi", "Achanak laat maarte waqt, ya hafto mein dheere dheere.", [], [KICK, INSID]],
  ["de", "अचानक लात मारते समय, या हफ्तों में धीरे धीरे।", [], [KICK, INSID]],
  ["en", "Kicking, sudden changes of direction and sprinting in football or hockey.", [KICK], [TWIST, FAST]],
  ["en", "Forceful kicking or a sudden stretch of the leg out to the side.", [KICK], [LUNGE, FAST]],
  ["en", "Kicking, cutting, sprinting. Football, hockey.", [KICK], [TWIST, FAST]],
  ["en", "They were sprinting and then planted and turned to cut away from a defender.", [], [TWIST, FAST]],
  ["hi", "Laat maarna, achanak direction badalna, daudna, football ya hockey mein.", [KICK], [TWIST, FAST]],
  ["de", "लात मारना, अचानक दिशा बदलना, दौड़ना, फुटबॉल या हॉकी में।", [KICK], [TWIST, FAST]],
  ["en", "Weeks if acute.", [], []],
  ["en", "Acute: two to six weeks. If it lingers, it can last months.", [], []],
  ["en", "Acute: weeks. Chronic: months.", [], []],
  ["en", "It has been on and off for a few months.", [], [INTER]],
  ["hi", "Achanak ho to hafte, purana ho to mahine.", [], []],
  ["de", "अचानक हो तो हफ्ते, पुराना हो तो महीने।", [], []],
  ["en", "Deep buttock pain that is worse with sitting, sometimes shooting down the back of the thigh.", [POST], [PSIT]],
  ["en", "The patient has pain in the buttock and cannot sit for more than half an hour. It sometimes spreads down the back of the thigh with tingling.", [POST], [PSIT]],
  ["en", "Buttock pain. Worse sitting. Sciatic-type leg pain.", [POST], [PSIT]],
  ["en", "They get a deep ache in the glutes after sitting in the car, and it shoots down the leg.", [POST], [PSIT, CAR]],
  ["hi", "Chutad mein gehra dard, der tak baithne par badhta hai, kabhi kabhi jaangh ke peeche tak jata hai.", [POST, PSIT], []],
  ["de", "चूतड़ में गहरा दर्द, देर तक बैठने पर बढ़ता है, कभी कभी जांघ के पीछे तक जाता है।", [POST, PSIT], []],
  ["en", "Gradual from long sitting, or sudden after a fall on the buttock.", [], [INSID, FALL]],
  ["en", "It crept up from a lot of sitting and driving, or began after a fall onto the buttock.", [FALL], [INSID]],
  ["en", "Gradual, or after a fall on the buttock.", [], [INSID, FALL]],
  ["en", "No injury at first, but it got much worse after a sudden increase in running.", [INSID], []],
  ["hi", "Dheere dheere ya chutad ke bal girne ke baad.", [], [INSID, FALL]],
  ["de", "धीरे धीरे या चूतड़ के बल गिरने के बाद।", [], [INSID, FALL]],
  ["en", "Long hours of sitting, driving, or a wallet in the back pocket.", [], [PSIT, INSID]],
  ["en", "A fall onto the buttock, or a sudden rise in running.", [], [FALL, INSID]],
  ["en", "Prolonged sitting. Fall. Running overload.", [], [PSIT, FALL, INSID]],
  ["en", "They drive long distances and then started running more.", [], [PSIT, INSID, RETURN]],
  ["hi", "Der tak baithna, gaadi chalana, ya chutad par girna.", [], [PSIT, FALL, INSID]],
  ["de", "देर तक बैठना, गाड़ी चलाना, या चूतड़ पर गिरना।", [], [PSIT, FALL, INSID]],
  ["en", "Weeks to months.", [], []],
  ["en", "It has gone on for several weeks.", [], []],
  ["en", "Weeks–months.", [], []],
  ["en", "Persistent for a few months now.", [], []],
  ["hi", "Hafte se mahine.", [], []],
  ["de", "हफ्ते से महीने।", [], []],
  ["en", "A snap at the front of the hip or groin when standing up from a chair or climbing stairs.", [INTSNAP], [CLICKOK, CLICKPAIN, STAIRS, GROIN, FLEXOR]],
  ["en", "The patient hears and feels a clunk on the outside of the hip when walking. It is not painful.", [EXTSNAP], [CLICKOK, CLICKPAIN, LATERAL]],
  ["en", "Internal snapping, front of the hip. Stairs, sit to stand.", [INTSNAP], [STAIRS, FLEXOR]],
  ["en", "They feel the hip snap over the side bone when they swing the leg, and there is a dull ache afterwards.", [EXTSNAP], [CLICKOK, CLICKPAIN, LATERAL]],
  ["hi", "Kulhe ke aage chatakne ki awaaz aati hai, kursi se uthte aur seedhiyan chadhte waqt.", [INTSNAP], [CLICKOK, CLICKPAIN, STAIRS, FLEXOR]],
  ["de", "कूल्हे के आगे चटकने की आवाज़ आती है, कुर्सी से उठते और सीढ़ियां चढ़ते समय।", [INTSNAP], [CLICKOK, CLICKPAIN, STAIRS, FLEXOR]],
  ["en", "Gradual, no injury.", [INSID], []],
  ["en", "It came on slowly with no injury, or after a minor twist.", [INSID], [TWIST]],
  ["en", "Gradual onset.", [INSID], []],
  ["en", "No single event. It started after months of dance practice.", [], [INSID]],
  ["hi", "Dheere dheere, koi chot nahi.", [INSID], []],
  ["de", "धीरे धीरे, कोई चोट नहीं।", [INSID], []],
  ["en", "Tendon flicking over a bony bump with repeated hip bending, in dancers and runners.", [], [INSID, FAST]],
  ["en", "Repeated hip flexion and extension, such as dance, running or gym work.", [], [INSID, FAST]],
  ["en", "Iliopsoas over the pelvic brim (internal) or IT band over the trochanter (external).", [], [INSID]],
  ["en", "They dance for hours and the hip started snapping as the leg swings.", [], [INSID]],
  ["hi", "Dance ya daud mein kulha baar baar mudna.", [], [INSID, FAST]],
  ["de", "डांस या दौड़ में कूल्हा बार बार मुड़ना।", [], [INSID, FAST]],
  ["en", "Months to years.", [], []],
  ["en", "It has been there for many months.", [], []],
  ["en", "Months–years. Most settle in 6–12 months.", [], []],
  ["en", "On and off for a year or two.", [], [INTER]],
  ["hi", "Mahine se saal.", [], []],
  ["de", "महीने से साल।", [], []],
  ["en", "The patient is a 52 year old accountant from Nagpur.", [], []],
  ["en", "Referred by the family doctor for physiotherapy.", [], []],
  ["en", "Wants to get back to playing with the grandchildren.", [], []],
  ["en", "A neighbour recommended the clinic.", [], []],
  ["en", "Her mother had a hip replacement last year.", [], []],
  ["en", "Assessment done on Monday and the plan was explained.", [], []],
  ["hi", "Mareez ek bank mein kaam karte hain aur Nagpur se aate hain.", [], []],
  ["de", "मरीज़ को डॉक्टर ने फिज़ियोथेरेपी के लिए भेजा है।", [], []],
];

// Same scoring as the other exams, except "may" answers are neutral.
export function scoreSheet(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, must, may] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const okSet = new Set([...must, ...may]);
    for (const g of got) { suggested++; if (okSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of must) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
