// hipSheetSetFresh.js -- a SECOND, fresh exam in the clinician's voice ("the patient", "they", short notes), written AFTER the Hip matcher
// had been fixed for the sheet's own sentences (hipSheetSet.js). None of these sentences was used to tune the matcher before their first
// run was recorded. Row = [lang, text, must, may] -- same meaning as in hipSheetSet.js. The answer keys are DRAFTS written by Claude for
// Aditi to check.
import { KEYS } from "./hipWildSets.js";

const { GROIN, FLEXOR, LATERAL, POST, ISCH, ADD, PUBIC, INSID, AGE, TWIST, FALL, KICK, LUNGE, FAST, RETURN, FADIR, CROSS, PSIT, HARD, LYING, WALK,
  STAIRS, CAR, INTER, CONST, NIGHT, MORN, IMPR, WORSE, CLICKOK, CLICKPAIN, CATCH, GIVEWAY, LOCK, INTSNAP, EXTSNAP, CREP } = KEYS;

export const HIP_SHEET_FRESH = [
  // FAI / labral tear
  ["en", "Deep anterior hip pain on sitting for long periods, worse getting out of the car.", [FLEXOR, PSIT, CAR], []],
  ["en", "Groin pain with deep squats. Clicking sound in the hip, painless.", [GROIN, CLICKOK], [FADIR]],
  ["en", "Sharp pain in the groin when the knee is pulled across the body.", [GROIN, FADIR], []],
  ["en", "Hip locks briefly after sitting cross-legged.", [LOCK], [CROSS, PSIT]],
  ["en", "Twisted the hip during a football match, then pain in the groin since.", [TWIST, GROIN], [FAST]],
  ["en", "Gradual onset in a hockey player, no injury, ache at the front of the hip.", [INSID, FLEXOR], [FAST]],
  ["en", "Feels the hip giving way when they pivot, with a catching sensation.", [GIVEWAY, CATCH], []],
  ["en", "Pain in the groin that comes and goes with activity.", [GROIN, INTER], []],
  ["hi", "Kulhe ke aage dard, ghutna seene ki taraf lane par badhta hai.", [FLEXOR], [FADIR]],
  ["hi", "Groin mein dard aur kulhe mein click ki awaaz, dard ke bina.", [GROIN], [CLICKOK]],
  ["de", "कूल्हे के आगे दर्द, देर तक बैठने पर बढ़ता है।", [FLEXOR, PSIT], []],
  ["de", "कूल्हा मुड़ने के बाद ग्रोइन में दर्द शुरू हुआ।", [GROIN], [TWIST]],
  // Hip osteoarthritis
  ["en", "Hip pain in the groin on walking, stiff first thing in the morning.", [GROIN, MORN], [WALK]],
  ["en", "Age-related degenerative changes, pain on stairs and when getting out of a chair.", [AGE, STAIRS], []],
  ["en", "Night pain in the hip, difficulty lying on that side.", [NIGHT, LYING], []],
  ["en", "Constant deep ache in the groin, rarely eases.", [GROIN, CONST], []],
  ["en", "Pain improves through the day once they get moving.", [IMPR], []],
  ["en", "Grinding in the hip when walking.", [CREP], [WALK]],
  ["en", "Cannot put on socks because the hip is stiff and painful.", [], [MORN]],
  ["en", "Worse through the day on their feet, better after rest.", [WORSE], [INTER]],
  ["hi", "Kulhe ke andar groin mein dard, subah akdan, chalne par badhta hai.", [GROIN, MORN], [WALK]],
  ["hi", "Ghisaav ki wajah se kulhe mein dard.", [AGE], []],
  ["de", "रात को कूल्हे में दर्द होता है और करवट लेटना मुश्किल है।", [NIGHT], [LYING]],
  ["de", "सुबह कूल्हे में अकड़न, चलने से थोड़ा आराम।", [MORN], [IMPR, WALK]],
  // Greater trochanteric pain syndrome
  ["en", "Lateral hip pain, cannot sleep on the affected side.", [LATERAL, LYING], [NIGHT]],
  ["en", "Pain over the greater trochanter on climbing stairs.", [LATERAL, STAIRS], []],
  ["en", "Outer hip pain after standing for hours at work.", [LATERAL], [INSID]],
  ["en", "Pain on the side of the hip, worse lying on that side.", [LATERAL, LYING], []],
  ["en", "No injury, gradual onset of pain on the outside of the hip.", [INSID, LATERAL], []],
  ["en", "Pain at night on the sore hip, wakes them when they roll over.", [NIGHT, LYING], [LATERAL]],
  ["en", "Trochanteric pain, better with rest, worse walking uphill.", [LATERAL], [WALK, INTER]],
  ["en", "Snapping on the outside of the hip when they climb stairs.", [EXTSNAP], [LATERAL, STAIRS, CLICKOK, CLICKPAIN]],
  ["hi", "Kulhe ke side mein dard, us karwat sone par badhta hai.", [LATERAL, LYING], [NIGHT]],
  ["hi", "Seedhiyan chadhne par kulhe ke bahar ki taraf dard.", [LATERAL, STAIRS], []],
  ["de", "कूल्हे के बाहर की तरफ दर्द, उस करवट लेटने पर बढ़ता है।", [LATERAL, LYING], []],
  ["de", "सीढ़ियां चढ़ने पर कूल्हे के साइड में दर्द।", [LATERAL, STAIRS], []],
  // Proximal hamstring tendinopathy
  ["en", "Ischial tuberosity pain on sitting on a hard bench.", [ISCH, HARD], [PSIT]],
  ["en", "Deep buttock ache when running fast, eases when they slow down.", [POST], [FAST, INTER]],
  ["en", "Pain at the sitting bone after long drives.", [ISCH], [PSIT, CAR]],
  ["en", "Gradual, no injury, after increasing weekly mileage.", [INSID], []],
  ["en", "Sprinting makes the sit bone pain worse.", [ISCH], [FAST]],
  ["en", "Pain in the buttock radiating to the back of the thigh on stretching.", [POST], []],
  ["en", "Hurts to sit on hard chairs, fine when standing.", [HARD], [PSIT]],
  ["en", "Symptoms worse the morning after a hill session.", [], [MORN, WORSE]],
  ["hi", "Sit bone par dard, sakht kursi par baithne se badhta hai.", [ISCH, HARD], [PSIT]],
  ["hi", "Tez daudne par chutad mein gehra dard.", [POST], [FAST]],
  ["de", "बैठने की हड्डी में दर्द, देर तक बैठने पर बढ़ता है।", [ISCH, PSIT], []],
  ["de", "धीरे धीरे शुरू हुआ, दौड़ की दूरी बढ़ाने के बाद।", [INSID], []],
  // Adductor-related groin pain
  ["en", "Sudden pain in the inner thigh while kicking the ball.", [ADD, KICK], [FAST]],
  ["en", "Groin pain after a sudden change of direction in hockey.", [GROIN], [TWIST, FAST]],
  ["en", "Tender adductors, groin pain squeezing the legs together.", [GROIN], [ADD]],
  ["en", "Pulled the inside of the thigh lunging for a wide pass.", [ADD, LUNGE], [FAST, KICK]],
  ["en", "Pubic pain and groin ache with sit-ups, gradual onset over weeks.", [PUBIC, GROIN], [INSID]],
  ["en", "Inner thigh pain on running at speed.", [ADD], [FAST]],
  ["en", "Pain high in the groin after tackling, worse kicking.", [GROIN, KICK], []],
  ["en", "Overstretched the groin doing the splits.", [], [GROIN]],
  ["hi", "Jaangh ke andar dard, laat maarte waqt achanak.", [ADD, KICK], []],
  ["hi", "Groin mein dard, direction badalne par badhta hai.", [GROIN], [TWIST]],
  ["de", "जांघ के अंदर दर्द, लात मारने पर।", [ADD, KICK], []],
  ["de", "ग्रोइन में दर्द, दौड़ते समय अचानक शुरू हुआ।", [GROIN], [FAST]],
  // Piriformis / deep gluteal syndrome
  ["en", "Buttock pain on prolonged sitting, tingling down the back of the leg.", [POST, PSIT], []],
  ["en", "Deep gluteal pain after a fall onto the buttock.", [POST, FALL], []],
  ["en", "Pain deep in the glutes when driving for long.", [POST, PSIT], [CAR]],
  ["en", "Sciatica-like pain, worse sitting on hard surfaces, better walking.", [HARD], [POST, PSIT]],
  ["en", "Piriformis tenderness, pain on squatting.", [], [POST]],
  ["en", "No injury, gradual onset after months of desk work.", [INSID], [PSIT]],
  ["en", "Worse after sitting more than half an hour.", [], [PSIT]],
  ["en", "Buttock pain with running hills, no back pain.", [POST], [FAST]],
  ["hi", "Chutad mein dard, der tak baithne par badhta hai aur pair mein jhunjhuni.", [POST, PSIT], []],
  ["hi", "Chutad par girne ke baad se gehra dard.", [POST, FALL], []],
  ["de", "नितंब में गहरा दर्द, देर तक बैठने पर बढ़ता है।", [POST, PSIT], []],
  ["de", "गाड़ी चलाने पर चूतड़ में दर्द और पैर में झनझनाहट।", [POST], [PSIT, CAR]],
  // Snapping hip
  ["en", "Audible snap at the front of the hip when lifting the leg.", [INTSNAP], [FLEXOR, CLICKOK, CLICKPAIN]],
  ["en", "Clunking on the outside of the hip when walking, no pain.", [EXTSNAP], [CLICKOK, LATERAL]],
  ["en", "Clicking in the hip, painless, for many months.", [CLICKOK], []],
  ["en", "Painful clicking in the hip when standing from a chair.", [CLICKPAIN], []],
  ["en", "Snap over the greater trochanter when they swing the leg.", [EXTSNAP], [LATERAL]],
  ["en", "Dancer with anterior hip snapping, gradual onset.", [INTSNAP, INSID], [FLEXOR]],
  ["en", "Hip catches when they flex it past 90 degrees.", [CATCH], []],
  ["en", "Grating and grinding in the hip.", [CREP], []],
  ["hi", "Kulhe ke aage tak ki awaaz aati hai, dard nahi hota.", [INTSNAP], [CLICKOK, FLEXOR]],
  ["hi", "Kulhe mein click ki awaaz, dard ke saath.", [CLICKPAIN], []],
  ["de", "कूल्हे में क्लिक की आवाज़, बिना दर्द के।", [CLICKOK], []],
  ["de", "कूल्हे के बाहर चटकने की आवाज़ टहलते समय।", [EXTSNAP], [LATERAL]],
  // must stay silent
  ["en", "Patient works as a driver and lives in Surat.", [], []],
  ["en", "Medical history: type 2 diabetes, on metformin.", [], []],
  ["en", "Pain score is 6 out of 10.", [], []],
  ["en", "He has been referred by his employer.", [], []],
  ["en", "She would like to return to yoga eventually.", [], []],
  ["en", "Husband brought the patient to the clinic.", [], []],
  ["hi", "Mareez ko pichle hafte doctor ne dekha tha.", [], []],
  ["de", "मरीज़ की उम्र पचास साल है।", [], []],
];
