// kneeSheetSet.js -- the sentences of the Knee "everyday words" sheet (PhysioMind-Knee-Everyday-Words-DRAFT.pdf), written the way
// the CLINICIAN would type about the patient ("the patient", "they"): English in four styles, Hinglish and Hindi. Used by
// kneeSheetSet.test.js (not a test itself). Row = [lang, text, must, may]:
//   must = options a physio would tick from that sentence (a miss costs recall)
//   may  = options that are also fair to suggest (neither right nor wrong: they do not count against precision)
//   anything else it suggests counts as wrong. A sentence with no must and no may must stay silent.
// lang: en = English, hi = Hinglish (Hindi in Latin letters), de = Hindi in Devanagari. The answer keys are DRAFTS written by Claude
// for Aditi to check. The sheet had 216 sentences; the Knee form has no question for "how it started" or "how long" as such,
// so those lines only count where they also say something a form question covers (e.g. "no injury, overuse", "morning stiffness").
import { KEYS, } from "./kneeWildSets.js";
import { understandStory } from "../kneePhraseMap.js";

const { ANT, AROUND, BELOW, MEDIAL, LATERAL, POPL, INSID, TWIST, DIRECT, HYPER, LAND, PIVOT, INTER, MORN, ACT, GPIVOT, GSTAIRS, GRANDOM, LKTRUE, LKMOM, SWELLNOW, WEIGHT, LOCKEDK, IMPR } = KEYS;

export const KNEE_SHEET = [
  ["en", "Knee gave way and swelled up straight away. The patient felt a pop. It keeps giving way now.", [SWELLNOW], [TWIST, GRANDOM]],
  ["en", "The patient says the knee just buckled under them, they heard a snap, and it puffed up in no time. It feels like it will fold again.", [], [SWELLNOW, GRANDOM]],
  ["en", "Knee twisted. Pop heard. Big swelling. Feels unstable.", [TWIST], [SWELLNOW, GRANDOM]],
  ["en", "They were playing when something went in the knee. They could not carry on, it blew up like a balloon, and now they do not trust it when they turn.", [], [SWELLNOW, GPIVOT, WEIGHT, GRANDOM]],
  ["hi", "Ghutna mud gaya, “pop” ki awaaz aayi aur turant sujan aa gayi. Ab ghutna dhokha deta hai.", [SWELLNOW], [TWIST, GRANDOM]],
  ["de", "घुटना मुड़ गया, “पॉप” की आवाज़ आई और तुरंत सूजन आ गई। अब घुटना धोखा देता है।", [SWELLNOW], [TWIST, GRANDOM]],
  ["en", "Sudden, in one moment, while playing.", [], []],
  ["en", "It happened in a flash. They were fine one second and not the next.", [], []],
  ["en", "Sudden, during sport.", [], []],
  ["en", "There was no warning. They were running or playing normally and then it just happened.", [], []],
  ["hi", "Achanak, khelte waqt ek hi pal mein.", [], []],
  ["de", "अचानक, खेलते समय एक ही पल में।", [], []],
  ["en", "Foot was stuck and they turned, or they landed badly from a jump.", [TWIST, LAND], [PIVOT]],
  ["en", "They planted the foot and twisted the body over it, or came down awkwardly after a jump.", [LAND], [TWIST, PIVOT]],
  ["en", "Twisted on a fixed foot, or bad landing.", [TWIST, LAND], [PIVOT]],
  ["en", "The foot stayed on the ground while the body turned, or they jumped for a ball and the knee collapsed inwards on landing.", [LAND], [TWIST, PIVOT]],
  ["hi", "Pair zameen par atka tha aur ghutna mud gaya, ya kood kar galat landing hui.", [TWIST, LAND], [PIVOT]],
  ["de", "पैर ज़मीन पर अटका था और घुटना मुड़ गया, या कूदकर गलत तरह से उतरा।", [TWIST, LAND], [PIVOT]],
  ["en", "Swelling for a week or two. If it is old, it has been giving way for months or years.", [], [GRANDOM]],
  ["en", "The swelling went down in a week or two, but the knee still lets them down now and then. It has been months or years.", [], [GRANDOM]],
  ["en", "New injury: swelling 1–2 weeks. Old injury: giving way for months or years.", [], [GRANDOM]],
  ["en", "For the first few days it was swollen and sore. Even after the swelling settled, it still gives way when they twist.", [GPIVOT], [GRANDOM]],
  ["hi", "Sujan hafte–do hafte rehti hai. Purani ho to mahino ya saalon se dhokha deta hai.", [], [GRANDOM]],
  ["de", "सूजन एक-दो हफ़्ते रहती है। पुरानी हो तो महीनों या सालों से धोखा देता है।", [], [GRANDOM]],
  ["en", "Pain and swelling at the back of the knee after a fall or accident. The knee feels loose.", [POPL], [SWELLNOW, GRANDOM, DIRECT]],
  ["en", "The patient had a fall or an accident and now the back of the knee hurts and is puffy. It feels wobbly or loose.", [POPL], [GRANDOM, DIRECT]],
  ["en", "Back-of-knee pain after fall or accident. Swollen. Feels loose.", [POPL], [GRANDOM, DIRECT]],
  ["en", "After the accident the shin took a hard knock. The knee is sore behind and feels like it sags, especially going downstairs.", [POPL], [GSTAIRS, DIRECT, GRANDOM]],
  ["hi", "Accident ya girne ke baad ghutne ke peeche dard aur sujan. Ghutna dheela lagta hai.", [POPL], [SWELLNOW, GRANDOM, DIRECT]],
  ["de", "दुर्घटना या गिरने के बाद घुटने के पीछे दर्द और सूजन। घुटना ढीला लगता है।", [POPL], [SWELLNOW, GRANDOM, DIRECT]],
  ["en", "Sudden, at the time of the fall or accident.", [], [DIRECT]],
  ["en", "Right when the fall or accident happened.", [], [DIRECT]],
  ["en", "Sudden, at the time of injury.", [], [DIRECT]],
  ["en", "They felt it straight away, though at first they thought it was nothing much.", [], [DIRECT]],
  ["hi", "Achanak, girte ya accident ke waqt.", [], [DIRECT]],
  ["de", "अचानक, गिरते या दुर्घटना के समय।", [], [DIRECT]],
  ["en", "Fell on a bent knee, or the knee hit the dashboard in an accident.", [DIRECT], []],
  ["en", "Landed on the knee while it was bent, or the front of the shin was hit hard while the knee was bent.", [DIRECT], []],
  ["en", "Fell on bent knee, or dashboard injury, or hit on the shin.", [DIRECT], []],
  ["en", "The front of the shin got pushed backwards. They came off a bike and landed on the front of the knee, or the car stopped suddenly and the knee hit the dashboard.", [DIRECT], [ANT]],
  ["hi", "Mude hue ghutne par gira, ya accident mein ghutna dashboard se takraya.", [DIRECT], []],
  ["de", "मुड़े हुए घुटने पर गिरा, या दुर्घटना में घुटना डैशबोर्ड से टकराया।", [DIRECT], []],
  ["en", "Days to weeks. Sometimes it hurts little at first, but the front of the knee aches later.", [ANT], []],
  ["en", "It has been a few days to a few weeks. At first it did not hurt much, but now the front of the knee aches.", [ANT], []],
  ["en", "Days to weeks. Mild at first, front-knee ache later.", [ANT], []],
  ["en", "It settled in a couple of weeks, but they still get a dull ache at the front of the knee when on their feet a lot.", [ANT], []],
  ["hi", "Kuch din se hafte. Kabhi shuru mein kam dard, par baad mein ghutne ke aage dard rehta hai.", [ANT], []],
  ["de", "कुछ दिन से हफ़्ते। कभी शुरू में कम दर्द, पर बाद में घुटने के आगे दर्द रहता है।", [ANT], []],
  ["en", "Pain along the joint line. The knee catches or locks and cannot be fully straightened.", [LKTRUE], [LKMOM, LOCKEDK]],
  ["en", "Sharp pain in the joint when they twist or squat deep. Sometimes it catches or gets stuck and has to be wiggled free. They cannot straighten it all the way.", [LKMOM], [LKTRUE, TWIST, PIVOT, LOCKEDK]],
  ["en", "Joint-line pain. Catching or locking. Cannot fully straighten. Some swelling.", [], [LKTRUE, LKMOM, LOCKEDK]],
  ["en", "The knee sometimes sticks halfway, like something is stuck inside. They have to shake it to get it moving, and it hurts on the inner or outer side.", [LKMOM], [LKTRUE, MEDIAL, LATERAL]],
  ["hi", "Ghutne ke jodd par dard. Ghutna atak jata hai ya lock ho jata hai, poora seedha nahi hota.", [LKTRUE], [LKMOM, LOCKEDK]],
  ["de", "घुटने के जोड़ की लाइन पर दर्द। घुटना अटक जाता है या लॉक हो जाता है, पूरा सीधा नहीं होता।", [LKTRUE], [LKMOM, LOCKEDK]],
  ["en", "Young: sudden with a twist, with swelling the next day. Older: slowly, or when getting up from the floor.", [TWIST], []],
  ["en", "They twisted it and it only swelled up the next morning.", [TWIST], []],
  ["en", "Sudden twist (younger) or slow / on getting up from the floor (older).", [TWIST], []],
  ["en", "Nothing big happened. They just stood up from sitting on the floor and felt it catch.", [LKMOM], []],
  ["hi", "Jawan: achanak mudne par, sujan agle din. Badi umar mein: dheere dheere ya zameen se uthte waqt.", [TWIST], []],
  ["de", "जवान: अचानक मुड़ने पर, सूजन अगले दिन। बड़ी उम्र में: धीरे-धीरे या ज़मीन से उठते समय।", [TWIST], []],
  ["en", "Twisted the knee with the foot fixed, or squatted deep and turned.", [TWIST], [PIVOT]],
  ["en", "Turned on a foot that was not moving, or twisted while squatting low.", [TWIST], [PIVOT]],
  ["en", "Twist with foot fixed, or deep squat and turn.", [TWIST], [PIVOT]],
  ["en", "They were crouching down, or cutting a turn in a game, and the body twisted over a planted foot.", [TWIST, PIVOT], []],
  ["hi", "Pair jama tha aur ghutna mud gaya, ya poora baith kar mudte waqt.", [TWIST], [PIVOT]],
  ["de", "पैर जमा था और घुटना मुड़ गया, या पूरा बैठकर मुड़ते समय।", [TWIST], [PIVOT]],
  ["en", "Days to weeks, but the catching or locking can keep coming back for months.", [], [LKTRUE, LKMOM, INTER]],
  ["en", "It settled in a few days to a couple of weeks, but the sticking comes back now and then, sometimes for months.", [], [LKTRUE, LKMOM, INTER]],
  ["en", "Days to weeks. Locking can keep recurring for months.", [], [LKTRUE, LKMOM, INTER]],
  ["en", "It got better but keeps catching on and off, month after month.", [], [LKTRUE, LKMOM, INTER]],
  ["hi", "Kuch din se hafte, par atakna ya lock hona mahino tak baar baar ho sakta hai.", [], [LKTRUE, LKMOM, INTER]],
  ["de", "कुछ दिन से हफ़्ते, पर अटकना या लॉक होना महीनों तक बार-बार हो सकता है।", [], [LKTRUE, LKMOM, INTER]],
  ["en", "Pain on the inner side of the knee after a knock from the outside. It feels wobbly sideways.", [MEDIAL, DIRECT], [GRANDOM]],
  ["en", "They were hit on the outside of the knee and now the inside is sore. The knee feels loose from side to side.", [MEDIAL, DIRECT], [GRANDOM]],
  ["en", "Inner-knee pain after a hit from outside. Wobbly sideways.", [MEDIAL, DIRECT], []],
  ["en", "They were tackled from the side. Now the inside of the knee is tender and feels like it wants to bend sideways.", [MEDIAL, DIRECT], []],
  ["hi", "Bahar se chot lagne ke baad ghutne ke andar wali taraf dard. Side mein hilta hua lagta hai.", [MEDIAL], [DIRECT, GRANDOM]],
  ["de", "बाहर से चोट लगने के बाद घुटने के अंदर की तरफ़ दर्द। बगल में हिलता हुआ लगता है।", [MEDIAL], [DIRECT, GRANDOM]],
  ["en", "Sudden, the moment of the hit.", [DIRECT], []],
  ["en", "Straight away, when they were hit.", [DIRECT], []],
  ["en", "Sudden.", [], []],
  ["en", "It hurt at that moment, not afterwards.", [], []],
  ["hi", "Achanak, chot lagte hi.", [], [DIRECT]],
  ["de", "अचानक, चोट लगते ही।", [], [DIRECT]],
  ["en", "Hit on the outside of the knee or leg while the foot was planted, or twisted playing football or skiing.", [DIRECT, TWIST], [PIVOT]],
  ["en", "Someone hit the knee or leg from the outside while the foot was on the ground, or they twisted playing football or on skis.", [DIRECT, TWIST], [PIVOT]],
  ["en", "Hit from outside with foot planted. Twist in football or skiing.", [DIRECT, TWIST], []],
  ["en", "The foot was planted and the force pushed the knee inwards, in a tackle or a fall while skiing.", [DIRECT], [TWIST, PIVOT]],
  ["hi", "Pair zameen par tha aur kisi ne ghutne ya taang ke bahar maara, ya football khelte mudte waqt.", [DIRECT, TWIST], []],
  ["de", "पैर ज़मीन पर था और किसी ने घुटने या टांग के बाहर मारा, या फ़ुटबॉल खेलते मुड़ते समय।", [DIRECT, TWIST], []],
  ["en", "A few weeks (about 2–6). A bad one can take 2–3 months.", [], []],
  ["en", "About 2 to 6 weeks. If it was bad, maybe 2 to 3 months.", [], []],
  ["en", "Mild: about 2–6 weeks. Severe: 2–3 months.", [], []],
  ["en", "Mild ones settle in a few weeks. A severe one can take a few months.", [], []],
  ["hi", "Kuch hafte (lagbhag 2–6). Gambhir mein 2–3 mahine.", [], []],
  ["de", "कुछ हफ़्ते (लगभग 2–6)। गंभीर में 2–3 महीने।", [], []],
  ["en", "Pain on the outer side of the knee after a knock on the inside. The knee feels unsteady sideways.", [LATERAL, DIRECT], [GRANDOM]],
  ["en", "They were hit on the inside of the knee and now the outside hurts. It feels shaky from side to side.", [LATERAL, DIRECT], []],
  ["en", "Outer-knee pain after a hit from inside. Unsteady sideways.", [LATERAL, DIRECT], []],
  ["en", "After the knock, the outer side of the knee is sore and the knee feels like it wobbles outwards.", [LATERAL], [DIRECT, GRANDOM]],
  ["hi", "Andar se chot lagne ke baad ghutne ke bahar wali taraf dard. Ghutna side mein asthir lagta hai.", [LATERAL], [DIRECT, GRANDOM]],
  ["de", "अंदर से चोट लगने के बाद घुटने के बाहर की तरफ़ दर्द। घुटना बगल में अस्थिर लगता है।", [LATERAL], [DIRECT, GRANDOM]],
  ["en", "Sudden, the moment of the hit.", [DIRECT], []],
  ["en", "Straight away, when they were hit.", [DIRECT], []],
  ["en", "Sudden.", [], []],
  ["en", "It hurt at the moment of the blow.", [DIRECT], []],
  ["hi", "Achanak, chot lagte hi.", [], [DIRECT]],
  ["de", "अचानक, चोट लगते ही।", [], [DIRECT]],
  ["en", "Blow to the inside of the knee, or the knee bent backwards or outwards with a twist. Ask about numbness or a dragging foot.", [DIRECT, HYPER], [TWIST]],
  ["en", "A knock on the inside of the knee, or the knee got bent backwards or outwards with a twist. Check if the foot feels numb or drags.", [DIRECT, HYPER], [TWIST]],
  ["en", "Blow to inner knee, or knee bent back or out. Check foot for numbness or dragging.", [DIRECT], [HYPER]],
  ["en", "The knee was pushed out or bent backwards, for example a kick to the inside of the knee or an awkward landing. Ask about numbness on top of the foot or the foot slapping the ground.", [DIRECT, HYPER], [LAND]],
  ["hi", "Ghutne ke andar maara gaya, ya ghutna peeche ya bahar ki taraf mud gaya. Pair sunn ho ya ghasit raha ho to batayein.", [DIRECT], [HYPER, TWIST]],
  ["de", "घुटने के अंदर मारा गया, या घुटना पीछे या बाहर की तरफ़ मुड़ गया। पैर सुन्न हो या घिसट रहा हो तो बताइए।", [DIRECT], [HYPER, TWIST]],
  ["en", "A few weeks for a mild one. A bad one needs a specialist.", [], []],
  ["en", "A mild one settles in a few weeks. A bad one needs to be seen by a specialist.", [], []],
  ["en", "Mild: a few weeks. Severe: specialist.", [], []],
  ["en", "A mild one should ease over a few weeks. If the knee stays wobbly, they need to see a specialist.", [], []],
  ["hi", "Halki ho to kuch hafte. Gambhir ho to specialist ko dikhana padega.", [], []],
  ["de", "हल्की हो तो कुछ हफ़्ते। गंभीर हो तो विशेषज्ञ को दिखाना पड़ेगा।", [], []],
  ["en", "Pain around or behind the kneecap on stairs, when squatting, or after sitting a long time.", [AROUND], [ACT]],
  ["en", "It hurts around or under the kneecap on stairs, squatting, kneeling, or after sitting a long time with the knee bent.", [AROUND], [ACT, BELOW]],
  ["en", "Kneecap pain. Stairs, squatting, long sitting.", [AROUND], []],
  ["en", "The knee aches at the front, especially in the cinema or on a long drive, and it hurts to go downstairs.", [ANT], [ACT]],
  ["hi", "Ghutne ki katori ke aas-paas ya peeche dard — seedhiyon par, baithne-uthne mein ya der tak baithne ke baad.", [AROUND], [ACT]],
  ["de", "घुटने की कटोरी के आसपास या पीछे दर्द — सीढ़ियों पर, उठने-बैठने में या देर तक बैठने के बाद।", [AROUND], [ACT]],
  ["en", "Gradual, with no injury. Began after doing more than usual.", [INSID], []],
  ["en", "It crept up gradually. No injury. It started when they began doing more than usual.", [INSID], []],
  ["en", "Gradual, no injury. After an increase in activity.", [INSID], []],
  ["en", "No fall or injury. It began after a new exercise, a new job, or more stairs.", [INSID], []],
  ["hi", "Dheere dheere, koi chot nahi. Zyada kaam ya exercise ke baad shuru hua.", [INSID], []],
  ["de", "धीरे-धीरे, कोई चोट नहीं। ज़्यादा काम या कसरत के बाद शुरू हुआ।", [INSID], []],
  ["en", "Too much too soon: more running, more stairs, or a new job. Hips and thighs are weak.", [INSID], []],
  ["en", "They did too much too soon: more running or stairs, a new job. Hips and thighs are on the weak side.", [INSID], []],
  ["en", "Overload: sudden increase in running, stairs or work. Weak hips and thighs.", [INSID], []],
  ["en", "The knee could not cope with the sudden jump in activity, like a new gym plan or more walking, and the leg muscles are not strong enough.", [INSID], []],
  ["hi", "Achanak zyada daudna, seedhiyan ya naya kaam. Kulhe aur jaanghon mein taakat kam.", [INSID], []],
  ["de", "अचानक ज़्यादा दौड़ना, सीढ़ियाँ या नया काम। कूल्हे और जाँघ में ताकत कम।", [INSID], []],
  ["en", "Months, sometimes years. It flares up when they do more.", [], [ACT, INTER]],
  ["en", "It has gone on for months, maybe years. It flares when they do more.", [], [ACT, INTER]],
  ["en", "Months to years. Flares with activity.", [], [ACT, INTER]],
  ["en", "It comes and goes. Better with rest, worse when they do more.", [], [ACT, INTER]],
  ["hi", "Mahino, kabhi saalon. Zyada karne par badh jata hai.", [], [ACT, INTER]],
  ["de", "महीनों, कभी सालों। ज़्यादा करने पर बढ़ जाता है।", [], [ACT, INTER]],
  ["en", "Pain just below the kneecap when jumping, landing or sprinting. One sore spot.", [BELOW], [ACT]],
  ["en", "Pain right under the kneecap when they jump, land or sprint. They can point to one sore spot.", [BELOW], []],
  ["en", "Pain below the kneecap with jumping or running. One tender spot.", [BELOW], []],
  ["en", "When they play there is a sore spot just under the kneecap. It is a bit stiff after sitting, eases as they warm up, and hurts again afterwards.", [BELOW], [ACT, IMPR]],
  ["hi", "Kudne, utarne ya tez daudne par katori ke theek neeche dard. Ek hi jagah dukhti hai.", [BELOW], [ACT]],
  ["de", "कूदने, उतरने या तेज़ दौड़ने पर कटोरी के ठीक नीचे दर्द। एक ही जगह दुखती है।", [BELOW], [ACT]],
  ["en", "Slowly. Sometimes it flares after a hard jumping session.", [], [INSID, LAND, INTER]],
  ["en", "It built up slowly. Sometimes it flared after a hard jumping session.", [INSID], [LAND, INTER]],
  ["en", "Gradual. Flares after hard sessions.", [], [INSID]],
  ["en", "No injury. It got worse after a heavy week of jumping or training.", [INSID], []],
  ["hi", "Dheere dheere. Kabhi zyada kudne ke baad achanak badhta hai.", [], [INSID, INTER, LAND]],
  ["de", "धीरे-धीरे। कभी ज़्यादा कूदने के बाद अचानक बढ़ता है।", [], [INSID, INTER, LAND]],
  ["en", "Jumping again and again (volleyball, basketball, football), or training suddenly increased.", [INSID], [LAND]],
  ["en", "Lots of jumping (volleyball, basketball, football) or a sudden increase in training.", [INSID], [LAND]],
  ["en", "Repeated jumping sports. Training spike.", [INSID], [LAND]],
  ["en", "They jump a lot in their sport and recently did more training than usual.", [INSID], [LAND]],
  ["hi", "Baar baar kudna (volleyball, basketball, football), ya training achanak badha dena.", [INSID], [LAND]],
  ["de", "बार-बार कूदना (वॉलीबॉल, बास्केटबॉल, फ़ुटबॉल), या ट्रेनिंग अचानक बढ़ा देना।", [INSID], [LAND]],
  ["en", "Weeks to months, often longer than 3 months.", [], []],
  ["en", "Weeks to months, often more than 3 months.", [], []],
  ["en", "Weeks to months. Often over 3 months.", [], []],
  ["en", "It has been going on for a few months and comes back whenever they train hard.", [], [ACT, INTER, INSID]],
  ["hi", "Hafte se mahine, aksar 3 mahine se zyada.", [], []],
  ["de", "हफ़्ते से महीने, अक्सर 3 महीने से ज़्यादा।", [], []],
  ["en", "Knee hurts and feels stiff on walking, stairs, or getting up after sitting. It creaks.", [], [ACT]],
  ["en", "The knee hurts and goes stiff when they walk, use stairs, or stand up after sitting. It creaks and sometimes swells.", [], [ACT]],
  ["en", "Knee pain and stiffness. Walking, stairs, sit-to-stand. Creaking. Some swelling.", [], [ACT]],
  ["en", "The knees are not what they were. Stiff in the morning, painful on stairs, and they crunch on bending.", [MORN], [ACT]],
  ["hi", "Ghutna dukhta aur akad jata hai — chalne, seedhiyon par, baith kar uthne par. Kharr-kharr awaaz aati hai.", [], [ACT]],
  ["de", "घुटना दुखता और अकड़ जाता है — चलने, सीढ़ियों पर, बैठकर उठने पर। खर-खर आवाज़ आती है।", [], [ACT]],
  ["en", "Slowly over months or years, usually after age 50. Stiff for a few minutes in the morning.", [INSID, MORN], []],
  ["en", "It came on slowly over months or years, usually after 50. Mornings are stiff but it loosens up in a few minutes.", [INSID, MORN], []],
  ["en", "Gradual, usually over 50. Morning stiffness under 30 minutes.", [MORN], [INSID]],
  ["en", "It crept up over the years. It is only stiff for the first half hour of the morning.", [MORN], [INSID]],
  ["hi", "Mahino ya saalon mein dheere dheere, aam taur par 50 ke baad. Subah kuch minute akdan.", [INSID, MORN], []],
  ["de", "महीनों या सालों में धीरे-धीरे, आमतौर पर 50 के बाद। सुबह कुछ मिनट अकड़न।", [INSID, MORN], []],
  ["en", "Wear and tear. More likely with extra weight, an old knee injury, or years of squatting or kneeling.", [INSID], []],
  ["en", "It is wear and tear. Worse with extra weight, an old knee injury, or years of squatting and sitting on the floor.", [INSID], []],
  ["en", "Degenerative. Risks: weight, old injury, squatting or kneeling.", [], [INSID]],
  ["en", "They have used their knees a lot over the years (squatting, kneeling, climbing) and had an old injury.", [], [INSID]],
  ["hi", "Ghisaav. Mote hone, purani chot ya saalon ki uthak-baithak aur ghutno ke bal baithne se zyada hota hai.", [INSID], []],
  ["de", "घिसाव। मोटापे, पुरानी चोट या सालों की उठक-बैठक और घुटनों के बल बैठने से ज़्यादा होता है।", [INSID], []],
  ["en", "Months to years, with good spells and bad spells.", [], [INTER]],
  ["en", "Months to years, with good days and bad days.", [], [INTER]],
  ["en", "Months to years. Flare-ups.", [], [INTER]],
  ["en", "Some weeks it is fine, some weeks it is bad, and it has been like this for years.", [], [INTER]],
  ["hi", "Mahine se saal, kabhi theek kabhi zyada.", [], [INTER]],
  ["de", "महीने से साल, कभी ठीक कभी ज़्यादा।", [], [INTER]],
  ["en", "Pain on the outside of the knee that starts part-way through a run and eases on stopping.", [LATERAL], [ACT]],
  ["en", "Pain on the outside of the knee that begins during a run and goes away when they stop.", [LATERAL], [ACT]],
  ["en", "Outer-knee pain during running. Eases with rest.", [LATERAL], [ACT]],
  ["en", "Partway into the run the outside of the knee starts to burn or hurt sharply and they have to slow down or stop. After a rest it is fine.", [LATERAL], [ACT]],
  ["hi", "Daudte waqt beech mein ghutne ke bahar wali taraf dard shuru hota hai, rukne par kam ho jata hai.", [LATERAL], [ACT]],
  ["de", "दौड़ते समय बीच में घुटने के बाहर की तरफ़ दर्द शुरू होता है, रुकने पर कम हो जाता है।", [LATERAL], [ACT]],
  ["en", "Slowly. Starts at about the same distance every time.", [], [INSID, ACT]],
  ["en", "It crept up. It always starts around the same distance.", [], [INSID, ACT]],
  ["en", "Gradual. Same distance each time.", [], [INSID, ACT]],
  ["en", "No injury. It just started coming on at about the same point on every run.", [INSID], [ACT]],
  ["hi", "Dheere dheere. Har baar lagbhag usi doori par shuru hota hai.", [], [INSID, ACT]],
  ["de", "धीरे-धीरे। हर बार लगभग उसी दूरी पर शुरू होता है।", [], [INSID, ACT]],
  ["en", "Running or cycling a lot, more distance than before, hills or downhill.", [INSID], []],
  ["en", "Lots of running or cycling, longer distances than before, hills or running downhill.", [INSID], []],
  ["en", "High mileage or cycling. Recent increase. Hills or downhill.", [INSID], []],
  ["en", "They have been running more than usual lately, especially on hills.", [INSID], []],
  ["hi", "Zyada daudna ya cycling, pehle se zyada doori, chadhai ya dhalaan.", [INSID], []],
  ["de", "ज़्यादा दौड़ना या साइकिल चलाना, पहले से ज़्यादा दूरी, चढ़ाई या ढलान।", [INSID], []],
  ["en", "Weeks to months. Most runners are back in about 6 weeks to 6 months.", [], []],
  ["en", "Weeks to months. Most runners are back to running in 6 weeks to 6 months.", [], []],
  ["en", "Weeks to months. Back to running in about 6 weeks–6 months.", [], []],
  ["en", "It has been bothering them for a few weeks. With rest and sensible training it settles.", [], []],
  ["hi", "Hafte se mahine. Zyadatar daudne wale 6 hafte se 6 mahine mein wapas daudte hain.", [], []],
  ["de", "हफ़्ते से महीने। ज़्यादातर दौड़ने वाले 6 हफ़्ते से 6 महीने में वापस दौड़ते हैं।", [], []],
];

// Same scoring as the other exams, except "may" answers are neutral.
export function scoreSheet(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, must, may] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const mustSet = new Set(must), okSet = new Set([...must, ...may]);
    for (const g of got) { suggested++; if (okSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of must) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
