// kneeSheetSetFresh.js -- a SECOND, fresh exam in the clinician's voice ("the patient", "they", short notes), written AFTER the Knee
// matcher had been fixed for the sheet's own sentences (kneeSheetSet.js). None of these sentences was used to tune the matcher before
// their first run was recorded. Row = [lang, text, must, may] -- same meaning as in kneeSheetSet.js. The answer keys are DRAFTS written by
// Claude for Aditi to check.
import { KEYS } from "./kneeWildSets.js";

const { ANT, AROUND, BELOW, MEDIAL, LATERAL, POPL, DIFFUSE, INSID, TWIST, DIRECT, HYPER, LAND, PIVOT, POSTOP, GNO, GPIVOT, GSTAIRS, GRANDOM,
  LKNO, LKTRUE, LKMOM, CONST, INTER, MORN, NIGHT, ACT, IMPR, SWELLNOW, LOCKEDK } = KEYS;

export const KNEE_SHEET_FRESH = [
  // ACL
  ["en", "Patient reports the knee gave way during a cutting move and swelled within the hour.", [GPIVOT, SWELLNOW], [PIVOT, TWIST]],
  ["en", "Heard a loud pop when they planted and twisted. Could not continue playing.", [TWIST], [PIVOT]],
  ["en", "Landed awkwardly after a rebound, knee buckled inwards.", [LAND], [GRANDOM]],
  ["en", "No contact. Pivoted on a planted foot and felt the knee shift.", [PIVOT], [TWIST]],
  ["en", "Feels unstable on turns and sometimes just gives way for no reason.", [GRANDOM], [GPIVOT]],
  ["en", "The knee swelled up like a balloon straight after it happened.", [SWELLNOW], []],
  ["en", "Old injury, years ago. The knee still buckles now and then.", [], [GRANDOM, INTER]],
  ["en", "Hit by a tackle from the side, then the knee gave way.", [DIRECT], [GRANDOM]],
  ["hi", "Khelte waqt ghutna mud gaya aur turant sujan aa gayi.", [TWIST, SWELLNOW], []],
  ["hi", "Kood kar utarte waqt ghutne ne jawab de diya.", [LAND], [GRANDOM]],
  ["de", "खेलते समय घुटना मुड़ गया और तुरंत सूजन आ गई।", [TWIST, SWELLNOW], []],
  ["de", "अब भी घुटना कभी भी धोखा देता है।", [GRANDOM], []],
  // PCL
  ["en", "Pain at the back of the knee since a fall onto the front of the shin.", [POPL], [DIRECT]],
  ["en", "Road traffic accident, knee hit the dashboard. Now swelling behind the knee.", [DIRECT, POPL], [SWELLNOW]],
  ["en", "Knee gives way on stairs after the accident.", [GSTAIRS], [DIRECT]],
  ["en", "Fell on a bent knee while riding a bike.", [DIRECT], []],
  ["en", "Posterior knee pain, mild swelling, no locking.", [POPL, LKNO], []],
  ["en", "Pain behind the knee worse on squatting.", [POPL], [ACT]],
  ["en", "No swelling, but the back of the knee feels tight.", [POPL], []],
  ["en", "Hyperextended the knee in a football collision.", [HYPER], [DIRECT]],
  ["hi", "Gaadi ke dashboard se ghutna takra gaya, ghutne ke peeche dard hai.", [DIRECT, POPL], []],
  ["hi", "Girne ke baad ghutne ke peeche sujan.", [POPL], [DIRECT, SWELLNOW]],
  ["de", "घुटने के बल गिरा, अब घुटने के पीछे दर्द है।", [DIRECT, POPL], []],
  ["de", "दुर्घटना में घुटना डैशबोर्ड से टकराया।", [DIRECT], []],
  // Meniscal tear
  ["en", "Medial joint line pain with a catching sensation after a twist.", [MEDIAL, LKMOM, TWIST], []],
  ["en", "Patient says the knee locked in a bent position and would not straighten.", [LKTRUE], [LOCKEDK]],
  ["en", "Clicking and catching on the lateral side when squatting.", [LKMOM], [LATERAL, ACT]],
  ["en", "Twisted on a planted foot during a game. Swelling came the next morning.", [TWIST], [PIVOT]],
  ["en", "Older patient, felt something go when getting up from a squat. Knee catches since.", [LKMOM], []],
  ["en", "No locking at all, only some clicking.", [LKNO], [LKMOM]],
  ["en", "Deep squat then rotated, sharp joint line pain.", [], [TWIST, PIVOT]],
  ["en", "Knee gives way when they pivot and it also locks.", [GPIVOT], [LKMOM, LKTRUE]],
  ["hi", "Ghutna mud gaya aur ab atak jata hai.", [TWIST, LKMOM], []],
  ["hi", "Ghutne ke andar ki taraf dard aur ghutna lock ho gaya.", [MEDIAL, LKTRUE], [LOCKEDK]],
  ["de", "घुटना मुड़ गया और अब अटक जाता है।", [TWIST, LKMOM], []],
  ["de", "घुटने के बाहर की तरफ दर्द और कभी कभी अटक जाता है।", [LATERAL, LKMOM], [INTER]],
  // MCL
  ["en", "Valgus force to the outside of the knee in a football tackle. Inner knee pain since.", [DIRECT, MEDIAL], []],
  ["en", "Pain along the inner side of the knee, tender to touch.", [MEDIAL], []],
  ["en", "Someone fell on the outside of their leg and the inside of the knee is sore.", [MEDIAL], [DIRECT]],
  ["en", "Kicked on the outer side of the knee, now medial knee pain.", [DIRECT, MEDIAL], []],
  ["en", "Twisted the knee skiing, pain on the inside, feels loose sideways.", [TWIST, MEDIAL], [GRANDOM]],
  ["en", "Pain inside of the knee after a hit.", [MEDIAL, DIRECT], []],
  ["en", "No giving way, but swelling and tenderness medially.", [GNO], []],
  ["en", "They were tackled from the outside in cricket, and the inner knee is swollen.", [DIRECT, MEDIAL], []],
  ["hi", "Bahar ki taraf se laat lagi, ghutne ke andar ki taraf dard hai.", [DIRECT, MEDIAL], []],
  ["hi", "Football mein ghutne par chot, andar ki taraf dard.", [DIRECT, MEDIAL], []],
  ["de", "बाहर से चोट लगी, घुटने के अंदर की तरफ दर्द है।", [MEDIAL], [DIRECT]],
  ["de", "टांग के बाहर मारा गया और घुटने में अंदर की तरफ सूजन।", [DIRECT], [MEDIAL]],
  // LCL
  ["en", "Varus blow to the inside of the knee, pain on the outer side now.", [DIRECT, LATERAL], []],
  ["en", "Outer knee pain, tender over the lateral joint line.", [LATERAL], []],
  ["en", "Hyperextended the knee with a twist and has outer knee pain.", [HYPER, LATERAL], [TWIST]],
  ["en", "Kick to the inner knee. The outside feels unstable.", [DIRECT], [LATERAL, GRANDOM]],
  ["en", "Numbness on top of the foot after the knee injury, foot dragging.", [], []],
  ["en", "Pain on the lateral side of the knee, no swelling.", [LATERAL], []],
  ["en", "Knee bent the wrong way when landing from a jump.", [HYPER, LAND], []],
  ["en", "Pain on the outside of the knee after a fall.", [LATERAL], [DIRECT]],
  ["hi", "Ghutne ke andar maara gaya, ab bahar ki taraf dard hai.", [LATERAL, DIRECT], []],
  ["hi", "Ghutna ulta mud gaya, ghutne ke bahar dard.", [HYPER, LATERAL], []],
  ["de", "घुटने के बाहर की तरफ दर्द, चोट अंदर से लगी थी।", [LATERAL], [DIRECT]],
  ["de", "घुटना पीछे की तरफ मुड़ गया।", [HYPER], []],
  // Patellofemoral pain
  ["en", "Anterior knee pain on stairs and after prolonged sitting.", [ANT], [ACT]],
  ["en", "Pain behind the kneecap, gradual onset, no injury.", [AROUND, INSID], []],
  ["en", "Symptoms started after the patient increased running distance.", [INSID], []],
  ["en", "Aches around the kneecap when squatting. Worse with downhill walking.", [AROUND], [ACT]],
  ["en", "Started after a new job with many stairs, no specific injury.", [INSID], []],
  ["en", "Pain at the front of the knee at the end of the day, comes and goes.", [ANT], [INTER, ACT]],
  ["en", "Teenager, growth spurt, pain around the patella with sport.", [AROUND], [ACT]],
  ["en", "Diffuse knee ache, cannot point to one spot.", [DIFFUSE], []],
  ["hi", "Katori ke aaspaas dard, seedhiyan chadhne par badhta hai.", [AROUND], [ACT]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi lagi.", [INSID], []],
  ["de", "घुटने की कटोरी के पीछे दर्द, सीढ़ियां चढ़ने पर बढ़ता है।", [AROUND], [ACT]],
  ["de", "ज्यादा दौड़ने से कटोरी के आसपास दर्द शुरू हुआ।", [INSID, AROUND], []],
  // Patellar tendinopathy
  ["en", "Pain below the kneecap with jumping, one tender spot on the tendon.", [BELOW], [ACT]],
  ["en", "Jumper's knee. Training load went up sharply this month.", [BELOW], [INSID]],
  ["en", "Patellar tendon pain after volleyball practice, gradual onset.", [BELOW, INSID], []],
  ["en", "Sore just under the kneecap when landing, better with rest.", [BELOW], [LAND, ACT]],
  ["en", "Worse the day after a heavy session, settles within a day.", [], [ACT, INTER]],
  ["en", "Pain at the bottom of the kneecap on stairs.", [BELOW], [ACT]],
  ["en", "Stiff after sitting, eases as they warm up.", [IMPR], []],
  ["en", "Overuse of the jumping muscles for months, no direct injury.", [INSID], []],
  ["hi", "Kudne par katori ke niche dard, ek hi jagah dukhti hai.", [BELOW], [ACT]],
  ["hi", "Dheere dheere shuru hua, training zyada karne se.", [INSID], []],
  ["de", "कूदने पर कटोरी के नीचे दर्द।", [BELOW], [ACT]],
  ["de", "धीरे धीरे शुरू हुआ, बिना चोट के।", [INSID], []],
  // Knee osteoarthritis
  ["en", "Morning stiffness for about 20 minutes, knee pain on stairs.", [MORN], [ACT]],
  ["en", "Gradual onset over several years, no injury.", [INSID], []],
  ["en", "Knee pain worse at night, stiff after sitting.", [NIGHT], [ACT]],
  ["en", "Diffuse aching around the whole knee, crunching on bending.", [DIFFUSE], []],
  ["en", "Old meniscus surgery 20 years ago, now stiffness and pain.", [], [POSTOP, INSID]],
  ["en", "Pain in the knee all the time but worse at the end of the day.", [CONST], []],
  ["en", "Pain improves once they get moving.", [IMPR], []],
  ["en", "Wear and tear changes, creaking, swelling on and off.", [INSID], [INTER]],
  ["hi", "Subah ghutna akad jata hai, chalne se thoda theek.", [MORN], [IMPR]],
  ["hi", "Saalon se dheere dheere dard badh raha hai.", [INSID], []],
  ["de", "सुबह घुटना अकड़ जाता है, सीढ़ियों पर दर्द।", [MORN], [ACT]],
  ["de", "रात को घुटने में दर्द और सुबह अकड़न।", [NIGHT, MORN], []],
  // Iliotibial band
  ["en", "Lateral knee pain starting at around 5 km of running.", [LATERAL], [ACT]],
  ["en", "Pain on the outside of the knee after a long downhill run, eases with rest.", [LATERAL], [ACT]],
  ["en", "Started after the patient increased weekly mileage.", [INSID], []],
  ["en", "Cyclist, sharp lateral knee pain at the same point of every ride.", [LATERAL], [ACT]],
  ["en", "No injury, pain comes on after about twenty minutes of running.", [INSID], [ACT]],
  ["en", "Stairs and downhill walking make the outer knee pain worse.", [LATERAL], [ACT]],
  ["en", "Burning pain on the outer side of the knee, settles within minutes of stopping.", [LATERAL], [ACT]],
  ["en", "Training errors, sudden mileage increase before a marathon.", [INSID], []],
  ["hi", "Daudte waqt ghutne ke bahar ki taraf dard shuru hota hai.", [LATERAL], [ACT]],
  ["hi", "Zyada daudne se ghutne ke bahar dard.", [INSID, LATERAL], []],
  ["de", "दौड़ते समय घुटने के बाहर की तरफ दर्द शुरू होता है।", [LATERAL], [ACT]],
  ["de", "ज्यादा चलने से घुटने के बाहर दर्द।", [INSID, LATERAL], []],
  // must stay silent
  ["en", "The patient is a 45 year old teacher from Pune.", [], []],
  ["en", "Referred by the GP for physiotherapy.", [], []],
  ["en", "Wants to return to sport as soon as possible.", [], []],
  ["en", "A friend recommended the clinic.", [], []],
  ["en", "Her husband has had knee problems too.", [], []],
  ["en", "Assessment done on Tuesday and the plan was explained.", [], []],
  ["hi", "Mareez ek school teacher hain aur Pune se aate hain.", [], []],
  ["de", "मरीज़ को डॉक्टर ने फिज़ियोथेरेपी के लिए भेजा है।", [], []],
];
