// lumbarSISheetSet.js -- the sentences of the Lumbar / SI "everyday words" sheet (PhysioMind-Lumbar-Everyday-Words-DRAFT.pdf), written the way the
// CLINICIAN would type about the patient ("the patient", "they", short notes): English in four styles, Hinglish and Hindi, for all 11
// conditions. Used by lumbarSISheetSet.test.js (not a test itself). Row = [lang, text, must, may]:
//   must = options a physio would tick from that sentence (a miss costs recall)
//   may  = options that are also fair to suggest (neither right nor wrong: they do not count against precision)
//   anything else it suggests counts as wrong. A sentence with no must and no may must stay silent.
// lang: en = English, hi = Hinglish (Hindi in Latin letters), de = Hindi in Devanagari. The answer keys are DRAFTS written by Claude
// for Aditi to check. The Lumbar form has no question for how it started or how long as such, so those lines only count where a sentence also says something a form question covers.
import { KEYS } from "./lumbarSIWildSets.js";
import { understandStory } from "../lumbarSIPhraseMap.js";

const { ABENT, ALL, ALR, ASIT, ASIT15, ASIT30, ASIT60, ASLUMP, ASTAND, ASTAND15, ASTAND30, CBISC, CRET, CSADDLE, CWEAK, FR70, FROSTEO, FRPM, FRSTER, IFAGE, IFFAM, IFIBD, IFINS, IFMORN, IFMOVE, IFPSO, IFREST, IFUVE, LBAND, LBULL, LBULU, LCEN, LLOW, LMID, LPARL, LPARR, LSIR, LSJ, MBEND, MCOUGH, MFALLB, MINS, MLBOTH, MLFLEX, MLFLOOR, MLROT, MNONE, MPOST, MPP, MSPORT, MSTUMBLE, MTWIST, NBIL, NL, NNO, PCONST, PCROOK, PFLAT, PINTTRIG, PINTUNP, PLEAN, PMORN, PNIGHT, PREST, PSECOND, PSUPPORT, RBIL, RBUR, RCAL, RNONE, RPTL, SCA, SCONST, SFEV, SNIGHT, SWT } = KEYS;

export const LUMBAR_SHEET = [
  ["en", "The patient has lower back pain with no leg pain, worse after sitting for a long time.", [RNONE, NNO], [LCEN, LBAND, LLOW, ASIT, ASIT15, ASIT30, ASIT60, ABENT]],
  ["en", "They say it's just the back that hurts, nothing goes into the leg, and sitting for long makes it worse.", [RNONE, NNO], [LCEN, LBAND, LLOW, ASIT, ASIT15, ASIT30, ASIT60, ABENT]],
  ["en", "LBP, no leg symptoms. Worse with prolonged sitting.", [RNONE, NNO], [LCEN, LBAND, LLOW, ASIT, ASIT15, ASIT30, ASIT60, ABENT]],
  ["en", "It's an ache across the lower back that stays in the back. There's no pain or tingling down either leg, and a long sit at the desk makes it worse.", [RNONE, NNO], [LCEN, LBAND, LLOW, ASIT, ASIT15, ASIT30, ASIT60, ABENT]],
  ["hi", "Kamar ke neeche dard, pair mein koi dard nahi, der tak baithne par badhta hai.", [RNONE, NNO], [LCEN, LBAND, LLOW, ASIT, ASIT15, ASIT30, ASIT60, ABENT]],
  ["de", "कमर के निचले हिस्से में दर्द, पैर में कोई दर्द नहीं, देर तक बैठने पर बढ़ता है।", [RNONE, NNO], [LCEN, LBAND, LLOW, ASIT, ASIT15, ASIT30, ASIT60, ABENT]],
  ["en", "Gradual onset, no clear cause.", [MINS], [MNONE, IFINS, MLFLEX, MBEND, MPOST]],
  ["en", "It came on slowly, they don't know why.", [MINS], [MNONE, IFINS, MLFLEX, MBEND, MPOST]],
  ["en", "Gradual. No injury.", [MINS], [MNONE, IFINS, MLFLEX, MBEND, MPOST]],
  ["en", "Over about two weeks it crept in, with no particular event.", [MINS], [MNONE, IFINS, MLFLEX, MBEND, MPOST]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [MINS], [MNONE, IFINS, MLFLEX, MBEND, MPOST]],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [MINS], [MNONE, IFINS, MLFLEX, MBEND, MPOST]],
  ["en", "Long hours of sitting at a desk and poor posture.", [MPOST], [MINS, MNONE, MBEND, ASIT, ASIT60, ASLUMP]],
  ["en", "They sit slouched at the computer all day.", [MPOST], [MINS, MNONE, MBEND, ASIT, ASIT60, ASLUMP]],
  ["en", "Desk job. Poor posture.", [MPOST], [MINS, MNONE, MBEND, ASIT, ASIT60, ASLUMP]],
  ["en", "A desk worker who sits hunched for eight hours, with the pain building through the week.", [MPOST], [MINS, MNONE, MBEND, ASIT, ASIT60, ASLUMP]],
  ["hi", "Der tak baithkar kaam, galat posture.", [MPOST], [MINS, MNONE, MBEND, ASIT, ASIT60, ASLUMP]],
  ["de", "देर तक बैठकर काम, गलत पोस्चर।", [MPOST], [MINS, MNONE, MBEND, ASIT, ASIT60, ASLUMP]],
  ["en", "Days to a few months.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "It has been there for about three weeks.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "3 weeks.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "On and off for two months, a bit worse in the last week.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["hi", "Kuch hafton se.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["de", "कुछ हफ्तों से।", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "The patient has low back pain with pain going down the back of the left thigh to the calf.", [RPTL, RCAL], [NL, LLOW, LSJ, ASIT]],
  ["en", "It starts in the lower back and shoots down the back of the left leg to the calf.", [RPTL, RCAL], [NL, LLOW, LSJ, ASIT]],
  ["en", "LBP with left sciatica: posterior thigh to calf.", [RPTL, RCAL], [NL, LLOW, LSJ, ASIT]],
  ["en", "The back hurts first, and then there is a sharp pain running down the back of the left thigh into the calf, with some tingling in the leg.", [RPTL, RCAL, NL], [LLOW, LSJ, ASIT]],
  ["hi", "Kamar dard ke saath baayein pair mein peeche jaangh se pindli tak dard.", [RPTL, RCAL], [NL, LLOW, LSJ, ASIT]],
  ["de", "कमर दर्द के साथ बाएं पैर में पीछे जांघ से पिंडली तक दर्द।", [RPTL, RCAL], [NL, LLOW, LSJ, ASIT]],
  ["en", "Sudden, lifting with the back bent and twisted.", [MLBOTH], [MLFLEX, MLROT, MLFLOOR]],
  ["en", "It came on when they lifted something heavy and turned at the same time.", [MLROT], [MLBOTH]],
  ["en", "Sudden. Lifting with flexion and rotation.", [MLBOTH], [MLFLEX, MLROT, MLFLOOR]],
  ["en", "They bent down to lift a heavy box off the floor, twisted to put it on the shelf, and felt something go in the back.", [MLBOTH], [MLFLEX, MLROT, MLFLOOR]],
  ["hi", "Jhuk kar bhaari cheez uthate aur ghumate waqt achanak shuru hua.", [MLBOTH], [MLFLEX, MLROT, MLFLOOR]],
  ["de", "झुककर भारी चीज़ उठाते और घूमते समय अचानक शुरू हुआ।", [MLBOTH], [MLFLEX, MLROT, MLFLOOR]],
  ["en", "Worse on coughing, sneezing and sitting.", [ASIT], [MCOUGH, MLBOTH, ASIT15]],
  ["en", "Coughing and sneezing shoot the pain down the leg, and sitting makes it worse.", [ASIT], [MCOUGH, MLBOTH, ASIT15]],
  ["en", "Worse with cough, sneeze and sitting.", [ASIT], [MCOUGH, MLBOTH, ASIT15]],
  ["en", "Every cough or sneeze sends a jolt down the leg, and sitting for even ten minutes makes it flare.", [ASIT], [MCOUGH, MLBOTH, ASIT15]],
  ["hi", "Khaansne, chheenkne aur baithne par dard badhta hai.", [ASIT], [MCOUGH, MLBOTH, ASIT15]],
  ["de", "खांसने, छींकने और बैठने पर दर्द बढ़ता है।", [ASIT], [MCOUGH, MLBOTH, ASIT15]],
  ["en", "Weeks.", [], []],
  ["en", "It has been about four weeks.", [], []],
  ["en", "4 weeks.", [], []],
  ["en", "It began a month ago and the leg pain has stayed the same.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has pain to the right of the midline in the lower back, worse on standing.", [LPARR, ASTAND], [ASTAND15, ASTAND30, RBUR, LLOW, LBAND]],
  ["en", "It's on the right side of the lower back, next to the spine, and standing makes it worse.", [LPARR, ASTAND], [ASTAND15, ASTAND30, RBUR, LLOW, LBAND]],
  ["en", "Right paraspinal LBP. Worse standing and extension.", [LPARR, ASTAND], [ASTAND15, ASTAND30, RBUR, LLOW, LBAND]],
  ["en", "The pain sits just right of the spine in the lower back. They feel it most when standing up straight and leaning backwards.", [LPARR, ASTAND], [ASTAND15, ASTAND30, RBUR, LLOW, LBAND]],
  ["hi", "Kamar ke neeche daayein taraf, reedh ke paas dard, khade rehne par badhta hai.", [LPARR, ASTAND], [ASTAND15, ASTAND30, RBUR, LLOW, LBAND]],
  ["de", "कमर के निचले हिस्से में दाईं तरफ, रीढ़ के पास दर्द, खड़े रहने पर बढ़ता है।", [LPARR, ASTAND], [ASTAND15, ASTAND30, RBUR, LLOW, LBAND]],
  ["en", "Sudden, after an awkward twist or reaching back.", [MTWIST], [MINS, MLROT]],
  ["en", "It started when they twisted to pick something up from the back seat.", [MTWIST], [MINS, MLROT]],
  ["en", "Sudden. Twist.", [MTWIST], [MINS, MLROT]],
  ["en", "They turned awkwardly to reach into the back seat of the car and felt a sharp catch in the right side of the back.", [MTWIST], [MINS, MLROT]],
  ["hi", "Achanak ghumne par shuru hua.", [MTWIST], [MINS, MLROT]],
  ["de", "अचानक घूमने पर शुरू हुआ।", [MTWIST], [MINS, MLROT]],
  ["en", "Better lying with the knees bent, or sitting.", [PCROOK], [PFLAT, PSUPPORT, ASIT]],
  ["en", "It eases when they lie with the knees bent or sit down.", [PCROOK], [PFLAT, PSUPPORT, ASIT]],
  ["en", "Better crook lying and sitting.", [PCROOK], [PFLAT, PSUPPORT, ASIT]],
  ["en", "When they lie on the back with the knees up the pain settles, and sitting also helps.", [PCROOK], [PFLAT, PSUPPORT, ASIT]],
  ["hi", "Ghutne mod kar letne par aaram.", [PCROOK], [PFLAT, PSUPPORT, ASIT]],
  ["de", "घुटने मोड़कर लेटने पर आराम।", [PCROOK], [PFLAT, PSUPPORT, ASIT]],
  ["en", "Days to weeks.", [], []],
  ["en", "It has been there for five days.", [], []],
  ["en", "5 days.", [], []],
  ["en", "It started last week and has been the same since.", [], []],
  ["hi", "Kuch dinon se.", [], []],
  ["de", "कुछ दिनों से।", [], []],
  ["en", "The patient has pain in both legs on standing and walking, relieved by sitting or leaning forward on a trolley.", [RBIL, ASTAND, PLEAN], [NBIL, PSUPPORT, ASIT]],
  ["en", "Both legs go heavy and sore when they walk or stand, and they have to sit down or lean on a trolley to get relief.", [RBIL, ASTAND, PLEAN], [NBIL, PSUPPORT, ASIT]],
  ["en", "Bilateral leg pain on walking. Eased by sitting and leaning forward.", [RBIL, PLEAN], [NBIL, PSUPPORT, ASIT, ASTAND]],
  ["en", "After about two hundred metres both legs feel heavy and numb. They find it eases when they sit down or lean on the shopping trolley.", [NBIL, PLEAN], [RBIL, PSUPPORT, ASIT]],
  ["hi", "Dono pairon mein chalne par dard, baithne ya trolley par aage jhukne par aaram.", [RBIL, PLEAN], [NBIL, PSUPPORT, ASIT, ASTAND]],
  ["de", "दोनों पैरों में चलने पर दर्द, बैठने या ट्रॉली पर आगे झुकने पर आराम।", [RBIL, PLEAN], [NBIL, PSUPPORT, ASIT, ASTAND]],
  ["en", "Gradual over months to years, age over 60.", [MINS], [MNONE, IFINS]],
  ["en", "It came on slowly over the last year, they are in their seventies.", [MINS], [MNONE, IFINS]],
  ["en", "Gradual. Older patient.", [MINS], [MNONE, IFINS]],
  ["en", "Over a couple of years the walking distance has come down, with no injury at all.", [MINS], [MNONE, IFINS]],
  ["hi", "Dheere dheere, umar ke saath badhta gaya.", [MINS], [MNONE, IFINS]],
  ["de", "धीरे धीरे, उम्र के साथ बढ़ता गया।", [MINS], [MNONE, IFINS]],
  ["en", "Age-related wear of the spine.", [], [MINS, MNONE, MPOST]],
  ["en", "It's the wear and tear of the back, as they get older.", [], [MINS, MNONE, MPOST]],
  ["en", "Degenerative.", [], [MINS, MNONE, MPOST]],
  ["en", "No injury. The doctor said the spine has worn with age and the canal has narrowed.", [], [MINS, MNONE, MPOST]],
  ["hi", "Umar ke saath reedh ka ghisav.", [], [MINS, MNONE, MPOST]],
  ["de", "उम्र के साथ रीढ़ का घिसाव।", [], [MINS, MNONE, MPOST]],
  ["en", "Months to years.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "It has been creeping up for about a year.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "1 year.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "Slowly worse over the last two years.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["hi", "Kai mahino se.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["de", "कई महीनों से।", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "The patient has pain over the right SI joint, worse on getting out of a chair and turning in bed.", [LSIR], [RBUR, ASIT, ASTAND]],
  ["en", "It's low on the right side near the dimple of the back, and it hurts when they stand up from a chair or roll over in bed.", [LSIR], [RBUR, ASIT, ASTAND]],
  ["en", "Right SIJ pain. Sit to stand and bed turning.", [LSIR], [RBUR, ASIT, ASTAND]],
  ["en", "They point to a spot just beside the base of the spine on the right. Getting up from a chair or turning over at night sets it off.", [], [LSIR, LPARR, LSJ, ASIT, ASTAND]],
  ["hi", "Daayein SI joint par dard, kursi se uthne aur bistar par palatne par badhta hai.", [LSIR], [RBUR, ASIT, ASTAND]],
  ["de", "दाएं एसआई जोड़ पर दर्द, कुर्सी से उठने और बिस्तर पर करवट लेने पर बढ़ता है।", [LSIR], [RBUR, ASIT, ASTAND]],
  ["en", "Sudden, after a fall onto the buttocks or a missed step.", [MFALLB], [MSTUMBLE, MPP]],
  ["en", "They fell on the bottom, or missed a step, and it started then.", [MFALLB], [MSTUMBLE, MPP]],
  ["en", "Sudden. Fall on the buttock.", [MFALLB], [MSTUMBLE, MPP]],
  ["en", "The pain began when they slipped on the stairs and landed hard on the right buttock.", [MFALLB], [MSTUMBLE, MPP]],
  ["hi", "Chutad ke bal girne ke baad achanak shuru hua.", [MFALLB], [MSTUMBLE, MPP]],
  ["de", "चूतड़ के बल गिरने के बाद अचानक शुरू हुआ।", [MFALLB], [MSTUMBLE, MPP]],
  ["en", "Fall onto the buttocks or a missed step.", [MFALLB], [MPP, MSTUMBLE]],
  ["en", "A hard landing on the bottom.", [MFALLB], [MPP, MSTUMBLE]],
  ["en", "Fall on the buttock.", [MFALLB], [MPP, MSTUMBLE]],
  ["en", "They slipped on wet floor and landed on the buttock.", [MFALLB], [MPP, MSTUMBLE]],
  ["hi", "Chutad par girne se.", [MFALLB], [MPP, MSTUMBLE]],
  ["de", "चूतड़ पर गिरने से।", [MFALLB], [MPP, MSTUMBLE]],
  ["en", "Days to months.", [], []],
  ["en", "It has been there for about six weeks.", [], []],
  ["en", "6 weeks.", [], []],
  ["en", "Since the fall last month it has not settled.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has a catch in the lower back when straightening up from bending, and it feels as if the back gives way.", [ABENT], [ASLUMP, ASIT, MBEND]],
  ["en", "When they bend and come back up, something catches in the lower back and it feels like it might give way.", [ABENT], [ASLUMP, ASIT, MBEND]],
  ["en", "Catching on straightening from flexion. Back feels unstable.", [ABENT], [ASLUMP, ASIT, MBEND]],
  ["en", "Coming up from tying the shoes there's a sudden catch and the back feels as if it might give way, so they hold onto the furniture.", [ABENT], [ASLUMP, ASIT, MBEND]],
  ["hi", "Jhukne ke baad seedha hote waqt kamar mein atak, aisa lagta hai ki kamar jawab de degi.", [ABENT], [ASLUMP, ASIT, MBEND]],
  ["de", "झुकने के बाद सीधा होते समय कमर में अटक, ऐसा लगता है कि कमर जवाब दे देगी।", [ABENT], [ASLUMP, ASIT, MBEND]],
  ["en", "Gradual, after an old back injury, with sudden flare-ups.", [], [MBEND, MINS, MNONE, MSTUMBLE, MLFLEX]],
  ["en", "An old injury and now it flares up with small movements.", [], [MBEND, MINS, MNONE, MSTUMBLE, MLFLEX]],
  ["en", "Old injury. Recurrent flare-ups.", [], [MBEND, MINS, MNONE, MSTUMBLE, MLFLEX]],
  ["en", "Four years ago they hurt the back lifting and ever since it has flared with simple movements.", [], [MBEND, MINS, MNONE, MSTUMBLE, MLFLEX]],
  ["hi", "Purani chot ke baad baar baar dard.", [], [MBEND, MINS, MNONE, MSTUMBLE, MLFLEX]],
  ["de", "पुरानी चोट के बाद बार बार दर्द।", [], [MBEND, MINS, MNONE, MSTUMBLE, MLFLEX]],
  ["en", "Repeated bending forward.", [MBEND], [MINS, MNONE, MLFLEX]],
  ["en", "Lots of bending forward at work.", [MBEND], [MINS, MNONE, MLFLEX]],
  ["en", "Repetitive flexion.", [MBEND], [MINS, MNONE, MLFLEX]],
  ["en", "They bend forward all day in the workshop and the back has been giving them trouble.", [MBEND], [MINS, MNONE, MLFLEX]],
  ["hi", "Baar baar aage jhukna.", [MBEND], [MINS, MNONE, MLFLEX]],
  ["de", "बार बार आगे झुकना।", [MBEND], [MINS, MNONE, MLFLEX]],
  ["en", "Months to years.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "On and off for about two years.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "2 years.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "Recurring flare-ups over three years.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["hi", "Kai saalon se.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["de", "कई सालों से।", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "The teenage patient has central low back pain on arching backwards and on standing.", [LCEN, ASTAND], [ALL, ALR, RNONE, MSPORT, LMID]],
  ["en", "A teenage gymnast with pain in the middle of the lower back when she arches backwards and when she stands for long.", [], [LCEN, LMID, ALL, ALR, RNONE, MSPORT, ASTAND, ASTAND30]],
  ["en", "Teen athlete. Central LBP. Worse extension and standing.", [LCEN, ASTAND], [ALL, ALR, RNONE, MSPORT, LMID]],
  ["en", "A fast bowler of sixteen with an ache right in the midline of the lower back, worst when leaning back or standing for a while.", [LCEN, ASTAND], [ALL, ALR, RNONE, MSPORT, LMID]],
  ["hi", "Kishor khilaadi, kamar ke neeche beech mein dard, peeche jhukne aur khade rehne par badhta hai.", [ASTAND], [LCEN, LMID, LLOW, ALL, ALR, RNONE, MSPORT]],
  ["de", "किशोर खिलाड़ी, कमर के निचले हिस्से में बीच में दर्द, पीछे झुकने और खड़े रहने पर बढ़ता है।", [ASTAND], [LCEN, LMID, LLOW, ALL, ALR, RNONE, MSPORT]],
  ["en", "Gradual, after a spell of extension sport.", [MSPORT], [MINS]],
  ["en", "It built up over a few weeks of gymnastics training.", [MSPORT], [MINS]],
  ["en", "Gradual. Extension sport.", [MSPORT], [MINS]],
  ["en", "It came on slowly through the cricket season, with no single injury.", [MSPORT], [MINS]],
  ["hi", "Khel mein dheere dheere shuru hua.", [MSPORT], [MINS]],
  ["de", "खेल में धीरे धीरे शुरू हुआ।", [MSPORT], [MINS]],
  ["en", "Repeated arching in sport, such as gymnastics or fast bowling.", [MSPORT], [MINS]],
  ["en", "She does gymnastics, a lot of back-bends.", [MSPORT], [MINS]],
  ["en", "Gymnast. Repeated extension.", [MSPORT], [MINS]],
  ["en", "He bowls fast for the school and trains four times a week.", [MSPORT], [MINS]],
  ["hi", "Gymnastics ya fast bowling mein peeche jhukna.", [MSPORT], [MINS]],
  ["de", "जिम्नास्टिक या फास्ट बॉलिंग में पीछे झुकना।", [MSPORT], [MINS]],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been there for about two months.", [], []],
  ["en", "2 months.", [], []],
  ["en", "Since the start of the season, about three months.", [], []],
  ["hi", "Kuch mahino se.", [], []],
  ["de", "कुछ महीनों से।", [], []],
  ["en", "The patient has pain and spasm in the muscles to the left of the spine in the lower back, with no leg pain.", [LPARL, RNONE, NNO], [LBAND, LLOW]],
  ["en", "The muscles on the left of the lower back have gone tight and sore, and nothing goes down the leg.", [LPARL, RNONE, NNO], [LBAND, LLOW]],
  ["en", "Left paraspinal pain and spasm. No leg symptoms.", [LPARL, RNONE, NNO], [LBAND, LLOW]],
  ["en", "It's a tight, sore band of muscle on the left side of the lower back that spasms when they move. There's no pain in the legs.", [LPARL, RNONE, NNO], [LBAND, LLOW]],
  ["hi", "Kamar ke neeche baayein taraf ki maspeshiyon mein dard aur akdan, pair mein dard nahi.", [LPARL, RNONE, NNO], [LBAND, LLOW]],
  ["de", "कमर के निचले हिस्से में बाईं तरफ की मांसपेशियों में दर्द और अकड़न, पैर में दर्द नहीं।", [LPARL, RNONE, NNO], [LBAND, LLOW]],
  ["en", "Sudden, lifting with the back bent.", [MLFLEX], [MLROT, MTWIST, MLFLOOR]],
  ["en", "It happened when they lifted something heavy with the back bent over.", [MLFLEX], [MLROT, MTWIST, MLFLOOR]],
  ["en", "Sudden. Lifting flexed.", [MLFLEX], [MLROT, MTWIST, MLFLOOR]],
  ["en", "They bent over to pick up a full water can and felt a pull in the lower back.", [MLFLEX], [MLROT, MTWIST, MLFLOOR]],
  ["hi", "Jhuk kar bhaari cheez uthate waqt achanak.", [MLFLEX], [MLROT, MTWIST, MLFLOOR]],
  ["de", "झुककर भारी चीज़ उठाते समय अचानक।", [MLFLEX], [MLROT, MTWIST, MLFLOOR]],
  ["en", "A heavy lift from the floor with the back bent.", [MLFLEX, MLFLOOR], [MLROT]],
  ["en", "They lifted a heavy box up from the floor.", [MLFLOOR], [MLFLEX, MLROT]],
  ["en", "Heavy lift from floor.", [MLFLOOR], [MLFLEX, MLROT]],
  ["en", "They were moving house and lifted heavy boxes from the floor all day.", [MLFLOOR], [MLFLEX, MLROT]],
  ["hi", "Zameen se bhaari saman uthana.", [MLFLOOR], [MLFLEX, MLROT]],
  ["de", "ज़मीन से भारी सामान उठाना।", [MLFLOOR], [MLFLEX, MLROT]],
  ["en", "Days to a few weeks.", [], []],
  ["en", "It happened four days ago.", [], []],
  ["en", "4 days.", [], []],
  ["en", "It came on last weekend and is slowly easing.", [], []],
  ["hi", "Kuch dinon se.", [], []],
  ["de", "कुछ दिनों से।", [], []],
  ["en", "The patient has a dull ache in the lower left buttock with tender knots, and no leg symptoms.", [LBULL, RNONE, NNO], [LBULU, LBAND, ASIT, ASIT60]],
  ["en", "It's a deep dull ache in the left buttock with sore spots, and nothing goes down the leg.", [RNONE, NNO], [LBULU, LBULL, LBAND]],
  ["en", "Left buttock myofascial pain. Tender knots. No neuro.", [NNO], [RNONE, LBULU, LBULL]],
  ["en", "They describe a heavy, dull ache in the lower left buttock and back muscles, with sore knots when pressed, worse after sitting for over an hour.", [LBULL, ASIT60], [RNONE, NNO, LBULU, LBAND, ASIT]],
  ["hi", "Baayein chutad ke neeche gehra dard, dabane par gaanth, pair mein dard nahi.", [LBULL, RNONE, NNO], [LBULU, LBAND, ASIT, ASIT60]],
  ["de", "बाएं चूतड़ के निचले हिस्से में गहरा दर्द, दबाने पर गांठ, पैर में दर्द नहीं।", [LBULL, RNONE, NNO], [LBULU, LBAND, ASIT, ASIT60]],
  ["en", "Gradual, linked with stress and a long desk day.", [MINS, MPOST], [ASIT, ASIT60, MNONE]],
  ["en", "It builds up when work is stressful and they sit for hours.", [MPOST], [MINS, MNONE, ASIT, ASIT60]],
  ["en", "Gradual. Stress.", [MINS], [MPOST, MNONE]],
  ["en", "Over several months, with a lot of work stress and long hours sitting.", [MPOST], [MINS, MNONE, ASIT, ASIT60]],
  ["hi", "Dheere dheere, tanaav aur der tak baithne se.", [MPOST], [MINS, MNONE, ASIT, ASIT60]],
  ["de", "धीरे धीरे, तनाव और देर तक बैठने से।", [MPOST], [MINS, MNONE, ASIT, ASIT60]],
  ["en", "Poor posture with long sitting.", [MPOST], [MINS]],
  ["en", "Sits on a hard office chair for hours.", [MPOST], [MINS]],
  ["en", "Long sitting. Poor posture.", [MPOST], [MINS]],
  ["en", "A call-centre agent who sits for ten hours without a break.", [MPOST], [MINS]],
  ["hi", "Der tak baithna.", [MPOST], [MINS]],
  ["de", "देर तक बैठना।", [MPOST], [MINS]],
  ["en", "Weeks to months.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "It has been there for a couple of months.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "2 months.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "Slowly worse over the last four months.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["hi", "Kuch mahino se.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["de", "कुछ महीनों से।", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "The patient has morning stiffness over 30 minutes that eases with exercise, and pain that wakes them in the second half of the night.", [IFMORN, IFMOVE, PSECOND], [IFAGE, IFINS, IFREST, PMORN, PREST, PNIGHT]],
  ["en", "They are stiff for more than half an hour every morning, it loosens up when they exercise, and the pain wakes them in the early hours.", [IFMORN, IFMOVE, PSECOND], [IFAGE, IFINS, IFREST, PMORN, PREST, PNIGHT]],
  ["en", "Morning stiffness over 30 min. Improves with exercise. Wakes second half of night.", [IFMORN, IFMOVE, PSECOND], [IFAGE, IFINS, IFREST, PMORN, PREST, PNIGHT]],
  ["en", "Every morning the back is stiff for about an hour. A walk or a workout loosens it up, but resting makes it worse, and they wake around three in the morning with pain.", [IFMORN, IFMOVE, PSECOND], [IFAGE, IFINS, IFREST, PMORN, PREST, PNIGHT]],
  ["hi", "Subah 30 minute se zyada akdan, kasrat se kam hota hai, raat ke doosre hisse mein dard se neend khulti hai.", [IFMORN, IFMOVE, PSECOND], [IFAGE, IFINS, IFREST, PMORN, PREST, PNIGHT]],
  ["de", "सुबह 30 मिनट से ज्यादा अकड़न, कसरत से कम होती है, रात के दूसरे हिस्से में दर्द से नींद खुलती है।", [IFMORN, IFMOVE, PSECOND], [IFAGE, IFINS, IFREST, PMORN, PREST, PNIGHT]],
  ["en", "Gradual onset over months, age under 45.", [IFINS, IFAGE], [MINS, MNONE]],
  ["en", "It crept up over a few months, they are in their twenties.", [IFINS, IFAGE], [MINS, MNONE]],
  ["en", "Insidious. Young patient.", [IFAGE], [IFINS, MINS, MNONE]],
  ["en", "A man of twenty-eight, no injury, with the pain building up slowly over four months.", [IFINS, IFAGE], [MINS, MNONE]],
  ["hi", "Dheere dheere, kam umar mein shuru hua.", [IFAGE], [IFINS, MINS, MNONE]],
  ["de", "धीरे धीरे, कम उम्र में शुरू हुआ।", [IFAGE], [IFINS, MINS, MNONE]],
  ["en", "A family history of ankylosing spondylitis, psoriasis or eye inflammation.", [IFFAM], [IFPSO, IFIBD, IFUVE]],
  ["en", "His father has ankylosing spondylitis.", [IFFAM], [IFPSO, IFIBD, IFUVE]],
  ["en", "FH of AS.", [IFFAM], [IFPSO, IFIBD, IFUVE]],
  ["en", "The father has ankylosing spondylitis and an uncle has psoriasis.", [IFFAM], [IFPSO, IFIBD, IFUVE]],
  ["hi", "Parivaar mein reedh ki sujan ka itihas.", [IFFAM], [IFPSO, IFIBD, IFUVE]],
  ["de", "परिवार में रीढ़ की सूजन का इतिहास।", [IFFAM], [IFPSO, IFIBD, IFUVE]],
  ["en", "More than 3 months.", [], []],
  ["en", "It has been going on for about six months.", [], []],
  ["en", "6 months.", [], []],
  ["en", "Slowly more than half a year, with the stiffness getting longer.", [], []],
  ["hi", "Kai mahino se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "The patient has numbness in the saddle area and cannot pass urine.", [CSADDLE, CRET], [CWEAK, CBISC]],
  ["en", "They have gone numb between the legs and cannot pass water.", [CSADDLE, CRET], [CWEAK, CBISC]],
  ["en", "Saddle numbness. Urinary retention.", [CSADDLE, CRET], [CWEAK, CBISC]],
  ["en", "Since this morning there is numbness around the groin and inner thighs, and they have not been able to pass urine all day.", [CSADDLE, CRET], [CWEAK, CBISC]],
  ["hi", "Jaangh ke beech sunn, peshaab nahi aa raha.", [CSADDLE, CRET], [CWEAK, CBISC]],
  ["de", "जांघ के बीच सुन्न, पेशाब नहीं आ रहा।", [CSADDLE, CRET], [CWEAK, CBISC]],
  ["en", "Back pain after minor trauma, with osteoporosis or long-term steroids.", [FROSTEO, FRSTER], [FRPM, FR70, MFALLB, MLFLEX, MBEND]],
  ["en", "A small fall and now severe back pain, and they have osteoporosis and take steroids.", [FROSTEO, FRSTER], [FRPM, FR70, MFALLB, MLFLEX, MBEND]],
  ["en", "Minor trauma. Osteoporosis. Steroids.", [FROSTEO, FRSTER], [FRPM, FR70, MFALLB, MLFLEX, MBEND]],
  ["en", "An elderly woman with known osteoporosis and long-term steroid use, who bent to lift a bag and felt a sharp pain in the back.", [FROSTEO, FRSTER], [FRPM, FR70, MFALLB, MLFLEX, MBEND]],
  ["hi", "Maamuli chot, haddi kamzori aur steroid ka sevan.", [FROSTEO, FRSTER], [FRPM, FR70, MFALLB, MLFLEX, MBEND]],
  ["de", "मामूली चोट, हड्डी कमज़ोरी और स्टेरॉइड का सेवन।", [FROSTEO, FRSTER], [FRPM, FR70, MFALLB, MLFLEX, MBEND]],
  ["en", "History of cancer with weight loss and constant night pain.", [SCA, SWT], [SNIGHT, SCONST, SFEV, PCONST, PNIGHT]],
  ["en", "She had breast cancer, has lost weight, and the pain is constant and worse at night.", [SCA, SWT], [SNIGHT, SCONST, SFEV, PCONST, PNIGHT]],
  ["en", "Hx cancer. Weight loss. Constant night pain.", [SCA, SWT, SNIGHT], [SCONST, SFEV, PCONST, PNIGHT]],
  ["en", "Treated for prostate cancer three years ago, has lost 6 kg without trying, and has a constant ache that wakes him at night.", [SCA, SWT], [SNIGHT, SCONST, SFEV, PCONST, PNIGHT]],
  ["hi", "Cancer ka itihas, wazan kam hua, raat ko lagatar dard.", [SCA, SWT], [SNIGHT, SCONST, SFEV, PCONST, PNIGHT]],
  ["de", "कैंसर का इतिहास, वज़न कम हुआ, रात को लगातार दर्द।", [SCA, SWT], [SNIGHT, SCONST, SFEV, PCONST, PNIGHT]],
  ["en", "Urgent; may be days or weeks.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "It has been getting worse over three weeks.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "3 weeks, worsening.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "Over a month, with the pain now constant.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["hi", "Kuch hafton se badhta hua.", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["de", "कुछ हफ्तों से बढ़ता हुआ।", [], [MINS, MNONE, IFINS, PINTTRIG, PINTUNP, PCONST]],
  ["en", "Patient works as a driver and lives in Surat.", [], []],
  ["en", "Medical history: type 2 diabetes, on metformin.", [], []],
  ["en", "Pain score is 6 out of 10.", [], []],
  ["en", "He has been referred by his employer.", [], []],
  ["en", "She would like to return to yoga eventually.", [], []],
  ["en", "Husband brought the patient to the clinic.", [], []],
  ["hi", "Mareez ko pichle hafte doctor ne dekha tha.", [], []],
  ["de", "मरीज़ की उम्र पचास साल है।", [], []],
];

// Same scoring as the other exams, except "may" answers are neutral.
export function scoreSheet(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, must, may] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const okSet = new Set([...must, ...may]);
    for (const g of got) { suggested++; if (okSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of must) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
