// lumbarSISheetSetFresh.js -- a SECOND, fresh exam in the clinician's voice ("the patient", "they", short notes), written AFTER the Lumbar
// matcher had been fixed for the sheet's own sentences (lumbarSISheetSet.js). None of these sentences was used to tune the matcher before
// their first run was recorded. Row = [lang, text, must, may] -- same meaning as in lumbarSISheetSet.js. The answer keys are DRAFTS written
// by Claude for Aditi to check.
import { KEYS } from "./lumbarSIWildSets.js";

const { LMID, RDORS, RL5, RL4, LSIB, LLOW, LSJ, LCEN, LPARR, LPARL, LBAND, LSIL, LSIR, LCOC, LBULU, LBULL, LBURU, LBURL, RNONE, RBELT, RGRL, RGRR, RPTL, RPTR, RCAL, RCAR, RBIL, RSOLE,
  MINS, MLFLEX, MLROT, MLBOTH, MLFLOOR, MTWIST, MBEND, MCOUGH, MSTRAIN, MSTUMBLE, MFALLB, MFALLH, MMVA, MSPORT, MPOST, MSURG, MPP, MILL, MNONE,
  ASIT, ASIT15, ASIT30, ASIT60, ASOFT, ASTAND, ASTAND15, ASTAND30, ASUP, APRO, ALL, ALR, ADRIVE, AREADBED, ASLUMP, ABENT, ATWIST,
  PFLAT, PCROOK, PPILKNEE, PSIDEKN, PSIDEPIL, PPRONE, PELBOW, PSUPPORT, PFIRM, PSHIFT, PWALK, PALL4, PLEAN, PLEGSUP,
  PCONST, PCONSTVAR, PINTTRIG, PINTUNP, PLOAD, PREST, PMORN, PEVE, PNIGHT, PWARM, PDELAY, PSECOND, PNOPAT, NNO, NL, NR, NBIL, BNORM,
  CWEAK, CSADDLE, CRET, CINCB, CINCW, CSEX, CBISC, FRHIGH, FROSTEO, FR70, FRSTER, FRPREV, FRPOINT, FRSEV, FRPM,
  IFAGE, IFINS,  IFMORN, IFMOVE, IFREST, IFALT, IFFAM, IFPSO, IFIBD, IFUVE, IFPERI, IFNSAID,
  SCONST, SAAA, SNIGHT, STHOR, SABD, SWT, SCA, SIV, SINF, SFEV, SFLANK, DSHOES, DBEND, DLIFTKID, DLIFTSH, DVAC, DBEDMOB, DOUTBED, DDRIVE, DHOUSE, DCHILD,
  WNO, WMOD, WRED, WSHORT, WMED, WLONG, WUNEMP, WUNABLE } = KEYS;

export const LUMBAR_SHEET_FRESH = [
  // non-specific / mechanical, muscle strain, myofascial
  ["en", "Central low back ache for a fortnight, worse after a long drive, nothing in the legs.", [LCEN, ADRIVE, RNONE], [NNO, MNONE, MINS]],
  ["en", "Spasm in the muscles to the right of the spine after shovelling snow.", [LPARR], [MLFLEX, MLROT]],
  ["en", "Pain eases when walking about, worse when sitting still for a long while.", [PWALK, ASIT], [ASIT15, ASIT30, ASIT60, IFREST, IFMOVE]],
  ["en", "Sudden sharp pain in the lower back when bending over to put on shoes.", [MBEND], [ABENT, LLOW, DSHOES]],
  ["en", "Stiff and sore on getting out of bed, loosens up as the day goes on.", [PMORN], [DOUTBED]],
  ["en", "Worse in the evening after a day of standing at the counter.", [PEVE, ASTAND], []],
  ["en", "Deep ache in the right buttock, tender points, no leg pain.", [RNONE], [LBURU, LBURL, NNO]],
  ["en", "Eases lying on the back with a pillow under the knees.", [PPILKNEE], [PFLAT]],
  ["hi", "Kamar ke beech mein dard, lambi gaadi chalane ke baad badhta hai, pair mein kuch nahi.", [LCEN, ADRIVE, RNONE], [NNO, LMID, DDRIVE]],
  ["hi", "Reedh ke daayein taraf maspeshiyon mein akdan, bhaari cheez uthane ke baad.", [LPARR], [MLFLEX, MLROT, MLFLOOR]],
  ["de", "कमर के बीच में दर्द, लंबी ड्राइव के बाद बढ़ता है, पैरों में कुछ नहीं।", [LCEN, ADRIVE, RNONE], [NNO, LMID, DDRIVE]],
  ["de", "बाईं तरफ रीढ़ के पास मांसपेशियों में अकड़न, भारी चीज़ उठाने के बाद।", [LPARL], [MLFLEX, MLROT, MLFLOOR]],
  // disc / radiculopathy
  ["en", "Shooting pain down the back of the right leg into the sole of the foot, with pins and needles.", [RPTR, RSOLE, NR], [RCAR]],
  ["en", "Left leg pain below the knee since lifting a wardrobe, worse on coughing.", [], [RCAL, RL5, RL4, NL, MLFLEX, MLFLOOR, MLROT, MLBOTH]],
  ["en", "Sitting is the worst, they have to stand up every ten minutes.", [ASIT], [ASIT15]],
  ["en", "Lying on the back with the knees bent gives some relief.", [PCROOK], []],
  ["en", "Pain began as they were bending forward to lift a heavy bag and then twisted to put it down.", [MLBOTH], [MLFLEX, MLROT]],
  ["en", "Sneezing sent a jolt down the left leg and the back locked.", [MCOUGH], []],
  ["en", "Numbness over the outer left calf and top of the foot.", [NL], [RCAL, RDORS, RL5]],
  ["hi", "Daayein pair ke peeche se talwe tak bijli jaisa dard, jhunjhuni ke saath.", [RSOLE, NR], [RPTR, RCAR]],
  ["de", "दाएं पैर के पीछे से तलवे तक बिजली जैसा दर्द, झुनझुनी के साथ।", [RSOLE, NR], [RPTR, RCAR]],
  // facet / spondylolysis
  ["en", "Pain on the left side of the lower back when standing up straight, eases on bending forward.", [LPARL], [ASTAND]],
  ["en", "Worse leaning backwards and twisting to the left, better sitting.", [], [PSUPPORT, PFIRM, ATWIST, ASIT]],
  ["en", "Fast bowler with a gradual onset of central low back pain over the season.", [MSPORT, LCEN], [MINS, MNONE, IFINS]],
  ["en", "Gymnast, pain on every back bend, no leg symptoms.", [MSPORT, RNONE], [NNO]],
  ["hi", "Gymnast hai, har baar peeche jhukne par kamar mein dard, pair mein koi dikkat nahi.", [MSPORT, RNONE], [NNO]],
  ["de", "जिम्नास्ट है, हर बार पीछे झुकने पर कमर में दर्द, पैर में कोई तकलीफ नहीं।", [MSPORT, RNONE], [NNO]],
  // stenosis
  ["en", "Elderly patient, pain and heaviness in both legs after walking about 100 metres, settles on sitting.", [RBIL], [NBIL, MINS, MNONE, PLEAN, ASIT, PSUPPORT, PWARM]],
  ["en", "Leans on the shopping trolley to walk any distance.", [PLEAN], []],
  ["en", "Cannot stand for long in the kitchen without both legs going numb.", [NBIL], [RBIL, ASTAND, ASTAND15, ASTAND30]],
  ["en", "Easier cycling than walking, bent forward over the handlebars.", [PLEAN], []],
  ["hi", "Buzurg mareez, dono pairon mein chalne par bhaaripan, baithne par aaram.", [], [RBIL, NBIL, ASIT, PWARM, PSUPPORT]],
  ["de", "बुजुर्ग मरीज़, दोनों पैरों में चलने पर भारीपन, बैठने पर आराम।", [], [RBIL, NBIL, ASIT, PWARM, PSUPPORT]],
  // SIJ / pelvis
  ["en", "Pain at the left SI joint when standing on one leg and climbing stairs.", [LSIL], [ATWIST, ASTAND]],
  ["en", "Developed after the second pregnancy, deep pain low on both sides of the back.", [MPP], [LSIB, LSIL, LSIR, LBAND]],
  ["en", "Sharp pain in the left buttock when rolling over in bed at night.", [], [LBULU, LBULL, ALL, PNIGHT, DBEDMOB]],
  ["en", "Slipped on the ice and landed hard on the tailbone.", [MFALLB, LCOC], []],
  ["en", "Hurts to sit on a hard seat, better on a cushion with a hole.", [ASIT], [LCOC, PSUPPORT]],
  ["hi", "Baayein SI joint par dard, ek pair par khade hone aur seedhi chadhne par.", [LSIL], [ATWIST, ASTAND]],
  ["de", "बाएं एसआई जोड़ पर दर्द, एक पैर पर खड़े होने और सीढ़ी चढ़ने पर।", [LSIL], [ATWIST, ASTAND]],
  // inflammatory
  ["en", "Twenty-five year old with a long stiffness in the morning that eases after a hot shower and a walk.", [IFAGE, IFMOVE], [IFMORN, PMORN]],
  ["en", "Pain alternates between the left and right buttock.", [IFALT], [LBULU, LBURU, LBULL, LBURL]],
  ["en", "Wakes with back pain in the early hours and has to get up and walk about.", [PSECOND], [IFREST, IFMOVE, PNIGHT]],
  ["en", "Anti-inflammatories work very well, within a day.", [IFNSAID], []],
  ["en", "History of psoriasis and a red painful eye last year.", [IFPSO, IFUVE], []],
  ["en", "Crohn's disease diagnosed at nineteen, now back pain.", [IFIBD], [IFAGE]],
  ["en", "Heel and knee pain as well as the back.", [IFPERI], []],
  ["hi", "Panchis saal ka mareez, subah der tak akdan, garam paani aur tahalne se kam hota hai.", [IFAGE, IFMOVE], [IFMORN, PMORN]],
  ["de", "पच्चीस साल का मरीज़, सुबह देर तक अकड़न, गर्म पानी और टहलने से कम होती है।", [IFAGE, IFMOVE], [IFMORN, PMORN]],
  // red flags
  ["en", "Numb between the legs and cannot tell when the bladder is full.", [CSADDLE], [CRET, CINCB]],
  ["en", "New leaking of urine since yesterday with the back pain.", [CINCB], []],
  ["en", "Both legs have gone weak over two days.", [CWEAK], [NBIL]],
  ["en", "Lost control of the bowels last night.", [CINCW], []],
  ["en", "Has been unable to have sex since the pain started.", [CSEX], []],
  ["en", "Fell off a ladder from three metres.", [FRHIGH, MFALLH], []],
  ["en", "Pain on pressing the spinous process after a minor fall, known osteoporosis.", [FRPOINT, FROSTEO], [MFALLB]],
  ["en", "Previous vertebral fracture two years ago, now new back pain.", [FRPREV], []],
  ["en", "Seventy-five year old with a small fall onto the back yesterday.", [FR70, MFALLB], []],
  ["en", "Post-menopausal woman with sudden pain after lifting a pot.", [FRPM], [MLFLEX]],
  ["en", "Constant pain, not changed by any position or movement.", [SCONST], [PCONST, FRSEV]],
  ["en", "Unexplained fever and night sweats with back pain.", [SFEV], [SNIGHT]],
  ["en", "Injects drugs, now fever and a very painful lower back.", [SIV, SFEV], []],
  ["en", "Pain goes round the flank to the front, burning on passing urine.", [SFLANK], []],
  ["en", "Upper back pain as well as the low back, and belly pain after meals.", [STHOR, SABD], []],
  ["en", "Throbbing in the abdomen, felt as a pulse.", [SAAA], []],
  ["hi", "Dono pairon mein kamzori, do din se, aur peshaab rokne mein dikkat.", [CWEAK], [CINCB, CRET, NBIL]],
  ["de", "दोनों पैरों में कमज़ोरी, दो दिन से, और पेशाब रोकने में दिक्कत।", [CWEAK], [CINCB, CRET, NBIL]],
  ["hi", "Bukhaar aur raat ko paseena ke saath kamar dard, wazan bhi kam hua.", [SFEV, SWT], [SNIGHT]],
  ["de", "बुखार और रात को पसीने के साथ कमर दर्द, वज़न भी कम हुआ।", [SFEV, SWT], [SNIGHT]],
  // everyday life and work
  ["en", "Cannot put on socks or shoes because of the back.", [DSHOES], []],
  ["en", "Cannot pick up the toddler from the cot.", [DLIFTKID], [DBEND, DCHILD]],
  ["en", "Struggles to push the vacuum around and mop the floor.", [DVAC], [DHOUSE]],
  ["en", "Takes ages to get out of bed in the morning because of the back.", [DOUTBED], [PMORN]],
  ["en", "Drives to work but has to stop every half hour.", [DDRIVE], [ADRIVE, ASIT30]],
  ["en", "Off work for the last six weeks.", [WMED], []],
  ["en", "On light duties since the injury.", [WMOD], []],
  ["en", "Working half days only.", [WRED], []],
  ["en", "Has not worked for the last eight months.", [WLONG], []],
  ["en", "Lost the job because of the long sick leave.", [WUNEMP], []],
  ["en", "No effect on work at all.", [WNO], []],
  ["hi", "Moze aur joote pehanne mein dikkat hoti hai kamar ki wajah se.", [DSHOES], []],
  ["de", "कमर की वजह से मोज़े और जूते पहनने में दिक्कत होती है।", [DSHOES], []],
  // must stay silent
  ["en", "Patient works as a driver and lives in Surat.", [], []],
  ["en", "Medical history: type 2 diabetes, on metformin.", [], []],
  ["en", "Pain score is 6 out of 10.", [], []],
  ["en", "He has been referred by his employer.", [], []],
  ["en", "She would like to return to yoga eventually.", [], []],
  ["en", "Husband brought the patient to the clinic.", [], []],
  ["hi", "Mareez ko pichle hafte doctor ne dekha tha.", [], []],
  ["de", "मरीज़ की उम्र पचास साल है।", [], []],
];
