// lumbarSIWildSets.js -- shared by the Lumbar/SI phrase-matcher tests (not a test itself).
// Sets of messy, real-life sentences written the way students type, each marked with what a physio would
// tick ("field|option"). These answer keys are DRAFTS written by Claude for Aditi to review.
// A = the first exam, used to find what the first draft missed; B and C = fair exams written after the
// earlier sets' fixes and NOT used to tune the matcher until their first run was recorded.
// See lumbarSIPhraseMapWild.test.js for the history.
import { LUMBAR_SI_PHRASES, understandStory } from "../lumbarSIPhraseMap.js";

const ks = (field) => Object.keys(LUMBAR_SI_PHRASES[field]).map((o) => `${field}|${o}`);
// location
const [LUP, LMID, LLOW, LSJ, LCEN, LPARR, LPARL, LBAND, LSAC, LSIL, LSIR, LSIB, LCOC, LBULU, LBULL, LBURU, LBURL, LISCL, LISCR] = ks("location");
// radiation
const [RNONE, RBELT, RGRL, RGRR, RBUL, RBUR, RPTL, RPTR, RATL, RATR, RLAT, RKNL, RKNR, RCAL, RCAR, RL5, RL4, RDORS, RSOLE, RTOEL, RTOER, RBIL] = ks("radiation");
// mechanism
const [MINS, MLFLEX, MLROT, MLBOTH, MLFLOOR, MTWIST, MBEND, MCOUGH, MSTRAIN, MSTUMBLE, MFALLB, MFALLH, MMVA, MSPORT, MPOST, MSURG, MPP, MILL, MNONE] = ks("mechanismType");
// postures
const [ASIT, ASIT15, ASIT30, ASIT60, ASOFT, ASTAND, ASTAND15, ASTAND30, ASUP, APRO, ALL, ALR, ADRIVE, AREADBED, ASLUMP, ABENT, ATWIST] = ks("aggPostures");
const [PFLAT, PCROOK, PPILKNEE, PSIDEKN, PSIDEPIL, PPRONE, PELBOW, PSUPPORT, PFIRM, PSHIFT, PWALK, PALL4, PLEAN, PLEGSUP] = ks("relPostures");
// 24-hour pattern
const [PCONST, PCONSTVAR, PINTTRIG, PINTUNP, PLOAD, PREST, PMORN, PEVE, PNIGHT, PWARM, PDELAY, PSECOND, PNOPAT] = ks("overallPattern");
// neuro, bladder baseline
const [NNO, NL, NR, NBIL] = ks("neuroPresent");
const [BNORM, BBLAD, BBOWEL, BNOTASK, BUNC] = ks("bladderBaseline");
// red flags
const [CNO, CWEAK, CSADDLE, CRET, CINCB, CINCW, CTONE, CSEX, CPROG, CBISC] = ks("redFlagsCauda");
const [FRNO, FRHIGH, FROSTEO, FR70, FRSTER, FRPREV, FRPOINT, FRSEV, FRPM] = ks("redFlagsFracture");
const [IFNO, IFAGE, IFINS, IFMORN, IFMOVE, IFREST, IFALT, IFFAM, IFPSO, IFIBD, IFUVE, IFPERI, IFNSAID, IFHLA, IFESR] = ks("redFlagsInflammatory");
const [SNO, SCONST, SNIGHT, STHOR, SABD, SAAA, SWT, SCA, SIV, SINF, SFEV, SFLANK] = ks("redFlagsSerious");
// function, work
const [DNONE, DSHOES, DBEND, DLIFTKID, DLIFTSH, DVAC, DBEDMOB, DOUTBED, DBATH, DDRIVE, DSEX, DGARD, DHOUSE, DCHILD] = ks("adlRestrictions");
const [WNO, WMILD, WMOD, WRED, WSHORT, WMED, WLONG, WUNEMP, WUNABLE] = ks("workImpact");
export const KEYS = {
  LUP, LMID, LLOW, LSJ, LCEN, LPARR, LPARL, LBAND, LSAC, LSIL, LSIR, LSIB, LCOC, LBULU, LBULL, LBURU, LBURL, LISCL, LISCR,
  RNONE, RBELT, RGRL, RGRR, RBUL, RBUR, RPTL, RPTR, RATL, RATR, RLAT, RKNL, RKNR, RCAL, RCAR, RL5, RL4, RDORS, RSOLE, RTOEL, RTOER, RBIL,
  MINS, MLFLEX, MLROT, MLBOTH, MLFLOOR, MTWIST, MBEND, MCOUGH, MSTRAIN, MSTUMBLE, MFALLB, MFALLH, MMVA, MSPORT, MPOST, MSURG, MPP, MILL, MNONE,
  ASIT, ASIT15, ASIT30, ASIT60, ASOFT, ASTAND, ASTAND15, ASTAND30, ASUP, APRO, ALL, ALR, ADRIVE, AREADBED, ASLUMP, ABENT, ATWIST,
  PFLAT, PCROOK, PPILKNEE, PSIDEKN, PSIDEPIL, PPRONE, PELBOW, PSUPPORT, PFIRM, PSHIFT, PWALK, PALL4, PLEAN, PLEGSUP,
  PCONST, PCONSTVAR, PINTTRIG, PINTUNP, PLOAD, PREST, PMORN, PEVE, PNIGHT, PWARM, PDELAY, PSECOND, PNOPAT,
  NNO, NL, NR, NBIL, BNORM, BBLAD, BBOWEL, BNOTASK, BUNC,
  CNO, CWEAK, CSADDLE, CRET, CINCB, CINCW, CTONE, CSEX, CPROG, CBISC,
  FRNO, FRHIGH, FROSTEO, FR70, FRSTER, FRPREV, FRPOINT, FRSEV, FRPM,
  IFNO, IFAGE, IFINS, IFMORN, IFMOVE, IFREST, IFALT, IFFAM, IFPSO, IFIBD, IFUVE, IFPERI, IFNSAID, IFHLA, IFESR,
  SNO, SCONST, SNIGHT, STHOR, SABD, SAAA, SWT, SCA, SIV, SINF, SFEV, SFLANK,
  DNONE, DSHOES, DBEND, DLIFTKID, DLIFTSH, DVAC, DBEDMOB, DOUTBED, DBATH, DDRIVE, DSEX, DGARD, DHOUSE, DCHILD,
  WNO, WMILD, WMOD, WRED, WSHORT, WMED, WLONG, WUNEMP, WUNABLE,
};

export const LUMBAR_SI_A = [
  // ── English ──
  ["en", "low back pain for three weeks after lifting a heavy box from the floor, bending and twisting at the same time", [MLFLOOR, MLBOTH]],
  ["en", "lifted a washing machine with a bent back and felt something go", [MLFLEX]],
  ["en", "pain started when I picked up my son while twisted to one side", [MLROT]],
  ["en", "it began when I sneezed", [MCOUGH]],
  ["en", "I was straining on the toilet and my back went", [MSTRAIN]],
  ["en", "I tripped on the kerb but did not fall, jarred my back", [MSTUMBLE]],
  ["en", "fell onto my bottom on the ice", [MFALLB]],
  ["en", "fell off a ladder at work", [MFALLH]],
  ["en", "rear ended on the motorway last year", [MMVA]],
  ["en", "hurt it playing football", [MSPORT]],
  ["en", "sitting at a desk all day with poor posture for years", [MPOST]],
  ["en", "pain started after my spinal operation", [MSURG]],
  ["en", "after the birth of my baby", [MPP]],
  ["en", "it came on gradually over months, no injury", [MINS, IFINS]],
  ["en", "pain on the left side of the lower back next to the spine", [LPARL]],
  ["en", "pain to the right of the spine in the lumbar area", [LPARR]],
  ["en", "pain across the whole lower back like a belt", [LBAND]],
  ["en", "pain right at the bottom of the spine where it meets the pelvis, L5 S1", [LSJ]],
  ["en", "pain over the right si joint", [LSIR]],
  ["en", "left sacroiliac joint is very tender", [LSIL]],
  ["en", "tailbone pain when I sit", [LCOC, ASIT]],
  ["en", "pain in the upper part of the left buttock", [LBULU]],
  ["en", "pain under the right buttock", [LBURL]],
  ["en", "sore on my left sitting bone", [LISCL]],
  ["en", "pain in the very middle of the spine", [LCEN]],
  ["en", "pain at L1 L2 level, just below the ribs", [LUP]],
  ["en", "the pain goes down the back of my left thigh", [RPTL]],
  ["en", "pain spreads to the right buttock", [RBUR]],
  ["en", "pain goes into the left groin", [RGRL]],
  ["en", "pain down to the right calf", [RCAR]],
  ["en", "pain down the front of the right thigh", [RATR]],
  ["en", "pain on the outer side of the thigh", [RLAT]],
  ["en", "pain on the outside of the lower leg", [RL5]],
  ["en", "pain along the inside of the shin", [RL4]],
  ["en", "numbness on the top of the foot", [RDORS]],
  ["en", "burning in the sole of my foot", [RSOLE]],
  ["en", "tingling in the toes of the left foot", [RTOEL, NL]],
  ["en", "pain stays in the back and does not spread", [RNONE]],
  ["en", "pain goes down both legs", [RBIL]],
  ["en", "sitting for more than 30 minutes brings it on", [ASIT30]],
  ["en", "cannot sit longer than an hour", [ASIT60]],
  ["en", "after sitting twenty minutes it starts", [ASIT15]],
  ["en", "standing for more than 15 minutes hurts", [ASTAND15]],
  ["en", "standing longer than half an hour is a problem", [ASTAND30]],
  ["en", "soft sofas make it much worse", [ASOFT]],
  ["en", "lying on my right side hurts", [ALR]],
  ["en", "cannot lie on the left side", [ALL]],
  ["en", "driving makes it worse", [ADRIVE]],
  ["en", "slouching at my desk aggravates it", [ASLUMP]],
  ["en", "standing bent forward at the sink is painful", [ABENT]],
  ["en", "sitting with my legs crossed makes it worse", [ATWIST]],
  ["en", "lying on my stomach is painful", [APRO]],
  ["en", "lying flat on my back is the worst", [ASUP]],
  ["en", "lying on my back with my knees bent helps", [PCROOK]],
  ["en", "a pillow between my knees when I sleep on my side helps", [PSIDEPIL]],
  ["en", "lying on my stomach on my elbows eases it", [PELBOW]],
  ["en", "walking slowly helps", [PWALK]],
  ["en", "being on all fours relieves it", [PALL4]],
  ["en", "leaning on the trolley helps when I walk round the supermarket", [PLEAN]],
  ["en", "lumbar roll behind my back helps when I sit", [PSUPPORT]],
  ["en", "sitting with my feet up relieves it", [PLEGSUP]],
  ["en", "constant pain that never goes away", [PCONST]],
  ["en", "it comes and goes with no pattern", [PINTUNP]],
  ["en", "worse in the morning", [PMORN]],
  ["en", "worse by the evening after the day on my feet", [PEVE]],
  ["en", "worse at night and wakes me", [PNIGHT]],
  ["en", "pain wakes me at 3 am", [PSECOND]],
  ["en", "pain the next day after gardening", [PDELAY]],
  ["en", "worse at rest, better when I move", [PREST, PWARM, IFREST]],
  ["en", "numbness in the right leg", [NR]],
  ["en", "tingling down my left leg", [NL]],
  ["en", "numbness in both legs", [NBIL]],
  ["en", "no numbness or tingling in the legs", [NNO]],
  ["en", "bladder and bowels were normal before the pain started", [BNORM]],
  ["en", "numb in the saddle area", [CSADDLE]],
  ["en", "cannot pass urine", [CRET]],
  ["en", "leaking urine since this started", [CINCB]],
  ["en", "new loss of bowel control", [CINCW]],
  ["en", "both legs have become weak", [CWEAK, NBIL]],
  ["en", "new erectile problems since the back pain", [CSEX]],
  ["en", "sciatica on both sides, new", [CBISC]],
  ["en", "no cauda equina signs", [CNO]],
  ["en", "fell from a height in a high energy accident", [FRHIGH, MFALLH]],
  ["en", "has osteoporosis and slipped on a wet floor", [FROSTEO]],
  ["en", "on steroids for years", [FRSTER]],
  ["en", "she had a compression fracture of the spine before", [FRPREV]],
  ["en", "very tender over one spinous process", [FRPOINT]],
  ["en", "post menopausal woman with sudden back pain", [FRPM]],
  ["en", "morning stiffness for an hour that eases with exercise", [IFMORN, IFMOVE, PMORN]],
  ["en", "rest makes it worse and I cannot lie still at night", [IFREST, PREST]],
  ["en", "pain alternating between the buttocks", [IFALT]],
  ["en", "my father has ankylosing spondylitis", [IFFAM]],
  ["en", "he has psoriasis", [IFPSO]],
  ["en", "crohns disease", [IFIBD]],
  ["en", "hla b27 positive", [IFHLA]],
  ["en", "esr and crp are high", [IFESR]],
  ["en", "brufen works wonders", [IFNSAID]],
  ["en", "weight loss without trying and pain at night getting worse", [SWT, SNIGHT, PNIGHT]],
  ["en", "history of breast cancer", [SCA]],
  ["en", "fever with back pain", [SFEV]],
  ["en", "pulsatile mass in the abdomen", [SAAA]],
  ["en", "pain in the flank", [SFLANK]],
  ["en", "no other red flags", [SNO]],
  ["en", "cant put my socks on", [DSHOES]],
  ["en", "difficulty turning over in bed", [DBEDMOB]],
  ["en", "cant get out of bed in the morning", [DOUTBED]],
  ["en", "mopping is painful", [DVAC]],
  ["en", "cannot lift my toddler", [DLIFTKID]],
  ["en", "no limitations in daily activities", [DNONE]],
  ["en", "off work for two weeks", [WSHORT]],
  ["en", "off sick for six weeks", [WMED]],
  ["en", "no work impact", [WNO]],
  ["en", "on light duties at work", [WMOD]],
  // ── must stay silent ──
  ["en", "my knee hurts at night", []],
  ["en", "neck pain when I look up", []],
  ["en", "the weather is nice today", []],
  ["en", "my friend has back pain", []],
  ["en", "no history of cancer", []],
  ["en", "my mother has psoriasis", [IFFAM]],
  ["en", "I did not fall or twist it", []],
  ["en", "the MRI report was normal", []],
  ["en", "upper back pain between the shoulder blades", []],
  ["en", "she works at a bank", []],
  // ── Hinglish ──
  ["hi", "kamar ke neeche wale hisse me dard hai", [LLOW]],
  ["hi", "kamar ke bayen taraf dard", [LPARL]],
  ["hi", "dayen si joint me dard", [LSIR]],
  ["hi", "dard bayen pair ki jaangh ke peeche tak jata hai", [RPTL]],
  ["hi", "dard dayen pindli tak utarta hai", [RCAR]],
  ["hi", "jhukkar bhaari saman uthaya aur kamar pakad gayi", [MLFLEX]],
  ["hi", "ghanto baithkar kaam karne se kamar dard", [MPOST]],
  ["hi", "baithne par dard badhta hai", [ASIT]],
  ["hi", "raat ko kamar dard se neend khul jati hai", [PNIGHT]],
  ["hi", "subah uthte hi kamar akad jati hai", [PMORN]],
  ["hi", "dono pairon me sunnpan aur kamzori", [NBIL, CWEAK]],
  ["hi", "peshab nahi ho pa raha", [CRET]],
  ["hi", "peshab nikal jata hai", [CINCB]],
  ["hi", "gaadi chalane me dikkat", [DDRIVE]],
  ["hi", "mere chacha ko cancer hai", []],
  ["hi", "ghutne me dard hai", []],
  ["hi", "kal barish hui thi", []],
  // ── Hindi (Devanagari) ──
  ["de", "कमर के बीच में दर्द है", [LMID, LCEN]],
  ["de", "रात को दर्द से नींद खुल जाती है", [PNIGHT]],
  ["de", "बैठने पर दर्द बढ़ता है", [ASIT]],
  ["de", "दोनों पैरों में सुन्नपन", [NBIL]],
  ["de", "पेशाब रुक गया है", [CRET]],
  ["de", "रात में कमर दर्द बढ़ता है", [PNIGHT]],
  ["de", "मेरी बहन को कैंसर था", []],
  ["de", "सिर में दर्द है", []],
];

export const LUMBAR_SI_B = [
  // ── English ──
  ["en", "44 yo builder, sharp LBP on the right side next to the spine since lifting a bag of cement off the ground, bent over and turned", [LPARR, MLFLOOR, MLBOTH]],
  ["en", "she says it hurts across the bottom of her back at the belt line", [LLOW]],
  ["en", "aching over both SI joints, worse when I get out of a chair", [LSIB]],
  ["en", "tender on the left PSIS, around the dimple", [LSIL]],
  ["en", "pain at the coccyx after falling onto the ice", [LCOC]],
  ["en", "deep ache in the right buttock, upper part", [LBURU]],
  ["en", "pain under the left buttock where I sit", [LBULL]],
  ["en", "sitting bone on the right is very sore", [LISCR]],
  ["en", "dull pain in the middle of the lumbar spine at L3", [LMID]],
  ["en", "pain spreads from the back into my left groin", [RGRL]],
  ["en", "it shoots down the back of the right leg as far as the knee", [RPTR, RKNR]],
  ["en", "pain on the front of the left thigh", [RATL]],
  ["en", "burning down the outside of my left leg to the foot", [RL5]],
  ["en", "inner shin pain on the right", [RL4]],
  ["en", "numb on the top of the right foot and big toe", [RDORS, RTOER, NR]],
  ["en", "tingling in the right toes", [RTOER, NR]],
  ["en", "pain spreads across the lower back from one side to the other", [RBELT, LBAND]],
  ["en", "pain only in the back, nothing in the legs", [RNONE]],
  ["en", "lifted a heavy sack with my back rounded and heard a pop", [MLFLEX]],
  ["en", "twisting to throw something and felt a catch in my back", [MTWIST]],
  ["en", "started with a big cough", [MCOUGH]],
  ["en", "missed the last step on the stairs and jolted my spine", [MSTUMBLE]],
  ["en", "dived off a wall and landed on my back", [MFALLH, MFALLB]],
  ["en", "bike accident last month", [MMVA]],
  ["en", "pulled something at the gym doing squats", [MSPORT]],
  ["en", "years of slouching at a computer", [MPOST]],
  ["en", "after the disc operation the pain began", [MSURG]],
  ["en", "pregnancy and then labour, back pain ever since", [MPP]],
  ["en", "after a bad bout of flu", [MILL]],
  ["en", "no idea what caused it", [MNONE]],
  ["en", "bending forward over the bathroom basin to brush my teeth sets it off", [ABENT]],
  ["en", "sitting for about twenty five minutes and then it flares", [ASIT15]],
  ["en", "sitting for 40 minutes is my limit", [ASIT30]],
  ["en", "cant sit for two hours in the car", [ASIT60]],
  ["en", "standing in the kitchen for half an hour is too much", [ASTAND30]],
  ["en", "i cant stand for more than twenty minutes", [ASTAND15]],
  ["en", "any sitting at all makes it worse", [ASIT]],
  ["en", "even a few minutes of standing hurts", [ASTAND]],
  ["en", "sitting on low sofas is the worst", [ASOFT]],
  ["en", "pain when lying on my back", [ASUP]],
  ["en", "sleeping on my front is painful", [APRO]],
  ["en", "cant sleep on my left side", [ALL]],
  ["en", "the long drive to work kills me", [ADRIVE]],
  ["en", "reading in bed propped on pillows hurts", [AREADBED]],
  ["en", "sitting with my back rounded on the sofa", [ASLUMP]],
  ["en", "sitting sideways at my desk twisted to the monitor", [ATWIST]],
  ["en", "lying flat on the floor helps", [PFLAT]],
  ["en", "pillow under my knees makes lying comfortable", [PPILKNEE]],
  ["en", "lying on my side with my knees tucked together eases it", [PSIDEKN]],
  ["en", "lying on my front on a pillow helps", [PPRONE]],
  ["en", "extension on my elbows relieves it", [PELBOW]],
  ["en", "sitting on a firm chair is better", [PFIRM]],
  ["en", "shifting my weight onto one leg while standing helps", [PSHIFT]],
  ["en", "hands and knees takes the load off", [PALL4]],
  ["en", "constant ache with ups and downs through the day", [PCONSTVAR]],
  ["en", "pain only when I lift or carry", [PLOAD]],
  ["en", "comes on with certain movements and settles after", [PINTTRIG]],
  ["en", "worse in the evening after a day of work", [PEVE]],
  ["en", "bad in the mornings", [PMORN]],
  ["en", "stiff at first then eases after a few minutes of moving about", [PWARM]],
  ["en", "pain wakes me up in the early hours", [PSECOND, PNIGHT]],
  ["en", "no pattern whatsoever, it is random", [PNOPAT, PINTUNP]],
  ["en", "numbness down the whole left leg", [NL]],
  ["en", "pins and needles in both feet", [NBIL]],
  ["en", "my bladder and bowels were normal until this started", [BNORM]],
  ["en", "i had bladder problems for years before the pain", [BBLAD]],
  ["en", "constipation for years before this", [BBOWEL]],
  ["en", "cant remember if my bladder was normal before", [BUNC]],
  ["en", "numbness around the genitals and between the legs", [CSADDLE]],
  ["en", "unable to empty my bladder", [CRET]],
  ["en", "wetting myself without realising", [CINCB]],
  ["en", "bowel accident, soiled myself", [CINCW]],
  ["en", "weakness in both legs, new since yesterday", [CWEAK, NBIL]],
  ["en", "reduced anal tone on examination", [CTONE]],
  ["en", "weakness spreading rapidly in both legs over a few hours", [CPROG, CWEAK, NBIL]],
  ["en", "serious car crash at speed", [FRHIGH, MMVA]],
  ["en", "aged 78 and slipped on a rug", [FR70]],
  ["en", "she is on prednisolone long term", [FRSTER]],
  ["en", "had a vertebral fracture three years ago", [FRPREV]],
  ["en", "constant severe pain regardless of position or movement", [FRSEV, SCONST, PCONST]],
  ["en", "started when I was 22", [IFAGE]],
  ["en", "stiff for an hour every morning", [IFMORN, PMORN]],
  ["en", "gets better with exercise and worse with rest", [IFMOVE, IFREST]],
  ["en", "pain swaps from one buttock to the other", [IFALT]],
  ["en", "my brother has uveitis", [IFFAM]],
  ["en", "treated for ulcerative colitis", [IFIBD]],
  ["en", "had iritis last year", [IFUVE]],
  ["en", "swollen knees and ankles as well", [IFPERI]],
  ["en", "diclofenac gave complete relief within a day", [IFNSAID]],
  ["en", "hla b27 positive", [IFHLA]],
  ["en", "pain does not change with position, same all the time", [SCONST]],
  ["en", "the night pain is getting worse each week and wakes me", [SNIGHT, PNIGHT]],
  ["en", "pain between the shoulder blades as well as the low back", [STHOR]],
  ["en", "stomach pain along with the back pain", [SABD]],
  ["en", "lost weight without trying", [SWT]],
  ["en", "she had breast cancer in 2018", [SCA]],
  ["en", "a history of intravenous drug use", [SIV]],
  ["en", "had a chest infection recently", [SINF]],
  ["en", "fever and chills with the back pain", [SFEV]],
  ["en", "loin pain on the left", [SFLANK]],
  ["en", "cant bend to tie my shoelaces", [DSHOES, DBEND]],
  ["en", "cant pick things up off the floor", [DBEND]],
  ["en", "lifting the grandchildren is impossible", [DLIFTKID]],
  ["en", "cant carry the shopping home", [DLIFTSH]],
  ["en", "hoovering is a nightmare", [DVAC]],
  ["en", "getting out of the bath is hard", [DBATH]],
  ["en", "sex is limited by the pain", [DSEX]],
  ["en", "cannot do any gardening", [DGARD]],
  ["en", "housework is a struggle", [DHOUSE]],
  ["en", "bathing and dressing my baby is hard", [DCHILD]],
  ["en", "working full duties with a bit of an ache", [WMILD]],
  ["en", "working half days now", [WRED]],
  ["en", "off work for three months", [WMED]],
  ["en", "off sick for a year", [WLONG]],
  ["en", "lost my job because of the back", [WUNEMP]],
  ["en", "can never go back to my old job", [WUNABLE]],
  // ── must stay silent ──
  ["en", "left shoulder pain on reaching", []],
  ["en", "plantar fasciitis in the right foot", []],
  ["en", "her sister has back pain too", []],
  ["en", "my uncle had bowel cancer", []],
  ["en", "no bladder problems", []],
  ["en", "the clinic opens at nine", []],
  ["en", "cervical pain with arm tingling", []],
  ["en", "we will review in two weeks", []],
  ["en", "my friend fell off a ladder", []],
  ["en", "I am going to Delhi next week", []],
  // ── Hinglish ──
  ["hi", "kamar ke upar wale hisse me dard hai", [LUP]],
  ["hi", "kamar ke dayen taraf dard hota hai", [LPARR]],
  ["hi", "tailbone me dard baithne par", [LCOC, ASIT]],
  ["hi", "dard bayen chutad se jaangh ke peeche tak jata hai", [RPTL, RBUL]],
  ["hi", "dayen pair ke angoothe me jhunjhuni", [RTOER, NR]],
  ["hi", "talwe me jalan hoti hai", [RSOLE]],
  ["hi", "jhukkar bhaari cheez uthayi aur kamar me jhatka laga", [MLFLEX]],
  ["hi", "chheenk aane par dard shuru hua", [MCOUGH]],
  ["hi", "ek ghante se zyada baithne par dard", [ASIT60]],
  ["hi", "gaadi chalate waqt kamar dard badhta hai", [ADRIVE]],
  ["hi", "ulta lette to dard", [APRO]],
  ["hi", "dheere chalne se aaram milta hai", [PWALK]],
  ["hi", "ghutno ke neeche takiya rakhne se aaram", [PPILKNEE]],
  ["hi", "shaam ko dard zyada", [PEVE]],
  ["hi", "subah ek ghanta akdan rehti hai", [IFMORN, PMORN]],
  ["hi", "bayen pair me sunnpan hai", [NL]],
  ["hi", "peshab pe control nahi", [CINCB]],
  ["hi", "dono pair achanak kamzor ho gaye", [CWEAK, NBIL]],
  ["hi", "bukhar ke saath kamar dard", [SFEV]],
  ["hi", "pocha lagane me dikkat", [DVAC]],
  ["hi", "bistar se uthne me dikkat hoti hai", [DOUTBED]],
  ["hi", "do hafte se kaam par nahi gaya", [WSHORT]],
  ["hi", "mere padosi ki kamar me dard hai", []],
  ["hi", "pet me dard hai", [SABD]],
  ["hi", "kal meeting hai", []],
  // ── Hindi (Devanagari) ──
  ["de", "कमर के नीचे वाले हिस्से में दर्द", [LLOW]],
  ["de", "दाएं पैर की पिंडली तक दर्द जाता है", [RCAR]],
  ["de", "बैठने पर कमर दर्द बढ़ता है", [ASIT]],
  ["de", "गाड़ी चलाने में दिक्कत", [DDRIVE]],
  ["de", "रात को दर्द से नींद खुल जाती है", [PNIGHT]],
  ["de", "सुबह कमर अकड़ जाती है", [PMORN]],
  ["de", "पेशाब निकल जाता है", [CINCB]],
  ["de", "मेरे पिताजी को कैंसर था", []],
  ["de", "आज बहुत गर्मी है", []],
];
export const LUMBAR_SI_C = [
  // ── English ──
  ["en", "31F bank clerk with an ache in the lower back and left buttock, started after picking up her toddler while turning", [MLROT]],
  ["en", "sharp pain in the middle of the back at the beltline when I bend to put on my shoes", [LLOW, DSHOES]],
  ["en", "tenderness over the sacrum", [LSAC]],
  ["en", "pain at L5 S1", [LSJ]],
  ["en", "tight muscles on the left of the spine", [LPARL]],
  ["en", "he complains of pain on the right sit bone when he cycles", [LISCR]],
  ["en", "pain high up in the lumbar region just under the ribs", [LUP]],
  ["en", "pain around both SI joints, worse climbing stairs", [LSIB]],
  ["en", "pain radiates from the low back into the right groin", [RGRR]],
  ["en", "pain referred to the left buttock only", [RBUL]],
  ["en", "sciatic pain down the right leg to the calf", [RCAR]],
  ["en", "numbness and tingling in the left toes", [RTOEL, NL]],
  ["en", "pain on the inner side of the right shin", [RL4]],
  ["en", "pain stays above the knee on the left", [RKNL]],
  ["en", "she has pain in both legs", [RBIL]],
  ["en", "pain on the outside of the thigh", [RLAT]],
  ["en", "pain through the front of the right thigh", [RATR]],
  ["en", "felt something go in my back while deadlifting off the floor", [MLFLOOR, MSPORT]],
  ["en", "picked up a heavy bag with a twisted trunk", [MLROT]],
  ["en", "bent forward to get something from the car boot and felt a spasm", [MBEND]],
  ["en", "pain started after a coughing fit", [MCOUGH]],
  ["en", "pushing hard on the toilet", [MSTRAIN]],
  ["en", "fell backwards down two steps landing on my tailbone", [MFALLB, LCOC]],
  ["en", "fell from a scaffold at work", [MFALLH]],
  ["en", "hit by a car as a pedestrian last month", [MMVA]],
  ["en", "rugby injury", [MSPORT]],
  ["en", "driving a lorry for years", [MPOST]],
  ["en", "after lumbar fusion surgery", [MSURG]],
  ["en", "pain since my c section", [MPP]],
  ["en", "after a bout of typhoid", [MILL]],
  ["en", "it just crept up on me with no injury", [MINS]],
  ["en", "can sit only about twenty minutes before it hurts", [ASIT15]],
  ["en", "sitting beyond half an hour is a problem", [ASIT30]],
  ["en", "an hour in the car and my back is on fire", [ASIT60, ADRIVE]],
  ["en", "even five minutes of standing hurts", [ASTAND]],
  ["en", "standing for more than 15 minutes is difficult", [ASTAND15]],
  ["en", "standing over thirty minutes", [ASTAND30]],
  ["en", "sitting on an unsupported stool is the worst", [ASOFT]],
  ["en", "bed rest makes it worse", [PREST, IFREST]],
  ["en", "lying on my right side hurts", [ALR]],
  ["en", "cannot lie on my back", [ASUP]],
  ["en", "lying face down is painful", [APRO]],
  ["en", "slouched on the sofa is the worst", [ASLUMP]],
  ["en", "leaning over the kitchen counter for a long time", []],
  ["en", "reading propped up in bed hurts", [AREADBED]],
  ["en", "sitting for long hours in the car is awful", [ASIT60, ADRIVE]],
  ["en", "lying flat on my back eases the pain", [PFLAT]],
  ["en", "with my knees bent up on the bed it settles", [PCROOK]],
  ["en", "pillow between my knees at night helps", [PSIDEPIL]],
  ["en", "prone lying helps", [PPRONE]],
  ["en", "good lumbar support when sitting helps", [PSUPPORT]],
  ["en", "walking at an easy pace relieves it", [PWALK]],
  ["en", "leaning forward on a shopping trolley relieves it", [PLEAN]],
  ["en", "on all fours it eases", [PALL4]],
  ["en", "legs elevated on a stool gives relief", [PLEGSUP]],
  ["en", "weight shifted onto my left leg eases it", [PSHIFT]],
  ["en", "the pain never goes away", [PCONST]],
  ["en", "pain only on certain movements", [PINTTRIG]],
  ["en", "worst at the end of the day", [PEVE]],
  ["en", "wakes me every night", [PNIGHT]],
  ["en", "worse when I lie still", [PREST, IFREST]],
  ["en", "pain comes the day after exercise", [PDELAY]],
  ["en", "no pattern at all", [PNOPAT]],
  ["en", "no numbness in my legs", [NNO]],
  ["en", "tingling in the right leg", [NR]],
  ["en", "weakness in both feet", [NBIL]],
  ["en", "overactive bladder for years before this", [BBLAD]],
  ["en", "not asked about bladder yet", [BNOTASK]],
  ["en", "numbness in the perineum", [CSADDLE]],
  ["en", "urinary retention", [CRET]],
  ["en", "she leaks urine", [CINCB]],
  ["en", "faecal incontinence", [CINCW]],
  ["en", "both legs weak and giving way", [CWEAK, NBIL]],
  ["en", "loss of erections since the back pain started", [CSEX]],
  ["en", "new sciatica in both legs", [CBISC]],
  ["en", "bilateral deficits progressing rapidly", [CPROG]],
  ["en", "road traffic accident at high speed", [FRHIGH, MMVA]],
  ["en", "has osteoporosis and bumped into a table", [FROSTEO]],
  ["en", "88 year old who tripped and fell", [FR70]],
  ["en", "taking steroid tablets for years", [FRSTER]],
  ["en", "point tenderness over L3", [FRPOINT]],
  ["en", "she has been through the menopause and the pain came on suddenly", [FRPM]],
  ["en", "pain unaffected by anything I do, severe and unrelenting", [FRSEV, PCONST]],
  ["en", "onset at age 28", [IFAGE]],
  ["en", "it crept on over several months", [IFINS, MINS]],
  ["en", "morning stiffness lasts about 45 minutes", [IFMORN, PMORN]],
  ["en", "stiffness gets better after exercise", [IFMOVE]],
  ["en", "restless at night and have to get up and walk", [IFREST]],
  ["en", "pain moves from one buttock to the other", [IFALT]],
  ["en", "my dad has ankylosing spondylitis", [IFFAM]],
  ["en", "psoriatic arthritis", [IFPSO]],
  ["en", "ibd", [IFIBD]],
  ["en", "uveitis", [IFUVE]],
  ["en", "other joints are swollen as well", [IFPERI]],
  ["en", "naproxen works really well", [IFNSAID]],
  ["en", "elevated esr", [IFESR]],
  ["en", "pain unchanged by position", [SCONST]],
  ["en", "pain at night that is progressively worse", [SNIGHT, PNIGHT]],
  ["en", "upper back pain too", [STHOR]],
  ["en", "pain in the abdomen as well", [SABD]],
  ["en", "a pulsating mass in the stomach", [SAAA]],
  ["en", "losing weight without trying", [SWT]],
  ["en", "history of lung cancer", [SCA]],
  ["en", "injecting drugs", [SIV]],
  ["en", "recent urinary infection", [SINF]],
  ["en", "fever and sweats with back pain", [SFEV]],
  ["en", "pain in the loin on the left", [SFLANK]],
  ["en", "no inflammatory features", [IFNO]],
  ["en", "no other red flags", [SNO]],
  ["en", "no signs of cauda equina", [CNO]],
  ["en", "no fracture indicators", [FRNO]],
  ["en", "cant put on my shoes and socks", [DSHOES]],
  ["en", "bending to the floor is hard", [DBEND]],
  ["en", "cant lift the kids", [DLIFTKID]],
  ["en", "lifting shopping bags hurts", [DLIFTSH]],
  ["en", "cannot mop the floor", [DVAC]],
  ["en", "turning over in bed is painful", [DBEDMOB]],
  ["en", "difficulty getting out of bed", [DOUTBED]],
  ["en", "cant get in and out of the bath", [DBATH]],
  ["en", "cant drive any more", [DDRIVE]],
  ["en", "gardening is out", [DGARD]],
  ["en", "no work impact", [WNO]],
  ["en", "on light duties", [WMOD]],
  ["en", "off work for 2 weeks", [WSHORT]],
  ["en", "been off for 8 weeks", [WMED]],
  ["en", "unable to work for a year", [WLONG]],
  ["en", "i got dismissed because of my back", [WUNEMP]],
  // ── must stay silent ──
  ["en", "right now I am a bit tired", []],
  ["en", "her ankle was sprained at netball", []],
  ["en", "the shoulder is stiff in the mornings", []],
  ["en", "my mother had a hysterectomy", []],
  ["en", "no history of cancer in the family", []],
  ["en", "he is a bus driver", []],
  ["en", "I have to be at the clinic by 9", []],
  ["en", "her cousin has sciatica", []],
  ["en", "cervical radiculopathy on the left", []],
  ["en", "the forecast is rain tomorrow", []],
  // ── Hinglish ──
  ["hi", "kamar ke dono taraf dard hai", [LBAND]],
  ["hi", "bayen si joint me dard", [LSIL]],
  ["hi", "tailbone me dard", [LCOC]],
  ["hi", "dard dayen jaangh ke aage tak jata hai", [RATR]],
  ["hi", "dard bayen ghutne tak jata hai", [RKNL]],
  ["hi", "dono pairon me dard", [RBIL]],
  ["hi", "bina chot ke dheere dheere kamar dard shuru hua", [MINS]],
  ["hi", "zameen se bhaari saman uthate waqt kamar me jhatka", [MLFLOOR]],
  ["hi", "tees minute se zyada baithne par dard", [ASIT30]],
  ["hi", "khade rehne par dard", [ASTAND]],
  ["hi", "seedha let kar aaram milta hai", [PFLAT]],
  ["hi", "dheere dheere chalne se aaram milta hai", [PWALK]],
  ["hi", "raat ko neend khul jati hai dard se", [PNIGHT]],
  ["hi", "dayen pair me jhunjhuni", [NR]],
  ["hi", "pair sunn ho jate hain dono", [NBIL]],
  ["hi", "peshab karne me dikkat", [CRET]],
  ["hi", "potty pe control nahi", [CINCW]],
  ["hi", "pehle se peshab ki dikkat thi", [BBLAD]],
  ["hi", "bukhar aur kamar me dard", [SFEV]],
  ["hi", "bachche ko utha nahi pata", [DLIFTKID]],
  ["hi", "gaadi chalane me dikkat", [DDRIVE]],
  ["hi", "naukri chhoot gayi", [WUNEMP]],
  ["hi", "mere dost ko cancer tha", []],
  ["hi", "sir me dard hai", []],
  ["hi", "kal bazaar gaya tha", []],
  // ── Hindi (Devanagari) ──
  ["de", "कमर के ऊपर वाले हिस्से में दर्द", [LUP]],
  ["de", "दाएं पैर में सुन्नपन", [NR]],
  ["de", "खड़े रहने पर दर्द", [ASTAND]],
  ["de", "सुबह कमर अकड़ जाती है", [PMORN]],
  ["de", "पेशाब पर कंट्रोल नहीं", [CINCB]],
  ["de", "बच्चे को उठा नहीं पाता", [DLIFTKID]],
  ["de", "मेरी मौसी को कैंसर था", []],
  ["de", "घुटने में दर्द है", []],
];

export function score(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, want] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const wantSet = new Set(want);
    for (const g of got) { suggested++; if (wantSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of want) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
