// shoulderWildSets.js -- shared by the Shoulder phrase-matcher tests (not a test itself).
// Sets of messy, real-life sentences written the way students type, each marked with what a physio would
// tick ("field|option"). These answer keys are DRAFTS written by Claude for Aditi to review.
// A = the first exam, used to find what the first version missed; B = the fair exam, written after A's
// fixes and not tuned on afterwards. See each set's test file for its history.
import { SHOULDER_PHRASES, understandStory } from "../shoulderPhraseMap.js";

const O = (field, i) => Object.keys(SHOULDER_PHRASES[field])[i];
const k = (field, i) => `${field}|${O(field, i)}`;
// mechanism
const INSID = k("mechanism", 0), FALL = k("mechanism", 1), DIRECT = k("mechanism", 2), FORCED = k("mechanism", 3), REPOH = k("mechanism", 4),
  THROW = k("mechanism", 5), LIFTOH = k("mechanism", 6), POSTOP = k("mechanism", 7), AGE = k("mechanism", 8);
// aggravating
const OH = k("aggravating", 0), BEHIND = k("aggravating", 1), ACROSS = k("aggravating", 2), LYING = k("aggravating", 3), LIFT = k("aggravating", 4), ARC = k("aggravating", 5);
// relieving
const REST = k("relieving", 0), SUPPORT = k("relieving", 1), ICEHEAT = k("relieving", 2), MEDS = k("relieving", 3), AVOID = k("relieving", 4);
// pattern
const CONST = k("pattern", 0), INTER = k("pattern", 1), MORN = k("pattern", 2), NIGHT = k("pattern", 3), ACT = k("pattern", 4), IMPR = k("pattern", 5);
// radiation
const NORAD = k("radiation", 0), ELBOW = k("radiation", 1), HAND = k("radiation", 2), NECK = k("radiation", 3), BLADES = k("radiation", 4);
// red flags
const FRAC = k("redFlags", 0), CANTLIFT = k("redFlags", 1), PROGR = k("redFlags", 2), NIGHTPOS = k("redFlags", 3), MASS = k("redFlags", 4),
  INFECT = k("redFlags", 5), CANCER = k("redFlags", 6), RFNONE = k("redFlags", 7);
export const KEYS = { INSID, FALL, DIRECT, FORCED, REPOH, THROW, LIFTOH, POSTOP, AGE, OH, BEHIND, ACROSS, LYING, LIFT, ARC, REST, SUPPORT, ICEHEAT, MEDS, AVOID,
  CONST, INTER, MORN, NIGHT, ACT, IMPR, NORAD, ELBOW, HAND, NECK, BLADES, FRAC, CANTLIFT, PROGR, NIGHTPOS, MASS, INFECT, CANCER, RFNONE };

export const SHOULDER_A = [
  // ── English ──
  ["en", "pain in my right shoulder for 3 months, started after painting the ceiling at home", [REPOH]],
  ["en", "it hurts when I try to reach the top shelf", [OH]],
  ["en", "cannot sleep on the left side, the shoulder hurts at night", [LYING, NIGHT]],
  ["en", "fell off my bike on to the shoulder last week, now I cannot lift the arm at all", [FALL, CANTLIFT]],
  ["en", "I play cricket and throw a lot, the pain comes from throwing", [THROW]],
  ["en", "the pain goes all the way down to my fingers", [HAND]],
  ["en", "pain is only in the shoulder, it doesn't go anywhere else", [NORAD]],
  ["en", "it eases when I put a pillow under my arm", [SUPPORT]],
  ["en", "an ice pack helps a lot", [ICEHEAT]],
  ["en", "I take diclofenac and it settles", [MEDS]],
  ["en", "the pain started gradually, there was no injury", [INSID]],
  ["en", "it is worse in the morning when I wake up and feel stiff", [MORN]],
  ["en", "pain only when I use the arm, fine at rest", [ACT]],
  ["en", "there is a hard lump on my collarbone", [MASS]],
  ["en", "the shoulder looks red and feels hot", [INFECT]],
  ["en", "I had breast cancer five years ago and now I have shoulder pain", [CANCER]],
  ["en", "pain at the back between the shoulder blades", [BLADES]],
  ["en", "the pain goes up to the neck", [NECK]],
  ["en", "pain came back after rotator cuff surgery last year", [POSTOP]],
  ["en", "she is 70, I think it is just wear and tear", [AGE]],
  ["en", "it hurts when I reach behind my back to fasten my bra", [BEHIND]],
  ["en", "painful when I reach across to the other shoulder", [ACROSS]],
  ["en", "I get pain halfway when I lift my arm out to the side, then it is fine", [ARC]],
  ["en", "constant pain getting worse every day, nothing eases it and it is not related to movement", [PROGR, CONST]],
  ["en", "at night the pain is there in whatever position I lie", [NIGHTPOS, NIGHT]],
  ["en", "someone yanked my arm hard while I was holding the dog leash", [FORCED]],
  ["en", "lifted a heavy suitcase into the overhead locker on a flight and felt a pop", [LIFTOH]],
  ["en", "got tackled in rugby, landed on the shoulder, it looks deformed", [FALL, DIRECT, FRAC]],
  ["en", "no history of cancer, no night pain, no red flags", [RFNONE]],
  ["en", "the pain is on and off", [INTER]],
  ["en", "it improves as the day goes on", [IMPR]],
  ["en", "I cannot lift anything heavy, it hurts to carry bags", [LIFT]],
  ["en", "pain when lying on that shoulder", [LYING]],
  ["en", "pain down to the elbow", [ELBOW]],
  ["en", "sleeping in a sling pillow arrangement keeps the arm supported and it feels better", [SUPPORT]],
  ["en", "hot water bag relieves it", [ICEHEAT]],
  // ── must stay silent ──
  ["en", "my knee hurts when I climb stairs", []],
  ["en", "lower back pain is worse in the morning", []],
  ["en", "the shoulder bag was heavy", []],
  ["en", "he shoulders a lot of responsibility at work", []],
  ["en", "I will carry the shoulder pads tomorrow", []],
  ["en", "I do not have any fracture or lump", []],
  ["en", "the pain is not there at night", []],
  ["en", "no numbness or tingling in the hand", []],
  ["en", "my friend has a frozen shoulder", []],
  ["en", "my grandfather had cancer", []],
  ["en", "the patient was told to avoid heavy lifting", []],
  ["en", "I have a headache and a cold", []],
  ["en", "the match was played in the morning", []],
  ["en", "please send the report by tonight", []],
  // ── Hinglish ──
  ["hi", "kandhe me dard hai jab haath upar karta hoon", [OH]],
  ["hi", "raat ko kandhe me dard hota hai aur us taraf let nahi pata", [NIGHT, LYING]],
  ["hi", "badminton khelte waqt kandhe me dard", [THROW]],
  ["hi", "peeche haath le jane me dard hota hai", [BEHIND]],
  ["hi", "gir ke kandha utar gaya tha", [FALL, FRAC]],
  ["hi", "dard kohni tak aata hai", [ELBOW]],
  ["hi", "dard gardan tak jata hai", [NECK]],
  ["hi", "sekai se aaram milta hai", [ICEHEAT]],
  ["hi", "dawai khane se dard kam hota hai", [MEDS]],
  ["hi", "aaram karne se theek ho jata hai", [REST]],
  ["hi", "bhari saman uthane se dard badh jata hai", [LIFT]],
  ["hi", "operation ke baad se kandhe me dard hai", [POSTOP]],
  ["hi", "umar ke saath ghisav ki wajah se hai", [AGE]],
  ["hi", "subah uthte hi kandha jakad jata hai", [MORN]],
  ["hi", "lagatar dard rehta hai, din raat", [CONST]],
  ["hi", "kabhi kabhi dard hota hai", [INTER]],
  ["hi", "kandhe me gaanth jaisa kuch hai", [MASS]],
  ["hi", "pehle cancer hua tha", [CANCER]],
  ["hi", "kandha laal aur garam hai", [INFECT]],
  ["hi", "bina chot ke dheere dheere dard shuru hua", [INSID]],
  ["hi", "dono kandhon ke beech dard", [BLADES]],
  ["hi", "dard ungliyon tak jata hai, jhunjhuni bhi hai", [HAND]],
  ["hi", "ghutne me dard hai", []],
  ["hi", "kamar dard raat ko zyada hota hai", []],
  ["hi", "kandhe me dard nahi hai", []],
  // ── Hindi (Devanagari) ──
  ["de", "कंधे में दर्द है और हाथ ऊपर करने में दर्द", [OH]],
  ["de", "रात को दर्द और करवट लेने में दर्द", [NIGHT, LYING]],
  ["de", "गिरने के बाद हाथ ऊपर नहीं उठ रहा", [CANTLIFT, FALL]],
  ["de", "गर्दन तक दर्द जाता है", [NECK]],
  ["de", "सिकाई से आराम मिलता है", [ICEHEAT]],
  ["de", "कंधे में गांठ है", [MASS]],
  ["de", "ऑपरेशन के बाद से कंधे में दर्द", [POSTOP]],
  ["de", "दोनों कंधों के बीच दर्द", [BLADES]],
  ["de", "बिना चोट के अपने आप शुरू हुआ", [INSID]],
  ["de", "टेनिस खेलने से कंधे में दर्द", [THROW]],
  ["de", "आज रात बारिश होगी", []],
  // ── mixed ──
  ["mx", "shoulder me pain hai jab overhead kaam karta hoon", [OH, REPOH]],
  ["mx", "rotator cuff ka operation hua tha 1 saal pehle", [POSTOP]],
];

// Set B: the fair exam. Written after Set A had been used to improve the matcher, and NOT used to tune it afterwards.
export const SHOULDER_B = [
  // ── English ──
  ["en", "left shoulder pain after gym, I think from too many overhead presses", [LIFTOH]],
  ["en", "stiff and sore every morning for the first hour", [MORN]],
  ["en", "the pain wakes me up around 3am", [NIGHT]],
  ["en", "I cannot comb my hair", [OH]],
  ["en", "pain when I wash my back in the shower", [BEHIND]],
  ["en", "it hurts if I put my hand in the back pocket", [BEHIND]],
  ["en", "it radiates down to my elbow sometimes", [ELBOW]],
  ["en", "tingling in my fingers and the pain shoots down the arm", [HAND]],
  ["en", "fell from the stairs on my right shoulder", [FALL]],
  ["en", "got hit by a cricket ball on the shoulder", [DIRECT]],
  ["en", "I swim 5 km a week and the pain comes in freestyle", [REPOH]],
  ["en", "she is a painter and works with her arms above her head", [REPOH]],
  ["en", "I had a dislocation two years ago, it is fine now", []],
  ["en", "heat pad in the evening gives relief", [ICEHEAT]],
  ["en", "ibuprofen helps", [MEDS]],
  ["en", "it gets worse when I carry my daughter", [LIFT]],
  ["en", "the pain never goes away", [CONST]],
  ["en", "occasional twinges, otherwise fine", [INTER]],
  ["en", "pain only comes after I play badminton", [ACT, THROW]],
  ["en", "I had a rotator cuff repair 6 months back", [POSTOP]],
  ["en", "age 68, degenerative changes on the X-ray", [AGE]],
  ["en", "the pain appeared out of nowhere, nothing I did", [INSID]],
  ["en", "weeks of a slowly building ache, no accident", [INSID]],
  ["en", "there is a swelling like a ball on top of my shoulder", [MASS]],
  ["en", "my shoulder is swollen, hot and red, and I have a fever", [INFECT]],
  ["en", "my mom had breast cancer, I have no history", []],
  ["en", "treated for lymphoma in 2019", [CANCER]],
  ["en", "pain at night in any position, I cannot get comfortable", [NIGHT, NIGHTPOS]],
  ["en", "the pain is the same whether I move or not and it keeps increasing", [PROGR]],
  ["en", "the doctor said it is a fracture of the collar bone", [FRAC]],
  ["en", "I fell and my arm is hanging, I can't move it", [FALL, CANTLIFT]],
  ["en", "pain when I turn over in bed onto that side", [LYING]],
  ["en", "I cannot lie on the right side", [LYING]],
  ["en", "a sling gave relief", [SUPPORT]],
  ["en", "relief when I avoid lifting the arm up", [AVOID]],
  ["en", "pain when throwing a javelin", [THROW]],
  ["en", "since the surgery on my shoulder I have had this pain", [POSTOP]],
  ["en", "painful arc when abducting the arm", [ARC]],
  ["en", "my tennis serve causes pain", [THROW]],
  ["en", "right after the fall I heard a crack", [FRAC]],
  // ── must stay silent ──
  ["en", "my elbow hurts when I grip a cup", []],
  ["en", "my ankle sprained last month", []],
  ["en", "hip pain at night", []],
  ["en", "I was at the hospital last night", []],
  ["en", "he was hit by criticism from the boss", []],
  ["en", "lifting weights is my hobby", []],
  ["en", "shoulder surgery is scheduled for next week", []],
  ["en", "no pain at night", []],
  ["en", "cancer awareness month starts today", []],
  ["en", "my father is a cancer patient", []],
  ["en", "she lifted the baby easily", []],
  ["en", "the sling bag is on the table", []],
  ["en", "the pain in my back is constant", []],
  ["en", "my knee gets stiff in the morning", []],
  ["en", "he does not play tennis any more", []],
  ["en", "I did not fall and I was not hit", []],
  ["en", "no lump, no redness", []],
  // ── Hinglish ──
  ["hi", "kandha bahut dukhta hai jab haath peeche karta hoon", [BEHIND]],
  ["hi", "kandhe me haath upar uthate hi dard hota hai", [OH]],
  ["hi", "raat ko sote waqt kandhe me dard se neend khul jati hai", [NIGHT]],
  ["hi", "cricket me bowling karne ke baad se dard shuru hua", [THROW]],
  ["hi", "pehle gir gaya tha scooter se, kandhe pe chot lagi", [FALL, DIRECT]],
  ["hi", "garam paani ki bottle se sikai karne par aaram milta hai", [ICEHEAT]],
  ["hi", "dard ki goli lene par thoda aaram milta hai", [MEDS]],
  ["hi", "aaram karta hoon to dard kam ho jata hai", [REST]],
  ["hi", "haath ko takiya pe rakhne se aaram", [SUPPORT]],
  ["hi", "upar ke kaam band kar diye to dard kam hua", [AVOID]],
  ["hi", "kandhe se kohni tak shooting dard", [ELBOW]],
  ["hi", "haath me jhunjhuni aur sunnpan hai", [HAND]],
  ["hi", "dard sirf kandhe me hai, kahin aur nahi jata", [NORAD]],
  ["hi", "peeth me beech me, dono shoulder blade ke paas dard", [BLADES]],
  ["hi", "raat ko dard zyada hota hai", [NIGHT]],
  ["hi", "dard har waqt rehta hai", [CONST]],
  ["hi", "subah ke waqt zyada akdan hoti hai", [MORN]],
  ["hi", "din me kaam karte waqt hi dard hota hai", [ACT]],
  ["hi", "operation ke 2 mahine baad dard shuru hua", [POSTOP]],
  ["hi", "pehle breast cancer ka operation hua tha", [CANCER]],
  ["hi", "kandhe me ubhaar sa dikh raha hai", [MASS]],
  ["hi", "kandha laal ho gaya hai aur chhune par garam lagta hai", [INFECT]],
  ["hi", "kandhe me dard ke saath bukhar bhi hai", []],
  ["hi", "chot nahi lagi thi, apne aap dard hua", [INSID]],
  ["hi", "bahut pehle ghutne ka operation hua tha", []],
  ["hi", "mere dada ko cancer tha", []],
  ["hi", "kal meeting subah 10 baje hai", []],
  // ── Hindi (Devanagari) ──
  ["de", "हाथ पीछे ले जाने में कंधे में बहुत दर्द होता है", [BEHIND]],
  ["de", "ऊपर की अलमारी से सामान निकालते समय दर्द", [OH]],
  ["de", "सोते समय उस तरफ करवट लेने पर दर्द", [LYING]],
  ["de", "सुबह उठने पर कंधा अकड़ जाता है", [MORN]],
  ["de", "गिरने के बाद कंधा बहुत टेढ़ा दिख रहा है", [FALL, FRAC]],
  ["de", "दर्द उंगलियों तक आता है और हाथ सुन्न हो जाता है", [HAND]],
  ["de", "गर्म सिकाई से राहत मिलती है", [ICEHEAT]],
  ["de", "दवा लेने के बाद दर्द कम होता है", [MEDS]],
  ["de", "आराम करने से दर्द कम हो जाता है", [REST]],
  ["de", "रात को दर्द के कारण नींद नहीं आती", [NIGHT]],
  ["de", "कंधे में गांठ जैसा कुछ महसूस होता है", [MASS]],
  ["de", "कैंसर का इलाज चल रहा है", [CANCER]],
  ["de", "टांग में दर्द है", []],
];

// Set C: a second fair exam, written after Set B's fixes. Its first run is the best estimate of how the matcher does
// on typing it has never seen; it was used to improve the matcher only afterwards (see shoulderPhraseMapWild.test.js).
export const SHOULDER_C = [
  // ── English ──
  ["en", "I injured it playing volleyball, smashing the ball repeatedly", [THROW]],
  ["en", "pain when I put on a coat, especially when the arm goes behind", [BEHIND]],
  ["en", "unable to sleep on my right side at all", [LYING]],
  ["en", "morning stiffness lasting around half an hour", [MORN]],
  ["en", "pain only when I swing the racquet", [ACT]],
  ["en", "the pain radiates into the forearm and hand with pins and needles", [HAND]],
  ["en", "I get discomfort at the base of my neck and top of the shoulder", []],
  ["en", "shoulder replaced two years ago and the pain is back", [POSTOP]],
  ["en", "pain with reaching for the seatbelt", [ACROSS]],
  ["en", "pain when I raise my arm to put the dishes on the shelf", [OH]],
  ["en", "my shoulder feels tight and painful on waking", [MORN]],
  ["en", "the pain is dull and there all the time", [CONST]],
  ["en", "it comes and goes depending on what I do", [INTER]],
  ["en", "had a bad fall from a horse last month, landed hard on my right shoulder", [FALL]],
  ["en", "there was no particular incident, it just crept up", [INSID]],
  ["en", "shoulder pain started after I hung heavy curtains", [REPOH]],
  ["en", "holding my elbow with the other hand helps", [SUPPORT]],
  ["en", "pain is relieved with a warm shower", [ICEHEAT]],
  ["en", "ibuprofen and paracetamol take the edge off", [MEDS]],
  ["en", "I just rest it and it gets better in two days", [REST]],
  ["en", "if I avoid reaching up the pain settles", [AVOID]],
  ["en", "there is a large lump near the armpit", [MASS]],
  ["en", "history of thyroid cancer", [CANCER]],
  ["en", "my wife has cancer", []],
  ["en", "the pain wakes me at night no matter how I lie", [NIGHT, NIGHTPOS]],
  ["en", "the arm feels dead after the fall and I can't raise it", [FALL, CANTLIFT]],
  ["en", "I heard a pop and then there was a deformity", [FRAC]],
  ["en", "constant severe pain that keeps getting worse, even resting does not help", [PROGR, CONST]],
  ["en", "red, warm and swollen area over the joint", [INFECT]],
  ["en", "no history of cancer or fractures", []],
  ["en", "lifted a heavy box overhead at work and felt something tear", [LIFTOH]],
  ["en", "shoulder pain after bowling long spells in cricket", [THROW]],
  ["en", "pain on throwing", [THROW]],
  ["en", "pain when I shampoo my hair", [OH]],
  // ── must stay silent ──
  ["en", "I have tennis elbow in my right arm", []],
  ["en", "my back hurts when I sit for long", []],
  ["en", "I went swimming on Sunday and had fun", []],
  ["en", "the physiotherapist asked me to lift my arm", []],
  ["en", "no pain in the other shoulder", []],
  ["en", "my neck is stiff in the morning", []],
  ["en", "my sister had a shoulder surgery", []],
  ["en", "he works at a cancer hospital", []],
  ["en", "I felt happy after the match", []],
  ["en", "the knee pain is worse at night", []],
  ["en", "please bring the sling bag", []],
  ["en", "I fell asleep on the sofa", []],
  // ── Hinglish ──
  ["hi", "kandhe me dard hai jab main kapde sukhane ke liye haath upar karta hoon", [OH]],
  ["hi", "peeche se haath ghumane par dard", [BEHIND]],
  ["hi", "dard raat ko kisi bhi taraf let ne par kam nahi hota", [NIGHT, NIGHTPOS]],
  ["hi", "badminton khelte waqt smash maarne se dard shuru hua", [THROW]],
  ["hi", "volleyball khelte hue gir gaya, kandhe me chot", [FALL, DIRECT]],
  ["hi", "dard kandhe se haath tak aur ungliyon tak jata hai", [HAND]],
  ["hi", "kohni tak dard utarta hai", [ELBOW]],
  ["hi", "dawa lene se thoda aaram milta hai", [MEDS]],
  ["hi", "garam sek se kaafi aaram", [ICEHEAT]],
  ["hi", "baju ke niche takiya rakhne se theek lagta hai", [SUPPORT]],
  ["hi", "haath upar na karne se dard nahi hota", [AVOID]],
  ["hi", "kandhe me ek gaanth si mehsoos ho rahi hai", [MASS]],
  ["hi", "mummy ko cancer tha, mujhe kandhe me dard hai", []],
  ["hi", "operation ke baad kandha jam gaya hai", [POSTOP]],
  ["hi", "umar ho gayi hai isliye dard rehta hai", [AGE]],
  ["hi", "subah sabse zyada dard hota hai", [MORN]],
  ["hi", "kabhi hota hai kabhi nahi", [INTER]],
  ["hi", "gir gaya tha seedhe kandhe ke upar", [FALL]],
  ["hi", "ghutne me dard hai, kandha theek hai", []],
  ["hi", "doctor ne bola fracture hai", [FRAC]],
  ["hi", "kal gym jaunga", []],
  ["hi", "barish ho rahi hai", []],
  // ── Hindi (Devanagari) ──
  ["de", "कंधे में दर्द है और हाथ पीछे ले जाने में तकलीफ", [BEHIND]],
  ["de", "दर्द कोहनी तक आता है", [ELBOW]],
  ["de", "सोने पर उस कंधे पर दबाव पड़ने से दर्द", [LYING]],
  ["de", "सुबह सबसे ज्यादा दर्द रहता है", [MORN]],
  ["de", "रात को दर्द बढ़ जाता है", [NIGHT]],
  ["de", "लगातार दर्द रहता है", [CONST]],
  ["de", "कभी कभी दर्द होता है", [INTER]],
  ["de", "गिरने से कंधे की हड्डी टूट गई", [FALL, FRAC]],
  ["de", "बर्फ लगाने से आराम मिलता है", [ICEHEAT]],
  ["de", "कंधे में सूजन और लालिमा है और गर्म लगता है", [INFECT]],
  ["de", "मेरी मां को कैंसर था", []],
  ["de", "कंधे का एक्सरे नॉर्मल है", []],
  ["de", "बारिश में बाहर नहीं गया", []],
];

export function score(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, want] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const wantSet = new Set(want);
    for (const g of got) { suggested++; if (wantSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of want) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
