// shoulderSheetSet.js -- the sentences of the Shoulder "everyday words" sheet (PhysioMind-Shoulder-Everyday-Words-DRAFT.pdf), written the way the
// CLINICIAN would type about the patient ("the patient", "they", short notes): English in four styles, Hinglish and Hindi, for all 10
// conditions. Used by shoulderSheetSet.test.js (not a test itself). Row = [lang, text, must, may]:
//   must = options a physio would tick from that sentence (a miss costs recall)
//   may  = options that are also fair to suggest (neither right nor wrong: they do not count against precision)
//   anything else it suggests counts as wrong. A sentence with no must and no may must stay silent.
// lang: en = English, hi = Hinglish (Hindi in Latin letters), de = Hindi in Devanagari. The answer keys are DRAFTS written by Claude
// for Aditi to check. The Shoulder form has no question for how it started or how long as such, so those lines only count where a sentence also says something a form question covers.
import { KEYS } from "./shoulderWildSets.js";
import { understandStory } from "../shoulderPhraseMap.js";

const { ACROSS, AGE, ARC, BEHIND, CANTLIFT, CONST, DIRECT, ELBOW, FALL, FORCED, FRAC, HAND, INSID, INTER, LIFT, LIFTOH, LYING, MORN, NECK, NIGHT, OH, POSTOP, REPOH, THROW } = KEYS;

export const SHOULDER_SHEET = [
  ["en", "The patient has pain on lifting the arm overhead, with a painful arc through the middle of the movement.", [OH, ARC], [LYING, NIGHT, LIFT]],
  ["en", "They say it hurts to reach up to a shelf, and the arm is sore halfway as it goes up to the side.", [OH, ARC], [LYING, NIGHT, LIFT]],
  ["en", "Overhead reaching painful. Painful arc mid-range.", [OH, ARC], [LYING, NIGHT, LIFT]],
  ["en", "It catches them when they reach up to put things on the top shelf. Raising the arm out to the side hurts halfway up and eases near the top.", [OH, ARC], [LYING, NIGHT, LIFT]],
  ["hi", "Haath upar uthane par kandhe mein dard, aadhe raste mein dard (painful arc).", [OH, ARC], [LYING, NIGHT, LIFT]],
  ["de", "हाथ ऊपर उठाने पर कंधे में दर्द, बीच में (आधे रास्ते) ज्यादा दर्द।", [OH, ARC], [LYING, NIGHT, LIFT]],
  ["en", "Gradual onset, no injury.", [INSID], []],
  ["en", "It crept up over a few weeks without any fall or injury.", [INSID], []],
  ["en", "Gradual. No trauma.", [INSID], []],
  ["en", "No single event. It built up slowly over a month or two and has not settled.", [INSID], []],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [INSID], []],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [INSID], []],
  ["en", "Repeated overhead work or sport, such as painting, swimming or racquet games.", [REPOH], [INSID]],
  ["en", "A lot of overhead work, painting the ceiling and putting things on high shelves, and swimming as well.", [REPOH], [INSID]],
  ["en", "Repetitive overhead activity. Overuse.", [REPOH], [INSID]],
  ["en", "They have been painting the house this month, mostly the ceiling, and swimming more than usual.", [REPOH], [INSID]],
  ["hi", "Upar haath karke bahut kaam kiya, chhat ki putai, tairna.", [REPOH], [INSID]],
  ["de", "ऊपर हाथ करके बहुत काम किया, छत की पुताई, तैराकी।", [REPOH], [INSID]],
  ["en", "Weeks to a few months.", [], []],
  ["en", "It has been there for about six weeks.", [], []],
  ["en", "6 weeks.", [], []],
  ["en", "On and off since the winter, so roughly three months.", [], [INTER]],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has pain when lifting objects and when lying on the affected shoulder at night.", [LIFT, LYING], [OH, NIGHT, ELBOW]],
  ["en", "It hurts when they lift anything, and at night they cannot lie on that shoulder.", [LIFT, LYING], [OH, NIGHT, ELBOW]],
  ["en", "Pain with lifting. Cannot lie on the shoulder at night.", [LIFT, LYING], [OH, NIGHT, ELBOW]],
  ["en", "Carrying the shopping bag and picking up the kettle hurt the shoulder now, and lying on that side keeps them awake.", [LIFT, LYING], [OH, NIGHT, ELBOW]],
  ["hi", "Kuch uthane par kandhe mein dard, raat ko us kandhe par letna mushkil.", [LIFT, LYING], [OH, NIGHT, ELBOW]],
  ["de", "कुछ उठाने पर कंधे में दर्द, रात को उस कंधे पर लेटना मुश्किल।", [LIFT, LYING], [OH, NIGHT, ELBOW]],
  ["en", "Gradual onset over weeks, no injury.", [INSID], [AGE]],
  ["en", "It came on slowly without any fall.", [INSID], [AGE]],
  ["en", "Gradual, no trauma.", [INSID], [AGE]],
  ["en", "It built up over a couple of months, no injury at all.", [INSID], [AGE]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [INSID], [AGE]],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [INSID], [AGE]],
  ["en", "Repeated overhead use at work or in sport.", [REPOH], [INSID, THROW, AGE]],
  ["en", "A lot of overhead work, mostly lifting boxes onto shelves and painting.", [REPOH], [INSID, THROW, AGE]],
  ["en", "Overuse. Repetitive overhead work.", [REPOH], [INSID, THROW, AGE]],
  ["en", "They paint ceilings for a living and the shoulder has been getting worse over the season.", [REPOH], [INSID, THROW, AGE]],
  ["hi", "Roz upar haath karke kaam, chhat ki putai.", [REPOH], [INSID, THROW, AGE]],
  ["de", "रोज ऊपर हाथ करके काम, छत की पुताई।", [REPOH], [INSID, THROW, AGE]],
  ["en", "A few months.", [], []],
  ["en", "About three months now.", [], []],
  ["en", "3 months.", [], []],
  ["en", "Slowly worse since the start of the year.", [], []],
  ["hi", "Kuch mahino se.", [], []],
  ["de", "कुछ महीनों से।", [], []],
  ["en", "The patient fell on the outstretched hand and now cannot lift the arm.", [FALL, CANTLIFT], [FRAC, LYING, NIGHT]],
  ["en", "They fell on their hand, and since then they just cannot raise the arm up.", [FALL, CANTLIFT], [FRAC, LYING, NIGHT]],
  ["en", "Fall on outstretched hand. Cannot lift the arm.", [FALL, CANTLIFT], [FRAC, LYING, NIGHT]],
  ["en", "A few days ago they slipped on the stairs and put the hand out to save themselves. The arm has been hanging and they cannot lift it at all.", [FALL, CANTLIFT], [FRAC, LYING, NIGHT]],
  ["hi", "Haath tek kar gir gaye, ab haath upar nahi utha pa rahe.", [FALL, CANTLIFT], [FRAC, LYING, NIGHT]],
  ["de", "हाथ टेककर गिर गए, अब हाथ ऊपर नहीं उठा पा रहे।", [FALL, CANTLIFT], [FRAC, LYING, NIGHT]],
  ["en", "Sudden onset after a fall.", [FALL], [FRAC, LIFT]],
  ["en", "It started straight away when they fell.", [FALL], [FRAC, LIFT]],
  ["en", "Sudden, after a fall.", [FALL], [FRAC, LIFT]],
  ["en", "It all began at the moment they fell on the stairs, nothing before that.", [FALL], [FRAC, LIFT]],
  ["hi", "Girne ke turant baad achanak shuru hua.", [FALL], [FRAC, LIFT]],
  ["de", "गिरने के तुरंत बाद अचानक शुरू हुआ।", [FALL], [FRAC, LIFT]],
  ["en", "Heavy lift overhead, with a sudden pop in the shoulder.", [LIFTOH], [FALL, FORCED, AGE]],
  ["en", "They lifted a heavy box onto the top shelf and felt something go in the shoulder.", [LIFTOH], [FALL, FORCED, AGE]],
  ["en", "Heavy overhead lift. Felt a pop.", [LIFTOH], [FALL, FORCED, AGE]],
  ["en", "They were putting a heavy suitcase onto the cupboard and felt a sudden tear in the shoulder, with weakness since.", [LIFTOH], [FALL, FORCED, AGE]],
  ["hi", "Almari par bhaari suitcase rakhte waqt kandhe mein achanak kuch fata.", [LIFTOH], [FALL, FORCED, AGE]],
  ["de", "अलमारी पर भारी सूटकेस रखते समय कंधे में अचानक कुछ फटा।", [LIFTOH], [FALL, FORCED, AGE]],
  ["en", "A few days to a few weeks.", [], []],
  ["en", "It happened last week and has not improved.", [], []],
  ["en", "1 week, no improvement.", [], []],
  ["en", "It has been three weeks since the fall and the arm is no better.", [], [FALL]],
  ["hi", "Pichle hafte se.", [], []],
  ["de", "पिछले हफ्ते से।", [], []],
  ["en", "The patient cannot reach behind the back and the shoulder aches badly at night.", [BEHIND, NIGHT], [OH, LYING, CONST]],
  ["en", "They can't reach behind to tuck in a shirt or fasten a bra, and the shoulder hurts most at night.", [BEHIND, NIGHT], [OH, LYING, CONST]],
  ["en", "Cannot reach behind back. Worse at night.", [BEHIND, NIGHT], [OH, LYING, CONST]],
  ["en", "It has become very stiff. Reaching behind the back is almost impossible now, and the night pain wakes them up.", [BEHIND, NIGHT], [OH, LYING, CONST]],
  ["hi", "Peeche haath nahi ja pata, raat ko kandhe mein bahut dard.", [BEHIND, NIGHT], [OH, LYING, CONST]],
  ["de", "पीछे हाथ नहीं जा पाता, रात को कंधे में बहुत दर्द।", [BEHIND, NIGHT], [OH, LYING, CONST]],
  ["en", "Gradual onset with no injury.", [INSID], [AGE]],
  ["en", "It crept in slowly over a few months, no fall or injury.", [INSID], [AGE]],
  ["en", "Gradual, no trauma.", [INSID], [AGE]],
  ["en", "It started as a mild ache and slowly got stiffer, with no accident at all.", [INSID], [AGE]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [INSID], [AGE]],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [INSID], [AGE]],
  ["en", "No clear cause, or after a period of keeping the arm still, such as after surgery.", [INSID, POSTOP], [AGE]],
  ["en", "Nothing they can think of, or it began after the arm was kept in a sling.", [INSID], [POSTOP, AGE]],
  ["en", "No cause. Or post immobilisation.", [INSID], [POSTOP, AGE]],
  ["en", "They are not sure how it began. It might be since the arm was kept in a sling after the fracture, and then diabetes may play a part.", [INSID], [POSTOP, AGE]],
  ["hi", "Kaaran pata nahi, ya sling ke baad shuru hua.", [INSID], [POSTOP, AGE]],
  ["de", "कारण पता नहीं, या स्लिंग के बाद शुरू हुआ।", [INSID], [POSTOP, AGE]],
  ["en", "Several months, often a year or more.", [], []],
  ["en", "It has been getting worse over about five months.", [], []],
  ["en", "5 months.", [], []],
  ["en", "Slowly worse for the last eight months, no sign of getting better.", [], []],
  ["hi", "Kai mahino se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "The patient has pain at the top of the shoulder on reaching across the body.", [ACROSS], [LYING, LIFT, OH]],
  ["en", "It hurts right on top of the shoulder when they reach across the body.", [ACROSS], [LYING, LIFT, OH]],
  ["en", "Pain on top of shoulder. Worse reaching across body.", [ACROSS], [LYING, LIFT, OH]],
  ["en", "They say the pain is just at the end of the collarbone, and it is worst when the arm goes across the chest, like when putting on a seatbelt.", [ACROSS], [LYING, LIFT, OH]],
  ["hi", "Kandhe ke upar dard, haath seene ke aar-paar le jane par badhta hai.", [ACROSS], [LYING, LIFT, OH]],
  ["de", "कंधे के ऊपर दर्द, हाथ सीने के आर-पार ले जाने पर बढ़ता है।", [ACROSS], [LYING, LIFT, OH]],
  ["en", "Sudden, after a fall onto the shoulder.", [FALL], [DIRECT, INSID]],
  ["en", "It started when they fell on the shoulder.", [FALL], [DIRECT, INSID]],
  ["en", "Sudden. Fall on the shoulder.", [FALL], [DIRECT, INSID]],
  ["en", "It began the day they came off the bike and landed on the point of the shoulder.", [FALL], [DIRECT, INSID]],
  ["hi", "Kandhe ke bal girne ke baad achanak shuru hua.", [FALL], [DIRECT, INSID]],
  ["de", "कंधे के बल गिरने के बाद अचानक शुरू हुआ।", [FALL], [DIRECT, INSID]],
  ["en", "Fall onto the point of the shoulder, or a direct blow in contact sport.", [FALL, DIRECT], []],
  ["en", "They landed hard on the shoulder when they fell off the bike.", [FALL], [DIRECT]],
  ["en", "Fall on the shoulder. Direct blow.", [FALL, DIRECT], []],
  ["en", "They were tackled in rugby and took a heavy hit onto the shoulder. The top of it has been sore since.", [DIRECT], [FALL]],
  ["hi", "Kandhe ke bal gir gaye, ya kandhe par chot lagi.", [FALL, DIRECT], []],
  ["de", "कंधे के बल गिर गए, या कंधे पर चोट लगी।", [FALL, DIRECT], []],
  ["en", "Days to weeks.", [], []],
  ["en", "It happened three weeks ago and is still sore.", [], []],
  ["en", "3 weeks.", [], []],
  ["en", "It was fine for a while and then flared again over the last month.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has pain at the front of the shoulder when reaching overhead and lifting.", [OH, LIFT], [BEHIND, ARC]],
  ["en", "It hurts at the front of the shoulder when they reach up high or lift anything.", [OH, LIFT], [BEHIND, ARC]],
  ["en", "Anterior shoulder pain. Overhead and lifting.", [OH, LIFT], [BEHIND, ARC]],
  ["en", "The ache at the front of the shoulder comes when they reach up and when they lift weights, and sometimes the shoulder clicks.", [OH, LIFT], [BEHIND, ARC]],
  ["hi", "Kandhe ke aage dard, upar haath uthane aur kuch uthane par badhta hai.", [OH, LIFT], [BEHIND, ARC]],
  ["de", "कंधे के आगे दर्द, ऊपर हाथ उठाने और कुछ उठाने पर बढ़ता है।", [OH, LIFT], [BEHIND, ARC]],
  ["en", "Overhead throwing, or a sudden pull on the arm.", [THROW, FORCED], [INSID, FALL]],
  ["en", "They throw a lot, or something yanked the arm suddenly.", [THROW, FORCED], [INSID, FALL]],
  ["en", "Throwing. Or sudden pull on arm.", [THROW, FORCED], [INSID, FALL]],
  ["en", "A cricket bowler who felt a sharp pain at the front of the shoulder while throwing, after months of heavy bowling.", [THROW], [INSID, REPOH, FORCED]],
  ["hi", "Cricket mein bahut phenkna, ya haath achanak kheencha gaya.", [THROW, FORCED], [INSID, FALL]],
  ["de", "क्रिकेट में बहुत फेंकना, या हाथ अचानक खींचा गया।", [THROW, FORCED], [INSID, FALL]],
  ["en", "Overhead throwing or racquet sport.", [THROW], [INSID, REPOH, FORCED]],
  ["en", "A cricketer who bowls all day.", [THROW], [INSID, REPOH, FORCED]],
  ["en", "Throwing sport.", [THROW], [INSID, REPOH, FORCED]],
  ["en", "They play cricket and bowl for hours at the nets.", [THROW], [INSID, REPOH, FORCED]],
  ["hi", "Cricket mein baar baar phenkna.", [THROW], [INSID, REPOH, FORCED]],
  ["de", "क्रिकेट में बार बार फेंकना।", [THROW], [INSID, REPOH, FORCED]],
  ["en", "Weeks to months.", [], []],
  ["en", "On and off for about two months.", [], [INTER]],
  ["en", "2 months.", [], []],
  ["en", "Worse during the season, so about four months in all.", [], []],
  ["hi", "Kuch mahino se.", [], []],
  ["de", "कुछ महीनों से।", [], []],
  ["en", "The patient feels the shoulder slip out when the arm is forced backward.", [FORCED], [OH, FALL, THROW, BEHIND, FRAC]],
  ["en", "Every time the arm is pulled back and out to the side, it feels as if the shoulder will pop out.", [FORCED], [OH, FALL, THROW, BEHIND, FRAC]],
  ["en", "Shoulder slips out with arm pulled back.", [FORCED], [OH, FALL, THROW, BEHIND, FRAC]],
  ["en", "They say the shoulder gave way when the arm was twisted back, and now it feels unsafe whenever they reach up and back.", [FORCED], [OH, FALL, THROW, BEHIND, FRAC]],
  ["hi", "Haath peeche khinchne par kandha bahar nikalta hai.", [FORCED], [OH, FALL, THROW, BEHIND, FRAC]],
  ["de", "हाथ पीछे खींचने पर कंधा बाहर निकलता है।", [FORCED], [OH, FALL, THROW, BEHIND, FRAC]],
  ["en", "Sudden at the first dislocation, then slipping with little force.", [], [FALL, FORCED, FRAC]],
  ["en", "It began when they fell, and afterwards it slips more easily.", [FALL], [FORCED, FRAC]],
  ["en", "Sudden. Past dislocation.", [], [FALL, FORCED, FRAC]],
  ["en", "It first came out during a fall off a bike, and since then it slips with even small movements.", [FALL], [FORCED, FRAC]],
  ["hi", "Pehli baar girne par kandha utra, uske baad baar baar.", [FALL], [FORCED, FRAC]],
  ["de", "पहली बार गिरने पर कंधा उतरा, उसके बाद बार बार।", [FALL], [FORCED, FRAC]],
  ["en", "Fall onto the arm, a tackle, or the arm forced out and back.", [FALL, FORCED], [DIRECT, THROW, FRAC]],
  ["en", "They were tackled in football and the arm was forced back.", [FORCED], [FALL, DIRECT, THROW, FRAC]],
  ["en", "Tackle. Arm forced out and back.", [FORCED], [FALL, DIRECT, THROW, FRAC]],
  ["en", "In a rugby tackle the arm was forced up and back and the shoulder came out.", [FORCED], [FALL, DIRECT, THROW, FRAC]],
  ["hi", "Football mein tackle, haath peeche mud gaya.", [FORCED], [FALL, DIRECT, THROW, FRAC]],
  ["de", "फुटबॉल में टैकल, हाथ पीछे मुड़ गया।", [FORCED], [FALL, DIRECT, THROW, FRAC]],
  ["en", "A few weeks, or years in repeat cases.", [], []],
  ["en", "Two dislocations in the last year.", [], []],
  ["en", "1 year.", [], []],
  ["en", "First dislocation two years ago, and it has slipped several times since.", [], [FRAC]],
  ["hi", "Kai mahino se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "The patient has severe pain in the shoulder at night and cannot raise the arm.", [NIGHT], [OH, LYING, CONST, LIFT]],
  ["en", "The shoulder hurts so much at night that they cannot sleep, and the arm will not go up.", [NIGHT], [OH, LYING, CONST, LIFT]],
  ["en", "Severe night pain. Cannot raise arm.", [NIGHT], [OH, LYING, CONST, LIFT]],
  ["en", "It was so bad last night that they had no sleep at all, and now they cannot lift the arm to reach up.", [NIGHT], [OH, LYING, CONST, LIFT]],
  ["hi", "Raat ko kandhe mein bahut tez dard, haath upar nahi uthta.", [NIGHT], [OH, LYING, CONST, LIFT]],
  ["de", "रात को कंधे में बहुत तेज दर्द, हाथ ऊपर नहीं उठता।", [NIGHT], [OH, LYING, CONST, LIFT]],
  ["en", "Sudden onset, no injury.", [INSID], []],
  ["en", "It began suddenly, with no fall or injury.", [INSID], []],
  ["en", "Sudden. No trauma.", [INSID], []],
  ["en", "It came out of nowhere over two days, and they had not hurt the shoulder at all.", [INSID], []],
  ["hi", "Achanak shuru hua, koi chot nahi.", [INSID], []],
  ["de", "अचानक शुरू हुआ, कोई चोट नहीं।", [INSID], []],
  ["en", "No injury; no clear cause.", [INSID], []],
  ["en", "They did nothing special, it just started.", [INSID], []],
  ["en", "No clear cause.", [INSID], []],
  ["en", "They have no idea why, and they had not lifted or done anything different that week.", [INSID], []],
  ["hi", "Koi chot nahi, kaaran pata nahi.", [INSID], []],
  ["de", "कोई चोट नहीं, कारण पता नहीं।", [INSID], []],
  ["en", "A few days to a few weeks.", [], []],
  ["en", "It has been this bad for about a week.", [], []],
  ["en", "1 week.", [], []],
  ["en", "It started ten days ago and has been getting worse each night.", [], []],
  ["hi", "Kuch dinon se.", [], []],
  ["de", "कुछ दिनों से।", [], []],
  ["en", "The patient has a stiff, aching shoulder, worst in the morning, and cannot reach behind the back.", [BEHIND, MORN], [OH, NIGHT, LYING, CONST]],
  ["en", "The shoulder is stiff first thing in the morning and they can't reach behind any more.", [BEHIND, MORN], [OH, NIGHT, LYING, CONST]],
  ["en", "Stiff shoulder. Worse in the morning. Cannot reach behind.", [BEHIND, MORN], [OH, NIGHT, LYING, CONST]],
  ["en", "It is stiff when they wake up and loosens a bit later. Reaching behind the back to dress has become hard.", [BEHIND, MORN], [OH, NIGHT, LYING, CONST]],
  ["hi", "Kandha subah akda rehta hai, peeche haath nahi ja pata.", [BEHIND, MORN], [OH, NIGHT, LYING, CONST]],
  ["de", "कंधा सुबह अकड़ा रहता है, पीछे हाथ नहीं जा पाता।", [BEHIND, MORN], [OH, NIGHT, LYING, CONST]],
  ["en", "Gradual over years, age over 50.", [INSID, AGE], []],
  ["en", "It has crept up over the years, no injury.", [INSID], [AGE]],
  ["en", "Gradual. Older patient.", [INSID, AGE], []],
  ["en", "It started in their fifties, with no real injury, and it has worsened year after year.", [INSID], [AGE]],
  ["hi", "Saalon mein dheere dheere, umar ke saath.", [INSID, AGE], []],
  ["de", "सालों में धीरे धीरे, उम्र के साथ।", [INSID, AGE], []],
  ["en", "Wear and tear with age, or after an old injury.", [AGE], [INSID, POSTOP, FALL]],
  ["en", "It is the age and wear, and an old fall as well.", [AGE], [INSID, POSTOP, FALL]],
  ["en", "Degenerative. Old injury.", [AGE], [INSID, POSTOP, FALL]],
  ["en", "They are in their sixties and had a fall years ago, and the shoulder has slowly worn since.", [AGE], [INSID, POSTOP, FALL]],
  ["hi", "Umar ke saath ghisav, purani chot.", [AGE], [INSID, POSTOP, FALL]],
  ["de", "उम्र के साथ घिसाव, पुरानी चोट।", [AGE], [INSID, POSTOP, FALL]],
  ["en", "Years.", [], []],
  ["en", "It has been there for several years.", [], []],
  ["en", "Years.", [], []],
  ["en", "Slowly worse over the last five years.", [], []],
  ["hi", "Kai saalon se.", [], []],
  ["de", "कई सालों से।", [], []],
  ["en", "The patient has neck pain that goes down the arm into the hand, with tingling in the fingers.", [NECK, HAND], [ELBOW]],
  ["en", "The pain starts in the neck and shoots down the arm to the fingers, and the hand tingles.", [NECK, HAND], [ELBOW]],
  ["en", "Neck pain. Radiates to the hand. Tingling.", [NECK, HAND], [ELBOW]],
  ["en", "It begins at the neck and spreads over the shoulder blade and down the arm, and the fingers go numb at night.", [NECK, HAND], [ELBOW]],
  ["hi", "Gardan se dard haath tak jata hai, ungliyon mein jhunjhuni.", [NECK, HAND], [ELBOW]],
  ["de", "गर्दन से दर्द हाथ तक जाता है, उंगलियों में झुनझुनी।", [NECK, HAND], [ELBOW]],
  ["en", "Gradual onset, or after straining the neck.", [], [INSID]],
  ["en", "It came on slowly, or after sleeping in an awkward position.", [], [INSID]],
  ["en", "Gradual. Or after a neck strain.", [], [INSID]],
  ["en", "No injury. It began after weeks of long hours at a desk with the neck bent forward.", [], [INSID]],
  ["hi", "Dheere dheere shuru hua, gardan mein khinchav ke baad.", [], [INSID]],
  ["de", "धीरे धीरे शुरू हुआ, गर्दन में खिंचाव के बाद।", [], [INSID]],
  ["en", "Poor posture, disc or neck arthritis.", [], [INSID, AGE]],
  ["en", "Hours at the computer with the head forward.", [], [INSID, AGE]],
  ["en", "Posture. Disc or neck arthritis.", [], [INSID, AGE]],
  ["en", "They work at a computer all day and the neck has been stiff and sore for a while.", [], [INSID, AGE]],
  ["hi", "Kaafi der computer par kaam, gardan akadi hui.", [], [INSID, AGE]],
  ["de", "काफी देर कंप्यूटर पर काम, गर्दन अकड़ी हुई।", [], [INSID, AGE]],
  ["en", "Days to months.", [], []],
  ["en", "A few weeks now.", [], []],
  ["en", "3 weeks.", [], []],
  ["en", "It started a month ago and gets worse when they look down.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "Patient works as a driver and lives in Surat.", [], []],
  ["en", "Medical history: type 2 diabetes, on metformin.", [], []],
  ["en", "Pain score is 6 out of 10.", [], []],
  ["en", "He has been referred by his employer.", [], []],
  ["en", "She would like to return to tennis eventually.", [], []],
  ["en", "Husband brought the patient to the clinic.", [], []],
  ["hi", "Mareez ko pichle hafte doctor ne dekha tha.", [], []],
  ["de", "मरीज़ की उम्र पचास साल है।", [], []],
];

// Same scoring as the other exams, except "may" answers are neutral.
export function scoreSheet(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, must, may] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const okSet = new Set([...must, ...may]);
    for (const g of got) { suggested++; if (okSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of must) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
