// thoracicWildSets.js -- shared by the Thoracic phrase-matcher tests (not a test itself).
// Sets of messy, real-life sentences written the way students type, each marked with what a physio would
// tick ("field|option"). These answer keys are DRAFTS written by Claude for Aditi to review.
// A = the first exam, used to find what the first draft missed; B and C = fair exams written after the
// earlier sets' fixes and NOT used to tune the matcher until their first run was recorded.
// See thoracicPhraseMapWild.test.js for the history.
import { THORACIC_PHRASES, understandStory } from "../thoracicPhraseMap.js";

const O = (field, i) => Object.keys(THORACIC_PHRASES[field])[i];
const k = (field, i) => `${field}|${O(field, i)}`;
// location
const UPPER = k("location", 0), MID = k("location", 1), LOWER = k("location", 2), CTJ = k("location", 3), TLJ = k("location", 4),
  ISC = k("location", 5), ISL = k("location", 6), ISR = k("location", 7), COSTO = k("location", 8), LATW = k("location", 9),
  ANTW = k("location", 10), STERN = k("location", 11), BAND = k("location", 12), PARA = k("location", 13);
// radiation
const RNONE = k("radiation", 0), RWALL = k("radiation", 1), RBLADE = k("radiation", 2), RANT = k("radiation", 3), RABD = k("radiation", 4),
  RGROIN = k("radiation", 5), RBILAT = k("radiation", 6), RCARD = k("radiation", 7);
// mechanism
const MINS = k("mechanismType", 0), MLIFT = k("mechanismType", 1), MROT = k("mechanismType", 2), MFALL = k("mechanismType", 3), MMVA = k("mechanismType", 4),
  MDESK = k("mechanismType", 5), MPOST = k("mechanismType", 6), MPP = k("mechanismType", 7), MOSTEO = k("mechanismType", 8), MVIRAL = k("mechanismType", 9), MNONE = k("mechanismType", 10);
// aggravating movements
const AROT = k("aggMovements", 0), ASIDE = k("aggMovements", 1), AEXT = k("aggMovements", 2), AFLEX = k("aggMovements", 3), ACOMB = k("aggMovements", 4),
  AIN = k("aggMovements", 5), AOUT = k("aggMovements", 6), ACOUGH = k("aggMovements", 7), ASNEEZE = k("aggMovements", 8), ALAUGH = k("aggMovements", 9),
  ASUST = k("aggMovements", 10), AQUICK = k("aggMovements", 11), ALIFT = k("aggMovements", 12), AREACH = k("aggMovements", 13);
// what helps
const THEAT = k("relTreatments", 0), TICE = k("relTreatments", 1), TMANIP = k("relTreatments", 2), TMOB = k("relTreatments", 3), TSTRETCH = k("relTreatments", 4),
  TBREATH = k("relTreatments", 5), TPOST = k("relTreatments", 6), TTAPE = k("relTreatments", 7), TNSAID = k("relTreatments", 8), TPARA = k("relTreatments", 9),
  TRELAX = k("relTreatments", 10), TNONE = k("relTreatments", 11);
// pattern
const PMECH = k("pattern", 0), PCONST = k("pattern", 1), PBREATH = k("pattern", 2), PACT = k("pattern", 3), PNIGHT = k("pattern", 4), PMORN = k("pattern", 5), PINFL = k("pattern", 6);
// red flags
const FNONE = k("redFlags", 0), FCONST = k("redFlags", 1), FNIGHT = k("redFlags", 2), FWORSE = k("redFlags", 3), FCARD = k("redFlags", 4), FCARDH = k("redFlags", 5),
  FRESP = k("redFlags", 6), FABD = k("redFlags", 7), FCA = k("redFlags", 8), FWT = k("redFlags", 9), FFEVER = k("redFlags", 10), FTRAUMA = k("redFlags", 11),
  FOSTEO = k("redFlags", 12), FLEGN = k("redFlags", 13), FLEGW = k("redFlags", 14), FAGE = k("redFlags", 15), FUNWELL = k("redFlags", 16);
// function
const NLIM = k("fnAdl", 0), NBREATH = k("fnAdl", 1), NCOUGH = k("fnAdl", 2), NSIT = k("fnAdl", 3), NDRIVE = k("fnAdl", 4), NCOMP = k("fnAdl", 5),
  NSPORT = k("fnAdl", 6), NLIFT = k("fnAdl", 7), NSLEEP = k("fnAdl", 8), NWORK = k("fnAdl", 9);
export const KEYS = { UPPER, MID, LOWER, CTJ, TLJ, ISC, ISL, ISR, COSTO, LATW, ANTW, STERN, BAND, PARA, RNONE, RWALL, RBLADE, RANT, RABD, RGROIN, RBILAT, RCARD,
  MINS, MLIFT, MROT, MFALL, MMVA, MDESK, MPOST, MPP, MOSTEO, MVIRAL, MNONE, AROT, ASIDE, AEXT, AFLEX, ACOMB, AIN, AOUT, ACOUGH, ASNEEZE, ALAUGH, ASUST, AQUICK, ALIFT, AREACH,
  THEAT, TICE, TMANIP, TMOB, TSTRETCH, TBREATH, TPOST, TTAPE, TNSAID, TPARA, TRELAX, TNONE, PMECH, PCONST, PBREATH, PACT, PNIGHT, PMORN, PINFL,
  FNONE, FCONST, FNIGHT, FWORSE, FCARD, FCARDH, FRESP, FABD, FCA, FWT, FFEVER, FTRAUMA, FOSTEO, FLEGN, FLEGW, FAGE, FUNWELL,
  NLIM, NBREATH, NCOUGH, NSIT, NDRIVE, NCOMP, NSPORT, NLIFT, NSLEEP, NWORK };

export const THORACIC_A = [
  // ── English ──
  ["en", "pain in the middle of my back for three weeks after lifting boxes at work", [MID, MLIFT]],
  ["en", "she has pain between the shoulder blades from sitting at a desk all day", [ISC, MDESK]],
  ["en", "pain at the base of the neck and upper back, started after a long flight", [CTJ, UPPER]],
  ["en", "sharp pain under the right shoulder blade when I take a deep breath", [ISR, AIN, PBREATH]],
  ["en", "pain wraps around my ribs to the front, like a tight belt", [BAND]],
  ["en", "it hurts to cough and sneeze", [ACOUGH, ASNEEZE]],
  ["en", "hurts when I laugh", [ALAUGH]],
  ["en", "pain gets worse when I twist to look behind me", [AROT]],
  ["en", "twisting and bending together is the worst", [ACOMB]],
  ["en", "leaning back to stretch relieves nothing, it hurts when I arch my back", [AEXT]],
  ["en", "pain when bending sideways to the left", [ASIDE]],
  ["en", "slouching makes the pain worse", [AFLEX]],
  ["en", "reaching up to the top shelf triggers the pain", [AREACH]],
  ["en", "pain on exhaling, breathing out hurts more", [AOUT, PBREATH]],
  ["en", "heat helps a bit", [THEAT]],
  ["en", "ice pack gives some relief", [TICE]],
  ["en", "the physio mobilised my back and it helped", [TMOB]],
  ["en", "paracetamol helps for a few hours", [TPARA]],
  ["en", "brufen helps the pain", [TNSAID]],
  ["en", "nothing helps, I have tried everything", [TNONE]],
  ["en", "stretching helps", [TSTRETCH]],
  ["en", "it is stiff in the morning and loosens up as I move", [PINFL]],
  ["en", "worse at night, it wakes me up", [PNIGHT]],
  ["en", "pain with every breath", [PBREATH]],
  ["en", "the pain is the same whatever position I take, nothing changes it", [PCONST, FCONST]],
  ["en", "pain is worse with movement and better with rest", [PMECH]],
  ["en", "pain after exercise, comes on with activity", [PACT]],
  ["en", "my mother had breast cancer", []],
  ["en", "history of breast cancer treated two years ago", [FCA]],
  ["en", "lost weight without trying, about 6 kilos in two months", [FWT]],
  ["en", "fever and chills along with the back pain", [FFEVER]],
  ["en", "known osteoporosis on treatment", [FOSTEO]],
  ["en", "pins and needles in both legs", [FLEGN]],
  ["en", "both legs feel weak and heavy", [FLEGW]],
  ["en", "chest tightness and sweating with the pain", [FCARD]],
  ["en", "he had a heart attack five years ago", [FCARDH]],
  ["en", "breathless on climbing a few stairs", [FRESP]],
  ["en", "pain after eating and loss of appetite", [FABD]],
  ["en", "no red flags", [FNONE]],
  ["en", "she fell down the stairs last week", [FTRAUMA, MFALL]],
  ["en", "I cannot take a deep breath because of the pain", [NBREATH]],
  ["en", "cannot sit for long at my desk", [NSIT]],
  ["en", "difficulty driving, I cannot turn to check my mirrors", [NDRIVE]],
  ["en", "I had to stop going to the gym", [NSPORT]],
  ["en", "cannot lift my child", [NLIFT]],
  ["en", "sleep is disturbed by the pain", [NSLEEP]],
  ["en", "no limitations in daily activities", [NLIM]],
  ["en", "the pain stays in the back and does not spread", [RNONE]],
  ["en", "pain goes round to the front of my chest", [RANT, RWALL]],
  ["en", "it spreads to the shoulder blade", [RBLADE]],
  ["en", "pain goes to the stomach area as well", [RABD]],
  ["en", "pain radiates down the left arm and into the jaw", [RCARD]],
  ["en", "after the car accident last year, rear ended at a signal", [MMVA]],
  ["en", "pain started after I had surgery on my back", [MPOST]],
  ["en", "started after delivery, mostly while breastfeeding", [MPP]],
  ["en", "no injury, it came on gradually over months", [MINS]],
  ["en", "cannot think of any cause", [MNONE]],
  ["en", "fractured a vertebra after a minor fall, she has weak bones", [MOSTEO, FOSTEO]],
  ["en", "sore ribs after a bad chest infection", [MVIRAL]],
  ["en", "twisted my back playing golf and felt a catch", [MROT]],
  ["en", "pain at the front of the chest wall, the ribs are tender", [ANTW]],
  ["en", "pain on the side of the ribs", [LATW]],
  ["en", "tenderness over the breastbone", [STERN]],
  ["en", "pain on both sides of the spine", [PARA]],
  ["en", "pain where the ribs meet the spine", [COSTO]],
  // ── must stay silent ──
  ["en", "my knee hurts at night", []],
  ["en", "neck pain when I look up", []],
  ["en", "the weather was hot yesterday", []],
  ["en", "his cousin has back pain", []],
  ["en", "no history of cancer", []],
  ["en", "I did not fall or twist it", []],
  ["en", "she works at a bank", []],
  ["en", "lower back pain when I bend forward", []],
  ["en", "my friend had a heart attack", []],
  ["en", "the MRI report was normal", []],
  // ── Hinglish ──
  ["hi", "peeth ke beech me dard hai", [MID]],
  ["hi", "kandhon ke beech me dard hota hai computer par kaam karte waqt", [ISC, MDESK]],
  ["hi", "bayen kandhe ki haddi ke neeche dard", [ISL]],
  ["hi", "dayen kandhe ki haddi ke paas dard", [ISR]],
  ["hi", "gehri saans lene par dard hota hai", [AIN, PBREATH]],
  ["hi", "khansi aane par peeth me dard", [ACOUGH]],
  ["hi", "chheenkne par dard badhta hai", [ASNEEZE]],
  ["hi", "mudne par peeth me dard", [AROT]],
  ["hi", "bhaari saman uthane par dard", [ALIFT]],
  ["hi", "garam sekai se aaram milta hai", [THEAT]],
  ["hi", "dolo lene se dard kam hota hai", [TPARA]],
  ["hi", "kuch bhi aaram nahi deta", [TNONE]],
  ["hi", "raat ko dard se neend khul jati hai", [PNIGHT]],
  ["hi", "subah uthte hi jakdan hoti hai", [PMORN]],
  ["hi", "bina chot ke dheere dheere dard shuru hua", [MINS]],
  ["hi", "bhaari saman uthate waqt peeth me khichav aaya", [MLIFT]],
  ["hi", "gir gaya tha peeth ke bal", [MFALL]],
  ["hi", "pehle cancer hua tha", [FCA]],
  ["hi", "bukhar aur peeth me dard", [FFEVER]],
  ["hi", "pairon me jhunjhuni aur kamzori", [FLEGN, FLEGW]],
  ["hi", "gehri saans nahi le pata", [NBREATH]],
  ["hi", "der tak baith nahi pata", [NSIT]],
  ["hi", "mere chacha ko cancer hai", []],
  ["hi", "ghutne me dard hai", []],
  ["hi", "aaj mausam accha hai", []],
  // ── Hindi (Devanagari) ──
  ["de", "पीठ के बीच में दर्द है", [MID]],
  ["de", "कंधों के बीच दर्द", [ISC]],
  ["de", "गहरी सांस लेने पर दर्द", [AIN, PBREATH]],
  ["de", "खांसी में दर्द होता है", [ACOUGH]],
  ["de", "रात को दर्द से नींद खुल जाती है", [PNIGHT]],
  ["de", "सुबह उठते ही जकड़न", [PMORN]],
  ["de", "बाइक से टकरा गया", [MMVA]],
  ["de", "पैरों में झनझनाहट", [FLEGN]],
  ["de", "सीने में जकड़न के साथ दर्द", [FCARD]],
  ["de", "हड्डियां कमजोर हैं", [FOSTEO]],
  ["de", "मेरी बहन को कैंसर है", []],
  ["de", "सिर में दर्द है", []],
];

export const THORACIC_B = [
  // ── English ──
  ["en", "42 yr old teacher, upper back pain bw shoulder blades after marking exam papers hunched over the desk for hrs", [ISC, MDESK, UPPER]],
  ["en", "pt c/o dull ache in mid back, worse when she coughs, no injury she can remember", [MID, ACOUGH, MNONE]],
  ["en", "pain just under the left shoulder blade on deep inspiration", [ISL, AIN, PBREATH]],
  ["en", "sharp stabbing pain at the back of the rib cage on the right when he rotates", [COSTO, AROT]],
  ["en", "the pain starts at the spine and goes around to the front along the ribs", [RWALL]],
  ["en", "sore along both sides of the spine after a day of gardening", [PARA]],
  ["en", "lifting the kids out of the car seat set it off", [ALIFT]],
  ["en", "hurts when i reach over my head to hang clothes", [AREACH]],
  ["en", "laughing really hurts the ribs", [ALAUGH]],
  ["en", "cant bend sideways without pain", [ASIDE]],
  ["en", "it is the long car journeys, being in one position for hours that brings it on", [ASUST]],
  ["en", "any sudden jerk of the trunk makes it flare", [AQUICK]],
  ["en", "a hot water bottle on it every evening settles it", [THEAT]],
  ["en", "she got relief from a cold pack", [TICE]],
  ["en", "the chiropractor cracked my back and the relief was big", [TMANIP]],
  ["en", "sitting up straight eases it", [TPOST]],
  ["en", "kinesiotape on the upper back helped", [TTAPE, UPPER]],
  ["en", "pranayama and deep breathing exercises help it settle", [TBREATH]],
  ["en", "myospaz tablets relieve the spasm", [TRELAX]],
  ["en", "diclofenac gel did not help at all", []],
  ["en", "tablets do not work and nothing makes it better", [TNONE]],
  ["en", "the pain disturbs my sleep every night and it is getting worse each week", [PNIGHT, FNIGHT]],
  ["en", "morning stiffness for an hour that gets better after I start moving about", [PINFL]],
  ["en", "pain increases the more active she is", [PACT]],
  ["en", "breathing in makes the pain sharp", [AIN, PBREATH]],
  ["en", "hurts to breathe", [PBREATH]],
  ["en", "its there all the time and doesnt change with rest or movement", [PCONST, FCONST]],
  ["en", "he was diagnosed with prostate cancer in 2019", [FCA]],
  ["en", "she has lost a lot of weight over the last few months with no diet", [FWT]],
  ["en", "temperature of 39 with shivering and the spine is tender", [FFEVER]],
  ["en", "dexa scan showed osteoporosis", [FOSTEO]],
  ["en", "numbness in both feet and legs since last week", [FLEGN]],
  ["en", "his legs have become very weak, he is dragging them", [FLEGW]],
  ["en", "tight crushing chest pain and sweating", [FCARD]],
  ["en", "he has had a bypass operation before", [FCARDH]],
  ["en", "shortness of breath at rest and coughing up some blood", [FRESP]],
  ["en", "belly pain after meals and vomiting", [FABD]],
  ["en", "she is 62 and has never had back pain before, this is the first time", [FAGE]],
  ["en", "feels generally unwell and washed out", [FUNWELL]],
  ["en", "had a fall from a ladder two days ago", [FTRAUMA, MFALL]],
  ["en", "the pain is felt in the chest wall at the front", [ANTW]],
  ["en", "pain at the side of my rib cage under the arm", [LATW]],
  ["en", "tender in the middle of the chest over the sternum", [STERN]],
  ["en", "belt like band of pain around the chest", [BAND]],
  ["en", "T5 to T8 area is tender", [MID]],
  ["en", "pain at the junction of the neck and back, C7", [CTJ]],
  ["en", "T12 L1 level ache", [TLJ]],
  ["en", "lower thoracic area at the back, just under the shoulder blades", [LOWER]],
  ["en", "the pain stays in one spot and doesn't travel", [RNONE]],
  ["en", "it also hurts in the groin", [RGROIN]],
  ["en", "pain on both sides of the chest as well", [RBILAT]],
  ["en", "the pain goes up into my left arm and jaw with a heavy chest", [RCARD, FCARD]],
  ["en", "rear-end collision on the motorway", [MMVA]],
  ["en", "after my operation on the spine the pain began", [MPOST]],
  ["en", "post partum, carrying the baby and feeding in a poor position", [MPP]],
  ["en", "pulled something lifting a heavy suitcase", [MLIFT]],
  ["en", "banged my back against the door frame", [MFALL]],
  ["en", "pain came on gradually over the last six months", [MINS]],
  ["en", "she had the flu and a nasty cough, then the ribs started hurting", [MVIRAL]],
  ["en", "cannot do my job properly because of the pain", [NWORK]],
  ["en", "sitting at the computer is not possible for more than 20 minutes", [NCOMP, NSIT]],
  ["en", "I have stopped driving long distances", [NDRIVE]],
  ["en", "I am afraid to sneeze", [NCOUGH]],
  ["en", "hard to get comfortable at night so I wake up often", [NSLEEP]],
  // ── must stay silent ──
  ["en", "his left knee swelled after the match", []],
  ["en", "I have a headache since morning", []],
  ["en", "we met at the clinic on Monday at 10", []],
  ["en", "her sister has osteoporosis", []],
  ["en", "my uncle was treated for lung cancer", []],
  ["en", "the shoulder is stiff and cannot lift the arm", []],
  ["en", "sciatica down the right leg", []],
  ["en", "my neighbour had a car accident", []],
  ["en", "the patient seems anxious today", []],
  ["en", "low back pain after gardening", []],
  // ── Hinglish ──
  ["hi", "peeth ke upar wale hisse me dard hai, laptop par kaam karta hoon", [UPPER, MDESK]],
  ["hi", "reedh ke dono taraf dard rehta hai", [PARA]],
  ["hi", "kandhe ki haddi ke neeche dard hota hai khaas kar bayen taraf", [ISL]],
  ["hi", "seene ke beech me dard hai", [STERN]],
  ["hi", "pasliyon ke charo taraf belt jaisa dard", [BAND]],
  ["hi", "dard peeth se seene tak aata hai", [RANT]],
  ["hi", "saans lete waqt dard hota hai", [AIN, PBREATH]],
  ["hi", "saans chhodte waqt dard badhta hai", [AOUT, PBREATH]],
  ["hi", "hasne par dard hota hai", [ALAUGH]],
  ["hi", "aage jhukne par dard badhta hai", [AFLEX]],
  ["hi", "peeche jhukne par dard", [AEXT]],
  ["hi", "ek hi position me der tak baithne se dard", [ASUST]],
  ["hi", "baraf lagane se aaram milta hai", [TICE]],
  ["hi", "brufen leta hoon to aaram milta hai", [TNSAID]],
  ["hi", "seedha baithne se aaram", [TPOST]],
  ["hi", "raat ko dard badh jata hai, neend nahi aati", [PNIGHT, NSLEEP]],
  ["hi", "subah akdan hoti hai jo chalne se theek ho jati hai", [PINFL]],
  ["hi", "saans lene par dard rehta hai", [AIN, PBREATH]],
  ["hi", "pichle hafte accident hua tha", [FTRAUMA]],
  ["hi", "mujhe pehle dil ki bimari ho chuki hai", [FCARDH]],
  ["hi", "saans phoolti hai", [FRESP]],
  ["hi", "bina koshish ke wazan kam ho gaya", [FWT]],
  ["hi", "dono pairon me kamzori hai", [FLEGW]],
  ["hi", "gaadi chalane me bahut dikkat hoti hai", [NDRIVE]],
  ["hi", "kaam par nahi ja pa raha hoon", [NWORK]],
  ["hi", "meri bhabhi ko cancer tha", []],
  ["hi", "ghutne ki sujan kam ho gayi", []],
  ["hi", "kal barish hui thi", []],
  // ── Hindi (Devanagari) ──
  ["de", "पीठ के ऊपरी हिस्से में दर्द रहता है", [UPPER]],
  ["de", "बाएं कंधे की हड्डी के नीचे दर्द", [ISL]],
  ["de", "सीने के बीच में दर्द है", [STERN]],
  ["de", "झुकने पर दर्द बढ़ जाता है", [AFLEX]],
  ["de", "छींकने पर पीठ में दर्द होता है", [ASNEEZE]],
  ["de", "गरम सेकाई से आराम मिलता है", [THEAT]],
  ["de", "बुखार के साथ पीठ दर्द है", [FFEVER]],
  ["de", "कैंसर का इलाज हुआ था", [FCA]],
  ["de", "पैरों में कमजोरी और चलने में दिक्कत", [FLEGW]],
  ["de", "सो नहीं पाता दर्द की वजह से", [NSLEEP]],
  ["de", "मेरे पिताजी को कैंसर था", []],
  ["de", "आज बहुत गर्मी है", []],
];
export const THORACIC_C = [
  // ── English ──
  ["en", "28F, software dev, WFH since covid, constant dull ache between the shoulder blades, worse by evening", [ISC, MDESK]],
  ["en", "my back hurts right in the middle, around the bra line, after carrying the suitcases up the stairs", [MID, MLIFT]],
  ["en", "sharp catching pain on the left side of the rib cage towards the back, started when I turned quickly", [LATW, MROT]],
  ["en", "pain under the right scapula, more so when I breathe deeply", [ISR, AIN, PBREATH]],
  ["en", "tender over the spinous processes at T3 and T4", [UPPER]],
  ["en", "he complains of burning pain going round the left side of the chest in a strip", [RWALL, LATW]],
  ["en", "pain also felt in front around the sternum when I lie flat", [STERN]],
  ["en", "bending down to tie shoelaces is the worst", [AFLEX]],
  ["en", "looking over my shoulder to reverse the car sets it off", [AROT]],
  ["en", "playing with the kids, lifting them onto my shoulders hurts", [ALIFT]],
  ["en", "pain when she lies back on the bed and arches", [AEXT]],
  ["en", "coughing fits are agony", [ACOUGH]],
  ["en", "a good laugh makes the ribs hurt", [ALAUGH]],
  ["en", "heat pad on the back relaxes it", [THEAT]],
  ["en", "ice makes no difference", []],
  ["en", "gentle mobilisations by the physio gave me relief last time", [TMOB]],
  ["en", "she says yoga stretches ease the tightness", [TSTRETCH]],
  ["en", "diclofenac tablets help take the edge off", [TNSAID]],
  ["en", "dolo 650 helps a bit", [TPARA]],
  ["en", "none of the medicines or exercises help", [TNONE]],
  ["en", "the stiffness is there when I wake and eases once I have walked about for half an hour", [PINFL]],
  ["en", "she is worse at night and cannot lie flat", [PNIGHT]],
  ["en", "pain brought on by activity and settles with rest", [PACT, PMECH]],
  ["en", "no matter how I sit or lie the ache is the same", [PCONST, FCONST]],
  ["en", "has had breast cancer surgery 3 years back", [FCA]],
  ["en", "weight has dropped 8 kg without trying", [FWT]],
  ["en", "he gets a fever in the evenings and sweats at night", [FFEVER]],
  ["en", "known case of osteoporosis, on alendronate", [FOSTEO]],
  ["en", "tingling down both legs when she walks", [FLEGN]],
  ["en", "legs buckle underneath him and feel like jelly", [FLEGW]],
  ["en", "pressure in the chest and pain in the left arm", [FCARD, RCARD]],
  ["en", "had angioplasty with a stent two years ago", [FCARDH]],
  ["en", "she gets breathless walking even short distances", [FRESP]],
  ["en", "feels sick after food and has gone off eating", [FABD]],
  ["en", "this is the first time at 58 that I have had this pain", [FAGE]],
  ["en", "feeling run down and off colour for weeks", [FUNWELL]],
  ["en", "a heavy fall on to the back from the bike last week", [MFALL, FTRAUMA]],
  ["en", "gradual onset, nothing specific happened", [MINS]],
  ["en", "pain began while breastfeeding my 3 month old", [MPP]],
  ["en", "pain began after the hospital operation", [MPOST]],
  ["en", "minor trip and then a vertebral compression fracture", [MOSTEO]],
  ["en", "sudden pain while the car was hit from behind at the lights", [MMVA]],
  ["en", "pain at the front and side of the lower ribs", [ANTW, LATW]],
  ["en", "dull ache in the bit of the spine where the ribs end", [TLJ]],
  ["en", "pain in the back of the neck going into the upper back", [UPPER, CTJ]],
  ["en", "does not go anywhere else, just in the one spot", [RNONE]],
  ["en", "it spreads across to my stomach", [RABD]],
  ["en", "pain referred between the shoulder blades from the neck", [ISC, RBLADE]],
  ["en", "the pain goes through to my breastbone", [RANT]],
  ["en", "cannot take a full breath without a sharp twinge", [NBREATH]],
  ["en", "afraid to cough", [NCOUGH]],
  ["en", "I have given up the gym and running", [NSPORT]],
  ["en", "cannot lift my toddler or the shopping bags", [NLIFT]],
  ["en", "my sitting tolerance is about 15 minutes", [NSIT]],
  // ── must stay silent ──
  ["en", "my left ankle is swollen", []],
  ["en", "the patient is a 35 year old male", []],
  ["en", "I will see her again next week", []],
  ["en", "she had a heart attack last year", [FCARDH]],
  ["en", "my mother has osteoporosis", []],
  ["en", "pain in the lower back radiating to the leg", []],
  ["en", "his neck is stiff in the mornings", []],
  ["en", "cancer runs in the family", []],
  ["en", "my friend fell from a ladder", []],
  ["en", "the hospital is near my house", []],
  // ── Hinglish ──
  ["hi", "peeth ke beech me dard hai, bhaari saman uthane ke baad shuru hua", [MID, MLIFT]],
  ["hi", "kandhon ke beech jalan jaisa dard rehta hai", [ISC]],
  ["hi", "dard pasliyon ke saath saath aage seene tak aata hai", [RWALL, RANT]],
  ["hi", "seene ke samne dard hai", [ANTW]],
  ["hi", "khansne par dard hota hai", [ACOUGH]],
  ["hi", "peeche mudkar dekhne par dard", [AROT]],
  ["hi", "jhukne par peeth me dard badhta hai", [AFLEX]],
  ["hi", "garam paani ki thaili se aaram milta hai", [THEAT]],
  ["hi", "dolo khane se dard kam hota hai", [TPARA]],
  ["hi", "kisi dawai se aaram nahi milta", [TNONE]],
  ["hi", "raat ko dard se neend khul jati hai aur roz badh raha hai", [PNIGHT, FNIGHT]],
  ["hi", "dard saans lene par badhta hai", [AIN, PBREATH]],
  ["hi", "pair sunn ho jate hain", [FLEGN]],
  ["hi", "seene me bhaaripan hai aur bayen haath me dard", [FCARD, RCARD]],
  ["hi", "pehle heart attack aa chuka hai", [FCARDH]],
  ["hi", "tez bukhar ke saath peeth me dard", [FFEVER]],
  ["hi", "haddiyan kamzor hain", [FOSTEO]],
  ["hi", "gir gaya tha kal peeth ke bal", [MFALL, FTRAUMA]],
  ["hi", "delivery ke baad se peeth dard", [MPP]],
  ["hi", "bahut der baithne se peeth me dard hota hai", [ASUST]],
  ["hi", "gym nahi ja pata", [NSPORT]],
  ["hi", "peeth dard ki wajah se kaam nahi kar pata", [NWORK]],
  ["hi", "mere dost ko heart attack aaya tha", []],
  ["hi", "pet me dard hai", []],
  ["hi", "kal main bazaar gaya tha", []],
  // ── Hindi (Devanagari) ──
  ["de", "कंधों के बीच में जलन जैसा दर्द रहता है", [ISC]],
  ["de", "पीठ के बीच में दर्द है", [MID]],
  ["de", "दाएं कंधे की हड्डी के पास दर्द", [ISR]],
  ["de", "सांस लेने पर पीठ में दर्द", [AIN, PBREATH]],
  ["de", "झुकने पर दर्द बढ़ता है", [AFLEX]],
  ["de", "बर्फ लगाने से आराम मिलता है", [TICE]],
  ["de", "रात को दर्द से नींद खुल जाती है और बढ़ रहा है", [PNIGHT, FNIGHT]],
  ["de", "सुबह उठने पर पीठ अकड़ जाती है", [PMORN]],
  ["de", "बुखार और पीठ में दर्द", [FFEVER]],
  ["de", "पैरों में झनझनाहट और कमजोरी", [FLEGN, FLEGW]],
  ["de", "गाड़ी चलाने में दिक्कत", [NDRIVE]],
  ["de", "मेरी मां को कैंसर था", []],
  ["de", "घुटने में दर्द है", []],
];

export function score(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, want] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const wantSet = new Set(want);
    for (const g of got) { suggested++; if (wantSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of want) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
