// thoracicSheetSet.js -- the sentences of the Thoracic "everyday words" sheet (PhysioMind-Thoracic-Everyday-Words-DRAFT.pdf), written the way the
// CLINICIAN would type about the patient ("the patient", "they", short notes): English in four styles, Hinglish and Hindi, for all 11
// conditions. Used by thoracicSheetSet.test.js (not a test itself). Row = [lang, text, must, may]:
//   must = options a physio would tick from that sentence (a miss costs recall)
//   may  = options that are also fair to suggest (neither right nor wrong: they do not count against precision)
//   anything else it suggests counts as wrong. A sentence with no must and no may must stay silent.
// lang: en = English, hi = Hinglish (Hindi in Latin letters), de = Hindi in Devanagari. The answer keys are DRAFTS written by Claude
// for Aditi to check. The Thoracic form has no question for how it started or how long as such, so those lines only count where a sentence also says something a form question covers.
import { KEYS } from "./thoracicWildSets.js";
import { understandStory } from "../thoracicPhraseMap.js";

const { ACOUGH, AFLEX, AIN, ALIFT, ANTW, AQUICK, AREACH, AROT, ASNEEZE, ASUST, BAND, COSTO, FABD, FAGE, FCA, FCARD, FCARDH, FCONST, FFEVER, FLEGN, FLEGW, FNIGHT, FNONE, FOSTEO, FRESP, FTRAUMA, FUNWELL, FWORSE, FWT, ISC, ISL, ISR, LATW, MDESK, MFALL, MID, MINS, MLIFT, MNONE, MOSTEO, MROT, MVIRAL, NBREATH, NCOMP, NCOUGH, NLIFT, NSIT, NSLEEP, NSPORT, NWORK, PACT, PARA, PBREATH, PCONST, PINFL, PMECH, PMORN, PNIGHT, RABD, RANT, RBLADE, RCARD, RNONE, RWALL, STERN, THEAT, TMANIP, TMOB, TNSAID, TPARA, TPOST, TRELAX, TSTRETCH, TTAPE, UPPER } = KEYS;

export const THORACIC_SHEET = [
  ["en", "The patient has an ache in the middle of the back, worse on twisting to look behind.", [MID, AROT], [RNONE, PMECH, ISC]],
  ["en", "They say the mid back hurts, twisting round makes it worse, and it does not go anywhere else.", [MID, AROT, RNONE], [PMECH, ISC]],
  ["en", "Mid thoracic pain. Worse: rotation. No radiation.", [MID, AROT, RNONE], [PMECH, ISC]],
  ["en", "It's an ache in the middle of the back that sharpens when they twist round to reach the back seat, and it stays put.", [MID, AROT, RNONE], [PMECH, ISC]],
  ["hi", "Peeth ke beech mein dard, ghumne par badhta hai, kahin aur nahi jata.", [MID, AROT, RNONE], [PMECH, ISC]],
  ["de", "पीठ के बीच में दर्द, घूमने पर बढ़ता है, कहीं और नहीं जाता।", [MID, AROT, RNONE], [PMECH, ISC]],
  ["en", "Gradual onset after long hours hunched over a desk.", [MDESK], [MINS, NCOMP, NSIT, NWORK]],
  ["en", "Started slowly, they sit at a computer all day with the shoulders rounded.", [MDESK], [MINS, NCOMP, NSIT, NWORK]],
  ["en", "Gradual. Desk posture.", [MDESK], [MINS, NCOMP, NSIT, NWORK]],
  ["en", "No single event, it built up over weeks of long hours at the laptop.", [MDESK], [MINS, NCOMP, NSIT, NWORK]],
  ["hi", "Dheere dheere shuru hua, din bhar computer par baithkar kaam.", [MDESK], [MINS, NCOMP, NSIT, NWORK]],
  ["de", "धीरे धीरे शुरू हुआ, दिन भर कंप्यूटर पर बैठकर काम।", [MDESK], [MINS, NCOMP, NSIT, NWORK]],
  ["en", "Manipulation gives them significant relief for a few days.", [TMANIP], [TMOB, MID]],
  ["en", "A crack from the physio helped a lot.", [TMANIP], [TMOB, MID]],
  ["en", "Better after manipulation.", [TMANIP], [TMOB, MID]],
  ["en", "When the chiropractor clicked the mid back it eased for days.", [TMANIP], [TMOB, MID]],
  ["hi", "Manipulation ke baad kai din aaram milta hai.", [TMANIP], [TMOB, MID]],
  ["de", "मैनिपुलेशन के बाद कई दिन आराम मिलता है।", [TMANIP], [TMOB, MID]],
  ["en", "Eased by heat and stretching.", [THEAT, TSTRETCH], [TMOB]],
  ["en", "A hot pack and a few stretches help.", [THEAT, TSTRETCH], [TMOB]],
  ["en", "Better: heat, stretching.", [THEAT, TSTRETCH], [TMOB]],
  ["en", "They put a hot water bottle on the back and do some stretches, which settles it.", [THEAT, TSTRETCH], [TMOB]],
  ["hi", "Garam sekai aur stretching se aaram milta hai.", [THEAT, TSTRETCH], [TMOB]],
  ["de", "गर्म सेकाई और स्ट्रेचिंग से आराम मिलता है।", [THEAT, TSTRETCH], [TMOB]],
  ["en", "Days to weeks.", [], []],
  ["en", "It has been there for about two weeks.", [], []],
  ["en", "2 weeks.", [], []],
  ["en", "It started last week and has been much the same since.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has a band of pain that wraps around the chest from the mid back.", [RWALL], [BAND, MID, LATW, ANTW, COSTO]],
  ["en", "The pain starts in the mid back and goes round the ribs like a belt.", [RWALL], [BAND, MID, LATW, ANTW, COSTO]],
  ["en", "Mid thoracic pain with dermatomal band around the chest.", [RWALL], [BAND, MID, LATW, ANTW, COSTO]],
  ["en", "It starts in the middle of the back and wraps round to the front like a tight strap.", [RWALL], [BAND, MID, LATW, ANTW, COSTO]],
  ["hi", "Peeth ke beech se pasliyon ke charo taraf patti jaisa dard.", [RWALL], [BAND, MID, LATW, ANTW, COSTO]],
  ["de", "पीठ के बीच से पसलियों के चारों ओर पट्टी जैसा दर्द।", [RWALL], [BAND, MID, LATW, ANTW, COSTO]],
  ["en", "Sudden onset lifting a heavy box, worse on bending forward.", [MLIFT, AFLEX], [ALIFT, MID, NLIFT]],
  ["en", "They lifted something heavy and felt a catch in the back; bending forward makes it worse.", [MLIFT, AFLEX], [ALIFT, MID, NLIFT]],
  ["en", "Lifting injury. Worse: flexion.", [MLIFT, AFLEX], [ALIFT, MID, NLIFT]],
  ["en", "Carrying a heavy suitcase up the stairs, something went in the mid back, and bending down is the worst.", [MLIFT, AFLEX], [ALIFT, MID, NLIFT]],
  ["hi", "Bhaari saman uthate waqt achanak peeth mein dard, aage jhukne par badhta hai.", [MLIFT, AFLEX], [ALIFT, MID, NLIFT]],
  ["de", "भारी सामान उठाते समय अचानक पीठ में दर्द, आगे झुकने पर बढ़ता है।", [MLIFT, AFLEX], [ALIFT, MID, NLIFT]],
  ["en", "Coughing, sneezing and taking a deep breath all make it worse.", [ACOUGH, ASNEEZE, AIN], [NCOUGH, NBREATH, PBREATH]],
  ["en", "Cough, sneeze or a deep breath in sets it off.", [ACOUGH, ASNEEZE, AIN], [NCOUGH, NBREATH, PBREATH]],
  ["en", "Worse: cough, sneeze, inspiration.", [ACOUGH, ASNEEZE, AIN], [NCOUGH, NBREATH, PBREATH]],
  ["en", "Every cough or sneeze shoots through the back, and a deep breath in catches too.", [ACOUGH, ASNEEZE, AIN], [NCOUGH, NBREATH, PBREATH]],
  ["hi", "Khansi, chheenk aur gehri saans lene par dard badhta hai.", [ACOUGH, ASNEEZE, AIN], [NCOUGH, NBREATH, PBREATH]],
  ["de", "खांसी, छींक और गहरी सांस लेने पर दर्द बढ़ता है।", [ACOUGH, ASNEEZE, AIN], [NCOUGH, NBREATH, PBREATH]],
  ["en", "The patient also has numbness and tingling in the legs.", [FLEGN], [FLEGW]],
  ["en", "Their legs feel numb and tingly when the back flares.", [FLEGN], [FLEGW]],
  ["en", "Leg paraesthesia with thoracic pain.", [FLEGN], [FLEGW]],
  ["en", "Alongside the back pain there is pins and needles down both legs.", [FLEGN, FLEGW], []],
  ["hi", "Peeth dard ke saath pairon mein sunnpan aur jhunjhuni.", [FLEGN], [FLEGW]],
  ["de", "पीठ दर्द के साथ पैरों में सुन्नपन और झुनझुनी।", [FLEGN], [FLEGW]],
  ["en", "Weeks.", [], []],
  ["en", "It has been about six weeks.", [], []],
  ["en", "6 weeks.", [], []],
  ["en", "It began after the lift a month ago and has not eased.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has sharp pain at the rib joint beside the spine, worse on deep breathing and twisting.", [COSTO, AIN, AROT], [PBREATH, LATW, NBREATH]],
  ["en", "Where the rib meets the spine on the right is sore, and a deep breath or a twist catches it.", [COSTO, AIN, AROT], [PBREATH, LATW, NBREATH]],
  ["en", "Costovertebral pain. Worse: deep inspiration, rotation.", [COSTO, AIN, AROT], [PBREATH, LATW, NBREATH]],
  ["en", "It's a stabbing pain beside the spine at the level of the ribs that catches when they breathe in deeply or turn.", [COSTO, AIN, AROT], [PBREATH, LATW, NBREATH]],
  ["hi", "Reedh ke paas pasli ke jod mein tez dard, gehri saans aur ghumne par badhta hai.", [COSTO, AIN, AROT], [PBREATH, LATW, NBREATH]],
  ["de", "रीढ़ के पास पसली के जोड़ में तेज़ दर्द, गहरी सांस और घूमने पर बढ़ता है।", [COSTO, AIN, AROT], [PBREATH, LATW, NBREATH]],
  ["en", "Sudden onset with a twist while reaching for something behind the seat.", [MROT], [AQUICK, MLIFT, NLIFT, ALIFT]],
  ["en", "It happened when they twisted quickly to reach into the back of the car.", [MROT], [AQUICK, MLIFT, NLIFT, ALIFT]],
  ["en", "Sudden. Twisting injury.", [MROT], [AQUICK, MLIFT, NLIFT, ALIFT]],
  ["en", "They turned awkwardly to grab a bag from the back seat and felt a sharp catch beside the spine.", [MROT], [AQUICK, MLIFT, NLIFT, ALIFT]],
  ["hi", "Peeche se saman uthane ke liye mudte waqt achanak dard shuru hua.", [MROT], [AQUICK, MLIFT, NLIFT, ALIFT]],
  ["de", "पीछे से सामान उठाने के लिए मुड़ते समय अचानक दर्द शुरू हुआ।", [MROT], [AQUICK, MLIFT, NLIFT, ALIFT]],
  ["en", "The pain comes with every breath in.", [PBREATH], [AIN, NBREATH]],
  ["en", "It hurts each time they breathe.", [PBREATH], [AIN, NBREATH]],
  ["en", "Pain with respiration.", [PBREATH], [AIN, NBREATH]],
  ["en", "Breathing in is what brings it on; it's fine when they hold their breath.", [PBREATH], [AIN, NBREATH]],
  ["hi", "Har saans ke saath dard hota hai.", [PBREATH], [AIN, NBREATH]],
  ["de", "हर सांस के साथ दर्द होता है।", [PBREATH], [AIN, NBREATH]],
  ["en", "Gentle mobilisation of the rib joint gave relief.", [TMOB], [TMANIP]],
  ["en", "Mobilising the ribs helped it settle.", [TMOB], [TMANIP]],
  ["en", "Better after rib mobilisation.", [TMOB], [TMANIP]],
  ["en", "After the physio mobilised the joints beside the spine, the sharp catch eased.", [TMOB], [TMANIP]],
  ["hi", "Pasli ke jod ki mobilisation se aaram mila.", [TMOB], [TMANIP]],
  ["de", "पसली के जोड़ की मोबिलाइज़ेशन से आराम मिला।", [TMOB], [TMANIP]],
  ["en", "Days to weeks.", [], []],
  ["en", "It has been there for four days.", [], []],
  ["en", "4 days.", [], []],
  ["en", "It came on last weekend and has been the same since.", [], []],
  ["hi", "Kuch dinon se.", [], []],
  ["de", "कुछ दिनों से।", [], []],
  ["en", "The patient has upper back pain that goes to the shoulder blade.", [UPPER, RBLADE], []],
  ["en", "The ache is at the top of the back and runs to the shoulder blade.", [UPPER, RBLADE], []],
  ["en", "Upper thoracic pain referring to the scapula.", [UPPER, RBLADE], []],
  ["en", "It sits at the top of the back and then spreads into the shoulder blade on that side.", [UPPER, RBLADE], []],
  ["hi", "Peeth ke upar ke hisse mein dard, kandhe ki haddi tak jata hai.", [UPPER, RBLADE], []],
  ["de", "पीठ के ऊपरी हिस्से में दर्द, कंधे की हड्डी तक जाता है।", [UPPER, RBLADE], []],
  ["en", "Worse when reaching overhead.", [AREACH], [ALIFT]],
  ["en", "Reaching up to a shelf brings it on.", [AREACH], [ALIFT]],
  ["en", "Worse: overhead reach.", [AREACH], [ALIFT]],
  ["en", "Hanging washing on the line or reaching the top shelf sets it off.", [AREACH], [ALIFT]],
  ["hi", "Haath upar le jane par dard badhta hai.", [AREACH], [ALIFT]],
  ["de", "हाथ ऊपर ले जाने पर दर्द बढ़ता है।", [AREACH], [ALIFT]],
  ["en", "Worse at night, and it disturbs their sleep.", [PNIGHT, NSLEEP], [FNIGHT, UPPER]],
  ["en", "Night pain keeps waking them.", [PNIGHT, NSLEEP], [FNIGHT, UPPER]],
  ["en", "Night pain, sleep disturbed.", [PNIGHT, NSLEEP], [FNIGHT, UPPER]],
  ["en", "They wake in the early hours with an ache across the upper back.", [PNIGHT, NSLEEP], [FNIGHT, UPPER]],
  ["hi", "Raat ko dard badhta hai aur neend kharab hoti hai.", [PNIGHT, NSLEEP], [FNIGHT, UPPER]],
  ["de", "रात को दर्द बढ़ता है और नींद खराब होती है।", [PNIGHT, NSLEEP], [FNIGHT, UPPER]],
  ["en", "Improved with postural correction.", [TPOST], [TSTRETCH]],
  ["en", "Sitting up straight and pulling the shoulders back helps.", [TPOST], [TSTRETCH]],
  ["en", "Better: postural correction.", [TPOST], [TSTRETCH]],
  ["en", "When they correct their posture and stop slouching the ache eases.", [TPOST], [TSTRETCH]],
  ["hi", "Posture theek karne se aaram milta hai.", [TPOST], [TSTRETCH]],
  ["de", "पोस्चर ठीक करने से आराम मिलता है।", [TPOST], [TSTRETCH]],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been there for about three months.", [], []],
  ["en", "3 months.", [], []],
  ["en", "Slowly more than half a year.", [], []],
  ["hi", "Kai mahino se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "The patient is a teenager with a rounded mid back and an ache after long sitting.", [MID, NSIT], [ASUST]],
  ["en", "A 15-year-old with a hump in the mid back that aches when sitting for long.", [MID, NSIT], [ASUST]],
  ["en", "Adolescent kyphosis. Mid thoracic ache. Sitting aggravates.", [MID, NSIT], [ASUST]],
  ["en", "Their parents noticed the back getting rounder, and it aches in the middle after school.", [], [MID, NSIT, ASUST]],
  ["hi", "Kishor ki peeth beech se gol, der tak baithne par dard.", [MID, NSIT], [ASUST]],
  ["de", "किशोर की पीठ बीच से गोल, देर तक बैठने पर दर्द।", [MID, NSIT], [ASUST]],
  ["en", "Pain with sport and heavy lifting at the gym.", [NSPORT, ALIFT], [PACT, MID, NLIFT]],
  ["en", "It aches after football practice and when lifting weights.", [NSPORT, ALIFT], [PACT, MID, NLIFT]],
  ["en", "Pain with sport and lifting.", [NSPORT, ALIFT], [PACT, MID, NLIFT]],
  ["en", "On the days they play cricket or lift at the gym the middle of the back is sore.", [NSPORT, ALIFT], [PACT, MID, NLIFT]],
  ["hi", "Khel kood aur bhaari vazan uthane par peeth mein dard.", [NSPORT, ALIFT], [PACT, MID, NLIFT]],
  ["de", "खेल कूद और भारी वज़न उठाने पर पीठ में दर्द।", [NSPORT, ALIFT], [PACT, MID, NLIFT]],
  ["en", "Gradual, no injury.", [MINS], [MNONE]],
  ["en", "It came on slowly with no known cause.", [MINS], [MNONE]],
  ["en", "Insidious onset, no trauma.", [MINS], [MNONE]],
  ["en", "No fall or injury, the back just got rounder and sorer over a year.", [], [MINS, MNONE]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [MINS], [MNONE]],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [MINS], [MNONE]],
  ["en", "Stretching and back exercises help.", [TSTRETCH], [TPOST, TMOB]],
  ["en", "Doing the stretches the physio gave them eases it.", [TSTRETCH], [TPOST, TMOB]],
  ["en", "Better: stretching.", [TSTRETCH], [TPOST, TMOB]],
  ["en", "When they stretch the chest and back first thing it feels looser.", [TSTRETCH], [TPOST, TMOB]],
  ["hi", "Stretching karne se aaram milta hai.", [TSTRETCH], [TPOST, TMOB]],
  ["de", "स्ट्रेचिंग करने से आराम मिलता है।", [TSTRETCH], [TPOST, TMOB]],
  ["en", "Months to years.", [], []],
  ["en", "It has been going on for about a year.", [], []],
  ["en", "1 year.", [], []],
  ["en", "Slowly over two years, getting more noticeable.", [], []],
  ["hi", "Kai mahino se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "The patient has rounded shoulders from long desk and phone use, with an ache between the shoulder blades.", [MDESK, ISC], [MINS, NCOMP, NSIT, UPPER, AFLEX]],
  ["en", "A desk worker with the shoulders rolled forward and an ache between the shoulder blades.", [MDESK, ISC], [MINS, NCOMP, NSIT, UPPER, AFLEX]],
  ["en", "Postural kyphosis. Interscapular ache. Desk work.", [MDESK, ISC], [MINS, NCOMP, NSIT, UPPER, AFLEX]],
  ["en", "Hours hunched over the laptop have left the shoulders rounded and a dull ache between the blades.", [MDESK, ISC], [MINS, NCOMP, NSIT, UPPER, AFLEX]],
  ["hi", "Der tak computer par jhukkar kaam, kandhon ke beech dard.", [MDESK, ISC], [MINS, NCOMP, NSIT, UPPER, AFLEX]],
  ["de", "देर तक कंप्यूटर पर झुककर काम, कंधों के बीच दर्द।", [MDESK, ISC], [MINS, NCOMP, NSIT, UPPER, AFLEX]],
  ["en", "Taping and postural reminders help.", [TTAPE, TPOST], []],
  ["en", "The postural tape helps them keep the shoulders back.", [TTAPE, TPOST], []],
  ["en", "Better: taping, postural correction.", [TTAPE, TPOST], []],
  ["en", "With tape across the shoulder blades and a reminder to sit tall it eases.", [TTAPE, TPOST], []],
  ["hi", "Tape lagane aur posture theek rakhne se aaram.", [TTAPE, TPOST], []],
  ["de", "टेप लगाने और पोस्चर ठीक रखने से आराम।", [TTAPE, TPOST], []],
  ["en", "Worse with sustained sitting, eases when they get up and move.", [ASUST, PMECH], [NSIT]],
  ["en", "Sitting in one position for long makes it worse, and moving around relieves it.", [ASUST, PMECH], [NSIT]],
  ["en", "Worse: sustained posture. Better: moving.", [ASUST, PMECH], [NSIT]],
  ["en", "The longer they stay in one position the worse it gets, and standing up and walking around settles it.", [ASUST, PMECH], [NSIT]],
  ["hi", "Der tak ek hi position mein baithne par badhta hai, chalne-phirne se kam hota hai.", [ASUST, PMECH], [NSIT]],
  ["de", "देर तक एक ही स्थिति में बैठने पर बढ़ता है, चलने-फिरने से कम होता है।", [ASUST, PMECH], [NSIT]],
  ["en", "Months.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["en", "It has been there for about four months.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["en", "4 months.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["en", "Gradually worse over the last year.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["hi", "Kuch mahino se.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["de", "कुछ महीनों से।", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["en", "The patient has a mild ache on the right side of the mid back and the right shoulder blade sticks out.", [ISR], [MID, COSTO]],
  ["en", "The right shoulder blade is more prominent and the back aches beside it.", [ISR], [MID, COSTO]],
  ["en", "Right thoracic curve. Mild right interscapular ache.", [ISR], [MID, COSTO]],
  ["en", "One shoulder blade on the right sticks out, and there's an ache next to it by the end of the day.", [ISR], [MID, COSTO]],
  ["hi", "Daayein kandhe ki haddi ubhri hui hai aur uske paas dard rehta hai.", [ISR], [MID, COSTO]],
  ["de", "दाएं कंधे की हड्डी उभरी हुई है और उसके पास दर्द रहता है।", [ISR], [MID, COSTO]],
  ["en", "Aches after standing for long or after sport.", [ASUST, NSPORT], [PACT]],
  ["en", "The back gets sore after a long time on their feet or after games.", [ASUST, NSPORT], [PACT]],
  ["en", "Pain after prolonged standing and sport.", [ASUST, NSPORT], [PACT]],
  ["en", "By the end of a school day on their feet, or after a match, the curve aches.", [ASUST, NSPORT], [PACT]],
  ["hi", "Der tak khade rehne ya khelne ke baad peeth mein dard.", [ASUST, NSPORT], [PACT]],
  ["de", "देर तक खड़े रहने या खेलने के बाद पीठ में दर्द।", [ASUST, NSPORT], [PACT]],
  ["en", "No cause, they were just found to have a curve.", [MNONE], [MINS]],
  ["en", "No known cause for the curve.", [MNONE], [MINS]],
  ["en", "Idiopathic. No trauma.", [MNONE], [MINS]],
  ["en", "Nobody knows why it curved; there was no injury or illness.", [MNONE], [MINS]],
  ["hi", "Koi wajah nahi pata, koi chot nahi.", [MNONE], [MINS]],
  ["de", "कोई वजह नहीं पता, कोई चोट नहीं।", [MNONE], [MINS]],
  ["en", "No red flags.", [FNONE], []],
  ["en", "Nothing worrying: no night pain, fever or weight loss.", [FNONE], []],
  ["en", "RF screen negative.", [FNONE], []],
  ["en", "They have none of the red flag features.", [FNONE], []],
  ["hi", "Koi red flag lakshan nahi.", [FNONE], []],
  ["de", "कोई रेड फ्लैग लक्षण नहीं।", [FNONE], []],
  ["en", "Months to years.", [], []],
  ["en", "The curve was noticed two years ago.", [], []],
  ["en", "2 years.", [], []],
  ["en", "Slowly noticeable over several years.", [], []],
  ["hi", "Kai saalon se.", [], []],
  ["de", "कई सालों से।", [], []],
  ["en", "The patient has pain at the front of the chest beside the breastbone, tender to press and worse on deep breathing.", [ANTW, AIN], [STERN, PBREATH]],
  ["en", "Sore on the front of the rib cage next to the sternum, a deep breath makes it worse.", [ANTW, AIN], [STERN, PBREATH]],
  ["en", "Anterior chest wall pain at costochondral junctions. Worse: deep inspiration.", [ANTW, AIN], [STERN, PBREATH]],
  ["en", "It's a sharp tenderness at the front of the chest by the breastbone that catches on a big breath in.", [ANTW, AIN], [STERN, PBREATH]],
  ["hi", "Seene ke aage chhati ke beech mein dabane par dard, gehri saans par badhta hai.", [ANTW, AIN], [STERN, PBREATH]],
  ["de", "सीने के आगे छाती के बीच में दबाने पर दर्द, गहरी सांस पर बढ़ता है।", [ANTW, AIN], [STERN, PBREATH]],
  ["en", "It started after a chest infection with a lot of coughing.", [MVIRAL], [ACOUGH, ANTW]],
  ["en", "Came on after a bad cold and a lot of coughing.", [MVIRAL], [ACOUGH, ANTW]],
  ["en", "Post viral illness with prolonged cough.", [MVIRAL], [ACOUGH, ANTW]],
  ["en", "Following a flu with days of heavy coughing, the front of the chest began to hurt.", [MVIRAL], [ACOUGH, ANTW]],
  ["hi", "Chest infection aur bahut khansi ke baad shuru hua.", [MVIRAL], [ACOUGH, ANTW]],
  ["de", "सीने के संक्रमण और बहुत खांसी के बाद शुरू हुआ।", [MVIRAL], [ACOUGH, ANTW]],
  ["en", "NSAIDs and a heat pack help.", [TNSAID, THEAT], [TPARA]],
  ["en", "Ibuprofen and heat ease it.", [TNSAID, THEAT], [TPARA]],
  ["en", "Better: NSAIDs, heat.", [TNSAID, THEAT], [TPARA]],
  ["en", "Anti-inflammatory tablets and a warm pack settle the pain.", [TNSAID, THEAT], [TPARA]],
  ["hi", "Dard ki dawai aur garam sekai se aaram.", [THEAT], [TNSAID, TPARA]],
  ["de", "दर्द की दवा और गर्म सेकाई से आराम।", [THEAT], [TNSAID, TPARA]],
  ["en", "No cardiac symptoms and the ECG was normal.", [], [FNONE]],
  ["en", "Heart checked and fine.", [], [FNONE]],
  ["en", "Cardiac cause excluded.", [], [FNONE]],
  ["en", "They have been checked for the heart and nothing was found.", [], [FNONE]],
  ["hi", "Dil ki jaanch ho chuki hai, sab theek hai.", [], [FNONE]],
  ["de", "दिल की जांच हो चुकी है, सब ठीक है।", [], [FNONE]],
  ["en", "Weeks.", [], []],
  ["en", "It has been there for about three weeks.", [], []],
  ["en", "3 weeks.", [], []],
  ["en", "It began after the cough a month ago and has not gone.", [], []],
  ["hi", "Kuch hafton se.", [], []],
  ["de", "कुछ हफ्तों से।", [], []],
  ["en", "The patient has tender knots in the muscles beside the left shoulder blade.", [ISL], [ISC, PARA]],
  ["en", "The left side next to the shoulder blade is full of sore, tight spots.", [ISL], [ISC, PARA]],
  ["en", "Left interscapular trigger points.", [ISL], [ISC, PARA]],
  ["en", "There are hard, tender knots in the muscle just inside the left shoulder blade.", [ISL], [ISC, PARA]],
  ["hi", "Baayein kandhe ki haddi ke paas maanspeshi mein dardnaak gaanth.", [ISL], [ISC, PARA]],
  ["de", "बाएं कंधे की हड्डी के पास मांसपेशी में दर्दनाक गांठ।", [ISL], [ISC, PARA]],
  ["en", "Muscle relaxant tablets help a bit.", [TRELAX], [TPARA, TNSAID]],
  ["en", "A muscle relaxant takes the tightness off.", [TRELAX], [TPARA, TNSAID]],
  ["en", "Better: muscle relaxants.", [TRELAX], [TPARA, TNSAID]],
  ["en", "When they take the muscle relaxant the knots loosen and the ache eases.", [TRELAX], [TPARA, TNSAID]],
  ["hi", "Maspeshi ko dheela karne wali dawai se aaram.", [TRELAX], [TPARA, TNSAID]],
  ["de", "मांसपेशी ढीली करने वाली दवा से आराम।", [TRELAX], [TPARA, TNSAID]],
  ["en", "Only when working at the computer, fine at weekends.", [PACT], [NCOMP, MDESK]],
  ["en", "It comes on with a day at the computer and is gone on days off.", [PACT], [NCOMP, MDESK]],
  ["en", "Activity-related: desk work only.", [PACT], [NCOMP, MDESK]],
  ["en", "On the days they are at the laptop it aches, but on holidays it's completely fine.", [PACT], [NCOMP, MDESK]],
  ["hi", "Sirf computer par kaam karne par dard, chhutti mein theek.", [PACT], [NCOMP, MDESK]],
  ["de", "सिर्फ कंप्यूटर पर काम करने पर दर्द, छुट्टी में ठीक।", [PACT], [NCOMP, MDESK]],
  ["en", "The pain is related to movement and posture, not constant.", [PMECH], []],
  ["en", "It depends on how they move and sit, and eases with a change of position.", [PMECH], []],
  ["en", "Mechanical pattern.", [PMECH], []],
  ["en", "Certain movements and positions bring it on, and changing position makes it settle.", [PMECH], []],
  ["hi", "Dard harkat aur posture se jura hai, lagatar nahi.", [PMECH], []],
  ["de", "दर्द हरकत और पोस्चर से जुड़ा है, लगातार नहीं।", [PMECH], []],
  ["en", "Weeks to months.", [], []],
  ["en", "It has been there for about two months.", [], []],
  ["en", "2 months.", [], []],
  ["en", "On and off for most of the year.", [], []],
  ["hi", "Kuch mahino se.", [], []],
  ["de", "कुछ महीनों से।", [], []],
  ["en", "The patient has morning stiffness of more than half an hour that eases once they get moving.", [PINFL], [PMORN, PMECH]],
  ["en", "They are stiff for about an hour every morning, and it loosens up with movement.", [PINFL], [PMORN, PMECH]],
  ["en", "Inflammatory pattern: morning stiffness >30 min, eases with exercise.", [PINFL], [PMORN, PMECH]],
  ["en", "Each morning the back is locked for an hour or so, but a walk or some exercise frees it up.", [PINFL], [PMORN, PMECH]],
  ["hi", "Subah aadhe ghante se zyada akdan, hilne dulne se kam hota hai.", [PINFL], [PMORN, PMECH]],
  ["de", "सुबह आधे घंटे से ज्यादा अकड़न, हिलने डुलने से कम होता है।", [PINFL], [PMORN, PMECH]],
  ["en", "Wakes in the second half of the night with back pain.", [PNIGHT], [FNIGHT, NSLEEP]],
  ["en", "The pain wakes them in the early hours.", [PNIGHT], [FNIGHT, NSLEEP]],
  ["en", "Night pain, wakes early hours.", [PNIGHT], [FNIGHT, NSLEEP]],
  ["en", "Around three or four in the morning they wake with an ache in the back and have to get up and move.", [PNIGHT], [FNIGHT, NSLEEP]],
  ["hi", "Raat ke doosre hisse mein dard se neend khul jati hai.", [PNIGHT], [FNIGHT, NSLEEP]],
  ["de", "रात के दूसरे हिस्से में दर्द से नींद खुल जाती है।", [PNIGHT], [FNIGHT, NSLEEP]],
  ["en", "NSAIDs are very effective.", [TNSAID], []],
  ["en", "A short course of anti-inflammatories takes most of the pain away.", [TNSAID], []],
  ["en", "Better: NSAIDs.", [TNSAID], []],
  ["en", "When they take the anti-inflammatory tablets the pain and stiffness largely go within a day.", [TNSAID], []],
  ["hi", "Dard ki dawai (NSAID) se kaafi aaram.", [TNSAID], []],
  ["de", "दर्द की दवा (NSAID) से काफी आराम।", [TNSAID], []],
  ["en", "Insidious onset over months.", [MINS], [MNONE]],
  ["en", "It crept on over many months with no injury.", [MINS], [MNONE]],
  ["en", "Gradual. No trauma.", [MINS], [MNONE]],
  ["en", "No single event, it built up slowly over about a year.", [MINS], [MNONE]],
  ["hi", "Dheere dheere shuru hua, koi chot nahi.", [MINS], [MNONE]],
  ["de", "धीरे धीरे शुरू हुआ, कोई चोट नहीं।", [MINS], [MNONE]],
  ["en", "More than 3 months.", [], []],
  ["en", "It has been going on for about eight months.", [], []],
  ["en", "8 months.", [], []],
  ["en", "Slowly more than a year, with the stiffness getting longer.", [], []],
  ["hi", "Kai mahino se.", [], []],
  ["de", "कई महीनों से।", [], []],
  ["en", "The patient has constant pain unaffected by position, wakes at night, and has lost weight.", [FCONST, FNIGHT, FWT], [PCONST, PNIGHT, NSLEEP]],
  ["en", "The pain never changes with movement, it wakes them at night, and they have lost weight without trying.", [FCONST, FNIGHT, FWT], [PCONST, PNIGHT, NSLEEP]],
  ["en", "Constant pain, night pain, weight loss.", [FCONST, FNIGHT, FWT], [PCONST, PNIGHT, NSLEEP]],
  ["en", "Nothing they do changes the pain, it's there through the night as well, and their clothes have become loose.", [FCONST, FNIGHT, FWT], [PCONST, PNIGHT, NSLEEP]],
  ["hi", "Dard lagatar rehta hai, position se farak nahi, raat ko jagata hai aur wazan kam hua.", [FCONST, FNIGHT, FWT], [PCONST, PNIGHT, NSLEEP]],
  ["de", "दर्द लगातार रहता है, स्थिति से फर्क नहीं, रात को जगाता है और वज़न कम हुआ।", [FCONST, FNIGHT, FWT], [PCONST, PNIGHT, NSLEEP]],
  ["en", "Chest tightness with pain down the left arm.", [FCARD, RCARD], [RANT]],
  ["en", "A tight band across the chest and the pain spreads to the left arm.", [FCARD, RCARD], [RANT]],
  ["en", "Chest tightness, left arm radiation.", [FCARD, RCARD], [RANT]],
  ["en", "It feels like a weight on the chest and the pain runs down into the left arm and jaw.", [FCARD, RCARD], [RANT]],
  ["hi", "Seene mein jakdan aur baayein haath mein dard.", [FCARD, RCARD], [RANT]],
  ["de", "सीने में जकड़न और बाएं हाथ में दर्द।", [FCARD, RCARD], [RANT]],
  ["en", "Short of breath and coughing blood.", [FRESP], []],
  ["en", "Breathless, and there was blood in the cough.", [FRESP], []],
  ["en", "SOB, haemoptysis.", [FRESP], []],
  ["en", "They get breathless on the stairs and brought up blood-stained phlegm.", [FRESP], []],
  ["hi", "Saans phoolti hai aur khansi mein khoon aaya.", [FRESP], []],
  ["de", "सांस फूलती है और खांसी में खून आया।", [FRESP], []],
  ["en", "Fever and feeling very unwell with the back pain.", [FFEVER, FUNWELL], []],
  ["en", "A high temperature, shivering and generally unwell.", [FFEVER, FUNWELL], []],
  ["en", "Fever, malaise, thoracic pain.", [FFEVER, FUNWELL], []],
  ["en", "They have had a fever for days and feel washed out, with severe back pain.", [FFEVER, FUNWELL], []],
  ["hi", "Bukhar aur bahut kamzori ke saath peeth dard.", [FFEVER, FUNWELL], []],
  ["de", "बुखार और बहुत कमज़ोरी के साथ पीठ दर्द।", [FFEVER, FUNWELL], []],
  ["en", "History of breast cancer, now unexplained weight loss and mid back pain.", [FCA, FWT], [MID]],
  ["en", "She had breast cancer in the past and has now lost weight with new back pain.", [FCA, FWT], [MID]],
  ["en", "Previous cancer. Unexplained weight loss. Thoracic pain.", [FCA, FWT], [MID]],
  ["en", "Having been treated for cancer a few years ago, they have now lost a lot of weight and the back is hurting.", [FCA, FWT], [MID]],
  ["hi", "Pehle cancer ho chuka hai, ab wazan kam aur peeth mein dard.", [FCA, FWT], [MID]],
  ["de", "पहले कैंसर हो चुका है, अब वज़न कम और पीठ में दर्द।", [FCA, FWT], [MID]],
  ["en", "Fell off a ladder, severe mid back pain since.", [FTRAUMA, MFALL], [MID]],
  ["en", "A bad fall from a ladder and the back has hurt badly ever since.", [FTRAUMA, MFALL], [MID]],
  ["en", "Recent fall from height. Severe thoracic pain.", [FTRAUMA, MFALL], [MID]],
  ["en", "They came off a ladder onto the ground a few days ago and the mid back is now agony.", [FTRAUMA, MFALL], [MID]],
  ["hi", "Seedhi se gire, tab se peeth mein bahut tez dard.", [FTRAUMA, MFALL], [MID]],
  ["de", "सीढ़ी से गिरे, तब से पीठ में बहुत तेज़ दर्द।", [FTRAUMA, MFALL], [MID]],
  ["en", "Known osteoporosis, pain after a minor fall.", [FOSTEO], [MOSTEO, MFALL, FTRAUMA, MID]],
  ["en", "They have osteoporosis and the back started hurting after a small slip.", [FOSTEO], [MOSTEO, MFALL, FTRAUMA, MID]],
  ["en", "Osteoporosis. Minimal trauma.", [FOSTEO], [MOSTEO, MFALL, FTRAUMA, MID]],
  ["en", "With thin bones from osteoporosis, a little stumble was enough to bring on sharp mid back pain.", [FOSTEO], [MOSTEO, MFALL, FTRAUMA, MID]],
  ["hi", "Haddi kamzor hai (osteoporosis), halki chot ke baad peeth dard.", [FOSTEO], [MOSTEO, MFALL, FTRAUMA, MID]],
  ["de", "हड्डी कमज़ोर है (ऑस्टियोपोरोसिस), हल्की चोट के बाद पीठ दर्द।", [FOSTEO], [MOSTEO, MFALL, FTRAUMA, MID]],
  ["en", "Both legs are weak and numb, with a band of pain round the trunk.", [FLEGW, FLEGN], [BAND, RWALL]],
  ["en", "Their legs have gone weak and numb on both sides.", [FLEGW, FLEGN], [BAND, RWALL]],
  ["en", "Bilateral leg weakness and numbness. Cord signs.", [FLEGW, FLEGN], [BAND, RWALL]],
  ["en", "Both legs feel heavy and numb and they are struggling to walk, with a tight band round the chest.", [FLEGW, FLEGN], [BAND, RWALL]],
  ["hi", "Dono pairon mein kamzori aur sunnpan.", [FLEGW, FLEGN], [BAND, RWALL]],
  ["de", "दोनों पैरों में कमज़ोरी और सुन्नपन।", [FLEGW, FLEGN], [BAND, RWALL]],
  ["en", "Pain after eating that goes through to the abdomen.", [FABD, RABD], []],
  ["en", "The back pain comes with eating and spreads to the stomach.", [FABD, RABD], []],
  ["en", "Thoracic pain radiating to abdomen. Worse with meals.", [FABD, RABD], []],
  ["en", "After meals the pain passes from the back round into the upper abdomen.", [FABD, RABD], []],
  ["hi", "Khane ke baad dard peeth se pet tak jata hai.", [FABD, RABD], []],
  ["de", "खाने के बाद दर्द पीठ से पेट तक जाता है।", [FABD, RABD], []],
  ["en", "Known heart disease and the pain feels like their angina.", [FCARDH], []],
  ["en", "They have had a heart attack before and this pain is the same as their heart pain.", [FCARDH], []],
  ["en", "Cardiac history. Pain reproduces cardiac pattern.", [FCARDH], []],
  ["en", "With a history of heart disease, this pain feels just like the angina they know.", [FCARDH], []],
  ["hi", "Dil ki bimari ka itihas hai aur dard dil ke dard jaisa hai.", [FCARDH], []],
  ["de", "दिल की बीमारी का इतिहास है और दर्द दिल के दर्द जैसा है।", [FCARDH], []],
  ["en", "A 70-year-old with a first episode of mid back pain and no cause.", [FAGE], [MNONE, MINS, MID]],
  ["en", "First ever mid back pain at 68 with no injury.", [FAGE], [MNONE, MINS, MID]],
  ["en", "Age >50, first episode, no mechanism.", [FAGE], [MNONE, MINS, MID]],
  ["en", "At seventy-two this is the first time they have had back pain, and nothing triggered it.", [FAGE], [MNONE, MINS, MID]],
  ["hi", "Pehli baar saath saal ki umar mein bina wajah peeth dard.", [FAGE], [MNONE, MINS, MID]],
  ["de", "पहली बार साठ साल की उम्र में बिना वजह पीठ दर्द।", [FAGE], [MNONE, MINS, MID]],
  ["en", "Urgent; may be days or weeks.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["en", "It has been getting worse over three weeks.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["en", "3 weeks, worsening.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["en", "Over a month, with the pain now constant.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["hi", "Kuch hafton se badhta hua.", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["de", "कुछ हफ्तों से बढ़ता हुआ।", [], [MINS, MNONE, PMECH, PCONST, FWORSE]],
  ["en", "Patient works as a driver and lives in Surat.", [], []],
  ["en", "Medical history: type 2 diabetes, on metformin.", [], []],
  ["en", "Pain score is 6 out of 10.", [], []],
  ["en", "He has been referred by his employer.", [], []],
  ["en", "She would like to return to yoga eventually.", [], []],
  ["en", "Husband brought the patient to the clinic.", [], []],
  ["hi", "Mareez ko pichle hafte doctor ne dekha tha.", [], []],
  ["de", "मरीज़ की उम्र पचास साल है।", [], []],
];

// Same scoring as the other exams, except "may" answers are neutral.
export function scoreSheet(rows) {
  let suggested = 0, right = 0, wanted = 0, found = 0;
  const wrong = [], missed = [];
  for (const [lang, text, must, may] of rows) {
    const got = understandStory(text).suggestions.map((s) => `${s.field}|${s.option}`);
    const okSet = new Set([...must, ...may]);
    for (const g of got) { suggested++; if (okSet.has(g)) right++; else wrong.push(`[${lang}] "${text}" -> WRONG ${g}`); }
    for (const w of must) { wanted++; if (got.includes(w)) found++; else missed.push(`[${lang}] "${text}" -> MISSED ${w}`); }
  }
  return { suggested, right, wanted, found, wrong, missed, precision: suggested ? right / suggested : 1, recall: wanted ? found / wanted : 1 };
}
