#!/usr/bin/env python3
"""Rebuilds the small icon font the app ships (src/fonts/tabler-icons-subset.*).

Why: the full Tabler icon font is ~500 KB (plus a 213 KB stylesheet) for more than
5,000 icons, and the app uses about thirty. Loading it from a third-party site
blocked the first screen on a weak connection. This keeps only the icons the app
really uses, so the font is a few KB and ships from our own site.

Run it after adding a new `ti-something` icon anywhere in src/ (the test
src/__tests__/tablerIconSubset.test.js fails until you do):

    python3 -m venv /tmp/fontenv && /tmp/fontenv/bin/pip install fonttools brotli
    /tmp/fontenv/bin/python tools/make-tabler-subset.py

It downloads the pinned Tabler release, finds every ti-* name used in src/,
index.html and tester.html, and rewrites the two files below.
"""
import io
import os
import re
import sys
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont

VERSION = "3.49.0"  # keep pinned: "latest" changes under us
BASE = f"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@{VERSION}/dist/"
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT_DIR = os.path.join(ROOT, "src", "fonts")

# Icon names that are built in code (e.g. "ti-chevron-" + (open ? "up" : "down")),
# which a text search cannot see. Add the full names here.
BUILT_IN_CODE = ["ti-chevron-up", "ti-chevron-down"]


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def used_icons():
    found = set(BUILT_IN_CODE)
    for folder in ("src",):
        for dirpath, dirs, files in os.walk(os.path.join(ROOT, folder)):
            dirs[:] = [d for d in dirs if d not in ("__tests__", "fonts", "node_modules")]
            for f in files:
                if f.endswith((".js", ".jsx", ".ts", ".tsx", ".css")):
                    text = open(os.path.join(dirpath, f), encoding="utf-8", errors="ignore").read()
                    found.update(re.findall(r"\bti-[a-z0-9]+(?:-[a-z0-9]+)*", text))
    for f in ("index.html", "tester.html"):
        text = open(os.path.join(ROOT, f), encoding="utf-8").read()
        found.update(re.findall(r"\bti-[a-z0-9]+(?:-[a-z0-9]+)*", text))
    # "ti-chevron-" + (...) shows up in a text search as "ti-chevron": that is the
    # start of a built name (listed in BUILT_IN_CODE), not an icon of its own.
    return sorted(n for n in found if not any(b.startswith(n + "-") for b in BUILT_IN_CODE))


def main():
    css = fetch(BASE + "tabler-icons.min.css").decode("utf-8")
    font = fetch(BASE + "fonts/tabler-icons.woff2")
    rules = dict(re.findall(r'\.(ti-[a-z0-9-]+):before\{content:"\\([0-9a-f]+)"\}', css))
    base_rule = re.search(r"\.ti\{[^}]*\}", css).group(0)

    names = used_icons()
    missing = [n for n in names if n not in rules]
    if missing:
        sys.exit(f"Not in Tabler {VERSION}: {', '.join(missing)}")

    codepoints = [int(rules[n], 16) for n in names]
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = []
    opts.hinting = False
    opts.notdef_outline = False
    opts.name_IDs = []
    f = TTFont(io.BytesIO(font))
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=codepoints)
    sub.subset(f)
    f.flavor = "woff2"
    os.makedirs(OUT_DIR, exist_ok=True)
    woff = os.path.join(OUT_DIR, "tabler-icons-subset.woff2")
    f.save(woff)

    lines = [
        f"/* Tabler Icons {VERSION} (MIT) - only the icons this app uses.",
        " * Generated by tools/make-tabler-subset.py. Do not edit by hand: add the icon",
        " * name to the code, then run that script. */",
        '@font-face{font-family:"tabler-icons";font-style:normal;font-weight:400;font-display:swap;'
        'src:url("./tabler-icons-subset.woff2") format("woff2")}',
        base_rule,
    ]
    lines += [f'.{n}:before{{content:"\\{rules[n]}"}}' for n in names]
    open(os.path.join(OUT_DIR, "tabler-icons-subset.css"), "w").write("\n".join(lines) + "\n")
    print(f"{len(names)} icons, font {os.path.getsize(woff)} bytes")
    print(", ".join(n[3:] for n in names))


if __name__ == "__main__":
    main()
