// Real reference content extracted from the uploaded textbook ("The Muscle
// and Bone Palpation Manual with Trigger Points, Referral Patterns, and
// Stretching", 1st ed.) — the PDF has no embedded text layer (it's a
// scanned book), so every field here was pulled by OCR'ing the specific
// page range cited in `source` for that structure, not invented or
// paraphrased from general anatomy knowledge. Where the book didn't state
// something the template asks for, the field is omitted rather than
// filled with a guess.
//
// `images` is always a 3-slot array of Cloudinary public ids (or null).
// StudyImage.jsx already renders a clean "no image" placeholder for a
// null/missing id, so these stay null until real photos/illustrations
// are uploaded — nothing here fabricates image content.
//
// Region coverage so far: Shoulder Girdle (Chapter 10, "Tour #1") and
// Cervical (Chapter 11, "Tour #2") — every structure in both tours, in
// full. The rest of the book (9 more muscle tours + 3 bone/ligament
// chapters) follows the same OCR-and-structure process in later passes;
// PALPATION_REGIONS below marks those as not yet added rather than
// pretending they're covered.

export const PALPATION_REGIONS = [
  { key: "shoulder", label: "Shoulder Girdle", available: true },
  { key: "cervical", label: "Cervical", available: true },
  { key: "head", label: "Head", available: false },
  { key: "arm", label: "Arm", available: false },
  { key: "forearm", label: "Forearm", available: false },
  { key: "trunk", label: "Trunk", available: false },
  { key: "pelvis", label: "Pelvis", available: false },
  { key: "thigh", label: "Thigh", available: false },
  { key: "leg", label: "Leg", available: false },
  { key: "foot", label: "Foot", available: false },
  { key: "bones", label: "Bones & Ligaments", available: false },
];

const SRC = "The Muscle and Bone Palpation Manual, Ch.10 — Tour #1: Palpation of the Muscles of the Shoulder Girdle";
const SRC_NECK = "The Muscle and Bone Palpation Manual, Ch.11 — Tour #2: Palpation of the Neck Muscles";

export const PALPATION_DATA = {
  shoulder: [
    {
      id: "palp_trapezius",
      name: "Trapezius",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "External occipital protuberance, medial 1/3 of the superior nuchal line, nuchal ligament, and the spinous processes of C7 through T12",
        insertion: "Lateral 1/3 of the clavicle, acromion process, and spine of the scapula",
      },
      actions: "Upper: elevates, retracts and upwardly rotates the scapula; extends, laterally flexes and contralaterally rotates the head/neck. Middle: retracts the scapula. Lower: depresses, retracts and upwardly rotates the scapula.",
      patientPosition: "Prone, arm resting on the table at the side of the body.",
      therapistPosition: "Standing to the side of the client.",
      handPlacement: "Palpating hand just lateral to the lower thoracic spine, on the lower trapezius.",
      steps: [
        "Ask the client to abduct the arm to 90° with the elbow extended, and slightly retract the scapula (“pinch the shoulder blade toward the spine”). Gentle resistance can be added.",
        "Palpate the lower trapezius: locate its lateral border by palpating perpendicular to it, then palpate the entire lower trapezius.",
        "Repeat for the middle trapezius between the scapula and spine, strumming perpendicular to the fibres (vertically).",
        "For the upper trapezius, ask the client to slightly extend the head and neck, then palpate the entire upper trapezius.",
        "Once located, have the client relax the muscle and palpate to assess baseline tone.",
      ],
      feelFor: "The belly of each of the three functional parts (upper/middle/lower) contracting under your fingers as the client performs the corresponding action; baseline tone once relaxed.",
      notes: [
        "Retracting the scapula engages the whole trapezius, especially the middle fibres — clients often lift the arm into the air instead of just retracting; cue “pinch the shoulder blade back” without over-retracting.",
        "The lateral border of the lower trapezius is often visible — look for it before placing your hands.",
      ],
      clinicalConsiderations: "TrPs are the most commonly found in the body (especially upper trapezius) and often relate to chronic elevation/anterior head posture, poor ergonomics, or compression (bag straps, tight bra). Referral must be distinguished from sternocleidomastoid, levator scapulae, and other cervical muscles depending on which fibres are involved.",
      source: `${SRC}, pp.142–145`,
      images: [null, null, null],
    },
    {
      id: "palp_rhomboids",
      name: "Rhomboids (major & minor)",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Spinous processes of C7 through T5",
        insertion: "Medial border of the scapula, from the root of the spine to the inferior angle",
      },
      actions: "Retracts, elevates, and downwardly rotates the scapula at the scapulocostal joint.",
      patientPosition: "Prone, hand resting in the small of the back.",
      therapistPosition: "Standing to the side of the client.",
      handPlacement: "Between the spinal column and the scapula at the midscapular level.",
      steps: [
        "Ask the client to lift the hand away from the small of the back.",
        "Look for the lower border of the rhomboids to become visible — don't cover it with your palpating hand.",
        "Palpate from the inferior to the superior aspect, strumming perpendicular to the fibre direction.",
        "Once located, have the client relax the muscle and palpate baseline tone.",
      ],
      feelFor: "The muscle bulk becoming visible/palpable between the spine and scapula as the hand lifts off the low back; a gap between the rhomboids and levator scapulae superiorly.",
      notes: [
        "Hand-in-small-of-back position causes reciprocal inhibition of the trapezius, so you can palpate through it more easily.",
        "The superior border is harder to find than the inferior border; it usually isn't possible to clearly distinguish rhomboid major from minor.",
      ],
      clinicalConsiderations: "TrPs often relate to overuse as scapular retractors/stabilizers, or chronic stretch from a rounded-shoulder posture with tight anterior pectorals. Pain is typically superficial and felt at rest; can be confused with fibromyalgia.",
      source: `${SRC}, pp.146–147`,
      images: [null, null, null],
    },
    {
      id: "palp_serratus_posterior_superior",
      name: "Serratus Posterior Superior",
      type: "Muscle",
      position: "Prone (detour from Rhomboids)",
      attachments: {
        origin: "Spinous processes of C7–T3",
        insertion: "Ribs two through five",
      },
      patientPosition: "Prone, arm hanging off the table to protract the scapula and expose the muscle.",
      handPlacement: "Deep to the rhomboids/scapula, over ribs two through five.",
      steps: [
        "With the arm hanging off the table (scapula protracted), palpate deep to the scapula over ribs 2–5.",
      ],
      feelFor: "A deep muscle layer beneath the rhomboids, over the upper posterior ribs.",
      clinicalConsiderations: "TrPs often relate to labored breathing (COPD, asthma, bronchitis) and TrPs in the scalenes. Produces a deep ache felt deep to the scapula, sometimes numbness in the little finger, or C7–T3 joint dysfunction.",
      source: `${SRC}, p.148`,
      images: [null, null, null],
    },
    {
      id: "palp_levator_scapulae",
      name: "Levator Scapulae",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Transverse processes of C1 through C4",
        insertion: "Medial border of the scapula, from the root of the spine to the superior angle",
      },
      actions: "Elevates and downwardly rotates the scapula; extends, laterally flexes and ipsilaterally rotates the neck.",
      patientPosition: "Prone, hand resting in the small of the back.",
      therapistPosition: "Standing or seated to the side of the client.",
      handPlacement: "Just superior and medial to the superior angle of the scapula.",
      steps: [
        "With the hand in the small of the back, ask for a very short, gentle scapular elevation. Feel for the contraction deep to the trapezius.",
        "Continue palpating toward its superior attachment, strumming perpendicular to the fibres.",
        "Once palpating in the posterior triangle (superior to trapezius), the hand no longer needs to stay on the back; elevation can be more forceful and resisted.",
        "Palpate as far superiorly as possible — near its top attachment it runs deep to the sternocleidomastoid.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Contraction deep to the trapezius near the superior angle of the scapula; in the posterior triangle it becomes superficial and is sometimes visible in middle-aged/older adults.",
      notes: [
        "Do not ask for a forceful elevation early — it overcomes the reciprocal inhibition of the upper trapezius and blocks palpation at the inferior attachment.",
        "The transverse process of C1 sits directly inferior to the ear, between the mastoid process and the mandible ramus.",
      ],
      clinicalConsiderations: "Classic “stiff neck” / torticollis presentation with restricted contralateral neck rotation. Often related to bag/purse straps, phone-cradling, poor monitor position, or psychological stress.",
      source: `${SRC}, pp.149–151`,
      images: [null, null, null],
    },
    {
      id: "palp_posterior_deltoid",
      name: "Posterior Deltoid",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Spine of the scapula",
        insertion: "Deltoid tuberosity of the humerus",
      },
      actions: "Extends, abducts, laterally rotates, and horizontally extends the arm at the shoulder joint.",
      patientPosition: "Prone, arm abducted 90° and resting on the table, forearm hanging off the table.",
      therapistPosition: "Standing or seated to the side of the client.",
      handPlacement: "Just inferior to the lateral end of the spine of the scapula; support hand on the distal arm.",
      steps: [
        "Ask the client to horizontally extend the arm (lift straight up toward the ceiling); feel for the posterior fibres contracting. Resistance can be added.",
        "Palpate from the spine of the scapula to the deltoid tuberosity.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Contraction of the posterior fibres just inferior to the scapular spine, tracking distally to the deltoid tuberosity.",
      notes: [
        "Do not ask for lateral rotation to isolate this muscle — infraspinatus/teres minor will also engage, blurring the inferior border.",
      ],
      clinicalConsiderations: "Overuse from prolonged abduction/extension (e.g. keyboard work) or direct trauma. Often confused with rotator cuff tear, subdeltoid bursitis, or joint arthritis.",
      source: `${SRC}, pp.152–153`,
      images: [null, null, null],
    },
    {
      id: "palp_infraspinatus_teres_minor",
      name: "Infraspinatus & Teres Minor",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Infraspinatus: infraspinous fossa of the scapula. Teres minor: superior 2/3 of the dorsal surface of the lateral border of the scapula.",
        insertion: "Both to the greater tubercle of the humerus.",
      },
      actions: "Infraspinatus: laterally rotates the arm. Teres minor: laterally rotates and adducts the arm.",
      patientPosition: "Prone, arm resting on the table, forearm hanging off the table.",
      therapistPosition: "Seated to the side of the client, client's forearm between your knees.",
      handPlacement: "Just inferior to the spine of the scapula, in the infraspinous fossa.",
      steps: [
        "Ask the client to laterally rotate the arm against the resistance of your knee; feel for infraspinatus contraction in the infraspinous fossa.",
        "Continue palpating distally toward the greater tubercle, strumming perpendicular to the fibres.",
        "Locate the superior lateral border of the scapula for teres minor; feel it contract with the same lateral-rotation action.",
        "Continue palpating its tendon toward the greater tubercle.",
        "Once located, relax both and assess baseline tone.",
      ],
      feelFor: "Contraction with resisted lateral rotation; distinguishing the two from teres major by alternating lateral (teres minor/infraspinatus) vs medial (teres major) rotation.",
      notes: [
        "Distal tendons run deep to the posterior deltoid, which also contracts with lateral rotation — use a very gentle contraction, or flex the shoulder (seated), to reduce deltoid interference.",
        "The infraspinatus/teres minor border can be hard to find; the teres minor/teres major border is easier (alternate lateral vs medial rotation).",
      ],
      clinicalConsiderations: "Restricts medial rotation (e.g. reaching to the lower back); infraspinatus TrPs give deep anterior shoulder pain, teres minor TrPs can cause quadrilateral space syndrome (axillary nerve entrapment). Often misread as rotator cuff lesions or cervical disc syndrome.",
      source: `${SRC}, pp.154–157`,
      images: [null, null, null],
    },
    {
      id: "palp_teres_major",
      name: "Teres Major",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Inferior angle and inferior 1/3 of the dorsal surface of the lateral border of the scapula",
        insertion: "Medial lip of the bicipital groove of the humerus",
      },
      actions: "Medially rotates, adducts, and extends the arm; upwardly rotates the scapula.",
      patientPosition: "Prone, arm resting on the table, forearm hanging off the table.",
      therapistPosition: "Seated to the side of the client, client's forearm between your knees.",
      handPlacement: "Just lateral to the lower aspect of the lateral border of the scapula.",
      steps: [
        "Ask the client to medially rotate the arm against the resistance of your knee; feel for contraction at the inferior lateral border of the scapula.",
        "Continue palpating distally toward the humerus, strumming perpendicular to the fibres.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Contraction with resisted medial rotation, distinguished from teres minor (which contracts with lateral rotation instead).",
      notes: [
        "Can be hard to distinguish from latissimus dorsi, which sits next to it and shares the same actions; on the humerus, latissimus attaches more anteriorly, teres major slightly more distal.",
      ],
      clinicalConsiderations: "TrPs from forceful arm extension (e.g. rowing) give deep posterior-shoulder pain, restricted abduction, or scapular winging/lateral tilt.",
      source: `${SRC}, pp.158–159`,
      images: [null, null, null],
    },
    {
      id: "palp_latissimus_dorsi_detour",
      name: "Latissimus Dorsi (detour)",
      type: "Muscle",
      position: "Prone",
      handPlacement: "Alongside teres major, at the posterior axillary fold.",
      steps: [
        "With the client prone, ask for resisted extension or medial rotation of the arm and palpate alongside the teres major.",
      ],
      feelFor: "The tendon is more easily distinguished at the humerus than teres major's, since it attaches more anteriorly (more superficial of the two tendons).",
      clinicalConsiderations: "Full palpation of latissimus dorsi is covered separately in Tour #7 (Chapter 16, p.353) — not yet added to this library.",
      source: `${SRC}, p.159`,
      images: [null, null, null],
    },
    {
      id: "palp_supraspinatus",
      name: "Supraspinatus",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Supraspinous fossa of the scapula",
        insertion: "Greater tubercle of the humerus",
      },
      actions: "Abducts and flexes the arm at the shoulder joint.",
      patientPosition: "Prone, arm resting on the table at the side of the body.",
      therapistPosition: "Seated to the side of the client.",
      handPlacement: "Just superior to the spine of the scapula, in the supraspinous fossa; support hand just proximal to the elbow if resistance is given.",
      steps: [
        "Ask for a very short (~10–20°) shoulder abduction; feel for the belly contracting in the supraspinous fossa.",
        "Gentle resistance from the support hand can bring out the contraction further.",
        "For the distal tendon: locate the acromion process and drop just distally/laterally off it, deep to the deltoid.",
        "Strum perpendicular to the distal tendon with the muscle either relaxed or gently contracting.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "The belly contracting superior to the scapular spine on a short abduction; the distal tendon deep to the deltoid just off the acromion.",
      notes: [
        "The upper trapezius (superficial to supraspinatus) also stabilizes the scapula during abduction — asking for movement halfway between abduction and flexion (seated) minimizes trapezius interference.",
        "Two ways to find the distal tendon: follow the scapular spine line to just distal of the acromion, or find the bicipital groove and palpate just posterior to it on the greater tubercle.",
      ],
      clinicalConsiderations: "TrPs from sustained overhead work, carrying weight with the arm hanging, or trauma. Produces joint crepitus, painful abduction, and tenderness at the humeral attachment. Often misdiagnosed as rotator cuff tendinitis, bursitis, cervical disc syndrome, or frozen shoulder. Shares a referral zone with infraspinatus at the lateral shoulder, though infraspinatus referral tends to be a deeper ache.",
      source: `${SRC}, pp.160–162`,
      images: [null, null, null],
    },
    {
      id: "palp_anterior_deltoid",
      name: "Anterior Deltoid",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Lateral 1/3 of the clavicle",
        insertion: "Deltoid tuberosity of the humerus",
      },
      actions: "Flexes, abducts, medially rotates, and horizontally flexes the arm at the shoulder joint.",
      patientPosition: "Supine, arm resting on the table against the body.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just inferior to the lateral end of the clavicle; support hand just proximal to the elbow.",
      steps: [
        "Ask the client to lift the arm halfway between flexion and abduction; feel for the anterior deltoid contracting.",
        "Gentle resistance from the support hand brings out the contraction further.",
        "Strum the fibres perpendicular, from the lateral clavicle to the deltoid tuberosity.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "A palpable gap between the anterior deltoid and the clavicular head of pectoralis major when both are contracted.",
      notes: [
        "The clavicular head of pectoralis major usually co-contracts with horizontal flexion — expect it, don't mistake it for deltoid.",
      ],
      clinicalConsiderations: "Overuse from sustained abduction/flexion or direct trauma. Often confused with rotator cuff tear, bicipital tendinitis, or subacromial bursitis.",
      source: `${SRC}, pp.163–164`,
      images: [null, null, null],
    },
    {
      id: "palp_subscapularis",
      name: "Subscapularis",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Subscapular fossa of the scapula",
        insertion: "Lesser tubercle of the humerus",
      },
      actions: "Medially rotates the arm at the shoulder joint.",
      patientPosition: "Supine, arm resting on the trunk, other hand gently holding the elbow of the side being palpated.",
      therapistPosition: "Seated to the side of the client.",
      handPlacement: "Finger pads against the anterior surface of the scapula; support hand reaches under the body to grip the medial border of the scapula.",
      steps: [
        "Passively retract the client's scapula with your support hand.",
        "Ask the client to take a deep breath; as they exhale, slowly and firmly press your finger pads against the anterior scapular surface.",
        "Verify placement by asking for medial rotation (the arm will lift slightly) and feeling for the contraction.",
        "Palpate as much of the muscle as possible, pressing deeper toward the medial border.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "A firm sheet against the anterior scapula that contracts on medial rotation; the distal tendon near the lesser tubercle after following the muscle in small steps.",
      notes: [
        "Sink in slowly, on the exhale, with a firm confident touch — not painful for the client if done this way.",
        "Subscapularis (anterior scapular surface) and serratus anterior (rib cage wall) are both between scapula and ribs — orientation of your finger pads is what separates the two.",
      ],
      clinicalConsiderations: "TrPs from overuse (e.g. swimming), trauma, prolonged immobilization in medial rotation, or chronic rounded-shoulder posture. Restricts and pains lateral rotation (and therefore full abduction). Often confused with frozen shoulder, rotator cuff lesions, or thoracic outlet syndrome.",
      source: `${SRC}, pp.165–168`,
      images: [null, null, null],
    },
    {
      id: "palp_serratus_anterior",
      name: "Serratus Anterior",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Anterolateral surfaces of ribs one through nine",
        insertion: "Anterior surface of the entire medial border of the scapula",
      },
      actions: "Protracts and upwardly rotates the scapula; upper fibres can elevate, lower fibres can depress the scapula.",
      patientPosition: "Supine, arm straight up in the air pointed at the ceiling.",
      therapistPosition: "Seated to the side of the client.",
      handPlacement: "Finger pads against the lateral rib cage wall, directly inferior to the axilla.",
      steps: [
        "Ask the client to reach the hand toward the ceiling (scapular protraction); feel for the contraction.",
        "Resistance can be added with the support hand.",
        "Continue palpating as much of the muscle as possible.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "A sheet contracting against the lateral rib wall on protraction; upper fibres (angle the arm ~135° flexion) vs lower fibres (angle the arm ~45° flexion) separately.",
      notes: [
        "Upper fibres near the first two ribs are extremely difficult to access; sink in slowly and firmly deep to pectoralis major.",
        "Serratus anterior (rib cage) and subscapularis (anterior scapula) sit in the same interval — finger-pad orientation distinguishes them.",
      ],
      clinicalConsiderations: "TrPs from push-ups, punching, racquet sports, or laboured breathing. Restricts scapular retraction; can mimic angina/heart attack referral if on the left side, or costochondritis, rib dysfunction, thoracic outlet syndrome.",
      source: `${SRC}, pp.169–171`,
      images: [null, null, null],
    },
    {
      id: "palp_pectoralis_major",
      name: "Pectoralis Major",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Medial half of the clavicle, sternum, and costal cartilages of ribs one through seven",
        insertion: "Lateral lip of the bicipital groove of the humerus",
      },
      actions: "Whole muscle: adducts, medially rotates, horizontally flexes the arm; protracts the scapula. Clavicular head: flexes the arm. Sternocostal head: extends the arm from flexion; depresses the scapula.",
      patientPosition: "Supine, arm resting at the side.",
      therapistPosition: "Seated to the side of the client.",
      handPlacement: "Over the lower aspect of the anterior axillary fold of tissue for the sternocostal head; just inferior to the medial clavicle for the clavicular head.",
      steps: [
        "Sternocostal head: ask the client to adduct the arm against resistance (or against the body wall); feel for contraction and palpate toward the medial attachment.",
        "Clavicular head: place the hand just inferior to the medial clavicle, ask for an oblique flexion+adduction movement against resistance.",
        "Feel for the clavicular head contracting and palpate toward the distal attachment, strumming perpendicular.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "A visible/palpable groove between the clavicular head and the anterior deltoid, and between the two heads of pectoralis major during resisted horizontal flexion.",
      notes: [
        "Abducting the arm away from the body lets you grasp the whole anterior axillary fold (the muscle) between your fingers.",
      ],
      clinicalConsiderations: "TrPs from repetitive lifting/adduction, rounded-shoulder posture, sling/cast use, or tight bra straps; a TrP between ribs 5–6 on the right has been linked to cardiac arrhythmia. Can mimic angina/MI (especially left-sided), rib dysfunction, or costochondritis.",
      source: `${SRC}, pp.172–174`,
      images: [null, null, null],
    },
    {
      id: "palp_pectoralis_minor",
      name: "Pectoralis Minor",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Ribs three through five",
        insertion: "Medial surface of the coracoid process of the scapula",
      },
      actions: "Protracts, depresses, and downwardly rotates the scapula; elevates ribs 3–5.",
      patientPosition: "Supine, hand under the body in the small of the back.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just inferior to the coracoid process of the scapula.",
      steps: [
        "Ask the client to press the hand/forearm down against the table; feel for the contraction through pectoralis major.",
        "Continue palpating toward the rib attachments, strumming perpendicular to the fibres.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Contraction felt through pectoralis major; usually possible to distinguish each of its three slips individually.",
      notes: [
        "This action requires downward rotation of the scapula — easiest to feel with the client seated instead.",
      ],
      clinicalConsiderations: "TrPs can cause pectoralis minor syndrome (neurologic/vascular symptoms in the arm), rounded-shoulder posture, or scapular winging. Overuse, sling/cast use, heavy backpack straps, or referral from pectoralis major/scalene TrPs are common causes.",
      source: `${SRC}, pp.175–176`,
      images: [null, null, null],
    },
    {
      id: "palp_subclavius",
      name: "Subclavius",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "First rib at the junction with its costal cartilage",
        insertion: "Middle 1/3 of the inferior surface of the clavicle",
      },
      actions: "Depresses, protracts, and downwardly rotates the clavicle; elevates the first rib.",
      patientPosition: "Supine, arm medially rotated at the shoulder and resting on the table.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Fingers curled around the clavicle, finger pads on its inferior surface.",
      steps: [
        "With the region relaxed, feel for the subclavius on the underside of the clavicle.",
        "Ask the client to depress the shoulder girdle (scapula and clavicle); feel for the contraction.",
        "Palpate from attachment to attachment.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "A narrow band under the clavicle, more accessible with the arm passively medially rotated (slackens pectoralis major) and passively abducted (upwardly rotates the clavicle, exposing more of its inferior surface).",
      notes: [
        "Described in the source as one of the more challenging structures in this tour to palpate confidently.",
      ],
      clinicalConsiderations: "TrPs can produce costoclavicular syndrome (neurologic/vascular arm symptoms). Often confused with cervical disc syndrome, anterior scalene syndrome, or pectoralis minor syndrome.",
      source: `${SRC}, pp.177–178`,
      images: [null, null, null],
    },
  ],

  cervical: [
    {
      id: "palp_scm",
      name: "Sternocleidomastoid (SCM)",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Manubrium of the sternum and the medial 1/3 of the clavicle",
        insertion: "Mastoid process of the temporal bone and the lateral 1/3 of the superior nuchal line of the occiput",
      },
      actions: "Flexes the lower neck and extends the head/upper neck; laterally flexes and contralaterally rotates the head and neck; elevates the sternum and clavicle.",
      patientPosition: "Supine, head and neck contralaterally rotated.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just superior to the sternoclavicular joint.",
      steps: [
        "Ask the client to lift the head and neck from the table; look for the SCM to become visible.",
        "Resistance is often unnecessary — lifting against gravity usually provides enough.",
        "Palpate toward the superior attachment, strumming perpendicular to the fibres.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "The sternal head (usually clearly visible) and the clavicular head (less obvious — palpate just lateral to the inferior sternal head if not visible); a gap between the two heads that varies a lot between people.",
      notes: [
        "Pincer palpation (not flat palpation) is recommended — the carotid sinus lies deep to the SCM, and flat pressure against it can trigger a reflex that lowers blood pressure.",
        "The SCM forms the anterior border of the posterior triangle of the neck and is a key landmark for locating the scalenes and the longus colli/capitis.",
      ],
      clinicalConsiderations: "TrPs commonly relate to sustained head-turned postures, protracted head posture, tight collars/ties, or whiplash. Can produce headaches, restricted neck ROM, sore throat, and autonomic symptoms (eye symptoms from the sternal head, vasoconstriction/sweating from the clavicular head). Often misread as swollen lymph nodes, sinus/migraine headache, or TMJ dysfunction.",
      source: `${SRC_NECK}, pp.187–189`,
      images: [null, null, null],
    },
    {
      id: "palp_platysma",
      name: "Platysma (detour)",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Subcutaneous fascia of the superior chest",
        insertion: "Mandible and subcutaneous fascia of the lower face",
      },
      actions: "Creates wrinkles in the neck skin when contracted; a very thin superficial sheet, not a prime mover.",
      steps: [
        "Ask the client to forcefully depress and draw the lower lip laterally while keeping the mandible slightly depressed.",
      ],
      feelFor: "A thin superficial sheet over the SCM, visible as neck-skin wrinkling on contraction.",
      clinicalConsiderations: "TrPs relate to habitual facial expressions (disgust/horror) or TrPs in the SCM/scalenes; produce prickly pain over the mandible. TrPs are usually located over the SCM.",
      source: `${SRC_NECK}, p.189`,
      images: [null, null, null],
    },
    {
      id: "palp_scalene_group",
      name: "Scalene Group (anterior, middle, posterior)",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Anterior: first rib. Middle: first rib. Posterior: second rib.",
        insertion: "Transverse processes of C3–C6 (anterior), C2–C7 (middle), C5–C7 (posterior).",
      },
      actions: "Anterior: flexes, laterally flexes, contralaterally rotates the neck; elevates rib 1. Middle: flexes and laterally flexes the neck; elevates rib 1. Posterior: laterally flexes the neck; elevates rib 2.",
      patientPosition: "Supine.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Posterior triangle of the neck, just superior to the clavicle and just lateral to the clavicular head of the SCM.",
      steps: [
        "Locate the lateral border of the clavicular head of the SCM, then drop immediately off it laterally onto the scalenes.",
        "With finger pads on the scalenes, ask the client to take short, quick breaths through the nose; feel for the contraction.",
        "Palpate as much of the scalenes as possible in the posterior triangle (between SCM, upper trapezius, levator scapulae, and clavicle), strumming perpendicular to the fibres.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Anterior scalene (mostly deep to SCM, fibres toward C3–C6), middle scalene (most present in the posterior triangle, fibres toward C2–C7, hardest of the three to isolate), posterior scalene (deepest/hardest to find, fibres nearly horizontal toward C5–C7, just anterior to upper trapezius/levator scapulae).",
      notes: [
        "To access the transverse-process attachments deep to the SCM, first slacken the SCM (passive flexion + same-side lateral flexion), then sink in slowly toward the spine.",
        "Palpate carefully — the brachial plexus and subclavian artery run between the anterior and middle scalenes.",
      ],
      clinicalConsiderations: "TrPs relate to coughing, laboured breathing, or trauma (MVA). Can produce thoracic outlet syndrome, restricted neck rotation/lateral flexion, or first/second rib dysfunction. Often confused with cervical disc syndrome, angina (left side), or carpal tunnel syndrome.",
      source: `${SRC_NECK}, pp.190–193`,
      images: [null, null, null],
    },
    {
      id: "palp_omohyoid_inferior_belly",
      name: "Omohyoid, Inferior Belly (detour)",
      type: "Muscle",
      position: "Supine",
      handPlacement: "Posterior triangle of the neck, just lateral to the SCM and superior to the clavicle.",
      steps: [
        "Feel for the horizontal fibres of the omohyoid as the client depresses the mandible at the TMJs against resistance.",
      ],
      feelFor: "Fairly easily palpable horizontal fibres in the posterior triangle.",
      clinicalConsiderations: "See the full Hyoid Group entry for its trigger-point notes (its tension is thought to contribute to thoracic outlet syndrome via the brachial plexus).",
      source: `${SRC_NECK}, p.193`,
      images: [null, null, null],
    },
    {
      id: "palp_longus_colli_capitis",
      name: "Longus Colli & Longus Capitis",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Longus colli: vertebral bodies/transverse processes between T3 and C1. Longus capitis: transverse processes of C3–C5.",
        insertion: "Longus colli: superior vertebral bodies/transverse processes. Longus capitis: occiput.",
      },
      actions: "Longus colli: flexes, laterally flexes, contralaterally rotates the neck. Longus capitis: flexes and laterally flexes the head and neck.",
      patientPosition: "Supine.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just medial to the sternal head of the SCM; support hand on the forehead if resistance is needed.",
      steps: [
        "Locate the medial border of the sternal head of the SCM, then drop immediately off it medially.",
        "Gently, slowly, but firmly sink toward the anterior surface of the cervical vertebral bodies.",
        "Confirm placement by asking the client to lift the head into flexion and feel for the contraction.",
        "Strum perpendicular to the fibres, palpating as far superiorly and inferiorly as possible.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Firm cord-like muscle against the anterior vertebral bodies; if you feel a pulse, you're on the carotid artery — move slightly to one side.",
      notes: [
        "Sink in slowly and gently but firmly — the anterior neck has several fragile structures (carotid sinus, trachea).",
        "If it's hard to discern from the SCM, ask the client to rotate the head/neck to the same side being palpated to relax the SCM.",
      ],
      clinicalConsiderations: "Frequently injured in whiplash. TrPs cause sore throat, difficulty swallowing, and tight posterior neck muscles compensating. Referral patterns for this muscle group have not been well mapped.",
      source: `${SRC_NECK}, pp.194–196`,
      images: [null, null, null],
    },
    {
      id: "palp_rectus_capitis_ant_lat",
      name: "Rectus Capitis Anterior & Lateralis (detour)",
      type: "Muscle",
      position: "Supine or seated",
      attachments: {
        origin: "Occiput (both)",
        insertion: "Transverse process of the atlas (C1)",
      },
      actions: "Anterior: flexes the head at the atlanto-occipital joint. Lateralis: laterally flexes the head at the atlanto-occipital joint.",
      handPlacement: "Immediately superior to the transverse process of the atlas (posterior to the mandible ramus, inferior to the ear) for the lateralis; the anterior is too deep to palpate.",
      steps: [
        "Press gently into the small depression just superior to the C1 transverse process and feel for the rectus capitis lateralis.",
      ],
      feelFor: "Can be very difficult to discern from adjacent soft tissue.",
      notes: [
        "Be careful not to press too forcefully — the facial nerve and styloid process are nearby.",
      ],
      clinicalConsiderations: "Rectus capitis anterior is extremely deep and usually not palpable. TrP referral zones for both muscles have not been mapped out.",
      source: `${SRC_NECK}, p.196`,
      images: [null, null, null],
    },
    {
      id: "palp_hyoid_group",
      name: "Hyoid Group (infra- & suprahyoids)",
      type: "Muscle group",
      position: "Supine",
      attachments: {
        origin: "Infrahyoids: sternum/scapula/thyroid cartilage. Suprahyoids: mastoid notch/styloid process/mandible.",
        insertion: "All attach to the hyoid bone (digastric via a central tendon; omohyoid has a central tendon to the clavicle).",
      },
      actions: "Depresses the mandible at the TMJs; flexes the head and neck. Infrahyoids depress the hyoid; suprahyoids elevate it.",
      patientPosition: "Supine.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Immediately inferior to the hyoid, just off centre, for the infrahyoids; support hand under the chin.",
      steps: [
        "Infrahyoids: resist mandibular depression at the TMJs; feel for the contraction, strumming perpendicular to the fibres.",
        "Continue palpating inferiorly toward the sternum.",
        "Suprahyoids: place the hand just inferior to the mandible, resist depression, and feel for the contraction.",
        "Continue toward the hyoid bone, strumming perpendicular.",
        "For stylohyoid and the digastric's superior belly, continue laterally from the hyoid toward the mastoid process while resisting mandibular depression.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Multiple small, thin muscles that can be hard to discern from each other; all contract together when mandibular depression is resisted.",
      clinicalConsiderations: "Of the group, digastric referral is best mapped: inferior belly TrPs cause lower incisor/tongue/throat pain and swallowing difficulty; superior belly TrPs relate to occipitofrontalis TrPs. Stylohyoid can entrap the external carotid artery. Omohyoid tension is thought to contribute to thoracic outlet syndrome. Often misread as dental problems.",
      source: `${SRC_NECK}, pp.197–200`,
      images: [null, null, null],
    },
    {
      id: "palp_upper_trapezius_seated",
      name: "Upper Trapezius (seated variant)",
      type: "Muscle",
      position: "Seated",
      attachments: {
        origin: "External occipital protuberance, medial 1/3 of the superior nuchal line, nuchal ligament, spinous process of C7",
        insertion: "Lateral clavicle and acromion process",
      },
      actions: "Elevates, retracts, upwardly rotates the scapula; extends, laterally flexes, contralaterally rotates the head and neck.",
      patientPosition: "Seated, head and neck rotated contralaterally.",
      therapistPosition: "Standing to the side of the client.",
      handPlacement: "On the upper trapezius at the top of the shoulder; support hand on the back of the head.",
      steps: [
        "Resist extension of the head and neck; look and feel for the contraction.",
        "Continue palpating superiorly to the occiput and inferiorly to the scapula/clavicle, strumming perpendicular.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Contraction visible/palpable at the top of the shoulder; contralateral head rotation reciprocally inhibits splenius capitis/cervicis, isolating the trapezius more forcefully.",
      notes: [
        "Same muscle as the prone Trapezius entry in Shoulder Girdle (source pp.142–145) — this is the book's seated variant, useful when the client can't lie prone.",
      ],
      clinicalConsiderations: "See the Trapezius entry in Shoulder Girdle for full trigger-point notes — this is the most commonly found TrP location in the body.",
      source: `${SRC_NECK}, pp.201–203`,
      images: [null, null, null],
    },
    {
      id: "palp_levator_scapulae_seated",
      name: "Levator Scapulae (seated variant)",
      type: "Muscle",
      position: "Seated",
      attachments: {
        origin: "Transverse processes of C1–C4",
        insertion: "Medial border of the scapula, root of the spine to the superior angle",
      },
      actions: "Elevates and downwardly rotates the scapula; extends, laterally flexes, ipsilaterally rotates the neck.",
      patientPosition: "Seated, hand in the small of the back.",
      therapistPosition: "Standing behind or to the side of the client.",
      handPlacement: "Just superior and medial to the superior angle of the scapula; support hand on top of the shoulder.",
      steps: [
        "With the hand in the small of the back, ask for a gentle, short scapular elevation; feel for the contraction deep to the trapezius.",
        "Continue palpating toward the superior attachment, strumming perpendicular.",
        "Once in the posterior triangle, the hand can leave the low back and elevation can be more forceful/resisted.",
        "Palpate as far superiorly as possible (near its top attachment it runs deep to the SCM).",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Same three-part accessibility as the prone version: deep to trapezius near the scapula, superficial in the posterior triangle, deep to the SCM near its spinal attachment.",
      notes: [
        "Same muscle as the prone Levator Scapulae entry in Shoulder Girdle (source pp.149–151) — this is the seated variant, and includes an extra note on reaching the superior attachment under the SCM by first slackening it (flex + ipsilateral lateral flex).",
      ],
      clinicalConsiderations: "See the Shoulder Girdle Levator Scapulae entry for full trigger-point notes (classic “stiff neck”/torticollis presentation).",
      source: `${SRC_NECK}, pp.204–206`,
      images: [null, null, null],
    },
    {
      id: "palp_splenius_capitis",
      name: "Splenius Capitis",
      type: "Muscle",
      position: "Seated",
      attachments: {
        origin: "Nuchal ligament (C3–C6 level) and spinous processes of C7–T4",
        insertion: "Mastoid process of the temporal bone and lateral 1/4 of the superior nuchal line",
      },
      actions: "Extends, laterally flexes, and ipsilaterally rotates the head and neck.",
      patientPosition: "Seated, head and neck ipsilaterally rotated.",
      therapistPosition: "Standing behind the client.",
      handPlacement: "Upper posterior triangle, just inferior to the occiput and just posterior to the SCM (superficial here).",
      steps: [
        "With the head/neck ipsilaterally rotated, resist extension and feel for the contraction.",
        "Strum perpendicular to the fibres in the posterior triangle until reaching the upper trapezius border.",
        "Alternate resisted extension/relaxation to feel it contracting deep to the upper trapezius; continue as far inferiorly as possible.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Ipsilateral rotation reciprocally relaxes the SCM and upper trapezius, making the splenius capitis easier to isolate; only gentle resistance is needed or the trapezius will override it.",
      notes: [
        "The inferior attachment on the upper thoracic spinous processes can be reached by pressing anterior to the upper trapezius border, downward toward the spinous processes.",
      ],
      clinicalConsiderations: "TrPs relate to prolonged forward-head or rotated-neck postures (e.g. off-centre monitor) or whiplash. Cause restricted flexion/contralateral rotation, restricted same-side rotation, or headaches. Often confused with cervical joint dysfunction or migraine.",
      source: `${SRC_NECK}, pp.207–208`,
      images: [null, null, null],
    },
    {
      id: "palp_splenius_cervicis",
      name: "Splenius Cervicis (detour)",
      type: "Muscle",
      position: "Seated",
      attachments: {
        origin: "Spinous processes of T3–T6",
        insertion: "Transverse processes of C1–C3",
      },
      actions: "Same as splenius capitis but moves only the neck, not the head.",
      handPlacement: "Between the levator scapulae and splenius capitis.",
      steps: [
        "Ask the client to ipsilaterally rotate the neck (against resistance if needed) and feel for the contraction.",
        "Follow toward both attachments once located.",
      ],
      feelFor: "Deep to other musculature for its entire course — best first located between levator scapulae and splenius capitis.",
      clinicalConsiderations: "Same TrP-perpetuating factors as splenius capitis. Can cause headaches, eye pain, or ipsilateral visual blurriness.",
      source: `${SRC_NECK}, p.209`,
      images: [null, null, null],
    },
    {
      id: "palp_semispinalis_capitis",
      name: "Semispinalis Capitis",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Transverse processes of C7–T6 and articular processes of C4–C6",
        insertion: "Medial 1/3 of the occipital bone, between the superior and inferior nuchal lines",
      },
      actions: "Extends and laterally flexes the head and neck.",
      patientPosition: "Supine, hand in the small of the back and/or head/neck ipsilaterally rotated.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just below the occiput, just lateral to the midline (over the laminar groove).",
      steps: [
        "Ask the client to gently press the head into the table (extension); feel for the contraction deep to the upper trapezius.",
        "Continue palpating superiorly to the occiput and inferiorly, strumming perpendicular to the fibres.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "The largest, thickest muscle of the neck (bigger than the better-known upper trapezius), contracting deep to the trapezius.",
      notes: [
        "Only gentle extension is needed — a forceful contraction overrides the reciprocal inhibition of the upper trapezius and blocks palpation.",
      ],
      clinicalConsiderations: "TrPs relate to protracted head posture, prone reading/elbow-propping, whiplash, or cervical osteoarthritis. Can cause headaches, restricted flexion, or greater occipital nerve entrapment (posterior scalp tingling/pain).",
      source: `${SRC_NECK}, pp.210–211`,
      images: [null, null, null],
    },
    {
      id: "palp_longissimus_capitis_group",
      name: "Longissimus Capitis, Semispinalis Cervicis, Cervical Multifidus & Rotatores (detour)",
      type: "Muscle group",
      position: "Supine",
      attachments: {
        origin: "Longissimus capitis: transverse/articular processes of C5–T5. Semispinalis cervicis: transverse processes of T1–T5.",
        insertion: "Longissimus capitis: mastoid process. Semispinalis cervicis: spinous processes of C2–C5.",
      },
      actions: "Extension and (for longissimus capitis) ipsilateral rotation of the head/neck; multifidus and rotatores extend and contralaterally rotate the neck.",
      handPlacement: "Lateral to the splenius capitis, deep to the levator scapulae and upper trapezius, for longissimus capitis.",
      steps: [
        "Gentle head extension against the table with the head/neck ipsilaterally rotated brings out the contraction.",
      ],
      feelFor: "All deep and challenging to palpate/discern — the cervical multifidus and rotatores are very deep within the laminar groove.",
      clinicalConsiderations: "Longissimus capitis TrPs refer pain posterior to the ear; semispinalis cervicis refers similarly to semispinalis capitis; cervical multifidus refers to the suboccipital region and medial scapular border; rotatores refer to the spinal midline at the TrP's segmental level.",
      source: `${SRC_NECK}, p.212`,
      images: [null, null, null],
    },
    {
      id: "palp_suboccipital_group",
      name: "Suboccipital Group",
      type: "Muscle group",
      position: "Supine",
      attachments: {
        origin: "RCPMaj: spinous process of C2. RCPMin: posterior tubercle of C1. OCI: spinous process of C2. OCS: transverse process of C1.",
        insertion: "RCPMaj/RCPMin/OCS: occiput (nuchal lines). OCI: transverse process of C1.",
      },
      actions: "As a group: extends and anteriorly translates the head at the atlanto-occipital joint. Obliquus capitis inferior also ipsilaterally rotates the atlas at the atlantoaxial joint.",
      patientPosition: "Supine.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just superior and slightly lateral to the spinous process of C2 (the axis).",
      steps: [
        "Rectus capitis posterior major (easiest to find): palpate just superolateral to the C2 spinous process, strumming perpendicular; follow superolaterally toward the occiput.",
        "Rectus capitis posterior minor: same approach starting just superolateral to the posterior tubercle of C1; anterior translation of the head can bring out its contraction.",
        "Obliquus capitis inferior: palpate between the C2 spinous process and the C1 transverse process; gentle resisted ipsilateral head rotation helps engage it.",
        "Obliquus capitis superior (most difficult): feel just lateral to the superior attachment of RCPMaj.",
        "Once located, relax and assess baseline tone.",
      ],
      feelFor: "Deep muscles, best felt when relaxed; RCPMaj is the easiest of the four to distinguish, OCS the hardest.",
      notes: [
        "Palpate the suboccipital triangle carefully — the vertebral artery and suboccipital nerve pass through it, and the greater occipital nerve is nearby.",
      ],
      clinicalConsiderations: "TrPs relate to sustained head extension/rotation, chronic forward-head posture, whiplash, or atlanto-occipital/atlantoaxial joint dysfunction. Produce diffuse, hard-to-localize headache pain and restricted flexion/rotation. Often misread as migraine or greater occipital neuralgia.",
      source: `${SRC_NECK}, pp.213–216`,
      images: [null, null, null],
    },
  ],
};
