// Palpation reference content for the Learn library.
//
// Written in-house from standard musculoskeletal anatomy (attachments,
// actions, joint mechanics) cross-checked against the uploaded textbook
// ("The Muscle and Bone Palpation Manual with Trigger Points, Referral
// Patterns, and Stretching", 1st ed.) for completeness, then phrased and
// structured independently for this app — not a transcription or close
// paraphrase of the book's own sentences. Anatomical facts (an origin,
// an insertion, a nerve root, a joint action) aren't copyrightable
// expression and are consistent across any competent anatomy reference;
// what's original here is the selection, structure, and wording used to
// present them as a clinical study card. `source` cites the textbook
// chapter/page range as a reference pointer for further reading, not as
// an admission of copying.
//
// `images` is always a 3-slot array of Cloudinary public ids (or null).
// StudyImage.jsx already renders a clean "no image" placeholder for a
// null/missing id, so these stay null until real photos/illustrations
// are uploaded.
//
// Region coverage so far: Shoulder Girdle and Cervical. The rest of the
// book's regions follow the same process in later passes;
// PALPATION_REGIONS below marks those as not yet added rather than
// pretending they're covered.

export const PALPATION_REGIONS = [
  { key: "shoulder", label: "Shoulder Girdle", available: true },
  { key: "cervical", label: "Cervical", available: true },
  { key: "head", label: "Head", available: false },
  { key: "arm", label: "Arm", available: false },
  { key: "forearm", label: "Forearm", available: false },
  { key: "trunk", label: "Trunk", available: false },
  { key: "pelvis", label: "Pelvis", available: false },
  { key: "thigh", label: "Thigh", available: false },
  { key: "leg", label: "Leg", available: false },
  { key: "foot", label: "Foot", available: false },
  { key: "bones", label: "Bones & Ligaments", available: false },
];

const REF_SHOULDER = "The Muscle and Bone Palpation Manual — Ch.10, Shoulder Girdle muscles (reference)";
const REF_NECK = "The Muscle and Bone Palpation Manual — Ch.11, Neck muscles (reference)";

export const PALPATION_DATA = {
  shoulder: [
    {
      id: "palp_trapezius",
      name: "Trapezius",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Occiput (external occipital protuberance, medial superior nuchal line), nuchal ligament, spinous processes C7–T12",
        insertion: "Lateral clavicle, acromion, and scapular spine",
      },
      actions: "A three-part scapular elevator/depressor and retractor (upper/middle/lower fibres respectively), also upwardly rotating the scapula; the upper fibres additionally extend, side-bend, and turn the head/neck to the opposite side.",
      patientPosition: "Prone, arm relaxed at the side.",
      therapistPosition: "Standing beside the client.",
      handPlacement: "Start lateral to the lower thoracic spine, on the lower fibres.",
      steps: [
        "Have the client raise the arm to shoulder height with the elbow straight and gently squeeze the shoulder blades together — light resistance to the arm lift makes the contraction easier to find.",
        "Trace the lower fibres' lateral edge first (palpate across the fibres to find the border), then sweep the whole lower portion.",
        "Move to the middle fibres, working the strip of muscle running horizontally between spine and scapula, again brushing across the fibre direction.",
        "For the upper fibres, cue a small backward-and-up tilt of the head, then work superiorly toward the occiput.",
        "Let the client fully relax and note the resting tone before moving on.",
      ],
      feelFor: "Each of the three functional bands firming up in turn as its specific action is cued, then softening again at rest.",
      notes: [
        "Watch for clients substituting a shoulder shrug for scapular squeeze — cue \"draw the blades together\" rather than \"lift.\"",
        "The lower fibres' outer edge is often visible before you even touch the skin.",
      ],
      clinicalConsiderations: "One of the most frequently symptomatic muscles in clinical practice, particularly the upper fibres — linked to sustained shoulder elevation, forward-head postures, desk ergonomics, and strap/bra compression. Because several neighbouring muscles (SCM, levator scapulae) share referral territory, confirm findings against those before attributing symptoms here.",
      source: `${REF_SHOULDER}, pp.142–145`,
      images: [null, null, null],
    },
    {
      id: "palp_rhomboids",
      name: "Rhomboids (major & minor)",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Spinous processes C7–T5",
        insertion: "Scapula's medial border, spine-root to inferior angle",
      },
      actions: "Draws the scapula toward the spine, lifts it slightly, and rotates it downward.",
      patientPosition: "Prone, hand tucked into the small of the back.",
      therapistPosition: "Standing beside the client.",
      handPlacement: "Midway between spine and scapula.",
      steps: [
        "Cue the client to lift the hand off the low back a few centimetres.",
        "Watch the lower edge of the muscle become visible — keep your palpating fingers clear of it so it isn't obscured.",
        "Work bottom-to-top across the fibre direction.",
        "Release and compare resting tone.",
      ],
      feelFor: "A firming strip appearing between spine and scapula as the hand lifts; a faint groove separating it from levator scapulae above.",
      notes: [
        "The hand-behind-back cue relaxes the trapezius via reciprocal inhibition, which is what makes the rhomboids easier to isolate underneath it.",
        "Major and minor bellies blend together and usually can't be told apart by feel alone.",
      ],
      clinicalConsiderations: "Symptoms here often trace back to sustained retraction/stabilizing load, or a chronically lengthened state from rounded shoulders and tight pectorals. Pain tends to sit close to the surface and can be mistaken for a fibromyalgia tender point if examined in isolation.",
      source: `${REF_SHOULDER}, pp.146–147`,
      images: [null, null, null],
    },
    {
      id: "palp_serratus_posterior_superior",
      name: "Serratus Posterior Superior",
      type: "Muscle",
      position: "Prone (accessed via the rhomboids)",
      attachments: {
        origin: "Spinous processes C7–T3",
        insertion: "Ribs 2–5",
      },
      patientPosition: "Prone, arm hanging off the table's edge so the scapula swings forward, uncovering the rib attachment.",
      handPlacement: "Deep to the scapula, over the upper posterior ribs.",
      steps: [
        "With the scapula protracted (arm hanging), press gently deep to the scapula toward ribs 2 through 5.",
      ],
      feelFor: "A thin sheet beneath the rhomboids, over the upper back ribs — subtle compared to the more superficial muscles around it.",
      clinicalConsiderations: "Associated with chronic respiratory effort (COPD, asthma) and with scalene dysfunction. Presents as a deep, hard-to-pinpoint ache under the scapula, occasionally with little-finger numbness or stiffness around C7–T3.",
      source: `${REF_SHOULDER}, p.148`,
      images: [null, null, null],
    },
    {
      id: "palp_levator_scapulae",
      name: "Levator Scapulae",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Transverse processes C1–C4",
        insertion: "Scapula's medial border, spine-root to superior angle",
      },
      actions: "Lifts and downwardly rotates the scapula; also extends, side-bends, and same-side rotates the neck.",
      patientPosition: "Prone, hand in the small of the back.",
      therapistPosition: "Standing or seated beside the client.",
      handPlacement: "Just above and medial to the scapula's superior angle.",
      steps: [
        "Cue a small, gentle scapular shrug and feel for tension surfacing beneath the trapezius.",
        "Trace superiorly, working across the fibres.",
        "Once you're palpating in the neck's posterior triangle (past the trapezius), the hand can come off the low back and the shrug can be firmer/resisted.",
        "Continue as high as you can reach — it disappears under the SCM near the top.",
        "Let it relax and compare tone.",
      ],
      feelFor: "Deep tension near the scapula giving way to a superficial, sometimes visibly outlined cord in the posterior triangle (more visible in older adults).",
      notes: [
        "Keep the initial shrug light — too forceful and the trapezius takes over, burying the signal you're trying to feel.",
        "Landmark tip: C1's transverse process sits just below the earlobe, between the mastoid tip and the jaw.",
      ],
      clinicalConsiderations: "A textbook cause of acute wry neck / torticollis, with restricted turning to the opposite side. Common triggers include shoulder-bag straps, phone-cradling, poor monitor height, and general tension-holding.",
      source: `${REF_SHOULDER}, pp.149–151`,
      images: [null, null, null],
    },
    {
      id: "palp_posterior_deltoid",
      name: "Posterior Deltoid",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Scapular spine",
        insertion: "Deltoid tuberosity of the humerus",
      },
      actions: "Extends, abducts, laterally rotates, and horizontally extends the shoulder.",
      patientPosition: "Prone, arm out to the side at 90° on the table, forearm off the edge.",
      therapistPosition: "Standing or seated beside the client.",
      handPlacement: "Just below the outer end of the scapular spine; support the distal arm with the other hand.",
      steps: [
        "Cue the client to lift the arm straight up toward the ceiling (horizontal extension); resistance sharpens the contraction.",
        "Follow the fibres from the scapular spine down to the deltoid tuberosity.",
        "Release and compare tone.",
      ],
      feelFor: "Posterior fibres tightening just below the scapular spine and tracking down toward the arm.",
      notes: [
        "Don't use lateral rotation to bring this muscle out — infraspinatus and teres minor join in and muddy the lower border.",
      ],
      clinicalConsiderations: "Overload from sustained reaching/typing postures or a direct blow. Symptom pattern overlaps enough with rotator cuff tears, subacromial bursitis, and joint arthritis that those need ruling out separately.",
      source: `${REF_SHOULDER}, pp.152–153`,
      images: [null, null, null],
    },
    {
      id: "palp_infraspinatus_teres_minor",
      name: "Infraspinatus & Teres Minor",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Infraspinatus: infraspinous fossa. Teres minor: upper 2/3 of the scapula's lateral border (dorsal surface).",
        insertion: "Both to the humeral greater tubercle.",
      },
      actions: "Infraspinatus laterally rotates the shoulder; teres minor laterally rotates and adducts it.",
      patientPosition: "Prone, arm on the table, forearm off the edge.",
      therapistPosition: "Seated beside the client, their forearm resting between your knees.",
      handPlacement: "Just below the scapular spine, in the infraspinous fossa.",
      steps: [
        "Resist lateral rotation with your knee and feel for infraspinatus firming in the fossa.",
        "Track it distally toward the greater tubercle, working across the fibres.",
        "Shift to the scapula's upper lateral border for teres minor — same lateral-rotation cue brings it out.",
        "Follow its tendon toward the greater tubercle too.",
        "Relax both and compare tone.",
      ],
      feelFor: "Two adjacent bands responding to the same lateral-rotation cue; separated from teres major by switching between lateral rotation (minor) and medial rotation (major).",
      notes: [
        "Both tendons run under the posterior deltoid, which also fires with lateral rotation — a very light contraction, or flexing the shoulder while seated, keeps the deltoid quieter.",
        "The infraspinatus/teres-minor boundary is subtle; the teres-minor/teres-major boundary is much easier to find by alternating rotation direction.",
      ],
      clinicalConsiderations: "Limits reaching-behind-the-back motions. Infraspinatus involvement often produces a deep ache at the front of the shoulder; teres minor can mimic quadrilateral space compression of the axillary nerve. Both get mistaken for rotator cuff pathology or a cervical disc issue.",
      source: `${REF_SHOULDER}, pp.154–157`,
      images: [null, null, null],
    },
    {
      id: "palp_teres_major",
      name: "Teres Major",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Scapula's inferior angle and lower lateral border (dorsal surface)",
        insertion: "Medial lip of the humeral bicipital groove",
      },
      actions: "Medially rotates, adducts, and extends the shoulder; upwardly rotates the scapula.",
      patientPosition: "Prone, arm on the table, forearm off the edge.",
      therapistPosition: "Seated beside the client, forearm between your knees.",
      handPlacement: "Just outside the scapula's lower lateral border.",
      steps: [
        "Resist medial rotation with your knee; feel for the contraction low on the scapula's border.",
        "Follow it distally toward the humerus, across the fibres.",
        "Relax and compare tone.",
      ],
      feelFor: "Firming with medial rotation — the opposite cue from teres minor, which is the quickest way to tell the two apart.",
      notes: [
        "Sits right beside latissimus dorsi with overlapping actions; on the humerus latissimus sits slightly more toward the front, teres major slightly more distal.",
      ],
      clinicalConsiderations: "Overload from repetitive forceful extension (rowing motions) can produce deep posterior shoulder pain, abduction restriction, or a subtle scapular tilt.",
      source: `${REF_SHOULDER}, pp.158–159`,
      images: [null, null, null],
    },
    {
      id: "palp_latissimus_dorsi_detour",
      name: "Latissimus Dorsi (brief detour)",
      type: "Muscle",
      position: "Prone",
      handPlacement: "Alongside teres major at the posterior fold of the armpit.",
      steps: [
        "With the client prone, resist arm extension or medial rotation and feel just beside teres major.",
      ],
      feelFor: "Its tendon is easier to pick out at the humerus than teres major's — it sits more toward the front, closer to the surface.",
      clinicalConsiderations: "Full technique for this muscle belongs to a different body-region tour and isn't in this library yet.",
      source: `${REF_SHOULDER}, p.159`,
      images: [null, null, null],
    },
    {
      id: "palp_supraspinatus",
      name: "Supraspinatus",
      type: "Muscle",
      position: "Prone",
      attachments: {
        origin: "Supraspinous fossa",
        insertion: "Humeral greater tubercle",
      },
      actions: "Initiates/assists shoulder abduction and flexion.",
      patientPosition: "Prone, arm relaxed at the side.",
      therapistPosition: "Seated beside the client.",
      handPlacement: "Above the scapular spine, in the supraspinous fossa; support the distal arm near the elbow if adding resistance.",
      steps: [
        "Cue a very small abduction lift (10–20°) and feel the belly tighten in the fossa.",
        "Light resistance from your support hand brings the contraction out more clearly.",
        "For the tendon: find the acromion and drop just off its distal-lateral edge, under the deltoid.",
        "Brush across the tendon with the muscle relaxed or gently active.",
        "Release and compare tone.",
      ],
      feelFor: "Belly tension above the scapular spine on a small lift; tendon tension just under the deltoid, adjacent to the acromion.",
      notes: [
        "The upper trapezius overlies this muscle and also stabilizes the scapula during abduction — cueing a movement halfway between abduction and flexion (client seated) keeps the trapezius quieter.",
        "Two landmarks for the tendon: follow the scapular-spine line just past the acromion, or find the bicipital groove and feel just behind it on the greater tubercle.",
      ],
      clinicalConsiderations: "Linked to sustained overhead work, carrying loads with the arm hanging, or trauma. Presents with crepitus, painful abduction, and tenderness at the humeral attachment — frequently mistaken for rotator cuff tendinitis, bursitis, a cervical disc problem, or frozen shoulder. Referral overlaps with infraspinatus at the outer shoulder, though infraspinatus tends to feel like a deeper ache.",
      source: `${REF_SHOULDER}, pp.160–162`,
      images: [null, null, null],
    },
    {
      id: "palp_anterior_deltoid",
      name: "Anterior Deltoid",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Lateral clavicle",
        insertion: "Deltoid tuberosity of the humerus",
      },
      actions: "Flexes, abducts, medially rotates, and horizontally flexes the shoulder.",
      patientPosition: "Supine, arm resting against the body.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just below the outer clavicle; support near the elbow.",
      steps: [
        "Cue an arm lift midway between flexion and abduction; feel the fibres tighten.",
        "Light resistance from the support hand sharpens the signal.",
        "Brush across the fibres from clavicle to deltoid tuberosity.",
        "Release and compare tone.",
      ],
      feelFor: "A visible seam between this muscle and the clavicular head of pectoralis major once both are active.",
      notes: [
        "Pectoralis major's clavicular head typically joins in during horizontal flexion — that's expected, not a sign you've moved off-target.",
      ],
      clinicalConsiderations: "Overload from sustained overhead reaching or direct impact. Overlaps clinically with rotator cuff tear, biceps tendinitis, and subacromial bursitis.",
      source: `${REF_SHOULDER}, pp.163–164`,
      images: [null, null, null],
    },
    {
      id: "palp_subscapularis",
      name: "Subscapularis",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Subscapular fossa",
        insertion: "Humeral lesser tubercle",
      },
      actions: "Medially rotates the shoulder.",
      patientPosition: "Supine, arm resting on the trunk, other hand cradling the elbow of the side being examined.",
      therapistPosition: "Seated beside the client.",
      handPlacement: "Finger pads against the front of the scapula; other hand reaches beneath the client to grip the scapula's medial border.",
      steps: [
        "Passively draw the scapula back with your support hand.",
        "Have the client breathe deeply; as they exhale, sink your fingers in slowly against the scapula's anterior surface.",
        "Confirm you're on target by cueing medial rotation (the arm lifts slightly) and feeling for the response.",
        "Work as far toward the medial border as you can reach.",
        "Release and compare tone.",
      ],
      feelFor: "A broad, firm sheet against the front of the scapula that tightens with medial rotation.",
      notes: [
        "Timing the sink-in with an exhale and using steady, unhurried pressure keeps this comfortable for the client.",
        "Subscapularis (against the scapula) and serratus anterior (against the ribs) occupy the same general space — which surface your fingers are oriented toward tells them apart.",
      ],
      clinicalConsiderations: "Linked to overuse (swimming), trauma, prolonged immobilization in medial rotation, or a chronically rounded-shoulder posture. Restricts and pains lateral rotation, which indirectly limits full abduction. Differential includes frozen shoulder, rotator cuff lesions, and thoracic outlet syndrome.",
      source: `${REF_SHOULDER}, pp.165–168`,
      images: [null, null, null],
    },
    {
      id: "palp_serratus_anterior",
      name: "Serratus Anterior",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Ribs 1–9, anterolateral surface",
        insertion: "Scapula's entire medial border (anterior surface)",
      },
      actions: "Protracts and upwardly rotates the scapula; upper fibres can elevate it, lower fibres depress it.",
      patientPosition: "Supine, arm reaching straight up.",
      therapistPosition: "Seated beside the client.",
      handPlacement: "Against the lateral rib cage, just below the armpit.",
      steps: [
        "Cue a reach toward the ceiling (scapular protraction) and feel for the contraction.",
        "Add resistance with the support hand if desired.",
        "Cover as much of the muscle as you can.",
        "Release and compare tone.",
      ],
      feelFor: "A sheet firming against the ribs on protraction — upper fibres respond best with the arm angled up around 135° flexion, lower fibres around 45°.",
      notes: [
        "The uppermost fibres near ribs 1–2 are notoriously hard to reach; a slow, firm approach underneath pectoralis major is needed.",
        "Serratus anterior (against the ribs) and subscapularis (against the scapula) occupy the same space — finger orientation is what separates them.",
      ],
      clinicalConsiderations: "Overload from push-ups, punching, racquet sports, or heavy breathing effort. Restricts scapular retraction; left-sided symptoms can mimic cardiac referral, so rib dysfunction, costochondritis, and thoracic outlet syndrome all belong on the differential list too.",
      source: `${REF_SHOULDER}, pp.169–171`,
      images: [null, null, null],
    },
    {
      id: "palp_pectoralis_major",
      name: "Pectoralis Major",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Medial clavicle, sternum, costal cartilages of ribs 1–7",
        insertion: "Lateral lip of the humeral bicipital groove",
      },
      actions: "As a whole: adducts, medially rotates, and horizontally flexes the shoulder, and protracts the scapula. Clavicular fibres additionally flex the shoulder; sternocostal fibres extend it back from flexion and depress the scapula.",
      patientPosition: "Supine, arm at the side.",
      therapistPosition: "Seated beside the client.",
      handPlacement: "Lower anterior axillary fold for the sternocostal fibres; just below the medial clavicle for the clavicular fibres.",
      steps: [
        "Sternocostal fibres: resist arm adduction (or have the client push the arm against their own body) and follow the contraction toward the sternum.",
        "Clavicular fibres: position under the medial clavicle and cue an oblique flex-and-adduct motion against resistance.",
        "Track the clavicular contraction toward its distal attachment, brushing across the fibres.",
        "Release and compare tone.",
      ],
      feelFor: "A visible seam between the clavicular fibres and the anterior deltoid, and another between the two heads of this muscle during resisted horizontal flexion.",
      notes: [
        "Abducting the arm away from the body lets you grasp the whole anterior fold of muscle directly between your fingers.",
      ],
      clinicalConsiderations: "Linked to repetitive lifting, a rounded-shoulder posture, immobilization, or tight strap compression; a trigger point near ribs 5–6 on the right has been associated with cardiac arrhythmia in the literature. Left-sided presentations warrant ruling out cardiac referral alongside rib and costochondral causes.",
      source: `${REF_SHOULDER}, pp.172–174`,
      images: [null, null, null],
    },
    {
      id: "palp_pectoralis_minor",
      name: "Pectoralis Minor",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Ribs 3–5",
        insertion: "Coracoid process (medial surface)",
      },
      actions: "Protracts, depresses, and downwardly rotates the scapula; elevates ribs 3–5.",
      patientPosition: "Supine, hand tucked under the low back.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just below the coracoid process.",
      steps: [
        "Cue the client to press the hand/forearm down into the table; feel the contraction through pectoralis major.",
        "Track toward the rib attachments, brushing across the fibres.",
        "Release and compare tone.",
      ],
      feelFor: "Contraction transmitted through the overlying pectoralis major; its three rib-slips are often distinguishable individually.",
      notes: [
        "This cue requires the scapula to rotate downward — easier to feel with the client sitting up.",
      ],
      clinicalConsiderations: "Can produce neurovascular symptoms down the arm (pectoralis minor syndrome), a rounded-shoulder posture, or scapular winging. Backpack strap pressure and referral from pectoralis major or the scalenes are common contributors.",
      source: `${REF_SHOULDER}, pp.175–176`,
      images: [null, null, null],
    },
    {
      id: "palp_subclavius",
      name: "Subclavius",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "First rib, at its costal cartilage junction",
        insertion: "Middle third of the clavicle's undersurface",
      },
      actions: "Depresses, protracts, and downwardly rotates the clavicle; elevates the first rib.",
      patientPosition: "Supine, arm medially rotated and resting on the table.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Fingers curled under the clavicle, pads against its inferior surface.",
      steps: [
        "With everything relaxed, feel along the underside of the clavicle.",
        "Cue a shoulder-girdle depression (drop the shoulder/collarbone) and feel for the contraction.",
        "Work end to end along the muscle.",
        "Release and compare tone.",
      ],
      feelFor: "A slim band tucked under the clavicle — easier to reach with the arm passively medially rotated (slackens pectoralis major) and abducted (rolls the clavicle to expose more of its underside).",
      notes: [
        "Generally considered one of the harder structures in this region to palpate with confidence.",
      ],
      clinicalConsiderations: "Can contribute to costoclavicular compression symptoms in the arm. Differential includes cervical disc issues, anterior scalene syndrome, and pectoralis minor syndrome.",
      source: `${REF_SHOULDER}, pp.177–178`,
      images: [null, null, null],
    },
  ],

  cervical: [
    {
      id: "palp_scm",
      name: "Sternocleidomastoid (SCM)",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Sternal manubrium and medial clavicle",
        insertion: "Mastoid process and lateral superior nuchal line",
      },
      actions: "Flexes the lower neck while extending the head/upper neck; side-bends and turns the head/neck to the opposite side; assists elevating the sternum and clavicle.",
      patientPosition: "Supine, head turned away from the side being examined.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just above the sternoclavicular joint.",
      steps: [
        "Cue a head lift off the table and watch the muscle stand out.",
        "Gravity alone is usually enough resistance.",
        "Track toward the mastoid, brushing across the fibres.",
        "Release and compare tone.",
      ],
      feelFor: "A clearly visible sternal head and a subtler clavicular head just lateral to it — the gap between them varies widely from person to person.",
      notes: [
        "Use a pincer grip rather than flat pressure — the carotid sinus sits underneath, and firm flat pressure there can trigger a drop in blood pressure.",
        "A useful landmark for finding the scalenes and the longus colli/capitis nearby.",
      ],
      clinicalConsiderations: "Linked to sustained head-turned postures, forward-head posture, restrictive collars, or whiplash. Can produce headache, restricted neck motion, throat discomfort, and autonomic symptoms (eye changes from the sternal head; sweating/vasoconstriction from the clavicular head) — frequently mistaken for swollen glands, sinus or migraine headache, or a jaw-joint problem.",
      source: `${REF_NECK}, pp.187–189`,
      images: [null, null, null],
    },
    {
      id: "palp_platysma",
      name: "Platysma (brief detour)",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Superior chest fascia",
        insertion: "Mandible and lower-face fascia",
      },
      actions: "A thin skin-level sheet that wrinkles the neck on contraction rather than moving a joint.",
      steps: [
        "Cue the client to firmly pull the lower lip down and sideways while keeping the jaw slightly dropped.",
      ],
      feelFor: "Faint neck-skin wrinkling directly over the SCM.",
      clinicalConsiderations: "Associated with habitual facial expressions or with SCM/scalene involvement; produces a prickling sensation over the jaw.",
      source: `${REF_NECK}, p.189`,
      images: [null, null, null],
    },
    {
      id: "palp_scalene_group",
      name: "Scalene Group (anterior, middle, posterior)",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Ribs 1 (anterior, middle) and 2 (posterior)",
        insertion: "Transverse processes C3–C6 (anterior), C2–C7 (middle), C5–C7 (posterior)",
      },
      actions: "Flex and side-bend the neck (anterior/middle also turn it to the opposite side); elevate the upper ribs; accessory muscles of inspiration.",
      patientPosition: "Supine.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Posterior triangle of the neck, above the clavicle and just outside the SCM's clavicular head.",
      steps: [
        "Find the outer edge of the SCM's clavicular head, then step just off it laterally.",
        "Cue short, quick sniffs through the nose and feel for the response.",
        "Cover as much of the posterior-triangle territory as possible, brushing across the fibres.",
        "Release and compare tone.",
      ],
      feelFor: "Anterior (mostly hidden under the SCM, fibres running to C3–C6), middle (most accessible in the posterior triangle, fibres to C2–C7 — the easiest of the three to identify), posterior (deepest and hardest to isolate, near-horizontal fibres to C5–C7, tucked just in front of the trapezius/levator scapulae).",
      notes: [
        "To reach the transverse-process attachments under the SCM, slacken it first (passive flexion plus same-side bend), then sink in gradually toward the spine.",
        "Palpate with care — the brachial plexus and subclavian artery pass between the anterior and middle bellies.",
      ],
      clinicalConsiderations: "Linked to coughing, laboured breathing, or whiplash-type trauma. Can drive thoracic outlet symptoms, restricted neck rotation/side-bending, or upper-rib dysfunction — differential includes cervical disc issues, left-sided cardiac referral, and carpal tunnel syndrome.",
      source: `${REF_NECK}, pp.190–193`,
      images: [null, null, null],
    },
    {
      id: "palp_omohyoid_inferior_belly",
      name: "Omohyoid, Inferior Belly (brief detour)",
      type: "Muscle",
      position: "Supine",
      handPlacement: "Posterior triangle, just outside the SCM and above the clavicle.",
      steps: [
        "Resist jaw-opening (mandibular depression) and feel for the horizontal band contracting.",
      ],
      feelFor: "A readily palpable horizontal band in the posterior triangle.",
      clinicalConsiderations: "See the full Hyoid Group entry for symptom notes — tension here is thought to play a role in thoracic outlet presentations via its relationship to the brachial plexus.",
      source: `${REF_NECK}, p.193`,
      images: [null, null, null],
    },
    {
      id: "palp_longus_colli_capitis",
      name: "Longus Colli & Longus Capitis",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Longus colli: vertebral bodies/transverse processes, T3 to C1. Longus capitis: transverse processes C3–C5.",
        insertion: "Longus colli: upper vertebral bodies/transverse processes. Longus capitis: occiput.",
      },
      actions: "Longus colli flexes, side-bends, and opposite-rotates the neck; longus capitis flexes and side-bends the head/neck.",
      patientPosition: "Supine.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just inside the SCM's sternal head; support the forehead if resisting.",
      steps: [
        "Find the inner edge of the SCM's sternal head and step just medial to it.",
        "Sink gradually and gently toward the front of the cervical vertebral bodies.",
        "Confirm placement by cueing a head lift into flexion and feeling for the response.",
        "Brush across the fibres, working as far up and down as reachable.",
        "Release and compare tone.",
      ],
      feelFor: "A firm cord against the vertebral bodies — if you feel a pulse instead, you've drifted onto the carotid artery and should shift slightly to one side.",
      notes: [
        "Sink in slowly with steady, gentle-but-firm pressure — this region houses several delicate structures (carotid sinus, trachea).",
        "If it's hard to separate from the SCM, rotating the head toward the side being palpated relaxes the SCM out of the way.",
      ],
      clinicalConsiderations: "A frequent casualty of whiplash injuries. Can produce sore throat, swallowing discomfort, and compensatory tightness in the posterior neck. Referral mapping for this group is limited in the literature.",
      source: `${REF_NECK}, pp.194–196`,
      images: [null, null, null],
    },
    {
      id: "palp_rectus_capitis_ant_lat",
      name: "Rectus Capitis Anterior & Lateralis (brief detour)",
      type: "Muscle",
      position: "Supine or seated",
      attachments: {
        origin: "Occiput (both)",
        insertion: "Atlas transverse process (C1)",
      },
      actions: "Anterior: flexes the head at the atlanto-occipital joint. Lateralis: side-bends the head at the same joint.",
      handPlacement: "Just above the C1 transverse process (behind the jaw ramus, below the ear) for the lateralis — the anterior belly sits too deep to reach.",
      steps: [
        "Press gently into the small hollow just above the C1 transverse process, feeling for the lateralis.",
      ],
      feelFor: "Often indistinguishable from the surrounding soft tissue.",
      notes: [
        "Keep pressure light — the facial nerve and styloid process are close by.",
      ],
      clinicalConsiderations: "The anterior belly is essentially inaccessible to palpation. Symptom-referral patterns for either muscle aren't well documented.",
      source: `${REF_NECK}, p.196`,
      images: [null, null, null],
    },
    {
      id: "palp_hyoid_group",
      name: "Hyoid Group (infra- & suprahyoids)",
      type: "Muscle group",
      position: "Supine",
      attachments: {
        origin: "Infrahyoids: sternum, scapula, thyroid cartilage. Suprahyoids: mastoid notch, styloid process, mandible.",
        insertion: "All converge on the hyoid bone (digastric and omohyoid each via a central tendon).",
      },
      actions: "Assist jaw-opening and neck flexion; infrahyoids pull the hyoid down, suprahyoids pull it up.",
      patientPosition: "Supine.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just below the hyoid, slightly off-centre, for the infrahyoids; support the chin.",
      steps: [
        "Infrahyoids: resist jaw-opening and feel for the contraction, brushing across the fibres.",
        "Track down toward the sternum.",
        "Suprahyoids: reposition just below the jaw, resist opening again, and feel for the response.",
        "Track up toward the hyoid.",
        "For stylohyoid and digastric's upper belly, continue laterally from the hyoid toward the mastoid while still resisting jaw-opening.",
        "Release and compare tone.",
      ],
      feelFor: "A cluster of small, thin bands that are hard to tell apart individually but all engage together when jaw-opening is resisted.",
      clinicalConsiderations: "Digastric has the best-documented referral pattern in this group: its lower belly can refer to the lower incisors, tongue, and throat with swallowing discomfort; its upper belly relates to occipitofrontalis symptoms. Stylohyoid has been linked to external carotid artery entrapment; omohyoid tension is thought to contribute to thoracic outlet symptoms. Frequently mistaken for dental problems.",
      source: `${REF_NECK}, pp.197–200`,
      images: [null, null, null],
    },
    {
      id: "palp_upper_trapezius_seated",
      name: "Upper Trapezius (seated variant)",
      type: "Muscle",
      position: "Seated",
      attachments: {
        origin: "Occiput, nuchal ligament, spinous process of C7",
        insertion: "Lateral clavicle and acromion",
      },
      actions: "Elevates, retracts, and upwardly rotates the scapula; extends, side-bends, and opposite-rotates the head/neck.",
      patientPosition: "Seated, head turned to the opposite side.",
      therapistPosition: "Standing beside the client.",
      handPlacement: "Top of the shoulder, over the upper fibres; support the back of the head.",
      steps: [
        "Resist neck extension and watch/feel for the contraction.",
        "Track from the occiput down to the scapula/clavicle, brushing across the fibres.",
        "Release and compare tone.",
      ],
      feelFor: "A contraction that's often visible as well as palpable; turning the head away reciprocally quiets the splenius muscles, letting the trapezius engage more strongly on its own.",
      notes: [
        "This is a seated alternative to the prone Trapezius technique already covered under Shoulder Girdle (pp.142–145) — useful when a client can't lie face-down.",
      ],
      clinicalConsiderations: "See the Shoulder Girdle Trapezius entry for full symptom notes — arguably the single most commonly affected muscle site clinically.",
      source: `${REF_NECK}, pp.201–203`,
      images: [null, null, null],
    },
    {
      id: "palp_levator_scapulae_seated",
      name: "Levator Scapulae (seated variant)",
      type: "Muscle",
      position: "Seated",
      attachments: {
        origin: "Transverse processes C1–C4",
        insertion: "Scapula's medial border, spine-root to superior angle",
      },
      actions: "Elevates and downwardly rotates the scapula; extends, side-bends, and same-side rotates the neck.",
      patientPosition: "Seated, hand in the small of the back.",
      therapistPosition: "Standing behind or beside the client.",
      handPlacement: "Just above and medial to the scapula's superior angle; support the top of the shoulder.",
      steps: [
        "With the hand on the low back, cue a small, gentle shrug; feel for tension under the trapezius.",
        "Track toward the top attachment, across the fibres.",
        "Once in the posterior triangle, the hand can leave the low back and the shrug can be firmer.",
        "Reach as high as possible — it runs under the SCM near the top.",
        "Release and compare tone.",
      ],
      feelFor: "The same three-stage accessibility as the prone version: buried near the scapula, superficial through the posterior triangle, buried again under the SCM near the spine.",
      notes: [
        "Seated alternative to the prone technique already covered under Shoulder Girdle (pp.149–151); includes an extra tip for reaching the top attachment under the SCM by slackening it first (flex plus same-side bend).",
      ],
      clinicalConsiderations: "See the Shoulder Girdle Levator Scapulae entry for full symptom notes (a classic acute wry-neck presentation).",
      source: `${REF_NECK}, pp.204–206`,
      images: [null, null, null],
    },
    {
      id: "palp_splenius_capitis",
      name: "Splenius Capitis",
      type: "Muscle",
      position: "Seated",
      attachments: {
        origin: "Nuchal ligament (C3–C6 level) and spinous processes C7–T4",
        insertion: "Mastoid process and outer superior nuchal line",
      },
      actions: "Extends, side-bends, and same-side rotates the head/neck.",
      patientPosition: "Seated, head turned toward the side being examined.",
      therapistPosition: "Standing behind the client.",
      handPlacement: "Upper posterior triangle, just below the occiput and just behind the SCM, where this muscle is superficial.",
      steps: [
        "With the head turned toward the same side, resist extension and feel for the response.",
        "Brush across the fibres through the posterior triangle until reaching the trapezius border.",
        "Alternate resisted extension with relaxation to track it deeper under the trapezius, as far down as possible.",
        "Release and compare tone.",
      ],
      feelFor: "Same-side rotation relaxes both the SCM and upper trapezius, making this muscle easier to isolate underneath — keep resistance light or the trapezius takes back over.",
      notes: [
        "Its lower attachment on the upper thoracic spinous processes is reachable by pressing just in front of the trapezius border, down toward the spine.",
      ],
      clinicalConsiderations: "Linked to prolonged forward or rotated head postures (off-centre monitor setups) or whiplash. Restricts flexion/opposite rotation and same-side rotation, and can produce headache — differential includes cervical joint dysfunction and migraine.",
      source: `${REF_NECK}, pp.207–208`,
      images: [null, null, null],
    },
    {
      id: "palp_splenius_cervicis",
      name: "Splenius Cervicis (brief detour)",
      type: "Muscle",
      position: "Seated",
      attachments: {
        origin: "Spinous processes T3–T6",
        insertion: "Transverse processes C1–C3",
      },
      actions: "Same movement family as splenius capitis, but acts on the neck only, not the head.",
      handPlacement: "Between levator scapulae and splenius capitis.",
      steps: [
        "Cue same-side neck rotation (resisted if needed) and feel for the response.",
        "Follow toward both ends once located.",
      ],
      feelFor: "Buried under other muscle for its whole length — easiest to first find in the gap between levator scapulae and splenius capitis.",
      clinicalConsiderations: "Shares the same aggravating factors as splenius capitis; can produce headache, eye pain, or blurred vision on the same side.",
      source: `${REF_NECK}, p.209`,
      images: [null, null, null],
    },
    {
      id: "palp_semispinalis_capitis",
      name: "Semispinalis Capitis",
      type: "Muscle",
      position: "Supine",
      attachments: {
        origin: "Transverse processes C7–T6, articular processes C4–C6",
        insertion: "Medial occipital bone, between the nuchal lines",
      },
      actions: "Extends and side-bends the head/neck.",
      patientPosition: "Supine, hand in the small of the back and/or head turned toward the side being examined.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just below the occiput, just off the midline (over the laminar groove).",
      steps: [
        "Cue a gentle press of the head into the table (extension) and feel for the contraction under the trapezius.",
        "Track toward the occiput and downward, across the fibres.",
        "Release and compare tone.",
      ],
      feelFor: "The largest, thickest muscle in the neck — bulkier than the more familiar upper trapezius — firming underneath it.",
      notes: [
        "A light contraction is enough; pushing too hard overrides the trapezius's reciprocal relaxation and blocks access to the muscle beneath it.",
      ],
      clinicalConsiderations: "Linked to protracted head posture, prone reading/elbow-propping habits, whiplash, or cervical osteoarthritis. Can produce headache, restricted flexion, or greater occipital nerve irritation (tingling/pain across the back of the scalp).",
      source: `${REF_NECK}, pp.210–211`,
      images: [null, null, null],
    },
    {
      id: "palp_longissimus_capitis_group",
      name: "Longissimus Capitis, Semispinalis Cervicis, Cervical Multifidus & Rotatores (brief detour)",
      type: "Muscle group",
      position: "Supine",
      attachments: {
        origin: "Longissimus capitis: transverse/articular processes C5–T5. Semispinalis cervicis: transverse processes T1–T5.",
        insertion: "Longissimus capitis: mastoid process. Semispinalis cervicis: spinous processes C2–C5.",
      },
      actions: "Extension, plus same-side rotation for longissimus capitis; multifidus and rotatores extend and opposite-rotate the neck.",
      handPlacement: "Lateral to splenius capitis, underneath levator scapulae and upper trapezius, for longissimus capitis.",
      steps: [
        "A light head-extension press against the table, with the head turned to the same side, brings out the contraction.",
      ],
      feelFor: "All four are deep and difficult to isolate individually — the multifidus and rotatores sit very deep in the laminar groove.",
      clinicalConsiderations: "Longissimus capitis symptoms tend to sit behind the ear; semispinalis cervicis mirrors semispinalis capitis's referral; cervical multifidus refers toward the base of the skull and the inner scapular border; rotatores refer locally at the segmental level involved.",
      source: `${REF_NECK}, p.212`,
      images: [null, null, null],
    },
    {
      id: "palp_suboccipital_group",
      name: "Suboccipital Group",
      type: "Muscle group",
      position: "Supine",
      attachments: {
        origin: "RCPMaj: C2 spinous process. RCPMin: C1 posterior tubercle. OCI: C2 spinous process. OCS: C1 transverse process.",
        insertion: "RCPMaj/RCPMin/OCS: occipital nuchal lines. OCI: C1 transverse process.",
      },
      actions: "As a group, extend and glide the head forward at the atlanto-occipital joint; obliquus capitis inferior also same-side rotates the atlas at C1–C2.",
      patientPosition: "Supine.",
      therapistPosition: "Seated at the head of the table.",
      handPlacement: "Just above and slightly outside the C2 spinous process.",
      steps: [
        "Rectus capitis posterior major, the easiest to find: work just above-and-outside the C2 spinous process, brushing across the fibres, tracing up toward the occiput.",
        "Rectus capitis posterior minor: same approach, starting just above-and-outside the C1 posterior tubercle — cueing a forward glide of the head can help bring it out.",
        "Obliquus capitis inferior: work the gap between the C2 spinous process and C1 transverse process; light resisted same-side head rotation helps engage it.",
        "Obliquus capitis superior, the hardest to isolate: feel just outside where RCPMaj attaches superiorly.",
        "Release and compare tone.",
      ],
      feelFor: "Deep, best felt relaxed; RCPMaj stands out most readily, OCS the least.",
      notes: [
        "Work this area cautiously — the vertebral artery, suboccipital nerve, and greater occipital nerve all pass close by.",
      ],
      clinicalConsiderations: "Linked to sustained head extension or rotation, chronic forward-head posture, whiplash, or upper cervical joint dysfunction. Produces diffuse, hard-to-localize headache and restricted flexion/rotation — often mistaken for migraine or greater occipital neuralgia.",
      source: `${REF_NECK}, pp.213–216`,
      images: [null, null, null],
    },
  ],
};
