// The session editor and the home-exercise-programme sender. Split out of
// AppModules.jsx because they pull in the whole exercise library (~130 KB of
// data) and are only needed once a session is opened; AppModules.jsx loads this
// file on demand (see its SessionDetailView wrapper).
import { useState } from "react";
import { downloadPDFFromHTML, injectViewerControls } from "./sharedClinicalData.js";
import { EXERCISE_DB, ALL_EXERCISES, PROGRAMME_TEMPLATES, TEMPLATE_TX } from "./sharedClinicalData.js";
import { EditableItemList, SessionPill, legacyTreatmentToList } from "./AppModules.jsx";

// ── HEP protocol helpers — versioned home programme with WhatsApp/PDF send ──
function hepDose(e){ const st=e.customSets||e.sets, rp=e.customReps||e.reps, hd=e.customHold||e.hold, fq=e.customFreq||e.freq; return [st&&rp?`${st}×${rp}`:st?`${st} sets`:rp?`${rp} reps`:"", hd?`hold ${hd}s`:"", fq||""].filter(Boolean).join(" · "); }
function buildHepWhatsAppText(d){
  const prog=Array.isArray(d.hep_programme)?d.hep_programme:[];
  if(!prog.length) return "";
  const v=parseInt(d.hep_version)||1;
  const lines=prog.map((e,i)=>`${i+1}. ${e.name} — ${hepDose(e)}`);
  return `🏥 ${d.clinic_name||"PhysioMind"} — Home Exercise Programme (v${v})\nPatient: ${d.dem_name||""}\nDate: ${new Date().toLocaleDateString("en-GB")}\n\n${lines.join("\n")}\n\nStop if severe pain. Mild discomfort is normal. Contact your physiotherapist if unsure.`;
}
export function sendHepWhatsApp(d){
  const text=buildHepWhatsAppText(d);
  if(!text){alert("No exercises in the home protocol yet.");return;}
  const phone=String(d.dem_phone||d.dem_contact||"").replace(/[^0-9]/g,"");
  const url=phone.length>=10?`https://wa.me/${phone}?text=${encodeURIComponent(text)}`:`https://wa.me/?text=${encodeURIComponent(text)}`;
  window.open(url,"_blank");
}
export function downloadHepPdf(d){
  const prog=Array.isArray(d.hep_programme)?d.hep_programme:[];
  if(!prog.length){alert("No exercises in the home protocol yet.");return;}
  const v=parseInt(d.hep_version)||1;
  const html=`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Home Exercise Programme</title>
<style>@page{size:A4;margin:18mm}*{box-sizing:border-box;font-family:'Segoe UI',Arial,sans-serif}body{background:#fff;color:#1a1a2e;font-size:11px;line-height:1.55}.header{border-bottom:3px solid #7c3aed;padding-bottom:12px;margin-bottom:16px;display:flex;justify-content:space-between}.logo{font-size:20px;font-weight:900;color:#7c3aed}.meta{text-align:right;font-size:10px;color:#555}.ex{border:1px solid #e2e8f0;border-radius:8px;margin-bottom:10px;overflow:hidden;break-inside:avoid}.ex-h{background:#7c3aed;color:#fff;padding:8px 12px;display:flex;justify-content:space-between}.ex-t{font-size:12px;font-weight:800}.ex-b{padding:10px 12px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:8px}.st{background:#f5f3ff;border-radius:6px;padding:5px 8px;text-align:center}.sv{font-size:13px;font-weight:900;color:#7c3aed}.sl{font-size:8px;color:#64748b;text-transform:uppercase}.desc{font-size:10.5px;color:#334155;margin-bottom:6px}.cues{background:#fefce8;border-left:3px solid #fbbf24;padding:5px 8px;font-size:10px;color:#713f12}.footer{margin-top:16px;padding-top:10px;border-top:1px solid #e2e8f0;font-size:9px;color:#94a3b8;text-align:center}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style>
</head><body>
<div class="header"><div><div class="logo">PhysioMind</div><div style="font-size:11px;color:#555;margin-top:2px">Home Exercise Programme — v${v}</div></div><div class="meta"><div><b>Patient:</b> ${d.dem_name||"—"}</div><div><b>Date:</b> ${new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"})}</div></div></div>
<p style="font-size:10px;color:#555;margin-bottom:14px">Perform exercises as prescribed. Stop if severe pain. Mild discomfort is normal. Contact your physiotherapist if unsure.</p>
${prog.map((ex,i)=>`<div class="ex"><div class="ex-h"><span class="ex-t">${i+1}. ${ex.name}</span><span style="font-size:9px;opacity:0.85">${ex.phase||""}</span></div><div class="ex-b"><div class="grid"><div class="st"><div class="sv">${ex.customSets||ex.sets||"—"}</div><div class="sl">Sets</div></div><div class="st"><div class="sv">${ex.customReps||ex.reps||"—"}</div><div class="sl">Reps</div></div><div class="st"><div class="sv">${(ex.customHold||ex.hold)?(ex.customHold||ex.hold)+"s":"—"}</div><div class="sl">Hold</div></div><div class="st"><div class="sv" style="font-size:9px">${ex.customFreq||ex.freq||"—"}</div><div class="sl">Freq</div></div></div><div class="desc">${ex.desc||""}</div>${ex.cues?`<div class="cues">💡 ${ex.cues}</div>`:""}</div></div>`).join("")}
<div class="footer">Generated by PhysioMind · ${new Date().toLocaleString()}</div>
</body></html>`;
  try{ downloadPDFFromHTML(html, `HEP_v${v}_${d.dem_name||"Patient"}_${Date.now()}.pdf`); }
  catch(e){ const w=window.open("","_blank"); w.document.write(injectViewerControls(html)); w.document.close(); setTimeout(()=>{try{w.print();}catch(_){}},500); }
}

// ── Screen 2: one session, fully editable — exercises, modalities,
// treatment (each with its own add/edit/remove), pain, and a quick note.
// For a brand-new (unsaved) session, exercises still edit the live,
// ongoing hep_programme exactly as before (today's changes should affect
// the active protocol). For a past, already-saved session, exercises are
// that session's own frozen snapshot -- editing it corrects the historical
// record without silently rewriting today's active protocol.
export default function SessionDetailView({ PC, data, set, navTo, sessionsArr, activeId, onBack }) {
  const isNew = activeId===null;
  const activeSession = isNew ? null : (sessionsArr.find(s=>s.id===activeId)||null);
  const lastSession = sessionsArr[0];
  const sessionNo = isNew ? sessionsArr.length+1 : (activeSession?.sessionNo||sessionsArr.length);

  const [qv, setQv] = useState(()=> isNew
    ? {pain_today:data.cc_vas_now||"",pain_after:"",response:"",next_plan:""}
    : {pain_today:activeSession?.vasStart||"",pain_after:activeSession?.vasEnd||"",response:activeSession?.quickNote||activeSession?.response||"",next_plan:activeSession?.nextPlan||""});
  const [saved, setSaved] = useState(false);
  const [pending, setPending] = useState([]);          // protocol change descriptions this visit (new session only)
  const [pickerOpen, setPickerOpen] = useState(false);
  const [pickerMode, setPickerMode] = useState("library");
  const [pickerSearch, setPickerSearch] = useState("");
  const [pickerRegion, setPickerRegion] = useState("all");
  const [openTemplate, setOpenTemplate] = useState(null);
  const [editId, setEditId] = useState(null);
  const [editDose, setEditDose] = useState({sets:"",reps:"",hold:""});
  const [removeId, setRemoveId] = useState(null);

  const [treatmentList, setTreatmentList] = useState(()=> isNew
    ? (Array.isArray(lastSession?.treatment) ? lastSession.treatment.map(t=>({...t})) : legacyTreatmentToList(lastSession?.treatmentGiven))
    : (Array.isArray(activeSession?.treatment) ? activeSession.treatment.map(t=>({...t})) : legacyTreatmentToList(activeSession?.treatmentGiven)));
  const [modalities, setModalities] = useState(()=> isNew ? [] : (Array.isArray(activeSession?.modalities)?activeSession.modalities.map(m=>({...m})):[]));
  const [pastExercises, setPastExercises] = useState(()=> isNew ? [] : (Array.isArray(activeSession?.exercises)?activeSession.exercises.map(e=>({...e})):[]));
  // Exercise Prescription -- a separate, standing treatment programme from
  // hep_programme (see ExercisePrescriptionModule, Treatment tab). This was
  // being prescribed for patients but never surfaced anywhere in Sessions.
  // Live for a new session (removing here removes from the real prescription,
  // same as Exercises does for hep_programme); a frozen snapshot for a past
  // session, same pattern as Exercises/Modalities/Treatment.
  const rxProgramme = Array.isArray(data.tx_exercise_prescription) ? data.tx_exercise_prescription : [];
  const [pastRx, setPastRx] = useState(()=> isNew ? [] : (Array.isArray(activeSession?.exercisePrescription)?activeSession.exercisePrescription.map(e=>({...e})):[]));
  const removeRx = (id) => { if(!set) return; set("tx_exercise_prescription", rxProgramme.filter(e=>e.id!==id)); };

  const txOptions = ["Joint mobilisation","Soft tissue massage","Dry needling","Exercise therapy","TENS/IFT","Neural mobilisation","Taping/strapping","Education & advice","Postural correction","Manual therapy","Other"];
  const modalityOptions = ["IFT","TENS","Hot pack","Cold pack","Ultrasound","Laser","Shockwave","Traction","Paraffin wax"];
  const inp = {width:"100%",background:PC.s2,border:`1px solid ${PC.border}`,borderRadius:8,color:PC.text,fontFamily:"inherit",outline:"none",padding:"8px 10px",fontSize:"0.8rem"};
  const lbl = {fontSize:"0.8rem",fontWeight:700,color:PC.muted,display:"block",marginBottom:4,textTransform:"uppercase",letterSpacing:"0.6px"};
  const sectionLbl = {fontSize:"0.82rem",fontWeight:800,color:PC.text,textTransform:"uppercase",letterSpacing:"0.7px",marginBottom:6};

  const prog = Array.isArray(data.hep_programme)?data.hep_programme:[];

  const addExercise = (ex) => {
    if(prog.find(p=>p.id===ex.id)) { setPickerOpen(false); return; }
    set("hep_programme",[...prog,{...ex,customSets:ex.sets,customReps:ex.reps,customHold:ex.hold,customFreq:ex.freq,notes:"",addedSession:sessionNo,addedDate:new Date().toISOString()}]);
    setPending(p=>[...p,`＋ ${ex.name}`]);
    setPickerOpen(false); setPickerSearch("");
  };
  const removeExercise = (id,reason) => {
    const ex=prog.find(p=>p.id===id);
    set("hep_programme",prog.filter(p=>p.id!==id));
    setPending(p=>[...p,`− ${ex?.name||id}${reason?` (${reason.toLowerCase()})`:""}`]);
    setRemoveId(null);
  };
  const startProgress = (e) => { setEditId(e.id); setEditDose({sets:String(e.customSets||e.sets||""),reps:String(e.customReps||e.reps||""),hold:String(e.customHold||e.hold||"")}); };
  const applyProgress = () => {
    const ex=prog.find(p=>p.id===editId); if(!ex){setEditId(null);return;}
    set("hep_programme",prog.map(p=>p.id===editId?{...p,customSets:editDose.sets,customReps:editDose.reps,customHold:editDose.hold,progressedSession:sessionNo}:p));
    setPending(p=>[...p,`↑ ${ex.name} ${editDose.sets}×${editDose.reps}${editDose.hold?` · ${editDose.hold}s`:""}`]);
    setEditId(null);
  };

  const addTxItem = (name) => setTreatmentList(list=>list.find(t=>t.name===name)?list:[...list,{id:Math.random().toString(36).slice(2,9),name,detail:""}]);
  const addTemplate = (key) => {
    const t=PROGRAMME_TEMPLATES[key]; if(!t) return;
    const exs=t.exercises.map(id=>ALL_EXERCISES.find(e=>e.id===id)).filter(Boolean).filter(e=>!prog.find(p=>p.id===e.id));
    if(exs.length){
      set("hep_programme",[...prog,...exs.map(ex=>({...ex,customSets:ex.sets,customReps:ex.reps,customHold:ex.hold,customFreq:ex.freq,notes:"",addedSession:sessionNo,addedDate:new Date().toISOString()}))]);
      setPending(p=>[...p,`＋ ${t.label} template (${exs.length} exercise${exs.length!==1?"s":""})`]);
    }
    const tx=TEMPLATE_TX[key];
    if(tx){ (tx.manual||[]).forEach(addTxItem); (tx.machine||[]).forEach(addTxItem); }
  };
  const pickerResults = (()=>{
    if(!pickerOpen) return [];
    let pool = pickerRegion==="all" ? ALL_EXERCISES : (Object.values(EXERCISE_DB[pickerRegion]?.categories||{}).flat());
    const q=pickerSearch.trim().toLowerCase();
    if(q) pool=pool.filter(e=>e.name.toLowerCase().includes(q)||String(e.target||"").toLowerCase().includes(q));
    return pool.filter(e=>!prog.find(p=>p.id===e.id)).slice(0,8);
  })();

  const saveNew = () => {
    set("cc_vas_now",qv.pain_today);
    let hepNote="";
    if(pending.length){
      const version=(parseInt(data.hep_version)||1)+1;
      set("hep_version",version);
      const log=Array.isArray(data.hep_log)?data.hep_log:[];
      set("hep_log",[{session:sessionNo,date:new Date().toLocaleDateString("en-GB"),changes:pending,version},...log]);
      hepNote=`HEP v${version}: ${pending.join(" · ")}`;
    }
    set("soap_extra_p",[qv.next_plan,hepNote].filter(Boolean).join(" | "));
    const exercisesSnapshot = prog.map(e=>({id:e.id,name:e.name,detail:hepDose(e)}));
    const rxSnapshot = rxProgramme.map(e=>({id:e.id,name:e.name,detail:hepDose(e)}));
    const entry = {
      id:(Date.now()).toString(36),date:new Date().toLocaleDateString("en-GB"),sessionNo,type:"Follow-up Treatment",
      vasStart:qv.pain_today,vasEnd:qv.pain_after||qv.pain_today,
      treatmentGiven:treatmentList.map(t=>t.name).join(", "),response:qv.response,nextPlan:qv.next_plan,hepChanges:pending,
      exercises:exercisesSnapshot, modalities, treatment:treatmentList, quickNote:qv.response,
      exercisePrescription:rxSnapshot,
      savedAt:new Date().toISOString()
    };
    set("tx_sessions",[entry,...sessionsArr]);
    setPending([]);
    setSaved(true);
    setTimeout(()=>{setSaved(false); navTo("home");},900);
  };

  const updatePast = () => {
    const updated = {
      ...activeSession,
      vasStart:qv.pain_today, vasEnd:qv.pain_after||qv.pain_today,
      treatmentGiven:treatmentList.map(t=>t.name).join(", "), response:qv.response, nextPlan:qv.next_plan,
      exercises:pastExercises, modalities, treatment:treatmentList, quickNote:qv.response,
      exercisePrescription:pastRx,
      editedAt:new Date().toISOString()
    };
    set("tx_sessions", sessionsArr.map(s=>s.id===activeId?updated:s));
    setSaved(true);
    setTimeout(()=>{setSaved(false); onBack();},700);
  };

  return(
    <div>
      <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}>
        <span onClick={onBack} style={{cursor:"pointer",fontSize:"0.95rem",color:PC.muted,lineHeight:1}} title="Back to sessions">←</span>
        <div style={{...sectionLbl,marginBottom:0}}>{isNew?`Today — Session ${sessionNo}`:`Session ${sessionNo} · ${activeSession?.date||""}`}</div>
      </div>

      {(()=>{
        const TEAL="#0F6E56", TEAL_BG=PC.isDark?"rgba(29,158,117,0.14)":"#E1F5EE", TEAL_BORDER="#5DCAA5";
        const start=parseFloat(qv.pain_today), end=parseFloat(qv.pain_after);
        const bothSet=!isNaN(start)&&!isNaN(end);
        const delta=bothSet?start-end:0;
        const endLower=bothSet&&end<start;
        const endStyle={...inp,...(endLower?{border:`1.5px solid ${TEAL_BORDER}`,background:TEAL_BG,color:TEAL,fontWeight:700}:{})};
        return(
          <div style={{background:PC.surface,border:`1px solid ${PC.border}`,borderRadius:12,padding:"12px 14px",marginBottom:14}}>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
              <div><label style={lbl}>Pain — start</label><input style={inp} type="number" min="0" max="10" placeholder="e.g. 5" value={qv.pain_today} onChange={e=>setQv(p=>({...p,pain_today:e.target.value}))}/></div>
              <div><label style={lbl}>Pain — end</label><input style={endStyle} type="number" min="0" max="10" placeholder="e.g. 3" value={qv.pain_after} onChange={e=>setQv(p=>({...p,pain_after:e.target.value}))}/></div>
            </div>
            {bothSet&&(
              <div style={{marginTop:10,display:"flex",alignItems:"center",gap:6,fontSize:"0.78rem",padding:"7px 10px",borderRadius:8,
                background:delta>0?TEAL_BG:(delta<0?"rgba(220,38,38,0.08)":PC.s2),
                color:delta>0?TEAL:(delta<0?"#dc2626":PC.muted)}}>
                <span style={{fontWeight:800}}>{delta>0?`↓ ${delta} point${delta!==1?"s":""} lower`:delta<0?`↑ ${Math.abs(delta)} point${Math.abs(delta)!==1?"s":""} higher`:"No change"}</span>
                <span style={{color:PC.muted}}>this session</span>
              </div>
            )}
          </div>
        );
      })()}

      <div style={{marginBottom:14}}>
        <div style={sectionLbl}>Treatment {isNew&&lastSession&&treatmentList.length>0&&<span style={{fontWeight:500,textTransform:"none",color:PC.muted}}>(copied from S{lastSession.sessionNo||sessionNo-1})</span>}</div>
        <EditableItemList PC={PC} items={treatmentList}
          onAdd={(it)=>setTreatmentList(l=>[...l,{id:Math.random().toString(36).slice(2,9),...it}])}
          onEdit={(id,patch)=>setTreatmentList(l=>l.map(t=>t.id===id?{...t,...patch}:t))}
          onRemove={(id)=>setTreatmentList(l=>l.filter(t=>t.id!==id))}
          addLabel="＋ Add treatment" quickOptions={txOptions}/>
      </div>

      <div style={{marginBottom:14}}>
        <div style={sectionLbl}>Modalities</div>
        <EditableItemList PC={PC} items={modalities}
          onAdd={(it)=>setModalities(l=>[...l,{id:Math.random().toString(36).slice(2,9),...it}])}
          onEdit={(id,patch)=>setModalities(l=>l.map(m=>m.id===id?{...m,...patch}:m))}
          onRemove={(id)=>setModalities(l=>l.filter(m=>m.id!==id))}
          addLabel="＋ Add modality" quickOptions={modalityOptions}/>
      </div>

      <div style={{marginBottom:10}}><label style={lbl}>Quick note</label><input style={inp} placeholder="e.g. Good improvement, less pain on movement" value={qv.response} onChange={e=>setQv(p=>({...p,response:e.target.value}))}/></div>
      <div style={{marginBottom:14}}><label style={lbl}>Plan for next session</label><input style={inp} placeholder="e.g. Progress to single-leg squat" value={qv.next_plan} onChange={e=>setQv(p=>({...p,next_plan:e.target.value}))}/></div>

      <div style={{marginBottom:14}}>
        <div style={sectionLbl}>Exercises {isNew&&prog.length>0&&<span style={{fontWeight:600,textTransform:"none"}}>· v{parseInt(data.hep_version)||1} · {prog.length} exercise{prog.length!==1?"s":""}</span>}</div>

        {isNew?(<>
          {prog.length===0&&(
            <div style={{padding:"10px 12px",background:PC.s2,borderRadius:9,fontSize:"0.8rem",color:PC.muted,marginBottom:8}}>No protocol yet — add exercises below or build it in the Exercise Prescription tab.</div>
          )}
          {prog.map(e=>(
            <div key={e.id} style={{marginBottom:5}}>
              <div style={{display:"flex",alignItems:"center",gap:7,padding:"8px 10px",background:e.addedSession===sessionNo?`${PC.accent}10`:PC.s2,border:`1px solid ${e.addedSession===sessionNo?PC.accent+"35":PC.border}`,borderRadius:9}}>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{fontSize:"0.76rem",fontWeight:700,color:PC.text}}>{e.name}
                    {e.addedSession===sessionNo&&<span style={{marginLeft:6,fontSize:"0.75rem",fontWeight:800,color:PC.accent}}>＋ just added</span>}
                    {e.progressedSession===sessionNo&&<span style={{marginLeft:6,fontSize:"0.75rem",fontWeight:800,color:PC.a3}}>↑ progressed</span>}
                  </div>
                  <div style={{fontSize:"0.82rem",color:PC.muted}}>{hepDose(e)}</div>
                </div>
                <SessionPill bg={`${PC.a3}18`} col={PC.a3} title="Progress dosage" onClick={()=>startProgress(e)}>↑</SessionPill>
                <SessionPill bg="rgba(220,38,38,0.1)" col="#dc2626" title="Remove" onClick={()=>setRemoveId(removeId===e.id?null:e.id)}>−</SessionPill>
              </div>
              {editId===e.id&&(
                <div style={{display:"flex",gap:6,alignItems:"center",padding:"7px 10px",background:`${PC.a3}08`,border:`1px dashed ${PC.a3}40`,borderRadius:9,marginTop:3}}>
                  {["sets","reps","hold"].map(f=>(
                    <input key={f} style={{...inp,width:62,padding:"5px 7px",fontSize:"0.82rem"}} placeholder={f} value={editDose[f]} onChange={ev=>setEditDose(p=>({...p,[f]:ev.target.value}))}/>
                  ))}
                  <span style={{fontSize:"0.78rem",color:PC.muted}}>sets × reps · hold s</span>
                  <button onClick={applyProgress} style={{marginLeft:"auto",padding:"5px 12px",borderRadius:7,border:"none",background:PC.a3,color:"#fff",fontWeight:800,fontSize:"0.75rem",cursor:"pointer"}}>✓ Apply</button>
                </div>
              )}
              {removeId===e.id&&(
                <div style={{display:"flex",gap:5,flexWrap:"wrap",padding:"7px 10px",background:"rgba(220,38,38,0.05)",border:"1px dashed rgba(220,38,38,0.35)",borderRadius:9,marginTop:3,alignItems:"center"}}>
                  <span style={{fontSize:"0.8rem",color:"#dc2626",fontWeight:700}}>Why?</span>
                  {["Mastered","Aggravating","Replaced","Other"].map(r=>(
                    <button key={r} onClick={()=>removeExercise(e.id,r)} style={{padding:"4px 10px",borderRadius:7,border:"1px solid rgba(220,38,38,0.3)",background:"transparent",color:"#dc2626",fontWeight:700,fontSize:"0.82rem",cursor:"pointer"}}>{r}</button>
                  ))}
                </div>
              )}
            </div>
          ))}

          {!pickerOpen?(
            <div onClick={()=>setPickerOpen(true)} style={{padding:"9px",border:`1.5px dashed ${PC.accent}50`,borderRadius:9,textAlign:"center",fontSize:"0.82rem",fontWeight:700,color:PC.accent,cursor:"pointer",marginBottom:10}}>＋ Add exercise from library</div>
          ):(
            <div style={{border:`1.5px solid ${PC.accent}35`,borderRadius:11,padding:"10px",marginBottom:10,background:`${PC.accent}06`}}>
              <div style={{display:"flex",gap:6,marginBottom:7}}>
                {[["library","📚 Library"],["templates","📦 Templates"]].map(([m,l])=>(
                  <button key={m} onClick={()=>setPickerMode(m)} style={{flex:1,padding:"7px",borderRadius:8,border:`1px solid ${pickerMode===m?PC.accent:PC.border}`,background:pickerMode===m?`${PC.accent}15`:"transparent",color:pickerMode===m?PC.accent:PC.muted,fontWeight:800,fontSize:"0.78rem",cursor:"pointer"}}>{l}</button>
                ))}
                <button onClick={()=>setPickerOpen(false)} style={{padding:"0 10px",borderRadius:8,border:`1px solid ${PC.border}`,background:"transparent",color:PC.muted,cursor:"pointer",fontWeight:700}}>✕</button>
              </div>
              {pickerMode==="templates"&&(
                <div>
                  {Object.entries(PROGRAMME_TEMPLATES).map(([key,t])=>{
                    const tx=TEMPLATE_TX[key];
                    const isOpen=openTemplate===key;
                    return(
                      <div key={key} style={{marginBottom:4}}>
                        <div onClick={()=>setOpenTemplate(isOpen?null:key)} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 10px",borderRadius:8,cursor:"pointer",background:PC.surface,border:`1px solid ${isOpen?PC.accent+"45":PC.border}`}}>
                          <div style={{flex:1,minWidth:0}}>
                            <div style={{fontSize:"0.82rem",fontWeight:700,color:PC.text}}>{t.label}</div>
                            <div style={{fontSize:"0.78rem",color:PC.muted}}>{t.exercises.length} exercises{tx?` · ${(tx.manual||[]).length} manual · ${(tx.machine||[]).length} machine`:""}</div>
                          </div>
                          <span style={{fontSize:"0.75rem",color:PC.accent,fontWeight:800}}>{isOpen?"▲":"▼"}</span>
                        </div>
                        {isOpen&&(
                          <div style={{padding:"8px 10px",border:`1px dashed ${PC.accent}35`,borderTop:"none",borderRadius:"0 0 8px 8px",background:`${PC.accent}05`}}>
                            <button onClick={()=>{addTemplate(key);setOpenTemplate(null);}} style={{width:"100%",padding:"8px",borderRadius:8,border:"none",background:`linear-gradient(135deg,${PC.accent},${PC.a2})`,color:"#fff",fontWeight:800,fontSize:"0.78rem",cursor:"pointer",marginBottom:7}}>＋ Add {t.exercises.length} exercises to protocol</button>
                            {tx&&(tx.manual||[]).length>0&&(
                              <div style={{marginBottom:5}}>
                                <div style={{fontSize:"0.75rem",fontWeight:800,color:PC.muted,textTransform:"uppercase",letterSpacing:"0.5px",marginBottom:3}}>🤲 Manual — tap to add to treatment</div>
                                <div style={{display:"flex",flexWrap:"wrap",gap:4}}>
                                  {tx.manual.map(m=><button key={m} onClick={()=>addTxItem(m)} style={{padding:"3px 9px",borderRadius:99,border:`1px solid ${treatmentList.find(t=>t.name===m)?PC.accent:PC.border}`,background:treatmentList.find(t=>t.name===m)?`${PC.accent}14`:PC.surface,color:treatmentList.find(t=>t.name===m)?PC.accent:PC.text,fontWeight:700,fontSize:"0.8rem",cursor:"pointer"}}>{treatmentList.find(t=>t.name===m)?"✓ ":""}{m}</button>)}
                                </div>
                              </div>
                            )}
                            {tx&&(tx.machine||[]).length>0&&(
                              <div>
                                <div style={{fontSize:"0.75rem",fontWeight:800,color:PC.muted,textTransform:"uppercase",letterSpacing:"0.5px",marginBottom:3}}>⚡ Machine — tap to add to treatment</div>
                                <div style={{display:"flex",flexWrap:"wrap",gap:4}}>
                                  {tx.machine.map(m=><button key={m} onClick={()=>addTxItem(m)} style={{padding:"3px 9px",borderRadius:99,border:`1px solid ${treatmentList.find(t=>t.name===m)?PC.a2:PC.border}`,background:treatmentList.find(t=>t.name===m)?`${PC.a2}14`:PC.surface,color:treatmentList.find(t=>t.name===m)?PC.a2:PC.text,fontWeight:700,fontSize:"0.8rem",cursor:"pointer"}}>{treatmentList.find(t=>t.name===m)?"✓ ":""}{m}</button>)}
                                </div>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
              {pickerMode==="library"&&(
              <div style={{display:"flex",gap:6,marginBottom:7}}>
                <input autoFocus style={{...inp,flex:1}} placeholder="Search exercises… e.g. plank, chin tuck" value={pickerSearch} onChange={e=>setPickerSearch(e.target.value)}/>
                <select style={{...inp,width:120}} value={pickerRegion} onChange={e=>setPickerRegion(e.target.value)}>
                  <option value="all">All regions</option>
                  {Object.entries(EXERCISE_DB).map(([k,r])=><option key={k} value={k}>{r.label}</option>)}
                </select>
              </div>
              )}
              {pickerMode==="library"&&pickerResults.length===0&&<div style={{fontSize:"0.66rem",color:PC.muted,padding:"4px 2px"}}>No matches — try another term or region.</div>}
              {pickerMode==="library"&&pickerResults.map(ex=>(
                <div key={ex.id} onClick={()=>addExercise(ex)} style={{display:"flex",alignItems:"center",gap:8,padding:"7px 9px",borderRadius:8,cursor:"pointer",background:PC.surface,border:`1px solid ${PC.border}`,marginBottom:4}}>
                  <div style={{flex:1,minWidth:0}}>
                    <div style={{fontSize:"0.82rem",fontWeight:700,color:PC.text}}>{ex.name}</div>
                    <div style={{fontSize:"0.78rem",color:PC.muted,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{ex.sets}×{ex.reps}{ex.hold?` · ${ex.hold}s`:""} · {ex.freq} · {ex.target}</div>
                  </div>
                  <span style={{fontSize:"0.82rem",fontWeight:800,color:PC.accent,flexShrink:0}}>＋ Add</span>
                </div>
              ))}
            </div>
          )}

          {pending.length>0&&(
            <div style={{padding:"8px 11px",background:`${PC.accent}0a`,border:`1px solid ${PC.accent}25`,borderRadius:9,fontSize:"0.75rem",color:PC.text,marginBottom:10,lineHeight:1.6}}>
              <span style={{fontWeight:800,color:PC.accent}}>This session:</span> {pending.join(" · ")} <span style={{color:PC.muted}}>(will be logged as v{(parseInt(data.hep_version)||1)+1} on save)</span>
            </div>
          )}
        </>):(
          <EditableItemList PC={PC} items={pastExercises}
            onAdd={(it)=>setPastExercises(l=>[...l,{id:Math.random().toString(36).slice(2,9),...it}])}
            onEdit={(id,patch)=>setPastExercises(l=>l.map(e=>e.id===id?{...e,...patch}:e))}
            onRemove={(id)=>setPastExercises(l=>l.filter(e=>e.id!==id))}
            addLabel="＋ Add exercise"/>
        )}
      </div>

      <div style={{marginBottom:14}}>
        <div style={sectionLbl}>Exercise Prescription {rxProgramme.length>0&&<span style={{fontWeight:600,textTransform:"none"}}>· {rxProgramme.length} exercise{rxProgramme.length!==1?"s":""}</span>}</div>
        {/* Exercise Prescription is a standing treatment programme, not a
            per-visit event like Modalities/Treatment -- always shows what's
            CURRENTLY prescribed (data.tx_exercise_prescription) whether
            you're looking at today's session or a past one, rather than a
            frozen historical snapshot. A past session freezing this the
            same way it freezes Modalities/Treatment meant exercises picked
            after that session was saved would never show up when you
            reopened it -- which is exactly what "not showing in session"
            reports were describing. */}
        {rxProgramme.length===0&&<div style={{fontSize:"0.78rem",color:PC.muted,padding:"4px 0 8px"}}>None prescribed yet.</div>}
        {rxProgramme.map(e=>(
          <div key={e.id} style={{display:"flex",alignItems:"center",gap:7,padding:"8px 10px",background:PC.s2,border:`1px solid ${PC.border}`,borderRadius:9,marginBottom:5}}>
            <div style={{flex:1,minWidth:0}}>
              <div style={{fontSize:"0.76rem",fontWeight:700,color:PC.text}}>{e.name}</div>
              <div style={{fontSize:"0.82rem",color:PC.muted}}>{hepDose(e)}</div>
            </div>
            <SessionPill bg="rgba(220,38,38,0.1)" col="#dc2626" title="Remove" onClick={()=>removeRx(e.id)}>−</SessionPill>
          </div>
        ))}
        <div onClick={()=>navTo("treatment")} style={{padding:"9px",border:`1.5px dashed ${PC.accent}50`,borderRadius:9,textAlign:"center",fontSize:"0.82rem",fontWeight:700,color:PC.accent,cursor:"pointer"}}>＋ Add / edit in Exercise Prescription →</div>
      </div>

      <button onClick={isNew?saveNew:updatePast} style={{width:"100%",padding:"13px",borderRadius:12,border:"none",background:"#0F6E56",color:"#fff",fontWeight:800,fontSize:"0.85rem",cursor:"pointer",marginBottom:8}}>
        {saved?(isNew?"✅ Session saved":"✅ Session updated"):(isNew?"Save session":"Update session")}
      </button>
      {isNew&&(
        <div style={{display:"flex",gap:8}}>
          <button onClick={()=>sendHepWhatsApp(data)} style={{flex:1,padding:"10px",borderRadius:9,border:`1px solid ${PC.a3}40`,background:`${PC.a3}10`,color:PC.a3,fontWeight:800,fontSize:"0.82rem",cursor:"pointer"}}>📲 Send protocol — WhatsApp</button>
          <button onClick={()=>downloadHepPdf(data)} style={{flex:1,padding:"10px",borderRadius:9,border:`1px solid ${PC.a2}40`,background:`${PC.a2}10`,color:PC.a2,fontWeight:800,fontSize:"0.82rem",cursor:"pointer"}}>📄 PDF handout</button>
        </div>
      )}
    </div>
  );
}

export { SessionDetailView };
