// The session editor and the home-exercise-programme sender. Split out of
// AppModules.jsx because they pull in the whole exercise library (~130 KB of
// data) and are only needed once a session is opened; AppModules.jsx loads this
// file on demand (see its SessionDetailView wrapper).
import { useState } from "react";
import { downloadPDFFromHTML, injectViewerControls } from "./sharedClinicalData.js";
import { EXERCISE_DB, ALL_EXERCISES, PROGRAMME_TEMPLATES, TEMPLATE_TX } from "./sharedClinicalData.js";
import { EditableItemList, SessionPill, legacyTreatmentToList } from "./AppModules.jsx";
import { isDraftSession, completedSessions, nextSessionNo, longDate, shortDate } from "./txSessions.js";

// ── HEP protocol helpers — versioned home programme with WhatsApp/PDF send ──
function hepDose(e){ const st=e.customSets||e.sets, rp=e.customReps||e.reps, hd=e.customHold||e.hold, fq=e.customFreq||e.freq; return [st&&rp?`${st}×${rp}`:st?`${st} sets`:rp?`${rp} reps`:"", hd?`hold ${hd}s`:"", fq||""].filter(Boolean).join(" · "); }
function buildHepWhatsAppText(d){
  const prog=Array.isArray(d.hep_programme)?d.hep_programme:[];
  if(!prog.length) return "";
  const v=parseInt(d.hep_version)||1;
  const lines=prog.map((e,i)=>`${i+1}. ${e.name} — ${hepDose(e)}`);
  return `🏥 ${d.clinic_name||"PhysioMind"} — Home Exercise Programme (v${v})\nPatient: ${d.dem_name||""}\nDate: ${new Date().toLocaleDateString("en-GB")}\n\n${lines.join("\n")}\n\nStop if severe pain. Mild discomfort is normal. Contact your physiotherapist if unsure.`;
}
export function sendHepWhatsApp(d){
  const text=buildHepWhatsAppText(d);
  if(!text){alert("No exercises in the home protocol yet.");return;}
  const phone=String(d.dem_phone||d.dem_contact||"").replace(/[^0-9]/g,"");
  const url=phone.length>=10?`https://wa.me/${phone}?text=${encodeURIComponent(text)}`:`https://wa.me/?text=${encodeURIComponent(text)}`;
  window.open(url,"_blank");
}
export function downloadHepPdf(d){
  const prog=Array.isArray(d.hep_programme)?d.hep_programme:[];
  if(!prog.length){alert("No exercises in the home protocol yet.");return;}
  const v=parseInt(d.hep_version)||1;
  const html=`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Home Exercise Programme</title>
<style>@page{size:A4;margin:18mm}*{box-sizing:border-box;font-family:'Segoe UI',Arial,sans-serif}body{background:#fff;color:#1a1a2e;font-size:11px;line-height:1.55}.header{border-bottom:3px solid #7c3aed;padding-bottom:12px;margin-bottom:16px;display:flex;justify-content:space-between}.logo{font-size:20px;font-weight:900;color:#7c3aed}.meta{text-align:right;font-size:10px;color:#555}.ex{border:1px solid #e2e8f0;border-radius:8px;margin-bottom:10px;overflow:hidden;break-inside:avoid}.ex-h{background:#7c3aed;color:#fff;padding:8px 12px;display:flex;justify-content:space-between}.ex-t{font-size:12px;font-weight:800}.ex-b{padding:10px 12px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:8px}.st{background:#f5f3ff;border-radius:6px;padding:5px 8px;text-align:center}.sv{font-size:13px;font-weight:900;color:#7c3aed}.sl{font-size:8px;color:#64748b;text-transform:uppercase}.desc{font-size:10.5px;color:#334155;margin-bottom:6px}.cues{background:#fefce8;border-left:3px solid #fbbf24;padding:5px 8px;font-size:10px;color:#713f12}.footer{margin-top:16px;padding-top:10px;border-top:1px solid #e2e8f0;font-size:9px;color:#94a3b8;text-align:center}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style>
</head><body>
<div class="header"><div><div class="logo">PhysioMind</div><div style="font-size:11px;color:#555;margin-top:2px">Home Exercise Programme — v${v}</div></div><div class="meta"><div><b>Patient:</b> ${d.dem_name||"—"}</div><div><b>Date:</b> ${new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"})}</div></div></div>
<p style="font-size:10px;color:#555;margin-bottom:14px">Perform exercises as prescribed. Stop if severe pain. Mild discomfort is normal. Contact your physiotherapist if unsure.</p>
${prog.map((ex,i)=>`<div class="ex"><div class="ex-h"><span class="ex-t">${i+1}. ${ex.name}</span><span style="font-size:9px;opacity:0.85">${ex.phase||""}</span></div><div class="ex-b"><div class="grid"><div class="st"><div class="sv">${ex.customSets||ex.sets||"—"}</div><div class="sl">Sets</div></div><div class="st"><div class="sv">${ex.customReps||ex.reps||"—"}</div><div class="sl">Reps</div></div><div class="st"><div class="sv">${(ex.customHold||ex.hold)?(ex.customHold||ex.hold)+"s":"—"}</div><div class="sl">Hold</div></div><div class="st"><div class="sv" style="font-size:9px">${ex.customFreq||ex.freq||"—"}</div><div class="sl">Freq</div></div></div><div class="desc">${ex.desc||""}</div>${ex.cues?`<div class="cues">💡 ${ex.cues}</div>`:""}</div></div>`).join("")}
<div class="footer">Generated by PhysioMind · ${new Date().toLocaleString()}</div>
</body></html>`;
  try{ downloadPDFFromHTML(html, `HEP_v${v}_${d.dem_name||"Patient"}_${Date.now()}.pdf`); }
  catch(e){ const w=window.open("","_blank"); w.document.write(injectViewerControls(html)); w.document.close(); setTimeout(()=>{try{w.print();}catch(_){}},500); }
}

// ── Screen 2: one session, fully editable — exercises, modalities,
// treatment (each with its own add/edit/remove), pain, and a quick note.
// For a brand-new (unsaved) session, exercises still edit the live,
// ongoing hep_programme exactly as before (today's changes should affect
// the active protocol). For a past, already-saved session, exercises are
// that session's own frozen snapshot -- editing it corrects the historical
// record without silently rewriting today's active protocol.
export default function SessionDetailView({ PC, data, set, navTo, sessionsArr, activeId, onBack, onStartNext, onOpen }) {
  // A brand-new session that has been saved as a draft is found again by its new id.
  const [createdId, setCreatedId] = useState(null);
  const lookupId = activeId!==null ? activeId : createdId;
  const found = lookupId===null ? null : (sessionsArr.find(s=>s.id===lookupId)||null);
  // A draft is edited exactly like a brand-new session; only a completed one is "past".
  const draft = found && isDraftSession(found) ? found : null;
  const isNew = lookupId===null || !!draft;
  const activeSession = isNew ? null : found;
  const done = completedSessions(sessionsArr);
  const lastSession = done[0];
  const sessionNo = draft ? (draft.sessionNo||nextSessionNo(sessionsArr)) : isNew ? nextSessionNo(sessionsArr) : (activeSession?.sessionNo||done.length);
  const [completed, setCompleted] = useState(null);   // entry just completed -> confirmation screen
  const [mode, setMode] = useState(isNew ? "edit" : "summary"); // completed sessions open as a read-only summary
  const [error, setError] = useState("");
  const [tab, setTab] = useState("treatment");
  const [draftSaved, setDraftSaved] = useState(false);

  const [qv, setQv] = useState(()=> draft
    ? {pain_today:draft.vasStart??"",pain_after:draft.vasEnd??"",response:draft.quickNote||"",next_plan:draft.nextPlan||""}
    : isNew
    ? {pain_today:data.cc_vas_now||lastSession?.vasEnd||"0",pain_after:"",response:"",next_plan:""}
    : {pain_today:activeSession?.vasStart||"",pain_after:activeSession?.vasEnd||"",response:activeSession?.quickNote||activeSession?.response||"",next_plan:activeSession?.nextPlan||""});
  const [saved, setSaved] = useState(false);
  const [pending, setPending] = useState(()=>Array.isArray(draft?.hepChanges)?draft.hepChanges:[]);          // protocol change descriptions this visit (new session only)
  const [pickerOpen, setPickerOpen] = useState(false);
  const [pickerMode, setPickerMode] = useState("library");
  const [pickerSearch, setPickerSearch] = useState("");
  const [pickerRegion, setPickerRegion] = useState("all");
  const [openTemplate, setOpenTemplate] = useState(null);
  const [editId, setEditId] = useState(null);
  const [editDose, setEditDose] = useState({sets:"",reps:"",hold:""});
  const [removeId, setRemoveId] = useState(null);

  const [treatmentList, setTreatmentList] = useState(()=> draft
    ? (Array.isArray(draft.treatment)?draft.treatment.map(t=>({...t})):[])
    : isNew
    ? (Array.isArray(lastSession?.treatment) ? lastSession.treatment.map(t=>({...t})) : legacyTreatmentToList(lastSession?.treatmentGiven))
    : (Array.isArray(activeSession?.treatment) ? activeSession.treatment.map(t=>({...t})) : legacyTreatmentToList(activeSession?.treatmentGiven)));
  const [modalities, setModalities] = useState(()=> draft ? (Array.isArray(draft.modalities)?draft.modalities.map(m=>({...m})):[]) : isNew ? [] : (Array.isArray(activeSession?.modalities)?activeSession.modalities.map(m=>({...m})):[]));
  const [pastExercises, setPastExercises] = useState(()=> isNew ? [] : (Array.isArray(activeSession?.exercises)?activeSession.exercises.map(e=>({...e})):[]));
  // Exercise Prescription -- a separate, standing treatment programme from
  // hep_programme (see ExercisePrescriptionModule, Treatment tab). This was
  // being prescribed for patients but never surfaced anywhere in Sessions.
  // Live for a new session (removing here removes from the real prescription,
  // same as Exercises does for hep_programme); a frozen snapshot for a past
  // session, same pattern as Exercises/Modalities/Treatment.
  const rxProgramme = Array.isArray(data.tx_exercise_prescription) ? data.tx_exercise_prescription : [];
  const [pastRx, setPastRx] = useState(()=> isNew ? [] : (Array.isArray(activeSession?.exercisePrescription)?activeSession.exercisePrescription.map(e=>({...e})):[]));
  const removeRx = (id) => { if(!set) return; set("tx_exercise_prescription", rxProgramme.filter(e=>e.id!==id)); };

  const txOptions = ["Joint mobilisation","Soft tissue massage","Dry needling","Exercise therapy","TENS/IFT","Neural mobilisation","Taping/strapping","Education & advice","Postural correction","Manual therapy","Other"];
  const modalityOptions = ["IFT","TENS","Hot pack","Cold pack","Ultrasound","Laser","Shockwave","Traction","Paraffin wax"];
  const inp = {width:"100%",background:PC.s2,border:`1px solid ${PC.border}`,borderRadius:8,color:PC.text,fontFamily:"inherit",outline:"none",padding:"8px 10px",fontSize:"0.8rem"};
  const lbl = {fontSize:"0.8rem",fontWeight:700,color:PC.muted,display:"block",marginBottom:4,textTransform:"uppercase",letterSpacing:"0.6px"};
  const sectionLbl = {fontSize:"0.82rem",fontWeight:800,color:PC.text,textTransform:"uppercase",letterSpacing:"0.7px",marginBottom:6};

  const prog = Array.isArray(data.hep_programme)?data.hep_programme:[];

  const addExercise = (ex) => {
    if(prog.find(p=>p.id===ex.id)) { setPickerOpen(false); return; }
    set("hep_programme",[...prog,{...ex,customSets:ex.sets,customReps:ex.reps,customHold:ex.hold,customFreq:ex.freq,notes:"",addedSession:sessionNo,addedDate:new Date().toISOString()}]);
    setPending(p=>[...p,`＋ ${ex.name}`]);
    setPickerOpen(false); setPickerSearch("");
  };
  const removeExercise = (id,reason) => {
    const ex=prog.find(p=>p.id===id);
    set("hep_programme",prog.filter(p=>p.id!==id));
    setPending(p=>[...p,`− ${ex?.name||id}${reason?` (${reason.toLowerCase()})`:""}`]);
    setRemoveId(null);
  };
  const startProgress = (e) => { setEditId(e.id); setEditDose({sets:String(e.customSets||e.sets||""),reps:String(e.customReps||e.reps||""),hold:String(e.customHold||e.hold||"")}); };
  const applyProgress = () => {
    const ex=prog.find(p=>p.id===editId); if(!ex){setEditId(null);return;}
    set("hep_programme",prog.map(p=>p.id===editId?{...p,customSets:editDose.sets,customReps:editDose.reps,customHold:editDose.hold,progressedSession:sessionNo}:p));
    setPending(p=>[...p,`↑ ${ex.name} ${editDose.sets}×${editDose.reps}${editDose.hold?` · ${editDose.hold}s`:""}`]);
    setEditId(null);
  };

  const addTxItem = (name) => setTreatmentList(list=>list.find(t=>t.name===name)?list:[...list,{id:Math.random().toString(36).slice(2,9),name,detail:""}]);
  const addTemplate = (key) => {
    const t=PROGRAMME_TEMPLATES[key]; if(!t) return;
    const exs=t.exercises.map(id=>ALL_EXERCISES.find(e=>e.id===id)).filter(Boolean).filter(e=>!prog.find(p=>p.id===e.id));
    if(exs.length){
      set("hep_programme",[...prog,...exs.map(ex=>({...ex,customSets:ex.sets,customReps:ex.reps,customHold:ex.hold,customFreq:ex.freq,notes:"",addedSession:sessionNo,addedDate:new Date().toISOString()}))]);
      setPending(p=>[...p,`＋ ${t.label} template (${exs.length} exercise${exs.length!==1?"s":""})`]);
    }
    const tx=TEMPLATE_TX[key];
    if(tx){ (tx.manual||[]).forEach(addTxItem); (tx.machine||[]).forEach(addTxItem); }
  };
  const pickerResults = (()=>{
    if(!pickerOpen) return [];
    let pool = pickerRegion==="all" ? ALL_EXERCISES : (Object.values(EXERCISE_DB[pickerRegion]?.categories||{}).flat());
    const q=pickerSearch.trim().toLowerCase();
    if(q) pool=pool.filter(e=>e.name.toLowerCase().includes(q)||String(e.target||"").toLowerCase().includes(q));
    return pool.filter(e=>!prog.find(p=>p.id===e.id)).slice(0,8);
  })();

  const buildEntry = (status) => {
    const now = new Date().toISOString();
    return {
      ...(draft||{}),
      id: draft?.id || (Date.now()).toString(36),
      date: draft?.date || new Date().toLocaleDateString("en-GB"),
      sessionNo, type:"Follow-up Treatment", status,
      vasStart:qv.pain_today, vasEnd:(qv.pain_after!==""||status==="draft")?qv.pain_after:qv.pain_today,
      treatmentGiven:treatmentList.map(t=>t.name).join(", "), response:qv.response, nextPlan:qv.next_plan, hepChanges:pending,
      exercises:prog.map(e=>({id:e.id,name:e.name,detail:hepDose(e)})), modalities, treatment:treatmentList, quickNote:qv.response,
      exercisePrescription:rxProgramme.map(e=>({id:e.id,name:e.name,detail:hepDose(e)})),
      savedAt: draft?.savedAt || now, updatedAt: now,
      ...(status==="completed" ? {completedAt:now} : {}),
    };
  };
  // Replace this session's draft in place (or add it as the newest entry).
  const putEntry = (entry) => set("tx_sessions", draft ? sessionsArr.map(x=>x.id===draft.id?entry:x) : [entry,...sessionsArr]);

  const saveDraft = () => {
    setError("");
    const entry = buildEntry("draft");
    putEntry(entry);
    setCreatedId(entry.id);
    setDraftSaved(true);
    setTimeout(()=>setDraftSaved(false),1800);
  };

  const completeSession = () => {
    if(treatmentList.length===0 && modalities.length===0 && !qv.response.trim()){
      setError("Add at least one treatment or a session note before completing.");
      return;
    }
    if(qv.pain_today===""||qv.pain_after===""||isNaN(parseFloat(qv.pain_today))||isNaN(parseFloat(qv.pain_after))){
      setError("Set the pain rating before and after treatment.");
      return;
    }
    setError("");
    set("cc_vas_now",qv.pain_after);
    let hepNote="";
    if(pending.length){
      const version=(parseInt(data.hep_version)||1)+1;
      set("hep_version",version);
      const log=Array.isArray(data.hep_log)?data.hep_log:[];
      set("hep_log",[{session:sessionNo,date:new Date().toLocaleDateString("en-GB"),changes:pending,version},...log]);
      hepNote=`HEP v${version}: ${pending.join(" · ")}`;
    }
    set("soap_extra_p",[qv.next_plan,hepNote].filter(Boolean).join(" | "));
    const entry = buildEntry("completed");
    putEntry(entry);
    setPending([]);
    setCompleted(entry);
  };

  const updatePast = () => {
    const updated = {
      ...activeSession,
      vasStart:qv.pain_today, vasEnd:qv.pain_after||qv.pain_today,
      treatmentGiven:treatmentList.map(t=>t.name).join(", "), response:qv.response, nextPlan:qv.next_plan,
      exercises:pastExercises, modalities, treatment:treatmentList, quickNote:qv.response,
      exercisePrescription:pastRx,
      editedAt:new Date().toISOString()
    };
    set("tx_sessions", sessionsArr.map(s=>s.id===activeId?updated:s));
    setSaved(true);
    setTimeout(()=>{setSaved(false); setMode("summary");},700);
  };

  const patientName = data.dem_name||"";
  const condition = data.cc_main||"";
  if(completed){
    return <SessionCompleted PC={PC} entry={completed} patientName={patientName}
      onSummary={()=>onOpen?onOpen(completed.id):setCompleted(null)}
      onNext={onStartNext} onBack={onBack}/>;
  }
  if(!isNew && mode==="summary" && activeSession){
    return <SessionSummary PC={PC} entry={activeSession} patientName={patientName} condition={condition}
      onEdit={()=>setMode("edit")} onHistory={onBack} onNext={onStartNext}/>;
  }
  const prevDate = lastSession ? longDate(lastSession.completedAt||lastSession.savedAt, lastSession.date) : "";
  const detailRow = (k,v) => <div style={{display:"flex",justifyContent:"space-between",gap:10,padding:"5px 0",fontSize:"0.82rem"}}><span style={{color:PC.muted}}>{k}</span><span style={{fontWeight:700,color:PC.text}}>{v}</span></div>;

  const initials = (patientName||"?").split(" ").map(w=>w[0]).filter(Boolean).slice(0,2).join("").toUpperCase();
  const TABS = [["treatment","Treatment"],["exercises","Exercises"],["notes","Notes"],["progress","Progress"]];
  const show = (t) => tab===t ? "block" : "none";
  const age = data.dem_age || data.age || "";
  const sex = data.dem_sex || data.sex || "";
  const sub = [sex, age?`${age} years`:""].filter(Boolean).join(" · ");
  const card = {background:PC.surface,border:`1px solid ${PC.border}`,borderRadius:16,padding:"12px 14px",marginBottom:14,boxShadow:"0 4px 14px rgba(109,40,217,.07)"};
  const orderBox = (o,t,children) => <div style={{order:o,display:show(t)}}>{children}</div>;

  return(
    <div>
      <div style={{borderRadius:20,overflow:"hidden",boxShadow:"0 14px 30px rgba(187,107,227,.30)",marginBottom:14}}>
        <div style={{background:"linear-gradient(135deg,#8f63f0 0%,#bb6be3 52%,#e77fc0 100%)",padding:"14px 14px 0"}}>
          <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:12}}>
            <span onClick={onBack} style={{cursor:"pointer",fontSize:"1.2rem",color:"#fff",lineHeight:1,padding:"4px 6px"}} title="Back to sessions">←</span>
            <div style={{width:54,height:54,borderRadius:16,background:"rgba(255,255,255,.9)",color:"#6D28D9",fontWeight:800,fontSize:"1.1rem",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{initials}</div>
            <div style={{flex:1,minWidth:0}}>
              <div style={{fontWeight:800,fontSize:"1.05rem",color:"#fff",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{patientName||"Patient"}</div>
              {sub&&<div style={{fontSize:"0.8rem",color:"rgba(255,255,255,.9)"}}>{sub}</div>}
              {condition&&<div style={{fontSize:"0.8rem",color:"rgba(255,255,255,.9)",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{condition}</div>}
            </div>
            <div style={{textAlign:"right",flexShrink:0}}>
              <div style={{background:"rgba(255,255,255,.92)",color:"#6D28D9",fontWeight:800,fontSize:"0.78rem",padding:"5px 10px",borderRadius:10}}>Session {sessionNo}</div>
              <div style={{fontSize:"0.72rem",color:"rgba(255,255,255,.92)",marginTop:4}}>{draft?"Draft · ":""}{isNew?shortDate(new Date().toISOString()):shortDate(activeSession?.completedAt||activeSession?.savedAt, activeSession?.date||"")}</div>
            </div>
          </div>
          <div role="tablist" style={{display:"flex",background:"#fff",borderRadius:"16px 16px 0 0",padding:"0 6px"}}>
            {TABS.map(([k,l])=>(
              <button key={k} role="tab" aria-selected={tab===k} type="button" onClick={()=>setTab(k)}
                style={{flex:1,padding:"12px 2px",background:"none",border:"none",borderBottom:`3px solid ${tab===k?"#6D28D9":"transparent"}`,color:tab===k?"#6D28D9":PC.muted,fontWeight:tab===k?800:600,fontSize:"0.85rem",cursor:"pointer",fontFamily:"inherit"}}>{l}</button>
            ))}
          </div>
        </div>
      </div>

      <div style={{display:show("treatment"),...card}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:10}}>
          <div style={{flex:1,minWidth:0}}>
            <div style={{...sectionLbl,marginBottom:2}}>Session Details</div>
            {detailRow("Date", isNew ? longDate(new Date().toISOString()) : longDate(activeSession?.completedAt||activeSession?.savedAt, activeSession?.date||""))}
            {detailRow("Session Number", sessionNo)}
            {isNew && lastSession && detailRow("Previous Session", prevDate)}
          </div>
          {done.length>0&&<button type="button" onClick={onBack} style={{padding:"10px 12px",borderRadius:12,border:"none",background:"#EDE9FE",color:"#6D28D9",fontWeight:800,fontSize:"0.8rem",cursor:"pointer",whiteSpace:"nowrap"}}>View History ›</button>}
        </div>
      </div>

      <div style={{display:"flex",flexDirection:"column"}}>
      <div style={{order:5,display:tab==="treatment"||tab==="progress"?"block":"none"}}>
      {(()=>{
        const TEAL="#0F6E56", TEAL_BG=PC.isDark?"rgba(29,158,117,0.14)":"#E1F5EE", TEAL_BORDER="#5DCAA5";
        const start=parseFloat(qv.pain_today), end=parseFloat(qv.pain_after);
        const bothSet=!isNaN(start)&&!isNaN(end);
        const delta=bothSet?start-end:0;
        const endLower=bothSet&&end<start;
        return(
          <div style={{background:PC.surface,border:`1px solid ${PC.border}`,borderRadius:12,padding:"12px 14px",marginBottom:14}}>
            <div style={sectionLbl}>Pain Rating (NRS)</div>
            <div style={{display:"flex",gap:14,flexWrap:"wrap"}}>
              <PainStepper PC={PC} label="Before" value={qv.pain_today} onChange={v=>setQv(p=>({...p,pain_today:v}))}/>
              <PainStepper PC={PC} label="After" value={qv.pain_after} onChange={v=>setQv(p=>({...p,pain_after:v}))} highlight={endLower?{border:TEAL_BORDER,bg:TEAL_BG,col:TEAL}:null}/>
            </div>
            {bothSet&&(
              <div style={{marginTop:10,display:"flex",alignItems:"center",gap:6,fontSize:"0.78rem",padding:"7px 10px",borderRadius:8,
                background:delta>0?TEAL_BG:(delta<0?"rgba(220,38,38,0.08)":PC.s2),
                color:delta>0?TEAL:(delta<0?"#dc2626":PC.muted)}}>
                <span style={{fontWeight:800}}>{delta>0?`↓ ${delta} point${delta!==1?"s":""} lower`:delta<0?`↑ ${Math.abs(delta)} point${Math.abs(delta)!==1?"s":""} higher`:"No change"}</span>
                <span style={{color:PC.muted}}>this session</span>
              </div>
            )}
          </div>
        );
      })()}
      </div>

      {orderBox(1,"treatment",
      <div style={{marginBottom:14}}>
        <div style={sectionLbl}>Treatment Performed {isNew&&lastSession&&treatmentList.length>0&&<span style={{fontWeight:500,textTransform:"none",color:PC.muted}}>(copied from S{lastSession.sessionNo||sessionNo-1})</span>}</div>
        <div style={{border:`1px solid ${PC.border}`,borderRadius:14,overflow:"hidden",background:PC.surface,marginBottom:8}}>
          {txOptions.filter(o=>o!=="Other").map(name=>{
            const on = !!treatmentList.find(t=>t.name===name);
            return (
              <div key={name} role="checkbox" aria-checked={on} tabIndex={0}
                onClick={()=>setTreatmentList(l=>on?l.filter(t=>t.name!==name):[...l,{id:Math.random().toString(36).slice(2,9),name,detail:""}])}
                onKeyDown={e=>{if(e.key===" "||e.key==="Enter"){e.preventDefault();e.currentTarget.click();}}}
                style={{display:"flex",alignItems:"center",gap:12,padding:"13px 14px",borderBottom:`1px solid ${PC.border}`,cursor:"pointer",minHeight:44}}>
                <span style={{width:24,height:24,borderRadius:7,flexShrink:0,display:"flex",alignItems:"center",justifyContent:"center",background:on?"#16A34A":"transparent",border:on?"none":`1.5px solid ${PC.border}`,color:"#fff",fontSize:"0.9rem",fontWeight:800}}>{on?"✓":""}</span>
                <span style={{flex:1,fontSize:"0.9rem",color:PC.text}}>{name}</span>
              </div>
            );
          })}
        </div>
        <EditableItemList PC={PC} items={treatmentList}
          onAdd={(it)=>setTreatmentList(l=>[...l,{id:Math.random().toString(36).slice(2,9),...it}])}
          onEdit={(id,patch)=>setTreatmentList(l=>l.map(t=>t.id===id?{...t,...patch}:t))}
          onRemove={(id)=>setTreatmentList(l=>l.filter(t=>t.id!==id))}
          addLabel="＋ Add treatment / add a note on one" quickOptions={[]}/>
      </div>)}

      {orderBox(2,"treatment",
      <div style={{marginBottom:14}}>
        <div style={sectionLbl}>Modalities</div>
        <EditableItemList PC={PC} items={modalities}
          onAdd={(it)=>setModalities(l=>[...l,{id:Math.random().toString(36).slice(2,9),...it}])}
          onEdit={(id,patch)=>setModalities(l=>l.map(m=>m.id===id?{...m,...patch}:m))}
          onRemove={(id)=>setModalities(l=>l.filter(m=>m.id!==id))}
          addLabel="＋ Add modality" quickOptions={modalityOptions}/>
      </div>)}

      {orderBox(3,"treatment",
      <div style={{marginBottom:10}}><label style={lbl}>Session Notes</label><textarea style={{...inp,minHeight:84,resize:"vertical"}} placeholder="Add treatment notes, patient response, changes, etc." value={qv.response} onChange={e=>setQv(p=>({...p,response:e.target.value}))}/></div>)}
      {orderBox(4,"notes",
      <div style={{marginBottom:14}}><label style={lbl}>Plan for next session</label><input style={inp} placeholder="e.g. Progress to single-leg squat" value={qv.next_plan} onChange={e=>setQv(p=>({...p,next_plan:e.target.value}))}/></div>)}

      {orderBox(6,"exercises",
<div>
      <div style={{marginBottom:14}}>
        <div style={sectionLbl}>Exercises / Home Program {isNew&&prog.length>0&&<span style={{fontWeight:600,textTransform:"none"}}>· v{parseInt(data.hep_version)||1} · {prog.length} exercise{prog.length!==1?"s":""}</span>}</div>

        {isNew?(<>
          {prog.length===0&&(
            <div style={{padding:"10px 12px",background:PC.s2,borderRadius:9,fontSize:"0.8rem",color:PC.muted,marginBottom:8}}>No protocol yet — add exercises below or build it in the Exercise Prescription tab.</div>
          )}
          {prog.map(e=>(
            <div key={e.id} style={{marginBottom:5}}>
              <div style={{display:"flex",alignItems:"center",gap:7,padding:"8px 10px",background:e.addedSession===sessionNo?`${PC.accent}10`:PC.s2,border:`1px solid ${e.addedSession===sessionNo?PC.accent+"35":PC.border}`,borderRadius:9}}>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{fontSize:"0.76rem",fontWeight:700,color:PC.text}}>{e.name}
                    {e.addedSession===sessionNo&&<span style={{marginLeft:6,fontSize:"0.75rem",fontWeight:800,color:PC.accent}}>＋ just added</span>}
                    {e.progressedSession===sessionNo&&<span style={{marginLeft:6,fontSize:"0.75rem",fontWeight:800,color:PC.a3}}>↑ progressed</span>}
                  </div>
                  <div style={{fontSize:"0.82rem",color:PC.muted}}>{hepDose(e)}</div>
                </div>
                <SessionPill bg={`${PC.a3}18`} col={PC.a3} title="Progress dosage" onClick={()=>startProgress(e)}>↑</SessionPill>
                <SessionPill bg="rgba(220,38,38,0.1)" col="#dc2626" title="Remove" onClick={()=>setRemoveId(removeId===e.id?null:e.id)}>−</SessionPill>
              </div>
              {editId===e.id&&(
                <div style={{display:"flex",gap:6,alignItems:"center",padding:"7px 10px",background:`${PC.a3}08`,border:`1px dashed ${PC.a3}40`,borderRadius:9,marginTop:3}}>
                  {["sets","reps","hold"].map(f=>(
                    <input key={f} style={{...inp,width:62,padding:"5px 7px",fontSize:"0.82rem"}} placeholder={f} value={editDose[f]} onChange={ev=>setEditDose(p=>({...p,[f]:ev.target.value}))}/>
                  ))}
                  <span style={{fontSize:"0.78rem",color:PC.muted}}>sets × reps · hold s</span>
                  <button onClick={applyProgress} style={{marginLeft:"auto",padding:"5px 12px",borderRadius:7,border:"none",background:PC.a3,color:"#fff",fontWeight:800,fontSize:"0.75rem",cursor:"pointer"}}>✓ Apply</button>
                </div>
              )}
              {removeId===e.id&&(
                <div style={{display:"flex",gap:5,flexWrap:"wrap",padding:"7px 10px",background:"rgba(220,38,38,0.05)",border:"1px dashed rgba(220,38,38,0.35)",borderRadius:9,marginTop:3,alignItems:"center"}}>
                  <span style={{fontSize:"0.8rem",color:"#dc2626",fontWeight:700}}>Why?</span>
                  {["Mastered","Aggravating","Replaced","Other"].map(r=>(
                    <button key={r} onClick={()=>removeExercise(e.id,r)} style={{padding:"4px 10px",borderRadius:7,border:"1px solid rgba(220,38,38,0.3)",background:"transparent",color:"#dc2626",fontWeight:700,fontSize:"0.82rem",cursor:"pointer"}}>{r}</button>
                  ))}
                </div>
              )}
            </div>
          ))}

          {!pickerOpen?(
            <div onClick={()=>setPickerOpen(true)} style={{padding:"9px",border:`1.5px dashed ${PC.accent}50`,borderRadius:9,textAlign:"center",fontSize:"0.82rem",fontWeight:700,color:PC.accent,cursor:"pointer",marginBottom:10}}>＋ Add exercise from library</div>
          ):(
            <div style={{border:`1.5px solid ${PC.accent}35`,borderRadius:11,padding:"10px",marginBottom:10,background:`${PC.accent}06`}}>
              <div style={{display:"flex",gap:6,marginBottom:7}}>
                {[["library","📚 Library"],["templates","📦 Templates"]].map(([m,l])=>(
                  <button key={m} onClick={()=>setPickerMode(m)} style={{flex:1,padding:"7px",borderRadius:8,border:`1px solid ${pickerMode===m?PC.accent:PC.border}`,background:pickerMode===m?`${PC.accent}15`:"transparent",color:pickerMode===m?PC.accent:PC.muted,fontWeight:800,fontSize:"0.78rem",cursor:"pointer"}}>{l}</button>
                ))}
                <button onClick={()=>setPickerOpen(false)} style={{padding:"0 10px",borderRadius:8,border:`1px solid ${PC.border}`,background:"transparent",color:PC.muted,cursor:"pointer",fontWeight:700}}>✕</button>
              </div>
              {pickerMode==="templates"&&(
                <div>
                  {Object.entries(PROGRAMME_TEMPLATES).map(([key,t])=>{
                    const tx=TEMPLATE_TX[key];
                    const isOpen=openTemplate===key;
                    return(
                      <div key={key} style={{marginBottom:4}}>
                        <div onClick={()=>setOpenTemplate(isOpen?null:key)} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 10px",borderRadius:8,cursor:"pointer",background:PC.surface,border:`1px solid ${isOpen?PC.accent+"45":PC.border}`}}>
                          <div style={{flex:1,minWidth:0}}>
                            <div style={{fontSize:"0.82rem",fontWeight:700,color:PC.text}}>{t.label}</div>
                            <div style={{fontSize:"0.78rem",color:PC.muted}}>{t.exercises.length} exercises{tx?` · ${(tx.manual||[]).length} manual · ${(tx.machine||[]).length} machine`:""}</div>
                          </div>
                          <span style={{fontSize:"0.75rem",color:PC.accent,fontWeight:800}}>{isOpen?"▲":"▼"}</span>
                        </div>
                        {isOpen&&(
                          <div style={{padding:"8px 10px",border:`1px dashed ${PC.accent}35`,borderTop:"none",borderRadius:"0 0 8px 8px",background:`${PC.accent}05`}}>
                            <button onClick={()=>{addTemplate(key);setOpenTemplate(null);}} style={{width:"100%",padding:"8px",borderRadius:8,border:"none",background:`linear-gradient(135deg,${PC.accent},${PC.a2})`,color:"#fff",fontWeight:800,fontSize:"0.78rem",cursor:"pointer",marginBottom:7}}>＋ Add {t.exercises.length} exercises to protocol</button>
                            {tx&&(tx.manual||[]).length>0&&(
                              <div style={{marginBottom:5}}>
                                <div style={{fontSize:"0.75rem",fontWeight:800,color:PC.muted,textTransform:"uppercase",letterSpacing:"0.5px",marginBottom:3}}>🤲 Manual — tap to add to treatment</div>
                                <div style={{display:"flex",flexWrap:"wrap",gap:4}}>
                                  {tx.manual.map(m=><button key={m} onClick={()=>addTxItem(m)} style={{padding:"3px 9px",borderRadius:99,border:`1px solid ${treatmentList.find(t=>t.name===m)?PC.accent:PC.border}`,background:treatmentList.find(t=>t.name===m)?`${PC.accent}14`:PC.surface,color:treatmentList.find(t=>t.name===m)?PC.accent:PC.text,fontWeight:700,fontSize:"0.8rem",cursor:"pointer"}}>{treatmentList.find(t=>t.name===m)?"✓ ":""}{m}</button>)}
                                </div>
                              </div>
                            )}
                            {tx&&(tx.machine||[]).length>0&&(
                              <div>
                                <div style={{fontSize:"0.75rem",fontWeight:800,color:PC.muted,textTransform:"uppercase",letterSpacing:"0.5px",marginBottom:3}}>⚡ Machine — tap to add to treatment</div>
                                <div style={{display:"flex",flexWrap:"wrap",gap:4}}>
                                  {tx.machine.map(m=><button key={m} onClick={()=>addTxItem(m)} style={{padding:"3px 9px",borderRadius:99,border:`1px solid ${treatmentList.find(t=>t.name===m)?PC.a2:PC.border}`,background:treatmentList.find(t=>t.name===m)?`${PC.a2}14`:PC.surface,color:treatmentList.find(t=>t.name===m)?PC.a2:PC.text,fontWeight:700,fontSize:"0.8rem",cursor:"pointer"}}>{treatmentList.find(t=>t.name===m)?"✓ ":""}{m}</button>)}
                                </div>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
              {pickerMode==="library"&&(
              <div style={{display:"flex",gap:6,marginBottom:7}}>
                <input autoFocus style={{...inp,flex:1}} placeholder="Search exercises… e.g. plank, chin tuck" value={pickerSearch} onChange={e=>setPickerSearch(e.target.value)}/>
                <select style={{...inp,width:120}} value={pickerRegion} onChange={e=>setPickerRegion(e.target.value)}>
                  <option value="all">All regions</option>
                  {Object.entries(EXERCISE_DB).map(([k,r])=><option key={k} value={k}>{r.label}</option>)}
                </select>
              </div>
              )}
              {pickerMode==="library"&&pickerResults.length===0&&<div style={{fontSize:"0.66rem",color:PC.muted,padding:"4px 2px"}}>No matches — try another term or region.</div>}
              {pickerMode==="library"&&pickerResults.map(ex=>(
                <div key={ex.id} onClick={()=>addExercise(ex)} style={{display:"flex",alignItems:"center",gap:8,padding:"7px 9px",borderRadius:8,cursor:"pointer",background:PC.surface,border:`1px solid ${PC.border}`,marginBottom:4}}>
                  <div style={{flex:1,minWidth:0}}>
                    <div style={{fontSize:"0.82rem",fontWeight:700,color:PC.text}}>{ex.name}</div>
                    <div style={{fontSize:"0.78rem",color:PC.muted,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{ex.sets}×{ex.reps}{ex.hold?` · ${ex.hold}s`:""} · {ex.freq} · {ex.target}</div>
                  </div>
                  <span style={{fontSize:"0.82rem",fontWeight:800,color:PC.accent,flexShrink:0}}>＋ Add</span>
                </div>
              ))}
            </div>
          )}

          {pending.length>0&&(
            <div style={{padding:"8px 11px",background:`${PC.accent}0a`,border:`1px solid ${PC.accent}25`,borderRadius:9,fontSize:"0.75rem",color:PC.text,marginBottom:10,lineHeight:1.6}}>
              <span style={{fontWeight:800,color:PC.accent}}>This session:</span> {pending.join(" · ")} <span style={{color:PC.muted}}>(will be logged as v{(parseInt(data.hep_version)||1)+1} on save)</span>
            </div>
          )}
        </>):(
          <EditableItemList PC={PC} items={pastExercises}
            onAdd={(it)=>setPastExercises(l=>[...l,{id:Math.random().toString(36).slice(2,9),...it}])}
            onEdit={(id,patch)=>setPastExercises(l=>l.map(e=>e.id===id?{...e,...patch}:e))}
            onRemove={(id)=>setPastExercises(l=>l.filter(e=>e.id!==id))}
            addLabel="＋ Add exercise"/>
        )}
      </div>

      <div style={{marginBottom:14}}>
        <div style={sectionLbl}>Exercise Prescription {rxProgramme.length>0&&<span style={{fontWeight:600,textTransform:"none"}}>· {rxProgramme.length} exercise{rxProgramme.length!==1?"s":""}</span>}</div>
        {/* Exercise Prescription is a standing treatment programme, not a
            per-visit event like Modalities/Treatment -- always shows what's
            CURRENTLY prescribed (data.tx_exercise_prescription) whether
            you're looking at today's session or a past one, rather than a
            frozen historical snapshot. A past session freezing this the
            same way it freezes Modalities/Treatment meant exercises picked
            after that session was saved would never show up when you
            reopened it -- which is exactly what "not showing in session"
            reports were describing. */}
        {rxProgramme.length===0&&<div style={{fontSize:"0.78rem",color:PC.muted,padding:"4px 0 8px"}}>None prescribed yet.</div>}
        {rxProgramme.map(e=>(
          <div key={e.id} style={{display:"flex",alignItems:"center",gap:7,padding:"8px 10px",background:PC.s2,border:`1px solid ${PC.border}`,borderRadius:9,marginBottom:5}}>
            <div style={{flex:1,minWidth:0}}>
              <div style={{fontSize:"0.76rem",fontWeight:700,color:PC.text}}>{e.name}</div>
              <div style={{fontSize:"0.82rem",color:PC.muted}}>{hepDose(e)}</div>
            </div>
            <SessionPill bg="rgba(220,38,38,0.1)" col="#dc2626" title="Remove" onClick={()=>removeRx(e.id)}>−</SessionPill>
          </div>
        ))}
        <div onClick={()=>navTo("treatment")} style={{padding:"9px",border:`1.5px dashed ${PC.accent}50`,borderRadius:9,textAlign:"center",fontSize:"0.82rem",fontWeight:700,color:PC.accent,cursor:"pointer"}}>＋ Add / edit in Exercise Prescription →</div>
      </div>
</div>)}
      </div>

      {tab==="progress"&&(
        <div style={card}>
          <div style={sectionLbl}>Previous sessions</div>
          {done.length===0&&<div style={{fontSize:"0.82rem",color:PC.muted}}>No completed sessions yet.</div>}
          {done.slice(0,8).map((x,i)=>{ const pl=painLine(x); return (
            <div key={x.id||i} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:"0.85rem",borderTop:i?`1px solid ${PC.border}`:"none"}}>
              <span style={{color:PC.text}}>Session {x.sessionNo||done.length-i} · <span style={{color:PC.muted}}>{shortDate(x.completedAt||x.savedAt,x.date||"")}</span></span>
              <strong>{pl?`${pl.a}→${pl.b}/10`:"–"}</strong>
            </div>); })}
        </div>
      )}
      {isNew&&tab==="exercises"&&(
        <div style={{display:"flex",gap:8,marginBottom:10}}>
          <button onClick={()=>sendHepWhatsApp(data)} style={{flex:1,padding:"10px",borderRadius:9,border:`1px solid ${PC.a3}40`,background:`${PC.a3}10`,color:PC.a3,fontWeight:800,fontSize:"0.82rem",cursor:"pointer"}}>📲 Send protocol — WhatsApp</button>
          <button onClick={()=>downloadHepPdf(data)} style={{flex:1,padding:"10px",borderRadius:9,border:`1px solid ${PC.a2}40`,background:`${PC.a2}10`,color:PC.a2,fontWeight:800,fontSize:"0.82rem",cursor:"pointer"}}>📄 PDF handout</button>
        </div>
      )}
      <div style={{position:"sticky",bottom:0,zIndex:5,background:PC.bg||"#fff",padding:"10px 0 calc(10px + env(safe-area-inset-bottom))",borderTop:`1px solid ${PC.border}`}}>
        {error&&<div role="alert" style={{fontSize:"0.8rem",color:"#dc2626",fontWeight:700,marginBottom:8}}>{error}</div>}
        {isNew?(
          <div style={{display:"flex",gap:8}}>
            <button onClick={saveDraft} style={{flex:1,padding:"14px 8px",borderRadius:12,border:"none",background:"#EDE9FE",color:"#6D28D9",fontWeight:800,fontSize:"0.88rem",cursor:"pointer"}}>
              {draftSaved?"✓ Draft saved":"Save Draft"}
            </button>
            <button onClick={completeSession} style={{flex:1.6,padding:"14px 8px",borderRadius:12,border:"none",background:"#6D28D9",color:"#fff",fontWeight:800,fontSize:"0.88rem",cursor:"pointer"}}>
              ✓ Complete Session →
            </button>
          </div>
        ):(
          <div style={{display:"flex",gap:8}}>
            <button onClick={()=>setMode("summary")} style={{flex:1,padding:"14px 8px",borderRadius:12,border:"none",background:"#EDE9FE",color:"#6D28D9",fontWeight:800,fontSize:"0.88rem",cursor:"pointer"}}>Cancel</button>
            <button onClick={updatePast} style={{flex:1.6,padding:"14px 8px",borderRadius:12,border:"none",background:"#6D28D9",color:"#fff",fontWeight:800,fontSize:"0.88rem",cursor:"pointer"}}>{saved?"✅ Session updated":"Update session"}</button>
          </div>
        )}
      </div>
    </div>
  );
}

// ── Small pieces used by the session screens ────────────────────────────────
const fmtDay = (e) => longDate(e.completedAt||e.savedAt, e.date||"");
const painLine = (e) => {
  const a=parseFloat(e.vasStart), b=parseFloat(e.vasEnd!==undefined&&e.vasEnd!==""?e.vasEnd:e.vasStart);
  return isNaN(a) ? null : {a, b: isNaN(b)?a:b};
};
const entryTreatments = (e) => [
  ...(Array.isArray(e.treatment)?e.treatment:legacyTreatmentToList(e.treatmentGiven)),
  ...(Array.isArray(e.modalities)?e.modalities:[]),
];

function PainStepper({ PC, label, value, onChange, highlight }) {
  const n = parseFloat(value);
  const has = !isNaN(n);
  const step = (d) => onChange(String(Math.max(0, Math.min(10, (has?n:0)+d))));
  const btn = {width:44,height:44,borderRadius:12,border:`1px solid ${PC.border}`,background:PC.s2,color:PC.text,fontSize:"1.2rem",fontWeight:800,cursor:"pointer",fontFamily:"inherit"};
  return (
    <div style={{flex:"1 1 130px"}}>
      <div style={{fontSize:"0.8rem",fontWeight:700,color:PC.muted,marginBottom:4}}>{label}</div>
      <div style={{display:"flex",alignItems:"center",gap:6}}>
        <button type="button" aria-label={`${label} pain minus`} onClick={()=>step(-1)} style={btn}>−</button>
        <div aria-label={`${label} pain`} style={{minWidth:54,height:44,borderRadius:12,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:800,fontSize:"1.15rem",
          border:`1.5px solid ${highlight?highlight.border:PC.border}`,background:highlight?highlight.bg:PC.surface,color:highlight?highlight.col:PC.text}}>
          {has?n:"–"}<span style={{fontSize:"0.72rem",color:PC.muted,marginLeft:2}}>/10</span>
        </div>
        <button type="button" aria-label={`${label} pain plus`} onClick={()=>step(1)} style={btn}>+</button>
      </div>
    </div>
  );
}

function PrimaryBtn({ children, onClick, ghost }) {
  return <button type="button" onClick={onClick} style={{width:"100%",padding:"14px",borderRadius:12,border:"none",background:ghost?"#EDE9FE":"#6D28D9",color:ghost?"#6D28D9":"#fff",fontWeight:800,fontSize:"0.9rem",cursor:"pointer",marginBottom:8}}>{children}</button>;
}

// Shown right after Complete Session.
function SessionCompleted({ PC, entry, patientName, onSummary, onNext, onBack }) {
  const pain = painLine(entry);
  return (
    <div style={{textAlign:"center",padding:"18px 4px"}}>
      <div style={{width:64,height:64,borderRadius:"50%",background:"#DCFCE7",color:"#16A34A",fontSize:"2rem",fontWeight:800,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 12px"}}>✓</div>
      <div style={{fontSize:"1.2rem",fontWeight:800,color:"#16A34A"}}>Session Completed</div>
      <div style={{marginTop:10,fontWeight:800,color:PC.text}}>{patientName}</div>
      <div style={{color:PC.muted,fontSize:"0.85rem"}}>Session {entry.sessionNo}</div>
      {pain&&<div style={{margin:"12px 0",fontSize:"0.9rem",color:PC.text}}>Pain <strong>{pain.a}/10 → {pain.b}/10</strong></div>}
      <div style={{color:PC.muted,fontSize:"0.82rem",marginBottom:18}}>Treatment recorded successfully.</div>
      <PrimaryBtn onClick={onSummary}>View Summary</PrimaryBtn>
      {onNext&&<PrimaryBtn ghost onClick={onNext}>Start Next Session</PrimaryBtn>}
      <div onClick={onBack} style={{cursor:"pointer",color:PC.muted,fontSize:"0.82rem",padding:8}}>Back to session history</div>
    </div>
  );
}

// Read-only view of one completed session.
function SessionSummary({ PC, entry, patientName, condition, onEdit, onHistory, onNext }) {
  const pain = painLine(entry);
  const items = entryTreatments(entry);
  const home = Array.isArray(entry.exercises)?entry.exercises:[];
  const note = entry.quickNote||entry.response||"";
  const card = {background:PC.surface,border:`1px solid ${PC.border}`,borderRadius:14,padding:"12px 14px",marginBottom:12};
  const h = {fontSize:"0.82rem",fontWeight:800,color:PC.text,textTransform:"uppercase",letterSpacing:"0.7px",marginBottom:6};
  return (
    <div>
      <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}>
        <span onClick={onHistory} style={{cursor:"pointer",fontSize:"1.1rem",color:PC.muted,padding:"4px 6px"}} title="Back to history">←</span>
        <div style={{flex:1,minWidth:0}}>
          <div style={{fontWeight:800,color:PC.text}}>{patientName}</div>
          {condition&&<div style={{fontSize:"0.78rem",color:PC.muted}}>{condition}</div>}
        </div>
        <span style={{fontSize:"0.75rem",fontWeight:800,padding:"4px 10px",borderRadius:99,background:"#DCFCE7",color:"#16A34A"}}>Completed</span>
      </div>
      <div style={card}>
        <div style={{fontWeight:800,color:PC.text}}>Session {entry.sessionNo}</div>
        <div style={{fontSize:"0.82rem",color:PC.muted}}>{fmtDay(entry)}</div>
        {pain&&<div style={{marginTop:8,fontSize:"0.9rem"}}>Pain <strong>{pain.a}/10 → {pain.b}/10</strong></div>}
      </div>
      <div style={card}>
        <div style={h}>Treatment Performed</div>
        {items.length===0&&<div style={{fontSize:"0.8rem",color:PC.muted}}>None recorded.</div>}
        {items.map((t,i)=><div key={t.id||i} style={{fontSize:"0.86rem",color:PC.text,padding:"3px 0"}}><span style={{color:"#16A34A",fontWeight:800}}>✓ </span>{t.name}{t.detail?<span style={{color:PC.muted}}> — {t.detail}</span>:null}</div>)}
      </div>
      {note&&<div style={card}><div style={h}>Patient Response</div><div style={{fontSize:"0.86rem",color:PC.text,whiteSpace:"pre-wrap"}}>{note}</div></div>}
      {entry.nextPlan&&<div style={card}><div style={h}>Plan for Next Session</div><div style={{fontSize:"0.86rem",color:PC.text}}>{entry.nextPlan}</div></div>}
      {home.length>0&&(
        <div style={card}>
          <div style={h}>Home Program</div>
          {home.map((e,i)=><div key={e.id||i} style={{padding:"3px 0",fontSize:"0.86rem",color:PC.text}}>{e.name}{e.detail?<span style={{color:PC.muted}}> · {e.detail}</span>:null}</div>)}
        </div>
      )}
      <PrimaryBtn ghost onClick={onHistory}>View History</PrimaryBtn>
      {onNext&&<PrimaryBtn onClick={onNext}>Start Next Session</PrimaryBtn>}
      <div onClick={onEdit} style={{cursor:"pointer",color:PC.muted,fontSize:"0.8rem",textAlign:"center",padding:8}}>Edit this session</div>
    </div>
  );
}

export { SessionDetailView };
